### ISSUE TITLE
AttributeError: 'OAuth2Credentials' object has no attribute 'expired'

### ISSUE THREAD

**Issue by sabeechen** [sabeechen/hassio-google-drive-backup#1]
Testing issue tracking

Traceback (most recent call last):
  File ".\backup.py", line 234, in backupnow
    self.checkForBackup()
  File ".\backup.py", line 296, in checkForBackup
    if self.creds.expired:
AttributeError: 'OAuth2Credentials' object has no attribute 'expired'

**Comment by sabeechen** [comment]
Done testing!
