### ISSUE TITLE
An unexpected error occurred: Remote end closed connection without response

### ISSUE THREAD

**Issue by emouawad** [sabeechen/hassio-google-drive-backup#100]
Error: Home Assistant refused to delete the snapshot
Partial Snapshot of Size 0B
 
![image](https://user-images.githubusercontent.com/6771272/65162350-c25b3f00-da41-11e9-8d67-4b2bc903b23c.png)

An unexpected error happened while creating the snapshot and now it is refusing to delete the problematic snapshot.

It's actually a problem in Hass.IO and not this addon cause I tried from Hass.IO snapshots and same issue cannot delete the problematic snapshot - not even a restart fixed the isssue. 

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 102, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 145, in sync
    upload.addSource(self.dest.save(upload, self.source.read(upload)))
  File "/app/backup/hasource.py", line 219, in read
    return self.harequests.download(item.slug())
  File "/app/backup/harequests.py", line 93, in download
    return SeekableRequest(url, self._getHassioHeaders()).prepare()
  File "/app/backup/seekablerequest.py", line 31, in prepare
    self.size()
  File "/app/backup/seekablerequest.py", line 36, in size
    self._size = self._getContentLength()
  File "/app/backup/seekablerequest.py", line 119, in _getContentLength
    f = urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

An unexpected error occurred: Remote end closed connection without response

**Comment by sabeechen** [comment]
Sorry not to get back to you sooner, for some reason I didnt get a email notification when you submitted this and I literally just noticed it.  If your still running into the problem:
* The supervisor logs (Hass.io > System > System Logs) might have some output that could tell you why it can't be deleted.  Most likely not though, I'd guess Hass.io attempts to read the snapshot contents when deleting it (which are probably corrupted) and then errors out.
*  You should still be able to delete the snapshot from Home Assistant manually.  You could install the samba add-on to get access to the /backup directory or use one of the ssh add-ons to get to it through the command line.  After that if you click the refresh icon on the snapshot page in Home Assistant I suspect it will clear out the bad snapshot.

**Comment by sabeechen** [comment]
Closing this due to age, feel free to reopen if there is still some way I can help.
