### ISSUE TITLE
Update Bug

### ISSUE THREAD

**Issue by Athosza** [sabeechen/hassio-google-drive-backup#1045]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.:

This is the error  I get.

Failed to call service update/install. Error updating Home Assistant Google Drive Backup: Can't install ghcr.io/sabeechen/hassio-google-drive-backup-aarch64:0.112.1: 500 Server Error for http+docker://localhost/v1.44/images/ghcr.io/sabeechen/hassio-google-drive-backup-aarch64:0.112.1/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")
```

 Addon version: `0.111.1`
 Home Assistant Version: `2024.5.4`
 Supervisor Version: `2024.05.1`
 Supervisor Channel: `stable`
 Hassos Version: `12.3`
 Docker Version: `25.0.5`
 Architecture: `aarch64`
 Machine: `raspberrypi3-64`
 Date: `2024-05-22T08:17:56.143874+00:00`
 Timezone: `Africa/Johannesburg`
 Failure Time: `Never`
 Last Good Sync: `2024-05-22T08:17:43.129853+00:00`
 Next Sync: `2024-05-22T10:19:36.018173+00:00`
 Next Backup: `2024-05-22T23:00:00+00:00`
 Next Cache Warm: `2024-05-22T10:07:47.122112+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2024-05-21T23:00:00Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 125,
        "detail": "",
        "size": "604.5 MB",
        "ignored_size": "5.4 GB",
        "free_space": "36.0 GB"
    },
    "GoogleDrive": {
        "backups": 7,
        "retained": 2,
        "deletable": 5,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2024-05-21T23:00:00Z",
        "max": 5,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "athosza@gmail.com",
        "size": "770.6 MB",
        "ignored_size": "0.0 B",
        "free_space": "1.7 TB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 5,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.BACKUP_TIME_OF_DAY": "01:00",
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 05-22 01:01:55 DEBUG [backup.drive.drivesource] Uploading Full Backup 2024-05-22 01:00:00 99.61%
05-22 01:01:55 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
05-22 01:01:58 DEBUG [backup.drive.drivesource] Uploading Full Backup 2024-05-22 01:00:00 100.00%
05-22 01:01:59 INFO [backup.drive.drivesource] Deleting 'Full Backup 2024-05-17 01:00:00' From Google Drive
05-22 01:02:00 DEBUG [backup.watcher] Checking backup source for changes...
05-22 01:02:01 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
05-22 01:02:01 INFO [backup.model.coordinator] Syncing Backups
05-22 02:54:43 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
05-22 02:54:43 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
05-22 02:55:15 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
05-22 02:55:26 DEBUG [backup.watcher] Checking backup source for changes...
05-22 03:00:20 DEBUG [backup.model.syncer] Sync requested by Coordinator
05-22 03:00:20 INFO [backup.model.coordinator] Syncing Backups
05-22 05:46:51 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
05-22 05:46:51 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
05-22 05:55:05 DEBUG [backup.model.syncer] Sync requested by Coordinator
05-22 05:55:05 INFO [backup.model.coordinator] Syncing Backups
05-22 08:03:58 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
05-22 08:03:58 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
05-22 08:06:00 DEBUG [backup.model.syncer] Sync requested by Coordinator
05-22 08:06:00 INFO [backup.model.coordinator] Syncing Backups
05-22 10:17:04 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
05-22 10:17:14 DEBUG [backup.watcher] Checking backup source for changes...
05-22 10:17:14 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
05-22 10:17:14 INFO [backup.model.coordinator] Syncing Backups
05-22 10:17:15 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
05-22 10:17:32 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
05-22 10:17:42 DEBUG [backup.watcher] Checking backup source for changes...
05-22 10:17:43 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
05-22 10:17:43 INFO [backup.model.coordinator] Syncing Backups
 ```
 ###### Supervisor Logs:
 ```
 [32m2024-05-22 10:17:04.245 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on cebe7a76_hassio_google_drive_backup[0m
[32m2024-05-22 10:17:04.389 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon cebe7a76_hassio_google_drive_backup[0m
[32m2024-05-22 10:17:04.393 INFO (MainThread) [supervisor.backups.manager] Backup 3c68d72f starting stage finishing_file[0m
[32m2024-05-22 10:17:04.418 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 3c68d72f completed[0m
[32m2024-05-22 10:17:04.423 INFO (MainThread) [supervisor.docker.addon] Updating image sabeechen/hassio-google-drive-backup-aarch64:0.111.1 to ghcr.io/sabeechen/hassio-google-drive-backup-aarch64:0.112.1[0m
[32m2024-05-22 10:17:04.425 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/sabeechen/hassio-google-drive-backup-aarch64 with tag 0.112.1.[0m
[31m2024-05-22 10:17:11.546 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/sabeechen/hassio-google-drive-backup-aarch64:0.112.1: 500 Server Error for http+docker://localhost/v1.44/images/ghcr.io/sabeechen/hassio-google-drive-backup-aarch64:0.112.1/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")[0m
[32m2024-05-22 10:17:14.747 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-05-22 10:17:14.761 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-05-22 10:17:14.837 INFO (MainThread) [supervisor.api.middleware.security] /backups/3c68d72f/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-05-22 10:17:14.914 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-05-22 10:17:14.926 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-05-22 10:17:32.653 INFO (MainThread) [supervisor.backups.manager] Backup b25bf544 starting stage addon_repositories[0m
[32m2024-05-22 10:17:32.654 INFO (MainThread) [supervisor.backups.manager] Backup b25bf544 starting stage docker_config[0m
[32m2024-05-22 10:17:32.654 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug b25bf544[0m
[32m2024-05-22 10:17:32.673 INFO (MainThread) [supervisor.backups.manager] Backup b25bf544 starting stage addons[0m
[32m2024-05-22 10:17:32.758 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on cebe7a76_hassio_google_drive_backup[0m
[32m2024-05-22 10:17:32.826 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon cebe7a76_hassio_google_drive_backup[0m
[32m2024-05-22 10:17:32.830 INFO (MainThread) [supervisor.backups.manager] Backup b25bf544 starting stage finishing_file[0m
[32m2024-05-22 10:17:32.853 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug b25bf544 completed[0m
[32m2024-05-22 10:17:32.857 INFO (MainThread) [supervisor.docker.addon] Updating image sabeechen/hassio-google-drive-backup-aarch64:0.111.1 to ghcr.io/sabeechen/hassio-google-drive-backup-aarch64:0.112.1[0m
[32m2024-05-22 10:17:32.858 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/sabeechen/hassio-google-drive-backup-aarch64 with tag 0.112.1.[0m
[31m2024-05-22 10:17:40.522 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/sabeechen/hassio-google-drive-backup-aarch64:0.112.1: 500 Server Error for http+docker://localhost/v1.44/images/ghcr.io/sabeechen/hassio-google-drive-backup-aarch64:0.112.1/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")[0m
[32m2024-05-22 10:17:42.983 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-05-22 10:17:42.994 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-05-22 10:17:43.068 INFO (MainThread) [supervisor.api.middleware.security] /backups/b25bf544/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-05-22 10:17:43.134 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-05-22 10:17:43.145 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-05-22 10:17:56.244 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/sabeechen/hassio-google-drive-backup-aarch64:0.112.1: 500 Server Error for http+docker://localhost/v1.44/images/ghcr.io/sabeechen/hassio-google-drive-backup-aarch64:0.112.1/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 461, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 170, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Home Assistant Google Drive Backup: Can't install ghcr.io/sabeechen/hassio-google-drive-backup-aarch64:0.112.1: 500 Server Error for http+docker://localhost/v1.44/images/ghcr.io/sabeechen/hassio-google-drive-backup-aarch64:0.112.1/json: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")[0m
[33m2024-05-22 10:17:47.282 WARNING (MainThread) [homeassistant.components.androidtv_remote] Disconnected from TV at 192.168.68.108[0m
[31m2024-05-22 10:17:47.492 ERROR (MainThread) [androidtvremote2] Device doesn't support sending keys. Try clearing the storage of the Android TV Remove Service system app. On the Android TV device, go to Settings > Apps > See all apps > Show system apps. Then, select Android TV Remote Service > Storage > Clear data/storage.[0m

 ```

**Comment by sabeechen** [comment]
This is most likely docker corruption.  Docker is a virtualization system that Home Assistant and addons run in.  There are some known issues with how Home Assistant uses it, if updating an addon or Home Assistant is suddenly interrupted  (eg a power or disk failure) then docker's cache of files locally can become corrupted.  If you want more detail, [this thread](https://github.com/sabeechen/hassio-google-drive-backup/issues/952) is where we first identified the issue.  AFAIK the home assistant team has no plan to fix it and there isn't anything I can do about it form the addon side of things.

In some cases it can be fixed by installing the SSH addon and running the command `ha su repair`.   A more reliably but much more complicated fix is to ssh into the host machine by installing SSH keys and manually deleting docker's cossupted files ([here is an example of a user doing that in the past](https://github.com/sabeechen/hassio-google-drive-backup/issues/952#issuecomment-1877103321)).  The process is complicated because Home Assistant really tries to keep you out of the host machine.

The easiest way to fix this is to create a new backup (through Home Assistant) reinstall Home Assistant and restore the backup.
