### ISSUE TITLE
Home Assistant refused to delete the backup

### ISSUE THREAD

**Issue by mpgoebel** [sabeechen/hassio-google-drive-backup#1110]
###### Description:
I am running Home Assistant on Unraid as a VM.  I had some issues with Unraid last night and i had to rebuild the flash drive because I needed to downgrade to restore my server to a useable state.  The add on was working flawlessly before last night.  I am backing up to a share on my server, i confirmed that external storage is still functioning.  HA itself could not delete the backup.  Any ideas? 

```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.112.1`
 Home Assistant Version: `2024.12.1`
 Supervisor Version: `2024.11.4`
 Supervisor Channel: `beta`
 Hassos Version: `14.0`
 Docker Version: `27.2.0`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2024-12-09T16:22:52.334899+00:00`
 Timezone: `America/Chicago`
 Failure Time: `2024-12-09T16:14:30.382141+00:00`
 Last Good Sync: `2024-12-09T16:14:29.834763+00:00`
 Next Sync: `2024-12-09T16:25:10.382141+00:00`
 Next Backup: `2024-12-09T09:00:00+00:00`
 Next Cache Warm: `2024-12-09T16:11:38.500161+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/ha/harequests.py:105 (delete)
  addon/backup/ha/harequests.py:34 (wrap_and_call)
  addon/backup/ha/harequests.py:280 (_sendHassioData)
  addon/backup/ha/harequests.py:225 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1059 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://supervisor/backups/6b158d69')
Whose handling caused:
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:222 (sync)
  addon/backup/model/model.py:280 (deleteBackup)
  addon/backup/ha/hasource.py:355 (delete)
  addon/backup/ha/harequests.py:34 (wrap_and_call)
  addon/backup/ha/harequests.py:111 (delete)
backup.exceptions.exceptions.HomeAssistantDeleteError

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 7,
        "retained": 0,
        "deletable": 7,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2024-12-08T09:00:00Z",
        "max": 8,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 7,
        "detail": "",
        "size": "932.6 MB",
        "ignored_size": "748.7 MB",
        "free_space": "39.4 GB"
    },
    "GoogleDrive": {
        "backups": 7,
        "retained": 0,
        "deletable": 7,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2024-12-08T09:00:00Z",
        "max": 8,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "mattgob86@gmail.com",
        "size": "932.6 MB",
        "ignored_size": "0.0 B",
        "free_space": "4.9 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 8,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 8,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.IGNORE_OTHER_BACKUPS": true,
    "Setting.DELETE_IGNORED_AFTER_DAYS": 7.0,
    "Setting.BACKUP_TIME_OF_DAY": "03:00",
    "Setting.GENERATIONAL_DAYS": 2,
    "Setting.GENERATIONAL_WEEKS": 2,
    "Setting.GENERATIONAL_MONTHS": 2,
    "Setting.GENERATIONAL_YEARS": 1,
    "Setting.SEND_ERROR_REPORTS": true,
    "Setting.BACKGROUND_COLOR": "#1c1c1c"
}
 ```
 ###### Addon Logs:
 ```
 12-09 10:05:44 INFO [backup.model.coordinator] I'll try again in 20 seconds
12-09 10:06:04 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-09 10:06:04 INFO [backup.model.coordinator] Syncing Backups
12-09 10:06:05 INFO [backup.ha.hasource] Deleting 'core_2024.12.0b2' from Home Assistant
12-09 10:06:05 ERROR [backup.model.coordinator] Home Assistant refused to delete the backup.
12-09 10:06:05 INFO [backup.model.coordinator] I'll try again in 40 seconds
12-09 10:06:18 INFO [backup.model.coordinator] Syncing Backups
12-09 10:06:19 INFO [backup.ha.hasource] Deleting 'core_2024.12.0b2' from Home Assistant
12-09 10:06:19 ERROR [backup.model.coordinator] Home Assistant refused to delete the backup.
12-09 10:06:19 INFO [backup.model.coordinator] I'll try again in 1 minutes, 20 seconds
12-09 10:06:29 INFO [backup.model.coordinator] Syncing Backups
12-09 10:06:29 INFO [backup.ha.hasource] Deleting 'core_2024.12.0b2' from Home Assistant
12-09 10:06:29 ERROR [backup.model.coordinator] Home Assistant refused to delete the backup.
12-09 10:06:29 INFO [backup.model.coordinator] I'll try again in 2 minutes, 40 seconds
12-09 10:07:32 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
12-09 10:09:09 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-09 10:09:09 INFO [backup.model.coordinator] Syncing Backups
12-09 10:09:09 INFO [backup.ha.hasource] Deleting 'core_2024.12.0b2' from Home Assistant
12-09 10:09:09 ERROR [backup.model.coordinator] Home Assistant refused to delete the backup.
12-09 10:09:09 INFO [backup.model.coordinator] I'll try again in 5 minutes, 20 seconds
12-09 10:14:29 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-09 10:14:29 INFO [backup.model.coordinator] Syncing Backups
12-09 10:14:30 INFO [backup.ha.hasource] Deleting 'core_2024.12.0b2' from Home Assistant
12-09 10:14:30 ERROR [backup.model.coordinator] Home Assistant refused to delete the backup.
12-09 10:14:30 INFO [backup.model.coordinator] I'll try again in 10 minutes, 40 seconds
12-09 10:14:33 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
12-09 10:21:58 INFO [backup.ha.hasource] Deleting 'core_2024.12.0b2' from Home Assistant
12-09 10:21:58 ERROR [backup.ui.uiserver] Error serving POST http://hass.mlghome.net/deleteSnapshot
12-09 10:21:58 ERROR [backup.ui.uiserver] 
  addon/backup/ha/harequests.py:105 (delete)
  addon/backup/ha/harequests.py:34 (wrap_and_call)
  addon/backup/ha/harequests.py:280 (_sendHassioData)
  addon/backup/ha/harequests.py:225 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1059 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://supervisor/backups/6b158d69')
Whose handling caused:
  addon/backup/ui/uiserver.py:801 (error_middleware)
  addon/backup/ui/uiserver.py:305 (deleteSnapshot)
  addon/backup/model/coordinator.py:295 (delete)
  addon/backup/model/coordinator.py:353 (_withSoftLock)
  addon/backup/model/coordinator.py:304 (_delete)
  addon/backup/ha/hasource.py:355 (delete)
  addon/backup/ha/harequests.py:34 (wrap_and_call)
  addon/backup/ha/harequests.py:111 (delete)
backup.exceptions.exceptions.HomeAssistantDeleteError

12-09 10:22:33 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
 ```
 ###### Supervisor Logs:
 ```
 [31m2024-12-09 10:06:19.116 ERROR (MainThread) [supervisor.backups.manager] Can't remove backup 6b158d69: [Errno 13] Permission denied: '/data/mounts/ArrayBU/6b158d69.tar'[0m
[32m2024-12-09 10:06:29.073 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:06:29.075 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:06:29.090 INFO (MainThread) [supervisor.api.middleware.security] /backups/6b158d69/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:06:29.385 INFO (MainThread) [supervisor.api.middleware.security] /backups/6b158d69 access from cebe7a76_hassio_google_drive_backup[0m
[31m2024-12-09 10:06:29.387 ERROR (MainThread) [supervisor.backups.manager] Can't remove backup 6b158d69: [Errno 13] Permission denied: '/data/mounts/ArrayBU/6b158d69.tar'[0m
[32m2024-12-09 10:09:09.665 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:09:09.667 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:09:09.682 INFO (MainThread) [supervisor.api.middleware.security] /backups/6b158d69/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:09:09.687 INFO (MainThread) [supervisor.api.middleware.security] /backups/6b158d69 access from cebe7a76_hassio_google_drive_backup[0m
[31m2024-12-09 10:09:09.689 ERROR (MainThread) [supervisor.backups.manager] Can't remove backup 6b158d69: [Errno 13] Permission denied: '/data/mounts/ArrayBU/6b158d69.tar'[0m
[33m2024-12-09 10:09:50.173 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[32m2024-12-09 10:14:29.835 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:14:29.837 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:14:29.855 INFO (MainThread) [supervisor.api.middleware.security] /backups/6b158d69/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:14:30.378 INFO (MainThread) [supervisor.api.middleware.security] /backups/6b158d69 access from cebe7a76_hassio_google_drive_backup[0m
[31m2024-12-09 10:14:30.381 ERROR (MainThread) [supervisor.backups.manager] Can't remove backup 6b158d69: [Errno 13] Permission denied: '/data/mounts/ArrayBU/6b158d69.tar'[0m
[33m2024-12-09 10:14:50.170 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[33m2024-12-09 10:19:50.170 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[33m2024-12-09 10:20:28.559 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[32m2024-12-09 10:21:58.954 INFO (MainThread) [supervisor.api.middleware.security] /backups/6b158d69 access from cebe7a76_hassio_google_drive_backup[0m
[31m2024-12-09 10:21:58.958 ERROR (MainThread) [supervisor.backups.manager] Can't remove backup 6b158d69: [Errno 13] Permission denied: '/data/mounts/ArrayBU/6b158d69.tar'[0m
[32m2024-12-09 10:22:51.706 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:22:51.957 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:22:52.169 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:22:52.172 INFO (MainThread) [supervisor.api.middleware.security] /core/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:22:52.173 INFO (MainThread) [supervisor.api.middleware.security] /core/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:22:52.212 INFO (MainThread) [supervisor.api.middleware.security] /core/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-09 10:22:52.336 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1320, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/yamaha/media_player.py", line 260, in update
    self._attr_is_volume_muted = self.zctrl.mute
                                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/rxv/rxv.py", line 764, in mute
    response = self._request('GET', request_text)
  File "/usr/local/lib/python3.13/site-packages/rxv/rxv.py", line 177, in _request
    res = self._session.post(
        self.ctrl_url,
    ...<2 lines>...
        timeout=self.http_timeout
    )
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[31m2024-12-09 10:21:53.837 ERROR (SyncWorker_2) [homeassistant.components.influxdb] InfluxDB database is not accessible due to '401: {"code":"unauthorized","message":"Unauthorized"}'. Please check that the database, username and password are correct and that the specified user has the correct permissions set. Retrying in 60 seconds.[0m

 ```
 
[home-assistant-google-drive-backup.log](https://github.com/user-attachments/files/18064503/home-assistant-google-drive-backup.log)
Copy the info from the previous page here

**Comment by sabeechen** [comment]
Sorry this took so long for me to respond, I had an unscheduled hiatus.  From the error in your supervisor logs:

```
2024-12-09 10:06:19.116 ERROR (MainThread) [supervisor.backups.manager] Can't remove backup 6b158d69: [Errno 13] Permission denied: '/data/mounts/ArrayBU/6b158d69.tar
```

Your network mount is blocking HA.  This could be ... a lot of things.  I get quite a few issues about NAS trouble, there isn't much I can do about it from the addon side.  HA needs to be able to talk to it for backup to work.
