### ISSUE TITLE
Google Drive Backup keeps stopping

### ISSUE THREAD

**Issue by apollojones** [sabeechen/hassio-google-drive-backup#1116]
Hello @sabeechen:

First of all, thanks for writing this add-on. It simplifies an potentially complex situation and makes backups easy.

I've been using it for some time without an issue, but just recently, the add-on just keeps stopping, showing as greyed out in my list of add-ons. Often I can just restart the add-on, but it always ends up stopping again. Sometimes when it has started, a backup can take place, and that might then make it to the end part of the process where a sync with Google Drive takes place.

The Supervisor log looks like this:

2024-12-14 12:16:07.882 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Home Assistant Google Drive Backup is failed, restarting...
2024-12-14 12:16:07.928 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_cebe7a76_hassio_google_drive_backup application
2024-12-14 12:16:33.470 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/sabeechen/hassio-google-drive-backup-aarch64 with version 0.112.1
2024-12-14 12:16:42.173 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:16:42.395 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:16:42.411 INFO (MainThread) [supervisor.api.middleware.security] /mounts access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:16:42.420 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:16:44.711 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:16:44.859 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:16:44.991 INFO (MainThread) [supervisor.api.middleware.security] /backups/8b2483a0/info access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:16:45.162 INFO (MainThread) [supervisor.api.middleware.security] /backups/b2d3ff30/info access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:18:24.650 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Home Assistant Google Drive Backup is failed, restarting...
2024-12-14 12:18:24.684 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_cebe7a76_hassio_google_drive_backup application
2024-12-14 12:19:03.230 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/sabeechen/hassio-google-drive-backup-aarch64 with version 0.112.1
2024-12-14 12:19:18.470 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:19:18.507 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:19:18.519 INFO (MainThread) [supervisor.api.middleware.security] /mounts access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:19:18.531 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:19:18.989 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:19:19.003 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:19:19.056 INFO (MainThread) [supervisor.api.middleware.security] /backups/8b2483a0/info access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:19:19.072 INFO (MainThread) [supervisor.api.middleware.security] /backups/b2d3ff30/info access from cebe7a76_hassio_google_drive_backup
2024-12-14 12:19:39.004 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-11796' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1491> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1505, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 291, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00

Actually, the Google Drive Backup log never really shows anything abnormal.

Could you provide some clues about what might be happening here? I'm finding it tricky to get into the issue in any depth to see what's happening.

Thanks in advance,
Mike,

**Comment by apollojones** [comment]
Just a few more points of clarification:
1. Once the add-on stops working it has never recovered by itself as far as I can see.
2. A full system restart including HW/Docker restart seems to provide the longest recovery, but still stops after some time.
3. Once working, the add-on syncs local backups to Drive as would be expected, presumably this process is effective as long as the add-on is working.
4. The failure mechanism seems elusive to me, but I'm not a full day-to-day SW expert so there may be other diagnosise that can be performed to surface the issues more clearly.

**Comment by apollojones** [comment]
Since the last Supervisor and OS updates have been installed this issue seems to have completely disappeared.

The add-on stays enabled all the time now, and backups take place as expected.

I am going to monitor this issue for a week or two now before closing the issue completely, and it does look like one of the rolled up improvements in either Supervisor or OS has fixed the issues I experienced.

Regards 
Mike.

**Comment by sabeechen** [comment]
I'm working through my backlog of unresponded issues, apologizes for not responding sooner.  I'm glad it started working for you, because I've never seen that error and have no idea what caused it!  Please re-open this issue if you think there is something I can help with.
