### ISSUE TITLE
back up occurs daily not every 7 days

### ISSUE THREAD

**Issue by briancrocker42** [sabeechen/hassio-google-drive-backup#1117]
the backups are occurring every day not every 7 days as I thought I had selected

Copy the info from the previous page 
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.112.1`
 Home Assistant Version: `2024.12.3`
 Supervisor Version: `2024.11.4`
 Supervisor Channel: `stable`
 Hassos Version: `14.0`
 Docker Version: `27.2.0`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2024-12-15T08:37:51.919357+00:00`
 Timezone: `Europe/London`
 Failure Time: `2024-12-13T07:15:17.374733+00:00`
 Last Good Sync: `2024-12-15T08:37:47.921820+00:00`
 Next Sync: `2024-12-15T11:14:40.209770+00:00`
 Next Backup: `2024-12-22T02:00:00+00:00`
 Next Cache Warm: `2024-12-15T11:07:24.279975+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2024-12-15T02:00:00Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 2,
        "detail": "",
        "size": "2.4 GB",
        "ignored_size": "841.1 MB",
        "free_space": "39.3 GB"
    },
    "GoogleDrive": {
        "backups": 6,
        "retained": 2,
        "deletable": 4,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2024-12-15T02:00:00Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "briancrocker42@gmail.com",
        "size": "3.2 GB",
        "ignored_size": "0.0 B",
        "free_space": "2.3 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.DAYS_BETWEEN_BACKUPS": 7.0,
    "Setting.DELETE_BEFORE_NEW_BACKUP": true,
    "Setting.BACKUP_TIME_OF_DAY": "02:00"
}
 ```
 ###### Addon Logs:
 ```
 12-15 02:07:52 DEBUG [backup.drive.driverequests] Sending 10 MB to Google Drive
12-15 02:07:58 DEBUG [backup.drive.drivesource] Uploading 2024-12-15 02:00:00 90.82%
12-15 02:07:58 DEBUG [backup.drive.driverequests] Sending 10 MB to Google Drive
12-15 02:08:04 DEBUG [backup.drive.drivesource] Uploading 2024-12-15 02:00:00 92.45%
12-15 02:08:04 DEBUG [backup.drive.driverequests] Sending 10 MB to Google Drive
12-15 02:08:11 DEBUG [backup.drive.drivesource] Uploading 2024-12-15 02:00:00 94.07%
12-15 02:08:11 DEBUG [backup.drive.driverequests] Sending 10 MB to Google Drive
12-15 02:08:17 DEBUG [backup.drive.drivesource] Uploading 2024-12-15 02:00:00 95.69%
12-15 02:08:17 DEBUG [backup.drive.driverequests] Sending 10 MB to Google Drive
12-15 02:08:23 DEBUG [backup.drive.drivesource] Uploading 2024-12-15 02:00:00 97.31%
12-15 02:08:23 DEBUG [backup.drive.driverequests] Sending 10 MB to Google Drive
12-15 02:08:29 DEBUG [backup.drive.drivesource] Uploading 2024-12-15 02:00:00 98.93%
12-15 02:08:30 DEBUG [backup.drive.driverequests] Sending 6.595703125 MB to Google Drive
12-15 02:08:35 DEBUG [backup.drive.drivesource] Uploading 2024-12-15 02:00:00 100.00%
12-15 02:08:36 DEBUG [backup.watcher] Checking backup source for changes...
12-15 02:08:36 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
12-15 02:08:36 INFO [backup.model.coordinator] Syncing Backups
12-15 04:10:58 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
12-15 04:10:58 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
12-15 04:19:23 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-15 04:19:23 INFO [backup.model.coordinator] Syncing Backups
12-15 05:51:00 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
12-15 05:51:00 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
12-15 05:57:53 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-15 05:57:53 INFO [backup.model.coordinator] Syncing Backups
12-15 07:44:02 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
12-15 07:44:02 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
12-15 07:53:42 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-15 07:53:42 INFO [backup.model.coordinator] Syncing Backups
12-15 08:37:47 INFO [backup.model.coordinator] Syncing Backups
 ```
 ###### Supervisor Logs:
 ```
 [32m2024-12-15 08:32:22.002 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode[0m
[32m2024-12-15 08:32:22.017 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m2024-12-15 08:32:22.025 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode[0m
[32m2024-12-15 08:32:22.187 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m2024-12-15 08:32:22.189 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m2024-12-15 08:32:22.348 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m2024-12-15 08:32:22.357 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode[0m
[32m2024-12-15 08:32:22.394 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m2024-12-15 08:32:25.938 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m2024-12-15 08:32:25.948 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered[0m
[32m2024-12-15 08:32:26.173 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m2024-12-15 08:32:26.216 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m2024-12-15 08:32:26.223 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode[0m
[32m2024-12-15 08:32:26.443 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m2024-12-15 08:32:26.580 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m2024-12-15 08:32:26.593 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode[0m
[32m2024-12-15 08:32:26.681 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m2024-12-15 08:32:26.859 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m2024-12-15 08:32:26.866 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode[0m
[32m2024-12-15 08:32:26.871 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant Core state changed to APIState(core_state='RUNNING', offline_db_migration=False)[0m
[32m2024-12-15 08:32:26.871 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance[0m
[32m2024-12-15 08:32:26.989 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m2024-12-15 08:36:56.234 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-15 08:36:56.240 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-15 08:36:56.246 INFO (MainThread) [supervisor.api.middleware.security] /mounts access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-15 08:36:56.250 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-15 08:37:47.925 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-15 08:37:47.933 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m2024-12-15 08:37:51.951 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2355, in forgiving_float_filter
    raise_no_default("float", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1909, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% set T = states('sensor.lanyard_mini_hygrometer_009f_temperature') | float %} {% set RH = states('sensor.rochester_stoke_united_kingdom_humidity')|float %} {% set SVP = 0.61078 * e ** (17.2694 * T / (T + 238.3)) %} {% set VPD = ((100-RH) / 100) * SVP %} {{-VPD | round(2) -}}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 748, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 633, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% set T = states('sensor.lanyard_mini_hygrometer_009f_temperature') | float %} {% set RH = states('sensor.rochester_stoke_united_kingdom_humidity')|float %} {% set SVP = 0.61078 * e ** (17.2694 * T / (T + 238.3)) %} {% set VPD = ((100-RH) / 100) * SVP %} {{-VPD | round(2) -}}' but no default was specified[0m
[31m2024-12-15 08:32:21.244 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% set T = states('sensor.lanyard_mini_hygrometer_009f_temperature') | float %} {% set RH = states('sensor.rochester_stoke_united_kingdom_humidity')|float %} {% set SVP = 0.61078 * e ** (17.2694 * T / (T + 238.3)) %} {% set VPD = ((100-RH) / 100) * SVP %} {{-VPD | round(2) -}}' but no default was specified') while processing template 'Template<template=({% set T = states('sensor.lanyard_mini_hygrometer_009f_temperature') | float %} {% set RH = states('sensor.rochester_stoke_united_kingdom_humidity')|float %} {% set SVP = 0.61078 * e ** (17.2694 * T / (T + 238.3)) %} {% set VPD = ((100-RH) / 100) * SVP %} {{-VPD | round(2) -}}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.vapor_deficit_2'[0m
[31m2024-12-15 08:36:28.580 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ states('sensor.solis_ac_output_total_power') | float + states('sensor.octopus_import') | float - states('sensor.ct_clamp_2') | float }}' but no default was specified') while processing template 'Template<template=({{ states('sensor.solis_ac_output_total_power') | float + states('sensor.octopus_import') | float - states('sensor.ct_clamp_2') | float }}) renders=12>' for attribute '_attr_native_value' in entity 'sensor.combined_power'[0m

 ```

**Comment by sabeechen** [comment]
Apologies for the late response, I'm working my way through the backlog of all my unresponded issues after a hiatus.

Nothing looks out or ordinary about your setup.  Right now I'm triaging issues that could be bugs for further digging and this has caught my attention.

**Comment by briancrocker42** [comment]
Thank you so much for looking at this. I now realise I had
forgotten automation running. Very sorry for raising a false issue.

Brian
