### ISSUE TITLE
"certificate verify failed: certificate has expired" while connecting to www.googleapis.com

### ISSUE THREAD

**Issue by coolcasa** [sabeechen/hassio-google-drive-backup#141]
Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 103, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 120, in sync
    self._syncSnapshots([self.source, self.dest])
  File "/app/backup/model.py", line 192, in _syncSnapshots
    from_source: Dict[str, AbstractSnapshot] = source.get()
  File "/app/backup/drivesource.py", line 73, in get
    self._info.drive_folder_id = self.getFolderId()
  File "/app/backup/drivesource.py", line 70, in getFolderId
    return self._getParentFolderId()
  File "/app/backup/drivesource.py", line 169, in _getParentFolderId
    self._folderId = self._validateFolderId()
  File "/app/backup/drivesource.py", line 187, in _validateFolderId
    if self._verifyBackupFolderWithQuery(folder_id):
  File "/app/backup/drivesource.py", line 154, in _verifyBackupFolderWithQuery
    folder = self._get(id)
  File "/app/backup/drivesource.py", line 192, in _get
    return self.drivebackend.get(id)
  File "/app/backup/driverequests.py", line 151, in get
    return self.retryRequest("GET", URL_FILES + id + "/?" + urlencode(q), is_json=True)
  File "/app/backup/driverequests.py", line 301, in retryRequest
    send_headers = self._getHeaders(refresh=refresh_token)
  File "/app/backup/driverequests.py", line 80, in _getHeaders
    "Authorization": "Bearer " + self.getToken(refresh=refresh),
  File "/app/backup/driverequests.py", line 137, in getToken
    resp = self.retryRequest("POST", URL_AUTH, is_json=True, data=data, auth_headers=self._getAuthHeaders(), cred_retry=False)
  File "/app/backup/driverequests.py", line 322, in retryRequest
    raise e
  File "/app/backup/driverequests.py", line 309, in retryRequest
    response = self._request_client.request(method, url, headers=send_headers, json=json, timeout=self.config.get(Setting.GOOGLE_DRIVE_TIMEOUT_SECONDS), data=data, stream=stream)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /oauth2/v4/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)')))

An unexpected error occurred: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /oauth2/v4/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)')))

**Comment by sabeechen** [comment]
If I'm reading this correctly, then your installation rejected google's SSL certificate when it tried to connect with Drive.  Thats very strange, because Google does a really good job of setting this kind of stuff up.  If I had to guess, I'd say:
1. There are some misconfigured DNS settings on your network.
2. Its just a transient error.

If its just a transient error you should see it go away if you restart the addon.  If its a DNS issue, you could rule that out by going to the add-on settings (gear icon at the top) and setting "172.217.8.170" for "Google IP Address Override" at the bottom.

**Comment by sabeechen** [comment]
Closing this out due to age, but if you think there is more I can do to help, feel free to reopen.
