### ISSUE TITLE
An unexpected error occurred: Remote end closed connection without response

### ISSUE THREAD

**Issue by fareek2** [sabeechen/hassio-google-drive-backup#159]
Please add some information about your configuration and the problem you ran into here. 
More info really helps speed up debugging, if you don't even read this and help me understand what happened, I probably won't help you.  
Remember that its just one guy back here doing all of this.  
If english isn't your first language, don't sweat it.  Just try to be clear and I'll do the same for you.  Some things you might consider including:
 * What were you doing when the problem happened?
 * A screenshot if its something visual.
 * What configuration options are you using with the add-on?
 * What logs is the add-on printing out?  You can see the detailed logs by clicking "Logs" at the right of the web-UI.
 * Are there any problematic looking logs from the Hassio supervisor?  You can get to them from the Home Assistant Interface from "Hass.io" > "System" > "System Log"
 

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 109, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 155, in sync
    upload.addSource(self.dest.save(upload, self.source.read(upload)))
  File "/app/backup/hasource.py", line 219, in read
    return self.harequests.download(item.slug())
  File "/app/backup/harequests.py", line 95, in download
    return SeekableRequest(url, self._getHassioHeaders()).prepare()
  File "/app/backup/seekablerequest.py", line 31, in prepare
    self.size()
  File "/app/backup/seekablerequest.py", line 36, in size
    self._size = self._getContentLength()
  File "/app/backup/seekablerequest.py", line 119, in _getContentLength
    f = urlopen(req)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1348, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.8/urllib/request.py", line 1323, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

An unexpected error occurred: Remote end closed connection without response

**Comment by sabeechen** [comment]
This is a transient error that can happen sometimes if your internet dies for a moment or a number of other reasons.  Did the addon resume uploading and work properly afterward?  I'd need more detail about what you were doing to dig into this.

**Comment by sabeechen** [comment]
Closing this for now, but feel free to reopen if you think there is some more help I can with.
