### ISSUE TITLE
404 client error at first install

### ISSUE THREAD

**Issue by Klagio** [sabeechen/hassio-google-drive-backup#168]
the log

03-19 15:20:06 DEBUG Making Hassio request: http://hassio/addons/self/info
03-19 15:20:06 DEBUG Making Hassio request: http://hassio/info
03-19 15:20:06 DEBUG Making Hassio request: http://hassio/homeassistant/info
03-19 15:20:06 DEBUG Making Hassio request: http://hassio/supervisor/info
03-19 15:20:06 INFO Starting server on port 8099
03-19 15:20:06 INFO Server started
03-19 15:20:06 DEBUG Sync requested by Coordinator
03-19 15:20:06 INFO Syncing Snapshots
03-19 15:20:06 DEBUG Making Hassio request: http://hassio/snapshots
03-19 15:20:06 DEBUG Making Hassio request: http://hassio/snapshots/ac02e91e/info
03-19 15:21:32 INFO Saving new Google Drive credentials
03-19 15:21:32 DEBUG Sync requested by GoogleDrive
03-19 15:21:32 INFO Syncing Snapshots
03-19 15:21:32 DEBUG Making Hassio request: http://hassio/snapshots
03-19 15:21:32 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
03-19 15:21:32 ERROR    
Traceback (most recent call last):   
  File "/app/backup/coordinator.py", line 109, in _sync   
    self._buildModel().sync(self._time.now())   
  File "/app/backup/model.py", line 127, in sync   
    self._syncSnapshots([self.source, self.dest])   
  File "/app/backup/model.py", line 205, in _syncSnapshots   
    from_source: Dict[str, AbstractSnapshot] = source.get()   
  File "/app/backup/drivesource.py", line 86, in get   
    self._info.drive_folder_id = self.getFolderId()   
  File "/app/backup/drivesource.py", line 79, in getFolderId   
    return self._getParentFolderId()   
  File "/app/backup/drivesource.py", line 204, in _getParentFolderId   
    self._folderId = self._validateFolderId()   
  File "/app/backup/drivesource.py", line 230, in _validateFolderId   
    return self._findDriveFolder()   
  File "/app/backup/drivesource.py", line 238, in _findDriveFolder   
    for child in self.drivebackend.query("mimeType='" + FOLDER_MIME_TYPE + "'"):   
  File "/app/backup/driverequests.py", line 173, in query   
    response = self.retryRequest("GET", URL_FILES + "?" + urlencode(q), is_json=True)   
  File "/app/backup/driverequests.py", line 358, in retryRequest   
    response.raise_for_status()   
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status   
    raise HTTPError(http_error_msg, response=self)   
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives   
   

03-19 15:21:32 INFO I'll try syncing again right now
03-19 15:21:33 DEBUG Sync requested by Coordinator
03-19 15:21:33 INFO Syncing Snapshots
03-19 15:21:33 DEBUG Making Hassio request: http://hassio/snapshots
03-19 15:21:33 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
03-19 15:21:33 ERROR    
Traceback (most recent call last):   
  File "/app/backup/coordinator.py", line 109, in _sync   
    self._buildModel().sync(self._time.now())   
  File "/app/backup/model.py", line 127, in sync   
    self._syncSnapshots([self.source, self.dest])   
  File "/app/backup/model.py", line 205, in _syncSnapshots   
    from_source: Dict[str, AbstractSnapshot] = source.get()   
  File "/app/backup/drivesource.py", line 86, in get   
    self._info.drive_folder_id = self.getFolderId()   
  File "/app/backup/drivesource.py", line 79, in getFolderId   
    return self._getParentFolderId()   
  File "/app/backup/drivesource.py", line 204, in _getParentFolderId   
    self._folderId = self._validateFolderId()   
  File "/app/backup/drivesource.py", line 230, in _validateFolderId   
    return self._findDriveFolder()   
  File "/app/backup/drivesource.py", line 238, in _findDriveFolder   
    for child in self.drivebackend.query("mimeType='" + FOLDER_MIME_TYPE + "'"):   
  File "/app/backup/driverequests.py", line 173, in query   
    response = self.retryRequest("GET", URL_FILES + "?" + urlencode(q), is_json=True)   
  File "/app/backup/driverequests.py", line 358, in retryRequest   
    response.raise_for_status()   
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status   
    raise HTTPError(http_error_msg, response=self)   
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives   
   

03-19 15:21:33 INFO I'll try syncing again in 10 seconds
03-19 15:21:43 DEBUG Sync requested by Coordinator
03-19 15:21:43 INFO Syncing Snapshots
03-19 15:21:43 DEBUG Making Hassio request: http://hassio/snapshots
03-19 15:21:43 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
03-19 15:21:44 ERROR    
Traceback (most recent call last):   
  File "/app/backup/coordinator.py", line 109, in _sync   
    self._buildModel().sync(self._time.now())   
  File "/app/backup/model.py", line 127, in sync   
    self._syncSnapshots([self.source, self.dest])   
  File "/app/backup/model.py", line 205, in _syncSnapshots   
    from_source: Dict[str, AbstractSnapshot] = source.get()   
  File "/app/backup/drivesource.py", line 86, in get   
    self._info.drive_folder_id = self.getFolderId()   
  File "/app/backup/drivesource.py", line 79, in getFolderId   
    return self._getParentFolderId()   
  File "/app/backup/drivesource.py", line 204, in _getParentFolderId   
    self._folderId = self._validateFolderId()   
  File "/app/backup/drivesource.py", line 230, in _validateFolderId   
    return self._findDriveFolder()   
  File "/app/backup/drivesource.py", line 238, in _findDriveFolder   
    for child in self.drivebackend.query("mimeType='" + FOLDER_MIME_TYPE + "'"):   
  File "/app/backup/driverequests.py", line 173, in query   
    response = self.retryRequest("GET", URL_FILES + "?" + urlencode(q), is_json=True)   
  File "/app/backup/driverequests.py", line 358, in retryRequest   
    response.raise_for_status()   
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status   
    raise HTTPError(http_error_msg, response=self)   
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives   
   

03-19 15:21:44 INFO I'll try syncing again in 20 seconds

**Comment by sabeechen** [comment]
I've seen this before when someone installs the addon but has never visited Google Drive before.   If you haven't, please visit [https://drive.google.com](https://drive.google.com) and log in with the same account you used to connect the addon.  Wait a few seconds, then click "Sync Now" on the addon (or just wait for it to retry).

I should add a better help message for this when the addon sees it.

**Comment by sabeechen** [comment]
I've added better messaging for this in the latest version (0.101.0) so new users should see some guidance when it happens.
