### ISSUE TITLE
Do not sync Snapshots to Google Drive: An unexpected error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/oauth2/v4/token

### ISSUE THREAD

**Issue by NapalmCandy** [sabeechen/hassio-google-drive-backup#170]
* What were you doing when the problem happened? Nothing, it doesn't sync for days, I tried to decline authorization and give it again
 * What configuration options are you using with the add-on? Sync every day at 3:00am
 * What logs is the add-on printing out?  You can see the detailed logs by clicking "Logs" at the right of the web-UI..... Don't understand what you are asking
 * Are there any problematic looking logs from the Hassio supervisor?  You can get to them from the Home Assistant Interface from "Hass.io" > "System" > "System Log"
 

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 109, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 127, in sync
    self._syncSnapshots([self.source, self.dest])
  File "/app/backup/model.py", line 205, in _syncSnapshots
    from_source: Dict[str, AbstractSnapshot] = source.get()
  File "/app/backup/drivesource.py", line 86, in get
    self._info.drive_folder_id = self.getFolderId()
  File "/app/backup/drivesource.py", line 79, in getFolderId
    return self._getParentFolderId()
  File "/app/backup/drivesource.py", line 204, in _getParentFolderId
    self._folderId = self._validateFolderId()
  File "/app/backup/drivesource.py", line 222, in _validateFolderId
    if self._verifyBackupFolderWithQuery(folder_id):
  File "/app/backup/drivesource.py", line 200, in _verifyBackupFolderWithQuery
    raise e
  File "/app/backup/drivesource.py", line 189, in _verifyBackupFolderWithQuery
    folder = self._get(id)
  File "/app/backup/drivesource.py", line 233, in _get
    return self.drivebackend.get(id)
  File "/app/backup/driverequests.py", line 154, in get
    return self.retryRequest("GET", URL_FILES + id + "/?" + urlencode(q), is_json=True)
  File "/app/backup/driverequests.py", line 304, in retryRequest
    send_headers = self._getHeaders(refresh=refresh_token)
  File "/app/backup/driverequests.py", line 80, in _getHeaders
    "Authorization": "Bearer " + self.getToken(refresh=refresh),
  File "/app/backup/driverequests.py", line 143, in getToken
    raise e
  File "/app/backup/driverequests.py", line 140, in getToken
    resp = self.retryRequest("POST", URL_AUTH, is_json=True, data=data, auth_headers=self._getAuthHeaders(), cred_retry=False)
  File "/app/backup/driverequests.py", line 358, in retryRequest
    response.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.googleapis.com/oauth2/v4/token

An unexpected error occurred: 400 Client Error: Bad Request for url: https://www.googleapis.com/oauth2/v4/token

**Comment by NapalmCandy** [comment]
After 15 days, I still have the problem.

I tried to reinstall, then I saw your repository it is not in my Hass.io, but when I try to add it do nothing. I can't add your repository don't show any error. So I can't reinstall.

Also it don't appears on Supervisor->Dashboard->Add-ons, but I can open from the side bar.

Please, can you help me?
