### ISSUE TITLE
Upload Problems

### ISSUE THREAD

**Issue by stibe881** [sabeechen/hassio-google-drive-backup#176]
i have this error message when i try to upload a snapshot:

Error details

Traceback (most recent call last):
  File "/app/backup/uiserver.py", line 574, in handleError
    return call()
  File "/app/backup/uiserver.py", line 490, in <lambda>
    return self.handleError(lambda: self._upload(slug))
  File "/app/backup/uiserver.py", line 493, in _upload
    self._coord.uploadSnapshot(slug)
  File "/app/backup/coordinator.py", line 147, in uploadSnapshot
    self._withSoftLock(lambda: self._uploadSnapshot(slug))
  File "/app/backup/coordinator.py", line 239, in _withSoftLock
    return callable()
  File "/app/backup/coordinator.py", line 147, in <lambda>
    self._withSoftLock(lambda: self._uploadSnapshot(slug))
  File "/app/backup/coordinator.py", line 159, in _uploadSnapshot
    created = self._model.source.save(snapshot, self._model.dest.read(snapshot))
  File "/app/backup/hasource.py", line 215, in save
    raise UploadFailed()
backup.exceptions.UploadFailed

can anyone help me?

Thanks

**Comment by sabeechen** [comment]
You'll probably want to check your supervisor logs, `Supervisor` > `System` > `Logs` > `Refresh` Right after you see the upload fail.  That error almost always means the Home Assistant Supervisor rejected the snapshot for some reason and the only way to get a clue why is in the supervisor logs.   Make sure you're machine also has at least twice the free space needed to store the snapshot.

**Comment by sabeechen** [comment]
I'm closing out old issues, if there is any other way I can help feel free to reopen this.
