### ISSUE TITLE
An unexpected error occurred: HTTPSConnectionPool(host='www.googleapis.com', port=443): Read timed out.

### ISSUE THREAD

**Issue by badamchuk** [sabeechen/hassio-google-drive-backup#177]
Please add some information about your configuration and the problem you ran into here. 
More info really helps speed up debugging, if you don't even read this and help me understand what happened, I probably won't help you.  
Remember that its just one guy back here doing all of this.  
If english isn't your first language, don't sweat it.  Just try to be clear and I'll do the same for you.  Some things you might consider including:
 * What were you doing when the problem happened?
 * A screenshot if its something visual.
 * What configuration options are you using with the add-on?
 * What logs is the add-on printing out?  You can see the detailed logs by clicking "Logs" at the right of the web-UI.
 * Are there any problematic looking logs from the Hassio supervisor?  You can get to them from the Home Assistant Interface from "Hass.io" > "System" > "System Log"
 

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 109, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 127, in sync
    self._syncSnapshots([self.source, self.dest])
  File "/app/backup/model.py", line 205, in _syncSnapshots
    from_source: Dict[str, AbstractSnapshot] = source.get()
  File "/app/backup/drivesource.py", line 86, in get
    self._info.drive_folder_id = self.getFolderId()
  File "/app/backup/drivesource.py", line 79, in getFolderId
    return self._getParentFolderId()
  File "/app/backup/drivesource.py", line 204, in _getParentFolderId
    self._folderId = self._validateFolderId()
  File "/app/backup/drivesource.py", line 230, in _validateFolderId
    return self._findDriveFolder()
  File "/app/backup/drivesource.py", line 238, in _findDriveFolder
    for child in self.drivebackend.query("mimeType='" + FOLDER_MIME_TYPE + "'"):
  File "/app/backup/driverequests.py", line 173, in query
    response = self.retryRequest("GET", URL_FILES + "?" + urlencode(q), is_json=True)
  File "/app/backup/driverequests.py", line 325, in retryRequest
    raise e
  File "/app/backup/driverequests.py", line 312, in retryRequest
    response = self._request_client.request(method, url, headers=send_headers, json=json, timeout=self.config.get(Setting.GOOGLE_DRIVE_TIMEOUT_SECONDS), data=data, stream=stream)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 757, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Read timed out.

An unexpected error occurred: HTTPSConnectionPool(host='www.googleapis.com', port=443): Read timed out.

**Comment by sabeechen** [comment]
Please read an answer some of the questions in the bug template and reopen if this continues to be a problem for you.
