### ISSUE TITLE
Unable to Start Google Drive Backup

### ISSUE THREAD

**Issue by Guyanthalas** [sabeechen/hassio-google-drive-backup#197]
Hassio 111.0

Trying to start, but it doesn't start. Gives this error:
`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/backup/__main__.py", line 11, in <module>
    from .uiserver import UIServer
  File "/app/backup/uiserver.py", line 3, in <module>
    import cherrypy
  File "/usr/lib/python3.8/site-packages/cherrypy/__init__.py", line 76, in <module>
    from . import _cprequest, _cpserver, _cptree, _cplogging, _cpconfig
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 13, in <module>
    from cherrypy import _cpreqbody
  File "/usr/lib/python3.8/site-packages/cherrypy/_cpreqbody.py", line 120, in <module>
    import cheroot.server
  File "/usr/lib/python3.8/site-packages/cheroot/server.py", line 87, in <module>
    from . import connections, errors, __version__
  File "/usr/lib/python3.8/site-packages/cheroot/connections.py", line 13, in <module>
    from .makefile import MakeFile
  File "/usr/lib/python3.8/site-packages/cheroot/makefile.py", line 10, in <module>
    import _pyio as io
ValueError: source code string cannot contain null bytes`

**Comment by sabeechen** [comment]
Thats a really weird error, something is wrong with the python runtime.

Was the addon working previously and it just stopped?  Or did you update hass.io and it failed?

The safest thing to do would be to uninstall and reinstall the addon, it looks to me like somehow the addon's docker image got corrupted.

**Comment by Guyanthalas** [comment]
That was silly of me, I'm not sure why I didn't try doing that before posting here. Long days at work I guess. 🙄 Either way, looks like its working. Thanks for the quick response!

**Comment by sabeechen** [comment]
No worries, glad it worked out.  I'd be curious to know if you run into this again.  I can't explain how this could have happened in the first place.

**Comment by Guyanthalas** [comment]
That sums up the majority of the errors I've had with Home Assistant, God bless it. ;) I assume it happened after an upgrade, but my particular unit is experiencing all kinds of problems (unrelated to this backup solution). I'll keep you posted if it crops up again.

**Comment by sabeechen** [comment]
Just a heads up that this error *could* be explained by disk corruption, which would also cause a flood of other random problems.
