### ISSUE TITLE
Webui logs give "401 unauthorized"

### ISSUE THREAD

**Issue by jugoke1** [sabeechen/hassio-google-drive-backup#227]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" 
above and write it here. 

  I get a "401 unauthorized" when trying to read logs in webui.
```

 Addon version: `0.101.1`
 Home Assistant Version: `0.113.3`
 Supervisor Version: `234`
 Architecture: `amd64`
 Date: `2020-08-18T08:05:49.967994+00:00`
 Timezone: `Europe/Brussels`
 Failure Time: `Never`
 Last Good Sync: `2020-08-18T08:02:49.070060+00:00`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 14,
        "retained": 1,
        "deletable": 13,
        "name": "HomeAssistant",
        "latest": "2020-08-14T14:17:46Z",
        "size": "26.3 MB"
    },
    "GoogleDrive": {
        "snapshots": 35,
        "retained": 2,
        "deletable": 33,
        "name": "GoogleDrive",
        "latest": "2020-08-14T14:17:46Z",
        "size": "54.9 MB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 0,
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 0,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 7.0,
    "Setting.SNAPSHOT_NAME": "REDACTED",
    "Setting.SNAPSHOT_TIME_OF_DAY": "09:30",
    "Setting.SPECIFY_SNAPSHOT_FOLDER": true
}
 ```
 ###### Addon Logs:
 ```
 08-18 09:58:49 INFO [backup.ui.uiserver] Server started
08-18 09:58:49 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-18 09:58:49 INFO [backup.model.coordinator] Syncing Snapshots
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/f1916817/info
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/807d3d6c/info
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/1837c4f9/info
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/65c8413b/info
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/605fd447/info
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/287a53bd/info
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/1a96f73e/info
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/7a10df37/info
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/7e818b52/info
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/9160a448/info
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/0bbc7e81/info
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/a1042841/info
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/9930aed8/info
08-18 09:58:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/ad3360c5/info
08-18 09:58:49 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-18 09:58:50 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1fiGvobJ7_1HihhhGc843vGdUehOtLk6U/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
08-18 09:58:50 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271fiGvobJ7_1HihhhGc843vGdUehOtLk6U%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-18 09:59:38 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
08-18 09:59:38 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
08-18 09:59:38 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/homeassistant/info
08-18 09:59:38 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
08-18 10:02:48 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/options
08-18 10:02:49 INFO [backup.model.coordinator] Syncing Snapshots
08-18 10:02:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-18 10:02:49 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1fiGvobJ7_1HihhhGc843vGdUehOtLk6U/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
08-18 10:02:49 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271fiGvobJ7_1HihhhGc843vGdUehOtLk6U%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
 ```
 ###### Supervisor Logs:
 ```
 [32m20-08-18 07:58:49 INFO (MainThread) [supervisor.api.security] /snapshots/1837c4f9/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-18 07:58:49 INFO (MainThread) [supervisor.api.security] /snapshots/65c8413b/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-18 07:58:49 INFO (MainThread) [supervisor.api.security] /snapshots/605fd447/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-18 07:58:49 INFO (MainThread) [supervisor.api.security] /snapshots/287a53bd/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-18 07:58:49 INFO (MainThread) [supervisor.api.security] /snapshots/1a96f73e/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-18 07:58:49 INFO (MainThread) [supervisor.api.security] /snapshots/7a10df37/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-18 07:58:49 INFO (MainThread) [supervisor.api.security] /snapshots/7e818b52/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-18 07:58:49 INFO (MainThread) [supervisor.api.security] /snapshots/9160a448/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-18 07:58:49 INFO (MainThread) [supervisor.api.security] /snapshots/0bbc7e81/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-18 07:58:49 INFO (MainThread) [supervisor.api.security] /snapshots/a1042841/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-18 07:58:49 INFO (MainThread) [supervisor.api.security] /snapshots/9930aed8/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-18 07:58:49 INFO (MainThread) [supervisor.api.security] /snapshots/ad3360c5/info access from cebe7a76_hassio_google_drive_backup[0m
[33m20-08-18 07:59:20 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m20-08-18 07:59:25 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[32m20-08-18 07:59:38 INFO (MainThread) [supervisor.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-18 07:59:38 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-18 08:02:49 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[33m20-08-18 08:03:09 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[32m20-08-18 08:04:28 INFO (MainThread) [supervisor.host.info] Update local host information[0m
[32m20-08-18 08:04:28 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1[0m
[33m20-08-18 08:04:30 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[32m20-08-18 08:04:30 INFO (MainThread) [supervisor.host.services] Update service information[0m
[32m20-08-18 08:04:30 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1[0m
[32m20-08-18 08:04:31 INFO (MainThread) [supervisor.host.network] Update local network DNS information[0m
[32m20-08-18 08:04:31 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager[0m
[32m20-08-18 08:04:31 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information[0m
[33m20-08-18 08:05:00 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m20-08-18 08:05:29 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[32m20-08-18 08:05:49 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: must contain at least one of entity_id, area_id.
2020-08-17 20:21:23 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140453784740480] must contain at least one of entity_id, area_id.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 122, in validate
    raise vol.Invalid("must contain at least one of {}.".format(", ".join(keys)))
voluptuous.error.Invalid: must contain at least one of entity_id, area_id.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 208, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: must contain at least one of entity_id, area_id.

 ```
  the info from the previous page here

**Comment by sabeechen** [comment]
The addon logs you posted don't contain the error.  In fact, it looks like the addon is humming along well.  Did you restart the addon before taking a snapshot of the issue?  The logs get deleted when you restart the addon.

**Comment by sabeechen** [comment]
I'm closing this for now, but if you can find and post the error I can take a look at it.

**Comment by jugoke1** [comment]
after i restarted homeassistant  and when i open the webui "logs" no logs are shown 
but i get the following messages instead of 401 unauthorized 
see attachment 

[home-assistant-google-drive-backup_20082020.log](https://github.com/sabeechen/hassio-google-drive-backup/files/5102022/home-assistant-google-drive-backup_20082020.log)

**Comment by sabeechen** [comment]
I can see in the log that it got an error trying to update the Home Assistant sensors, but it looks like it suceeded on subsequent attempts.  Getting an error once in a while trying to reach Home Assistant is normal (especially if you're restarting it), its only a problem if you see it persistently.

Is the addon actually doing something wrong, or is this bug just about seeing the error message?
