### ISSUE TITLE
Error with Supervisor - Huge Snapshot size

### ISSUE THREAD

**Issue by FaserF** [sabeechen/hassio-google-drive-backup#250]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
Since some days my backup size "exploded". Normally its around 90MB, now its over 2GB. And since that day I am also getting everyday a message from this addon.
I am unable to sync my backups. I have checked the following:

- Exclude useless stuff from being backed up
- Reinstalled the addon
- Deleted all Snapshots on HA
- Tried a manual sync
```

 Addon version: `0.101.2`
 Home Assistant Version: `0.114.3`
 Supervisor Version: `None`
 Supervisor Channel: `stable`
 Hassos Version: `None`
 Docker Version: `None`
 Architecture: `armv7`
 Machine: `None`
 Date: `2020-08-31T12:13:58.744663+00:00`
 Timezone: `Europe/Berlin`
 Failure Time: `2020-08-31T12:13:51.169496+00:00`
 Last Good Sync: `2020-08-31T12:13:55.020779+00:00`
 ###### Exception:
 ```
 
  addon/backup/util/asynchttpgetter.py:133 (read)
  /site-packages/aiohttp/streams.py:416 (readexactly)
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
Whose handling caused:
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:162 (sync)
  addon/backup/drive/drivesource.py:148 (save)
  addon/backup/drive/driverequests.py:252 (create)
  addon/backup/util/asynchttpgetter.py:140 (read)
backup.exceptions.exceptions.SupervisorUnexpectedError

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 1,
        "retained": 0,
        "deletable": 1,
        "name": "HomeAssistant",
        "latest": "2020-08-31T01:02:34Z",
        "size": "2.3 GB"
    },
    "GoogleDrive": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "GoogleDrive",
        "latest": "2020-08-25T01:27:31Z",
        "size": "335.2 MB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 1,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 1.0,
    "Setting.USE_SSL": true
}
 ```
 ###### Addon Logs:
 ```
 08-31 14:13:45 DEBUG [backup.worker.watcher] Backup directory modified event
08-31 14:13:45 INFO [backup.drive.drivesource] Uploading 'Partial Snapshot 2020-08-31 03:02:32' to Google Drive
08-31 14:13:45 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
08-31 14:13:45 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
08-31 14:13:45 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
08-31 14:13:45 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
08-31 14:13:45 INFO [backup.model.coordinator] I'll try again in an hour
08-31 14:13:48 INFO [backup.model.coordinator] Syncing Snapshots
08-31 14:13:48 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-31 14:13:48 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271VH1lSvaMwY62T8gAuATtSn5p7HPJL13y%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-31 14:13:49 INFO [backup.drive.drivesource] Uploading 'Partial Snapshot 2020-08-31 03:02:32' to Google Drive
08-31 14:13:49 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
08-31 14:13:49 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uy4NTMbKPNZxHcB5WINkIhLENa1JaiN07K-agTBz74Bwa9fse1DOUJT_65mCtmZR-610e2yil9emJW4st6Aqbs
08-31 14:13:49 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2456944640
08-31 14:13:49 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
08-31 14:13:49 INFO [backup.model.coordinator] I'll try again in an hour
08-31 14:13:50 INFO [backup.worker.watcher] Backup directory changed
08-31 14:13:50 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
08-31 14:13:50 INFO [backup.model.coordinator] Syncing Snapshots
08-31 14:13:50 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-31 14:13:50 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271VH1lSvaMwY62T8gAuATtSn5p7HPJL13y%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-31 14:13:51 INFO [backup.drive.drivesource] Uploading 'Partial Snapshot 2020-08-31 03:02:32' to Google Drive
08-31 14:13:51 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
08-31 14:13:51 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uy4NTMbKPNZxHcB5WINkIhLENa1JaiN07K-agTBz74Bwa9fse1DOUJT_65mCtmZR-610e2yil9emJW4st6Aqbs
08-31 14:13:51 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2456944640
08-31 14:13:51 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
08-31 14:13:51 INFO [backup.model.coordinator] I'll try again in an hour
08-31 14:13:55 INFO [backup.model.coordinator] Syncing Snapshots
08-31 14:13:55 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-31 14:13:55 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271VH1lSvaMwY62T8gAuATtSn5p7HPJL13y%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
 ```
 ###### Supervisor Logs:
 ```
 [32m20-08-31 12:12:34 INFO (SyncWorker_6) [supervisor.docker.interface] Clean addon_cebe7a76_hassio_google_drive_backup application[0m
[32m20-08-31 12:12:35 INFO (SyncWorker_2) [supervisor.docker.addon] Start Docker add-on sabeechen/hassio-google-drive-backup-armv7 with version 3.12[0m
[32m20-08-31 12:12:37 INFO (MainThread) [supervisor.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:12:37 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:12:37 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:12:37 INFO (MainThread) [supervisor.api.security] /snapshots/081ecbfd/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:12:37 INFO (MainThread) [supervisor.api.security] /snapshots/3acdc48e/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:12:50 INFO (SyncWorker_7) [supervisor.docker.interface] Stop addon_cebe7a76_hassio_google_drive_backup application[0m
[32m20-08-31 12:12:52 INFO (SyncWorker_7) [supervisor.docker.interface] Clean addon_cebe7a76_hassio_google_drive_backup application[0m
[32m20-08-31 12:12:53 INFO (SyncWorker_1) [supervisor.docker.addon] Start Docker add-on sabeechen/hassio-google-drive-backup-armv7 with version 3.12[0m
[32m20-08-31 12:12:55 INFO (MainThread) [supervisor.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:12:55 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:12:55 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:12:55 INFO (MainThread) [supervisor.api.security] /snapshots/081ecbfd/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:12:55 INFO (MainThread) [supervisor.api.security] /snapshots/3acdc48e/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:13:14 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:13:45 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:13:45 INFO (MainThread) [supervisor.api.security] /snapshots/3acdc48e/remove access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:13:45 INFO (MainThread) [supervisor.snapshots] Removed snapshot file 3acdc48e[0m
[32m20-08-31 12:13:45 INFO (MainThread) [supervisor.api.security] /snapshots/081ecbfd/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:13:45 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 081ecbfd[0m
[32m20-08-31 12:13:48 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:13:49 INFO (MainThread) [supervisor.api.security] /snapshots/081ecbfd/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:13:49 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 081ecbfd[0m
[32m20-08-31 12:13:50 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:13:51 INFO (MainThread) [supervisor.api.security] /snapshots/081ecbfd/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:13:51 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 081ecbfd[0m
[32m20-08-31 12:13:55 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-08-31 12:13:58 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 2020-08-31 14:08:19 WARNING (SyncWorker_29) [homeassistant.components.eq3btsmart.climate] Updating the state failed: Failed to connect to peripheral 00:1A:22:0A:F7:66, addr type: public
2020-08-31 14:08:19 WARNING (SyncWorker_29) [homeassistant.components.eq3btsmart.climate] Updating the state failed: Failed to connect to peripheral 00:1A:22:0B:A8:0E, addr type: public
2020-08-31 14:09:19 WARNING (SyncWorker_10) [homeassistant.components.eq3btsmart.climate] Updating the state failed: Failed to connect to peripheral 00:1A:22:0A:F7:66, addr type: public
2020-08-31 14:09:19 WARNING (SyncWorker_10) [homeassistant.components.eq3btsmart.climate] Updating the state failed: Failed to connect to peripheral 00:1A:22:0B:A8:0E, addr type: public
2020-08-31 14:10:19 WARNING (SyncWorker_50) [homeassistant.components.eq3btsmart.climate] Updating the state failed: Failed to connect to peripheral 00:1A:22:0A:F7:66, addr type: public
2020-08-31 14:10:19 WARNING (SyncWorker_0) [homeassistant.components.eq3btsmart.climate] Updating the state failed: Failed to connect to peripheral 00:1A:22:0B:A8:0E, addr type: public
2020-08-31 14:11:19 WARNING (SyncWorker_39) [homeassistant.components.eq3btsmart.climate] Updating the state failed: Failed to connect to peripheral 00:1A:22:0A:F7:66, addr type: public
2020-08-31 14:11:19 WARNING (SyncWorker_23) [homeassistant.components.eq3btsmart.climate] Updating the state failed: Failed to connect to peripheral 00:1A:22:0B:A8:0E, addr type: public
2020-08-31 14:12:19 WARNING (SyncWorker_5) [homeassistant.components.eq3btsmart.climate] Updating the state failed: Failed to connect to peripheral 00:1A:22:0A:F7:66, addr type: public
2020-08-31 14:12:19 WARNING (SyncWorker_32) [homeassistant.components.eq3btsmart.climate] Updating the state failed: Failed to connect to peripheral 00:1A:22:0B:A8:0E, addr type: public
2020-08-31 14:12:46 ERROR (MainThread) [custom_components.dwd_weather] Unexpected error fetching DWD Weather Coordinator for Ebersberg-Halbing data: day is out of range for month
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 143, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 131, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/dwd_weather/connector.py", line 51, in async_update
    return await self._hass.async_add_executor_job(self._update)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dwd_weather/connector.py", line 74, in _update
    temp_max = self.dwd_weather.get_daily_max(
  File "/usr/local/lib/python3.8/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 164, in get_daily_max
    weather_data = self.get_day_values(timestamp)
  File "/usr/local/lib/python3.8/site-packages/simple_dwd_weatherforecast/dwdforecast.py", line 221, in get_day_values
    endtime = datetime(timestamp.year, timestamp.month,
ValueError: day is out of range for month
2020-08-31 14:13:19 WARNING (SyncWorker_27) [homeassistant.components.eq3btsmart.climate] Updating the state failed: Failed to connect to peripheral 00:1A:22:0A:F7:66, addr type: public
2020-08-31 14:13:19 WARNING (SyncWorker_18) [homeassistant.components.eq3btsmart.climate] Updating the state failed: Failed to connect to peripheral 00:1A:22:0B:A8:0E, addr type: public

 ```

**Comment by FaserF** [comment]
Ooops, sorry. Have the same issue as #243 
Will close this issue and keep an eye on the other issue.
