### ISSUE TITLE
The Supervisor Returned an Unexpected Response

### ISSUE THREAD

**Issue by matteobombardi** [sabeechen/hassio-google-drive-backup#251]
The Supervisor Returned an Unexpected Response
The addon was unable to communicate with the Supervisor because it gave back an unreadable response. This addon must communicate with the supervisor to create snapshots, load configuration, etc. Without the supervisor the addon will not be able to do anything useful. This usually resolves itself after the addon retrys, but if you see this error stick around for a while you can try:

Syncing again with the button below. The addon will also retry on its own periodically.
Restarting the addon, the supervisor, or the whole machine Home Assistant is running on. Sometimes the supervisor can get into a bad state and this works around it.
If the problem persists, file an issue on GitHub to let the developer of this addon know about it. He might be able to help.
SYNC AGAIN

###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.101.2`
 Home Assistant Version: `0.114.4`
 Supervisor Version: `None`
 Supervisor Channel: `stable`
 Hassos Version: `None`
 Docker Version: `None`
 Architecture: `armv7`
 Machine: `None`
 Date: `2020-09-01T18:32:47.808054+00:00`
 Timezone: `Europe/Rome`
 Failure Time: `2020-09-01T18:27:15.074561+00:00`
 Last Good Sync: `2020-09-01T18:27:13.268306+00:00`
 ###### Exception:
 ```
 
  addon/backup/util/asynchttpgetter.py:133 (read)
  /site-packages/aiohttp/streams.py:416 (readexactly)
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
Whose handling caused:
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:162 (sync)
  addon/backup/drive/drivesource.py:148 (save)
  addon/backup/drive/driverequests.py:252 (create)
  addon/backup/util/asynchttpgetter.py:140 (read)
backup.exceptions.exceptions.SupervisorUnexpectedError

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "latest": "2020-09-01T01:42:11Z",
        "size": "2.9 GB"
    },
    "GoogleDrive": {
        "snapshots": 10,
        "retained": 0,
        "deletable": 10,
        "name": "GoogleDrive",
        "latest": "2020-08-31T01:36:42Z",
        "size": "1.1 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 10,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 1.0,
    "Setting.SNAPSHOT_TIME_OF_DAY": "03:00",
    "Setting.GENERATIONAL_DAYS": 7,
    "Setting.GENERATIONAL_WEEKS": 1,
    "Setting.GENERATIONAL_MONTHS": 1,
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 09-01 19:30:26 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1X85sXow6ZpXfhpzOJigbT08j6_QoxNpY/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
09-01 19:30:26 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271X85sXow6ZpXfhpzOJigbT08j6_QoxNpY%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
09-01 19:30:27 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-09-01 03:42:10' to Google Drive
09-01 19:30:27 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
09-01 19:30:27 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-UzGd1MkDydyrpa0h0X1VFxwGbniQbKUjHpB5e0bBrbss0BeKsE98AmTNllFkrHflD2C4mIZp_5o-Ep55UWSVQk
09-01 19:30:27 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2566522880
09-01 19:30:27 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
09-01 19:30:27 INFO [backup.model.coordinator] I'll try again in 21(ish) minutes
09-01 19:51:47 DEBUG [backup.model.syncer] Sync requested by Coordinator
09-01 19:51:47 INFO [backup.model.coordinator] Syncing Snapshots
09-01 19:51:47 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
09-01 19:51:47 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1X85sXow6ZpXfhpzOJigbT08j6_QoxNpY/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
09-01 19:51:48 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271X85sXow6ZpXfhpzOJigbT08j6_QoxNpY%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
09-01 19:51:48 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-09-01 03:42:10' to Google Drive
09-01 19:51:48 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
09-01 19:51:48 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-UzGd1MkDydyrpa0h0X1VFxwGbniQbKUjHpB5e0bBrbss0BeKsE98AmTNllFkrHflD2C4mIZp_5o-Ep55UWSVQk
09-01 19:51:48 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2566522880
09-01 19:51:48 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
09-01 19:51:48 INFO [backup.model.coordinator] I'll try again in 42(ish) minutes
09-01 20:27:13 INFO [backup.model.coordinator] Syncing Snapshots
09-01 20:27:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
09-01 20:27:13 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
09-01 20:27:13 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1X85sXow6ZpXfhpzOJigbT08j6_QoxNpY/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
09-01 20:27:13 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271X85sXow6ZpXfhpzOJigbT08j6_QoxNpY%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
09-01 20:27:14 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-09-01 03:42:10' to Google Drive
09-01 20:27:14 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
09-01 20:27:14 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-UzGd1MkDydyrpa0h0X1VFxwGbniQbKUjHpB5e0bBrbss0BeKsE98AmTNllFkrHflD2C4mIZp_5o-Ep55UWSVQk
09-01 20:27:15 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2566522880
09-01 20:27:15 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
09-01 20:27:15 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m20-09-01 17:09:41 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 50371125[0m
[32m20-09-01 17:10:22 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 17:10:22 INFO (MainThread) [supervisor.api.security] /snapshots/50371125/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 17:10:22 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 50371125[0m
[32m20-09-01 17:11:43 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 17:11:43 INFO (MainThread) [supervisor.api.security] /snapshots/50371125/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 17:11:43 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 50371125[0m
[32m20-09-01 17:14:23 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 17:14:24 INFO (MainThread) [supervisor.api.security] /snapshots/50371125/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 17:14:24 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 50371125[0m
[32m20-09-01 17:19:44 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 17:19:46 INFO (MainThread) [supervisor.api.security] /snapshots/50371125/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 17:19:46 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 50371125[0m
[32m20-09-01 17:30:26 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 17:30:27 INFO (MainThread) [supervisor.api.security] /snapshots/50371125/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 17:30:27 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 50371125[0m
[32m20-09-01 17:38:35 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token[0m
[32m20-09-01 17:51:47 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 17:51:48 INFO (MainThread) [supervisor.api.security] /snapshots/50371125/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 17:51:48 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 50371125[0m
[32m20-09-01 18:08:41 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token[0m
[32m20-09-01 18:27:13 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 18:27:14 INFO (MainThread) [supervisor.api.security] /snapshots/50371125/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 18:27:14 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 50371125[0m
[32m20-09-01 18:32:47 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 18:32:47 INFO (MainThread) [supervisor.api.security] /core/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 18:32:47 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 18:32:47 INFO (MainThread) [supervisor.api.security] /core/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-01 18:32:47 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
2020-09-01 20:32:00 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.luce_camera_3_last_seen fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 263, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 454, in async_device_update
    await self.async_update()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/template/sensor.py", line 235, in async_update
    self._state = self._template.async_render()
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 230, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
2020-09-01 20:32:27 WARNING (MainThread) [frontend.js.latest.202008110] Icon mdi:mixcloud was removed from MDI, please replace this icon with an other icon in your config, it will be removed in version 0.115.
2020-09-01 20:32:27 ERROR (MainThread) [frontend.js.latest.202008110] https://mbombardi.duckdns.org:8123/hacsfiles/custom-sidebar/custom-sidebar.js:104:22 Uncaught TypeError: Cannot read property 'length' of null

 ```

**Comment by matteobombardi** [comment]
I found the issue, the backup file exceed the google drive maximum supported size.

A better error message would be great.

Thank you

**Comment by sabeechen** [comment]
Are you sure that was the problem?  Google Drive's maximum size is [5TB](https://support.google.com/drive/answer/37603?hl=en), which would be a hell of a snapshot.  

I've had a bunch of users run into this error (SupervisorUnexpectedError) but we haven't been able to [figure out why](#226).  Sometimes it seems to randomly resolve itself, if you did something that fixed it, I'd be curious to know what worked.

**Comment by matteobombardi** [comment]
Hi my friend, I'm not sure if this limit is gdrive related but I'm sure that the issue is due to the filesize.

A 3TB snapshot have returned the error, I've deleted it, reduced to 300MB and it works now

Maybe some kind of timeout?

**Comment by sabeechen** [comment]
You guys are awesome!  The snapshot size does appear to be what causes the problem and I was able to reproduce this on a pi2.  Moreover, downloading a snapshot through the Supervisor web-ui (Supervisor > Snapshots) also fails, which pretty much means this is definitely a problem with the supervisor.  In fact this happens even when this addon isn't installed.  It looks like it was just a coincidence that we started noticing it after a release.

I've [opened a bug in the supervisor](https://github.com/home-assistant/supervisor/issues/2047) and dumped everything I've learned there, so hopefully we'll hear back from them.

**Comment by sabeechen** [comment]
Its likely, 3TB is pretty massive.  Google Drive's maximum file size is 5TB so that shouldn't be a problem.  If you're Unable to download the 3TB snapshot through the supervisor's snapshot page ("Supervisor" -> "Snapshots" in the HA interface) then its the same issue.
