### ISSUE TITLE
Please add a title

### ISSUE THREAD

**Issue by orlandogil2007** [sabeechen/hassio-google-drive-backup#261]
Copy the info from the previous p
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.101.2`
 Home Assistant Version: `0.114.4`
 Supervisor Version: `None`
 Supervisor Channel: `stable`
 Hassos Version: `None`
 Docker Version: `None`
 Architecture: `amd64`
 Machine: `None`
 Date: `2020-09-16T03:49:31.892241+00:00`
 Timezone: `America/New_York`
 Failure Time: `2020-09-16T03:49:04.713169+00:00`
 Last Good Sync: `2020-09-16T03:49:04.606660+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:133 (sync)
  addon/backup/model/model.py:216 (_syncSnapshots)
  addon/backup/drive/drivesource.py:84 (get)
  addon/backup/drive/drivesource.py:187 (getFolderId)
  addon/backup/drive/folderfinder.py:58 (get)
  addon/backup/drive/folderfinder.py:107 (_readFolderId)
  addon/backup/drive/folderfinder.py:148 (_verify)
  addon/backup/drive/driverequests.py:141 (get)
  addon/backup/drive/driverequests.py:319 (retryRequest)
  addon/backup/drive/driverequests.py:85 (_getHeaders)
  addon/backup/drive/driverequests.py:130 (getToken)
  addon/backup/creds/exchanger.py:82 (refresh)
  addon/backup/creds/exchanger.py:95 (_refresh_google)
  addon/backup/creds/driverequester.py:32 (request)
  addon/backup/creds/driverequester.py:98 (raiseForKnownErrors)
backup.exceptions.exceptions.CredRefreshGoogleError: invalid_grant

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 2,
        "retained": 0,
        "deletable": 2,
        "name": "HomeAssistant",
        "latest": "2020-09-16T02:17:11Z",
        "size": "12.3 MB"
    },
    "GoogleDrive": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "latest": null,
        "size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 10,
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 40,
    "Setting.SEND_ERROR_REPORTS": true,
    "Setting.CONFIRM_MULTIPLE_DELETES": false
}
 ```
 ###### Addon Logs:
 ```
 09-15 23:45:14 INFO [backup.model.coordinator] I'll try again in 10 seconds
09-15 23:45:24 DEBUG [backup.model.syncer] Sync requested by Coordinator
09-15 23:45:24 INFO [backup.model.coordinator] Syncing Snapshots
09-15 23:45:24 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
09-15 23:45:24 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
09-15 23:45:24 ERROR [backup.model.coordinator] Couldn't refresh your credentials with Google because: 'invalid_grant'
09-15 23:45:24 INFO [backup.model.coordinator] I'll try again in 20 seconds
09-15 23:45:44 DEBUG [backup.model.syncer] Sync requested by Coordinator
09-15 23:45:44 INFO [backup.model.coordinator] Syncing Snapshots
09-15 23:45:44 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
09-15 23:45:44 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
09-15 23:45:44 ERROR [backup.model.coordinator] Couldn't refresh your credentials with Google because: 'invalid_grant'
09-15 23:45:44 INFO [backup.model.coordinator] I'll try again in 40 seconds
09-15 23:46:24 DEBUG [backup.model.syncer] Sync requested by Coordinator
09-15 23:46:24 INFO [backup.model.coordinator] Syncing Snapshots
09-15 23:46:24 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
09-15 23:46:24 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
09-15 23:46:24 ERROR [backup.model.coordinator] Couldn't refresh your credentials with Google because: 'invalid_grant'
09-15 23:46:24 INFO [backup.model.coordinator] I'll try again in 1(ish) minutes
09-15 23:47:45 DEBUG [backup.model.syncer] Sync requested by Coordinator
09-15 23:47:45 INFO [backup.model.coordinator] Syncing Snapshots
09-15 23:47:45 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
09-15 23:47:45 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
09-15 23:47:45 ERROR [backup.model.coordinator] Couldn't refresh your credentials with Google because: 'invalid_grant'
09-15 23:47:45 INFO [backup.model.coordinator] I'll try again in 2(ish) minutes
09-15 23:49:04 INFO [backup.model.coordinator] Syncing Snapshots
09-15 23:49:04 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
09-15 23:49:04 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
09-15 23:49:04 ERROR [backup.model.coordinator] Couldn't refresh your credentials with Google because: 'invalid_grant'
09-15 23:49:04 INFO [backup.model.coordinator] I'll try again in 5(ish) minutes
 ```
 ###### Supervisor Logs:
 ```
 [32m20-09-16 03:41:36 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-16 03:41:53 INFO (MainThread) [supervisor.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-16 03:41:53 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-16 03:41:56 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[33m20-09-16 03:43:26 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m20-09-16 03:43:34 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m20-09-16 03:43:35 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m20-09-16 03:43:35 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m20-09-16 03:43:36 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m20-09-16 03:43:36 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m20-09-16 03:43:37 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m20-09-16 03:43:37 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m20-09-16 03:43:37 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m20-09-16 03:43:38 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[32m20-09-16 03:45:11 INFO (SyncWorker_0) [supervisor.docker.interface] Stop addon_cebe7a76_hassio_google_drive_backup application[0m
[32m20-09-16 03:45:11 INFO (SyncWorker_0) [supervisor.docker.interface] Clean addon_cebe7a76_hassio_google_drive_backup application[0m
[32m20-09-16 03:45:12 INFO (SyncWorker_3) [supervisor.docker.addon] Start Docker add-on sabeechen/hassio-google-drive-backup-amd64 with version 3.12[0m
[32m20-09-16 03:45:13 INFO (MainThread) [supervisor.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-16 03:45:13 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-16 03:45:13 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-16 03:45:13 INFO (MainThread) [supervisor.api.security] /snapshots/dd87bd6a/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-16 03:45:13 INFO (MainThread) [supervisor.api.security] /snapshots/c5fbe808/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-16 03:45:14 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-16 03:45:24 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-16 03:45:44 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-16 03:46:24 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-16 03:47:45 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-16 03:49:04 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-09-16 03:49:31 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.DatabaseError) database disk image is malformed
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{}', 'LOCAL', '2020-09-16 03:49:29.024612', '2020-09-16 03:49:29.027008', '9f3f6979f7cf11ea9115bbbfe5c1d0d9', None, None)]
(Background on this error at: http://sqlalche.me/e/13/4xp6) (Background on this error at: http://sqlalche.me/e/13/7s2a)
/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py:561: SAWarning: Session's state has been changed on a non-active transaction - this state will be discarded.
  util.warn(
2020-09-15 23:49:30 ERROR (Recorder) [homeassistant.components.recorder] Error executing query: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.DatabaseError) database disk image is malformed
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{}', 'LOCAL', '2020-09-16 03:49:29.024612', '2020-09-16 03:49:29.027008', '9f3f6979f7cf11ea9115bbbfe5c1d0d9', None, None)]
(Background on this error at: http://sqlalche.me/e/13/4xp6) (Background on this error at: http://sqlalche.me/e/13/7s2a)
2020-09-15 23:49:30 ERROR (Recorder) [homeassistant.components.recorder] Error saving events: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.DatabaseError) database disk image is malformed
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{}', 'LOCAL', '2020-09-16 03:49:29.024612', '2020-09-16 03:49:29.027008', '9f3f6979f7cf11ea9115bbbfe5c1d0d9', None, None)]
(Background on this error at: http://sqlalche.me/e/13/4xp6) (Background on this error at: http://sqlalche.me/e/13/7s2a)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 433, in _commit_event_session_or_retry
    self._commit_event_session()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 484, in _commit_event_session
    self.event_session.commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 502, in commit
    self._assert_active(prepared_ok=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 289, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.DatabaseError) database disk image is malformed
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{}', 'LOCAL', '2020-09-16 03:49:29.024612', '2020-09-16 03:49:29.027008', '9f3f6979f7cf11ea9115bbbfe5c1d0d9', None, None)]
(Background on this error at: http://sqlalche.me/e/13/4xp6) (Background on this error at: http://sqlalche.me/e/13/7s2a)

 ```
 age here

**Comment by sabeechen** [comment]
Most likely your credentials with Google Drive just expired.  There are a number of ways that can happen.  Did you try clicking the link to reautheticate the addon with Google Drive?

**Comment by sabeechen** [comment]
I'm closing this for now, but feel free to reopen it if there is more I can help with.

**Comment by orlandogil2007** [comment]
Hi I fix the problem on HA, the workaround is open the HA https not http.

Best Regards.
