### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by biejay** [sabeechen/hassio-google-drive-backup#27]
Please add info about your configuration here, along with a brief description of what you were doing and what happened.  Detail is always helpful for investigating an error.  You can enable verbos logging by setting {"verbose": true} in your add-on configuration and including that here.  :

Traceback (most recent call last):
  File "/app/backup/engine.py", line 92, in doBackupWorkflow
    self._checkForBackup()
  File "/app/backup/engine.py", line 312, in _checkForBackup
    self.drive.saveSnapshot(to_backup, self.hassio.downloadUrl(to_backup), self.folder_id)
  File "/app/backup/drive.py", line 96, in saveSnapshot
    media: MediaIoBaseUpload = MediaIoBaseUpload(stream, mimetype='application/tar', chunksize=262144, resumable=True)
  File "/usr/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/googleapiclient/http.py", line 439, in __init__
    self._fd.seek(0, os.SEEK_END)
  File "/app/backup/responsestream.py", line 43, in seek
    self._load_all()
  File "/app/backup/responsestream.py", line 17, in _load_all
    self._bytes.write(chunk)
MemoryError

**Comment by sabeechen** [comment]
It looks like you're using an older version of the add-on (which tried to load the whole snapshot into memory when backing up), please update.  You can click refresh in the upper right of the add-on store page if hass.io doesn't see the update for some reason.  I'd also recommend turning on auto update.

**Comment by sabeechen** [comment]
Haven't heard back in a bit so ill assume this fixed it, reopen and let me know if you still have trouble.

**Comment by biejay** [comment]
Thanks that solved it! Wanted to wait a day to see if it works.
