### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by quasimodo1427** [sabeechen/hassio-google-drive-backup#281]
Copy the info from
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.101.3`
 Home Assistant Version: `0.116.2`
 Supervisor Version: `247`
 Supervisor Channel: `stable`
 Hassos Version: `4.13`
 Docker Version: `19.03.11`
 Architecture: `armv7`
 Machine: `raspberrypi3`
 Date: `2020-10-14T21:44:56.460859+00:00`
 Timezone: `America/Detroit`
 Failure Time: `2020-10-14T21:44:49.221817+00:00`
 Last Good Sync: `2020-10-14T21:44:48.902587+00:00`
 ###### Exception:
 ```
 
  addon/backup/util/asynchttpgetter.py:133 (read)
  /site-packages/aiohttp/streams.py:416 (readexactly)
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
Whose handling caused:
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:162 (sync)
  addon/backup/drive/drivesource.py:150 (save)
  addon/backup/drive/driverequests.py:252 (create)
  addon/backup/util/asynchttpgetter.py:140 (read)
backup.exceptions.exceptions.SupervisorUnexpectedError

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "latest": "2020-10-13T19:48:16Z",
        "size": "9.5 GB"
    },
    "GoogleDrive": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "latest": null,
        "size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 2.0,
    "Setting.USE_SSL": true
}
 ```
 ###### Addon Logs:
 ```
 10-14 17:44:25 INFO [backup.model.coordinator] I'll try again right now
10-14 17:44:25 DEBUG [backup.model.syncer] Sync requested by Coordinator
10-14 17:44:25 INFO [backup.model.coordinator] Syncing Snapshots
10-14 17:44:25 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-14 17:44:25 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271KxGVgD63yVjWwnTFpSa3CJjolxFJb0TR%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-14 17:44:25 INFO [backup.drive.drivesource] Uploading 'Tuesday, Oct 13, 2020' to Google Drive
10-14 17:44:25 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
10-14 17:44:25 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uy8BG--D_DROSHsAfj28T66Wj7l6lersHAwDdZzw97vbfcHHcRF2DAyVPCttfmIYSE9H_hk-j2U4w302eBibGrCjK-L3g
10-14 17:44:26 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2536540160
10-14 17:44:26 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
10-14 17:44:26 INFO [backup.model.coordinator] I'll try again in 10 seconds
10-14 17:44:36 DEBUG [backup.model.syncer] Sync requested by Coordinator
10-14 17:44:36 INFO [backup.model.coordinator] Syncing Snapshots
10-14 17:44:36 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-14 17:44:36 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271KxGVgD63yVjWwnTFpSa3CJjolxFJb0TR%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-14 17:44:36 INFO [backup.drive.drivesource] Uploading 'Tuesday, Oct 13, 2020' to Google Drive
10-14 17:44:36 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
10-14 17:44:36 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uy8BG--D_DROSHsAfj28T66Wj7l6lersHAwDdZzw97vbfcHHcRF2DAyVPCttfmIYSE9H_hk-j2U4w302eBibGrCjK-L3g
10-14 17:44:36 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2536540160
10-14 17:44:36 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
10-14 17:44:36 INFO [backup.model.coordinator] I'll try again in 20 seconds
10-14 17:44:48 INFO [backup.model.coordinator] Syncing Snapshots
10-14 17:44:48 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-14 17:44:48 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271KxGVgD63yVjWwnTFpSa3CJjolxFJb0TR%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-14 17:44:49 INFO [backup.drive.drivesource] Uploading 'Tuesday, Oct 13, 2020' to Google Drive
10-14 17:44:49 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
10-14 17:44:49 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uy8BG--D_DROSHsAfj28T66Wj7l6lersHAwDdZzw97vbfcHHcRF2DAyVPCttfmIYSE9H_hk-j2U4w302eBibGrCjK-L3g
10-14 17:44:49 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2536540160
10-14 17:44:49 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
10-14 17:44:49 INFO [backup.model.coordinator] I'll try again in 40 seconds
 ```
 ###### Supervisor Logs:
 ```
 [32m20-10-14 21:43:16 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:43:29 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:43:29 INFO (MainThread) [supervisor.api.security] /snapshots/3490b088/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:43:29 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 3490b088[0m
[32m20-10-14 21:44:09 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:10 INFO (MainThread) [supervisor.api.security] /snapshots/3490b088/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:10 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 3490b088[0m
[32m20-10-14 21:44:16 INFO (SyncWorker_3) [supervisor.docker.interface] Stop addon_cebe7a76_hassio_google_drive_backup application[0m
[32m20-10-14 21:44:18 INFO (SyncWorker_3) [supervisor.docker.interface] Clean addon_cebe7a76_hassio_google_drive_backup application[0m
[32m20-10-14 21:44:20 INFO (SyncWorker_6) [supervisor.docker.addon] Start Docker add-on sabeechen/hassio-google-drive-backup-armv7 with version 3.12[0m
[32m20-10-14 21:44:24 INFO (MainThread) [supervisor.api.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:24 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:24 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:24 INFO (MainThread) [supervisor.api.security] /snapshots/3490b088/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:24 INFO (MainThread) [supervisor.api.security] /snapshots/d2f9026d/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:24 INFO (MainThread) [supervisor.api.security] /snapshots/71e707ed/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:24 INFO (MainThread) [supervisor.api.security] /snapshots/cf771166/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:24 INFO (MainThread) [supervisor.api.security] /snapshots/3490b088/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:24 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 3490b088[0m
[32m20-10-14 21:44:25 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:25 INFO (MainThread) [supervisor.api.security] /snapshots/3490b088/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:25 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 3490b088[0m
[32m20-10-14 21:44:36 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:36 INFO (MainThread) [supervisor.api.security] /snapshots/3490b088/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:36 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 3490b088[0m
[32m20-10-14 21:44:48 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:49 INFO (MainThread) [supervisor.api.security] /snapshots/3490b088/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-14 21:44:49 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 3490b088[0m
[32m20-10-14 21:44:56 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.OSError: [Errno 113] Host is unreachable: 'rtsp://quasimodo1:1427pd1427@192.168.1.31/live'; last error log: [tcp] Connection to tcp://192.168.1.31:554?timeout=5000000 failed: Host is unreachable
2020-10-14 17:43:19 ERROR (SyncWorker_31) [homeassistant.components.rest.sensor] Error fetching data: http://192.168.1.191:2323/?cmd=deviceInfo&type=json&password=lanalane1427 failed with HTTPConnectionPool(host='192.168.1.191', port=2323): Max retries exceeded with url: /?cmd=deviceInfo&type=json&password=lanalane1427 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x5ce95910>: Failed to establish a new connection: [Errno 111] Connection refused'))
2020-10-14 17:43:19 WARNING (MainThread) [homeassistant.components.sensor] Platform rest not ready yet. Retrying in 150 seconds.
2020-10-14 17:43:56 ERROR (stream_worker) [libav.tcp] Connection to tcp://192.168.1.31:554?timeout=5000000 failed: Host is unreachable
2020-10-14 17:43:56 ERROR (stream_worker) [homeassistant.components.stream.worker] Stream connection failed: rtsp://quasimodo1:1427pd1427@192.168.1.31/live
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 48, in stream_worker
    _stream_worker_internal(hass, stream, quit_event)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 65, in _stream_worker_internal
    container = av.open(stream.source, options=stream.options)
  File "av/container/core.pyx", line 354, in av.container.core.open
  File "av/container/core.pyx", line 225, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.OSError: [Errno 113] Host is unreachable: 'rtsp://quasimodo1:1427pd1427@192.168.1.31/live'; last error log: [tcp] Connection to tcp://192.168.1.31:554?timeout=5000000 failed: Host is unreachable
2020-10-14 17:44:36 ERROR (stream_worker) [libav.tcp] Connection to tcp://192.168.1.31:554?timeout=5000000 failed: Host is unreachable
2020-10-14 17:44:36 ERROR (stream_worker) [homeassistant.components.stream.worker] Stream connection failed: rtsp://quasimodo1:1427pd1427@192.168.1.31/live
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 48, in stream_worker
    _stream_worker_internal(hass, stream, quit_event)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 65, in _stream_worker_internal
    container = av.open(stream.source, options=stream.options)
  File "av/container/core.pyx", line 354, in av.container.core.open
  File "av/container/core.pyx", line 225, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.OSError: [Errno 113] Host is unreachable: 'rtsp://quasimodo1:1427pd1427@192.168.1.31/live'; last error log: [tcp] Connection to tcp://192.168.1.31:554?timeout=5000000 failed: Host is unreachable

 ```
  the previous page here

**Comment by sabeechen** [comment]
This is almost certainly another instance of #226. You'll see this if you are both:

  * Using the 32-bit arm verison of Home Assistant (you are)
  * Have a snapshot over 2GB in size (you do)

It is caused by a bug in the supervisor. You can verify this is the case by going to the supervisor's own snapshots page (Supervisor > Snapshots) and trying to download the snapshot, which will fail. I've filed [an issue](https://github.com/home-assistant/supervisor/issues/2047) with them but it is still unresolved.

The only ways to work around this right now are:

 * Install and run the 64 bit version of Home Assistant (Admittedly I don't know why the 32 bit versions are recommended).
 * Keep the snapshot below 2GB. Usually large snapshots are from storing the database or camera images, and usually the snapshot can do without them.

I'll update #266 when I have any new information on the issue.

Duplicate #226
