### ISSUE TITLE
Having trouble syncing with supervisor

### ISSUE THREAD

**Issue by quasimodo1427** [sabeechen/hassio-google-drive-backup#282]
Copy the info from the previous
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.101.3`
 Home Assistant Version: `0.116.2`
 Supervisor Version: `247`
 Supervisor Channel: `beta`
 Hassos Version: `4.14`
 Docker Version: `19.03.11`
 Architecture: `armv7`
 Machine: `raspberrypi3`
 Date: `2020-10-15T09:43:59.474009+00:00`
 Timezone: `America/Detroit`
 Failure Time: `2020-10-15T09:43:49.926140+00:00`
 Last Good Sync: `2020-10-15T09:43:49.461029+00:00`
 ###### Exception:
 ```
 
  addon/backup/util/asynchttpgetter.py:133 (read)
  /site-packages/aiohttp/streams.py:416 (readexactly)
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
Whose handling caused:
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:162 (sync)
  addon/backup/drive/drivesource.py:150 (save)
  addon/backup/drive/driverequests.py:252 (create)
  addon/backup/util/asynchttpgetter.py:140 (read)
backup.exceptions.exceptions.SupervisorUnexpectedError

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "latest": "2020-10-14T23:56:33Z",
        "size": "9.5 GB"
    },
    "GoogleDrive": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "latest": null,
        "size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 2.0,
    "Setting.SNAPSHOT_TIME_OF_DAY": "03:00",
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 10-15 03:44:46 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1KxGVgD63yVjWwnTFpSa3CJjolxFJb0TR/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
10-15 03:44:46 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271KxGVgD63yVjWwnTFpSa3CJjolxFJb0TR%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-15 03:44:47 INFO [backup.drive.drivesource] Uploading 'Wednesday, Oct 14, 2020' to Google Drive
10-15 03:44:47 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
10-15 03:44:47 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Ux2HNgqZ9iNvl7OvAIIQLcZ7yuiq7z1y8xMFCvucKCxATK8d5jRHf_UgXIOMHEL_wx3qrBn89AEroCU6bUjRVeBD9b29Q
10-15 03:44:47 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2546145280
10-15 03:44:47 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
10-15 03:44:47 INFO [backup.model.coordinator] I'll try again in an hour
10-15 04:44:47 DEBUG [backup.model.syncer] Sync requested by Coordinator
10-15 04:44:47 INFO [backup.model.coordinator] Syncing Snapshots
10-15 04:44:47 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-15 04:44:47 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
10-15 04:44:47 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1KxGVgD63yVjWwnTFpSa3CJjolxFJb0TR/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
10-15 04:44:47 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271KxGVgD63yVjWwnTFpSa3CJjolxFJb0TR%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-15 04:44:47 INFO [backup.drive.drivesource] Uploading 'Wednesday, Oct 14, 2020' to Google Drive
10-15 04:44:47 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
10-15 04:44:47 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Ux2HNgqZ9iNvl7OvAIIQLcZ7yuiq7z1y8xMFCvucKCxATK8d5jRHf_UgXIOMHEL_wx3qrBn89AEroCU6bUjRVeBD9b29Q
10-15 04:44:47 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2546145280
10-15 04:44:47 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
10-15 04:44:47 INFO [backup.model.coordinator] I'll try again in an hour
10-15 05:43:49 INFO [backup.model.coordinator] Syncing Snapshots
10-15 05:43:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-15 05:43:49 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1KxGVgD63yVjWwnTFpSa3CJjolxFJb0TR/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
10-15 05:43:49 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271KxGVgD63yVjWwnTFpSa3CJjolxFJb0TR%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-15 05:43:49 INFO [backup.drive.drivesource] Uploading 'Wednesday, Oct 14, 2020' to Google Drive
10-15 05:43:49 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
10-15 05:43:49 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Ux2HNgqZ9iNvl7OvAIIQLcZ7yuiq7z1y8xMFCvucKCxATK8d5jRHf_UgXIOMHEL_wx3qrBn89AEroCU6bUjRVeBD9b29Q
10-15 05:43:49 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 2546145280
10-15 05:43:49 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
10-15 05:43:49 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m20-10-15 06:51:21 INFO (MainThread) [supervisor.host.info] Update local host information[0m
[32m20-10-15 06:51:22 INFO (MainThread) [supervisor.host.services] Update service information[0m
[32m20-10-15 06:51:22 INFO (MainThread) [supervisor.host.network] Update local network information[0m
[32m20-10-15 06:51:23 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information[0m
[32m20-10-15 07:01:43 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-15 07:31:52 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-15 07:44:46 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-15 07:44:47 INFO (MainThread) [supervisor.api.security] /snapshots/635837e4/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-15 07:44:47 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 635837e4[0m
[32m20-10-15 08:02:01 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-15 08:31:17 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json[0m
[32m20-10-15 08:32:10 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-15 08:44:47 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-15 08:44:47 INFO (MainThread) [supervisor.api.security] /snapshots/635837e4/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-15 08:44:47 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 635837e4[0m
[32m20-10-15 08:58:03 INFO (MainThread) [supervisor.host.info] Update local host information[0m
[32m20-10-15 08:58:04 INFO (MainThread) [supervisor.host.services] Update service information[0m
[32m20-10-15 08:58:04 INFO (MainThread) [supervisor.host.network] Update local network information[0m
[32m20-10-15 08:58:05 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information[0m
[32m20-10-15 09:02:18 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-15 09:31:19 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m20-10-15 09:31:19 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository[0m
[32m20-10-15 09:31:19 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m20-10-15 09:31:20 INFO (MainThread) [supervisor.store] Load add-ons from store: 67 all - 0 new - 0 remove[0m
[32m20-10-15 09:32:27 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-15 09:43:49 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-15 09:43:49 INFO (MainThread) [supervisor.api.security] /snapshots/635837e4/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-15 09:43:49 INFO (MainThread) [supervisor.api.snapshots] Download snapshot 635837e4[0m
[32m20-10-15 09:43:59 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.OSError: [Errno 113] Host is unreachable: 'rtsp://quasimodo1:1427pd1427@192.168.1.31/live'; last error log: [tcp] Connection to tcp://192.168.1.31:554?timeout=5000000 failed: Host is unreachable
2020-10-15 05:42:52 WARNING (stream_worker) [homeassistant.components.stream.worker] Timestamp overflow detected: dts = 604976, resetting stream
2020-10-15 05:42:55 WARNING (stream_worker) [homeassistant.components.stream.worker] Dropping out of order packet: 132300 <= 132300
2020-10-15 05:43:03 ERROR (stream_worker) [libav.tcp] Connection to tcp://192.168.1.31:554?timeout=5000000 failed: Host is unreachable
2020-10-15 05:43:03 ERROR (stream_worker) [homeassistant.components.stream.worker] Stream connection failed: rtsp://quasimodo1:1427pd1427@192.168.1.31/live
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 48, in stream_worker
    _stream_worker_internal(hass, stream, quit_event)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 65, in _stream_worker_internal
    container = av.open(stream.source, options=stream.options)
  File "av/container/core.pyx", line 354, in av.container.core.open
  File "av/container/core.pyx", line 225, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.OSError: [Errno 113] Host is unreachable: 'rtsp://quasimodo1:1427pd1427@192.168.1.31/live'; last error log: [tcp] Connection to tcp://192.168.1.31:554?timeout=5000000 failed: Host is unreachable
2020-10-15 05:43:43 ERROR (stream_worker) [libav.tcp] Connection to tcp://192.168.1.31:554?timeout=5000000 failed: Host is unreachable
2020-10-15 05:43:43 ERROR (stream_worker) [homeassistant.components.stream.worker] Stream connection failed: rtsp://quasimodo1:1427pd1427@192.168.1.31/live
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 48, in stream_worker
    _stream_worker_internal(hass, stream, quit_event)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 65, in _stream_worker_internal
    container = av.open(stream.source, options=stream.options)
  File "av/container/core.pyx", line 354, in av.container.core.open
  File "av/container/core.pyx", line 225, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.OSError: [Errno 113] Host is unreachable: 'rtsp://quasimodo1:1427pd1427@192.168.1.31/live'; last error log: [tcp] Connection to tcp://192.168.1.31:554?timeout=5000000 failed: Host is unreachable

 ```
  page here

**Comment by sabeechen** [comment]
This is almost certainly another instance of #226. You'll see this if you are both:

  * Using the 32-bit arm verison of Home Assistant (you are)
  * Have a snapshot over 2GB in size (you do)

It is caused by a bug in the supervisor. You can verify this is the case by going to the supervisor's own snapshots page (Supervisor > Snapshots) and trying to download the snapshot, which will fail. I've filed [an issue](https://github.com/home-assistant/supervisor/issues/2047) with them but it is still unresolved.

The only ways to work around this right now are:

 * Install and run the 64 bit version of Home Assistant (Admittedly I don't know why the 32 bit versions are recommended).
 * Keep the snapshot below 2GB. Usually large snapshots are from storing the database or camera images, and usually the snapshot can do without them.

I'll update #266 when I have any new information on the issue.

Duplicate #226
