### ISSUE TITLE
Synchro not working

### ISSUE THREAD

**Issue by Nessy1970** [sabeechen/hassio-google-drive-backup#285]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.101.3`
 Home Assistant Version: `0.116.4`
 Supervisor Version: `247`
 Supervisor Channel: `stable`
 Hassos Version: `4.13`
 Docker Version: `19.03.11`
 Architecture: `armv7`
 Machine: `raspberrypi3`
 Date: `2020-10-16T09:26:34.399889+00:00`
 Timezone: `Europe/Paris`
 Failure Time: `2020-10-16T09:12:47.274113+00:00`
 Last Good Sync: `2020-10-16T09:12:47.228729+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:133 (sync)
  addon/backup/model/model.py:216 (_syncSnapshots)
  addon/backup/drive/drivesource.py:84 (get)
  addon/backup/drive/drivesource.py:189 (getFolderId)
  addon/backup/drive/folderfinder.py:52 (get)
  addon/backup/drive/folderfinder.py:80 (save)
FileNotFoundError: [Errno 2] No such file or directory: '/data/folder.dat'

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 11,
        "retained": 0,
        "deletable": 11,
        "name": "HomeAssistant",
        "latest": "2020-10-16T09:05:52Z",
        "size": "690.5 MB"
    },
    "GoogleDrive": {
        "snapshots": 25,
        "retained": 0,
        "deletable": 25,
        "name": "GoogleDrive",
        "latest": "2020-09-26T16:02:43Z",
        "size": "1.4 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 25,
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 25,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 0.0,
    "Setting.SNAPSHOT_NAME": "REDACTED",
    "Setting.SNAPSHOT_PASSWORD": "REDACTED",
    "Setting.IGNORE_IPV6_ADDRESSES": true
}
 ```
 ###### Addon Logs:
 ```
 10-16 11:08:34 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:133 (sync)
  addon/backup/model/model.py:216 (_syncSnapshots)
  addon/backup/drive/drivesource.py:84 (get)
  addon/backup/drive/drivesource.py:189 (getFolderId)
  addon/backup/drive/folderfinder.py:52 (get)
  addon/backup/drive/folderfinder.py:80 (save)
FileNotFoundError: [Errno 2] No such file or directory: '/data/folder.dat'

10-16 11:08:34 INFO [backup.model.coordinator] I'll try again in an hour
10-16 11:08:40 DEBUG [backup.worker.watcher] Backup directory changed
10-16 11:08:40 DEBUG [backup.worker.watcher] Backup directory was written to, we'll reload snapshots from Home Assistant soon
10-16 11:08:40 DEBUG [backup.worker.watcher] Backup directory modified event
10-16 11:08:40 DEBUG [backup.worker.watcher] Backup directory changed
10-16 11:08:40 DEBUG [backup.worker.watcher] Backup directory modified event
10-16 11:08:40 DEBUG [backup.worker.watcher] Backup directory changed
10-16 11:08:40 DEBUG [backup.worker.watcher] Backup directory modified event
10-16 11:08:40 DEBUG [backup.worker.watcher] Backup directory changed
10-16 11:08:40 DEBUG [backup.worker.watcher] Backup directory modified event
10-16 11:08:45 INFO [backup.worker.watcher] Backup directory changed
10-16 11:08:45 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
10-16 11:08:45 INFO [backup.model.coordinator] Syncing Snapshots
10-16 11:08:45 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-16 11:08:45 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/356ca1df/info
10-16 11:08:45 INFO [backup.drive.folderfinder] Saving snapshot folder: 1glyZrTBuGgaktSiu6rew7Fohre17G-yl
10-16 11:08:45 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:133 (sync)
  addon/backup/model/model.py:216 (_syncSnapshots)
  addon/backup/drive/drivesource.py:84 (get)
  addon/backup/drive/drivesource.py:189 (getFolderId)
  addon/backup/drive/folderfinder.py:52 (get)
  addon/backup/drive/folderfinder.py:80 (save)
FileNotFoundError: [Errno 2] No such file or directory: '/data/folder.dat'

10-16 11:08:45 INFO [backup.model.coordinator] I'll try again in an hour
10-16 11:10:00 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
10-16 11:10:00 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
10-16 11:10:00 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
10-16 11:10:00 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
10-16 11:12:01 INFO [backup.drive.drivesource] Saving new Google Drive credentials
10-16 11:12:20 INFO [backup.drive.drivesource] Saving new Google Drive credentials
10-16 11:12:47 INFO [backup.model.coordinator] Syncing Snapshots
10-16 11:12:47 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-16 11:12:47 INFO [backup.drive.folderfinder] Saving snapshot folder: 1glyZrTBuGgaktSiu6rew7Fohre17G-yl
10-16 11:12:47 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:133 (sync)
  addon/backup/model/model.py:216 (_syncSnapshots)
  addon/backup/drive/drivesource.py:84 (get)
  addon/backup/drive/drivesource.py:189 (getFolderId)
  addon/backup/drive/folderfinder.py:52 (get)
  addon/backup/drive/folderfinder.py:80 (save)
FileNotFoundError: [Errno 2] No such file or directory: '/data/folder.dat'

10-16 11:12:47 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m20-10-16 09:05:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_nginx_proxy[0m
[32m20-10-16 09:05:52 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on a0d7b954_ssh[0m
[32m20-10-16 09:05:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_ssh[0m
[32m20-10-16 09:05:52 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_ssh[0m
[32m20-10-16 09:05:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_ssh[0m
[32m20-10-16 09:05:52 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_mosquitto[0m
[32m20-10-16 09:05:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto[0m
[32m20-10-16 09:05:52 INFO (MainThread) [supervisor.addons.addon] Build snapshot for add-on core_configurator[0m
[32m20-10-16 09:05:52 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator[0m
[32m20-10-16 09:05:52 INFO (MainThread) [supervisor.snapshots] Snapshot 356ca1df store folders[0m
[32m20-10-16 09:05:52 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder media[0m
[32m20-10-16 09:05:52 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder media done[0m
[32m20-10-16 09:05:52 INFO (SyncWorker_2) [supervisor.snapshots.snapshot] Snapshot folder ssl[0m
[32m20-10-16 09:05:52 INFO (SyncWorker_2) [supervisor.snapshots.snapshot] Snapshot folder ssl done[0m
[32m20-10-16 09:05:52 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Snapshot folder addons/local[0m
[32m20-10-16 09:05:52 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Snapshot folder addons/local done[0m
[32m20-10-16 09:05:52 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder share[0m
[32m20-10-16 09:05:52 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder share done[0m
[32m20-10-16 09:05:52 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder homeassistant[0m
[32m20-10-16 09:08:10 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done[0m
[32m20-10-16 09:08:34 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-16 09:08:40 INFO (MainThread) [supervisor.snapshots] Full-Snapshot 356ca1df done[0m
[32m20-10-16 09:08:45 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-16 09:08:45 INFO (MainThread) [supervisor.api.security] /snapshots/356ca1df/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-16 09:10:00 INFO (MainThread) [supervisor.api.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-16 09:10:00 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-16 09:12:47 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-16 09:22:34 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json[0m
[32m20-10-16 09:26:34 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 131, in _async_update_data
    return await self.update_method()
  File "/usr/src/homeassistant/homeassistant/components/upnp/device.py", line 128, in async_get_traffic_data
    values = await asyncio.gather(
  File "/usr/local/lib/python3.8/site-packages/async_upnp_client/profiles/igd.py", line 89, in async_get_total_bytes_received
    result = await action.async_call()
  File "/usr/local/lib/python3.8/site-packages/async_upnp_client/client.py", line 519, in async_call
    raise UpnpError('Error during async_call(), status: %s, body: %s' %
async_upnp_client.client.UpnpError: Error during async_call(), status: 500, body: <?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>401</errorCode><errorDescription>Invalid Action</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2617  100  2617    0     0   196k      0 --:--:-- --:--:-- --:--:--  212k
2020-10-16 11:25:47 ERROR (MainThread) [homeassistant.components.upnp] Unexpected error fetching Freebox Server data: Error during async_call(), status: 500, body: <?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>401</errorCode><errorDescription>Invalid Action</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 143, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 131, in _async_update_data
    return await self.update_method()
  File "/usr/src/homeassistant/homeassistant/components/upnp/device.py", line 128, in async_get_traffic_data
    values = await asyncio.gather(
  File "/usr/local/lib/python3.8/site-packages/async_upnp_client/profiles/igd.py", line 89, in async_get_total_bytes_received
    result = await action.async_call()
  File "/usr/local/lib/python3.8/site-packages/async_upnp_client/client.py", line 519, in async_call
    raise UpnpError('Error during async_call(), status: %s, body: %s' %
async_upnp_client.client.UpnpError: Error during async_call(), status: 500, body: <?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>401</errorCode><errorDescription>Invalid Action</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2617  100  2617    0     0   196k      0 --:--:-- --:--:-- --:--:--  196k

 ```

**Comment by kayo77** [comment]
I have the same problem

`
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.101.3`
 Home Assistant Version: `0.116.4`
 Supervisor Version: `249`
 Supervisor Channel: `stable`
 Hassos Version: `4.14`
 Docker Version: `19.03.11`
 Architecture: `armv7`
 Machine: `raspberrypi3`
 Date: `2020-10-23T18:38:24.508233+00:00`
 Timezone: `Europe/Warsaw`
 Failure Time: `2020-10-23T18:37:36.039032+00:00`
 Last Good Sync: `2020-10-23T18:37:36.009599+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:133 (sync)
  addon/backup/model/model.py:216 (_syncSnapshots)
  addon/backup/drive/drivesource.py:84 (get)
  addon/backup/drive/drivesource.py:189 (getFolderId)
  addon/backup/drive/folderfinder.py:52 (get)
  addon/backup/drive/folderfinder.py:80 (save)
FileNotFoundError: [Errno 2] No such file or directory: '/data/folder.dat'

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "latest": "2020-10-22T00:54:17Z",
        "size": "104.0 MB"
    },
    "GoogleDrive": {
        "snapshots": 14,
        "retained": 0,
        "deletable": 14,
        "name": "GoogleDrive",
        "latest": "2020-10-22T00:54:17Z",
        "size": "344.2 MB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 14,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 1.0,
    "Setting.SNAPSHOT_TIME_OF_DAY": "02:00",
    "Setting.IGNORE_IPV6_ADDRESSES": true
}
 ```
 ###### Addon Logs:
 ```
 10-23 18:56:10 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
10-23 18:56:10 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-23 18:56:11 INFO [backup.drive.folderfinder] Found Home Assistant Snapshots
10-23 18:56:11 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271tkiSUMG08tk38vCB0NcAAnQOlF-oLYbf%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-23 18:56:11 ERROR [backup.model.coordinator] A backup folder already exists.  Please visit the add-on Web UI to select where to backup.
10-23 18:56:11 INFO [backup.model.coordinator] I'll try again in an hour
10-23 19:56:12 DEBUG [backup.model.syncer] Sync requested by Coordinator
10-23 19:56:12 INFO [backup.model.coordinator] Syncing Snapshots
10-23 19:56:12 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-23 19:56:12 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
10-23 19:56:12 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-23 19:56:13 INFO [backup.drive.folderfinder] Found Home Assistant Snapshots
10-23 19:56:13 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271tkiSUMG08tk38vCB0NcAAnQOlF-oLYbf%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-23 19:56:13 ERROR [backup.model.coordinator] A backup folder already exists.  Please visit the add-on Web UI to select where to backup.
10-23 19:56:13 INFO [backup.model.coordinator] I'll try again in an hour
10-23 20:35:26 INFO [backup.model.coordinator] Syncing Snapshots
10-23 20:35:26 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-23 20:35:26 INFO [backup.drive.folderfinder] Saving snapshot folder: 1tkiSUMG08tk38vCB0NcAAnQOlF-oLYbf
10-23 20:35:26 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:133 (sync)
  addon/backup/model/model.py:216 (_syncSnapshots)
  addon/backup/drive/drivesource.py:84 (get)
  addon/backup/drive/drivesource.py:189 (getFolderId)
  addon/backup/drive/folderfinder.py:52 (get)
  addon/backup/drive/folderfinder.py:80 (save)
FileNotFoundError: [Errno 2] No such file or directory: '/data/folder.dat'

10-23 20:35:26 INFO [backup.model.coordinator] I'll try again in an hour
10-23 20:37:25 INFO [backup.model.coordinator] Syncing Snapshots
10-23 20:37:25 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-23 20:37:25 INFO [backup.drive.folderfinder] Saving snapshot folder: 1tkiSUMG08tk38vCB0NcAAnQOlF-oLYbf
10-23 20:37:25 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:133 (sync)
  addon/backup/model/model.py:216 (_syncSnapshots)
  addon/backup/drive/drivesource.py:84 (get)
  addon/backup/drive/drivesource.py:189 (getFolderId)
  addon/backup/drive/folderfinder.py:52 (get)
  addon/backup/drive/folderfinder.py:80 (save)
FileNotFoundError: [Errno 2] No such file or directory: '/data/folder.dat'

10-23 20:37:25 INFO [backup.model.coordinator] I'll try again in an hour
10-23 20:37:36 INFO [backup.model.coordinator] Syncing Snapshots
10-23 20:37:36 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-23 20:37:36 INFO [backup.drive.folderfinder] Saving snapshot folder: 1tkiSUMG08tk38vCB0NcAAnQOlF-oLYbf
10-23 20:37:36 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:133 (sync)
  addon/backup/model/model.py:216 (_syncSnapshots)
  addon/backup/drive/drivesource.py:84 (get)
  addon/backup/drive/drivesource.py:189 (getFolderId)
  addon/backup/drive/folderfinder.py:52 (get)
  addon/backup/drive/folderfinder.py:80 (save)
FileNotFoundError: [Errno 2] No such file or directory: '/data/folder.dat'

10-23 20:37:36 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m20-10-23 15:32:43 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-23 15:56:08 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-23 16:02:08 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m20-10-23 16:02:18 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/yllibed/hassio repository[0m
[32m20-10-23 16:02:18 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository[0m
[32m20-10-23 16:02:18 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m20-10-23 16:02:18 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/danielwelch/hassio-zigbee2mqtt repository[0m
[32m20-10-23 16:02:18 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m20-10-23 16:02:20 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 0 remove[0m
[32m20-10-23 16:02:44 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-23 16:32:45 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-23 16:56:10 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-23 17:02:25 INFO (MainThread) [supervisor.host.info] Updating local host information[0m
[32m20-10-23 17:02:26 INFO (MainThread) [supervisor.host.services] Updating service information[0m
[32m20-10-23 17:02:26 INFO (MainThread) [supervisor.host.network] Updating local network information[0m
[32m20-10-23 17:02:27 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
[32m20-10-23 17:02:45 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-23 17:32:46 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-23 17:56:12 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-23 18:02:07 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files[0m
[32m20-10-23 18:02:08 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m20-10-23 18:02:47 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-23 18:32:48 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-23 18:35:26 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-23 18:35:44 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-23 18:35:45 INFO (MainThread) [supervisor.api.security] /core/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-23 18:37:25 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-23 18:37:36 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-23 18:38:24 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 2020-10-23 20:09:46 ERROR (Thread-1694) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:10:46 ERROR (Thread-1695) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:11:46 ERROR (Thread-1696) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:12:46 ERROR (Thread-1697) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:13:46 ERROR (Thread-1698) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:14:46 ERROR (Thread-1699) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:15:46 ERROR (Thread-1700) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:16:46 ERROR (Thread-1701) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:17:46 ERROR (Thread-1702) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:18:46 ERROR (Thread-1703) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:19:46 ERROR (Thread-1704) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:20:46 ERROR (Thread-1705) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:21:46 ERROR (Thread-1706) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:22:46 ERROR (Thread-1707) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:23:46 ERROR (Thread-1708) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:24:46 ERROR (Thread-1709) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:25:46 ERROR (Thread-1710) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:26:46 ERROR (Thread-1711) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:27:46 ERROR (Thread-1712) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:28:46 ERROR (Thread-1713) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:29:46 ERROR (Thread-1714) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:30:46 ERROR (Thread-1715) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:31:46 ERROR (Thread-1716) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:32:46 ERROR (Thread-1717) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:33:46 ERROR (Thread-1718) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:34:46 ERROR (Thread-1719) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:35:46 ERROR (Thread-1720) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:36:46 ERROR (Thread-1721) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device
2020-10-23 20:37:46 ERROR (Thread-1722) [custom_components.mitemp_bt.sensor] HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device

 ```
 `

**Comment by sabeechen** [comment]
Now that is strange, that directory its complaining about should always be available to the addon.  A few questions I have:

- Did this just start happening out of the blue, or did it start after some change you might have made (eg updating Home Assistant)?
- I suspect it might be a problem the supervisor is causing.   Could I have to try reinstalling the addon?  If you copy your config before you uninstall it and then copy it back before starting up again, you won't lose any of your snapshots or configuration (though you'll have to authenticate it with Google Drive again).  The addon will confirm you want to use a previously created snapshot folder once it starts up.

**Comment by kayo77** [comment]
Today Ive upgraded to HassOS 4.15
Everything is ok now.

**Comment by sabeechen** [comment]
I'm pretty sure this is a supervisor problem then.   There are ... a lot of problems that the supervisor can cause.  Some are persistant bugs, some are things they fix quickly, and some are transient problems that disappear as mysteriously as they arose.  The system has a lot of complexity owing to its docker foundation.

For anyone seeing this, I'd recommend the following:
1.  Make sure youre using the latest version of Home Assistant.
2. Restart the addon.
3. Restart the host machine.
4. Uninstall and then reinstall the addon (make sure you copy out your settings).

If none of that works, please reopen this bug and I'll try to help diagnose things further.
