### ISSUE TITLE
Upload Failed in google drive backup

### ISSUE THREAD

**Issue by rickbell** [sabeechen/hassio-google-drive-backup#289]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.101.3`
 Home Assistant Version: `0.116.4`
 Supervisor Version: `247`
 Supervisor Channel: `stable`
 Hassos Version: `4.13`
 Docker Version: `19.03.11`
 Architecture: `armv7`
 Machine: `raspberrypi3`
 Date: `2020-10-20T13:44:14.250243+00:00`
 Timezone: `Europe/Athens`
 Failure Time: `Never`
 Last Good Sync: `2020-10-20T13:35:35.848511+00:00`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "HomeAssistant",
        "latest": null,
        "size": "0.0 B"
    },
    "GoogleDrive": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "GoogleDrive",
        "latest": "2020-10-18T16:02:49Z",
        "size": "327.1 MB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 10-20 16:35:35 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
10-20 16:35:35 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
10-20 16:35:35 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
10-20 16:35:35 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
10-20 16:35:35 INFO [backup.ui.uiserver] Starting server on port 8099
10-20 16:35:35 INFO [backup.ui.uiserver] Server started
10-20 16:35:35 DEBUG [backup.model.syncer] Sync requested by Coordinator
10-20 16:35:35 INFO [backup.model.coordinator] Syncing Snapshots
10-20 16:35:35 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-20 16:35:35 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
10-20 16:35:36 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/159voMUgyvt7fkZImzUbeA2eXOeg3bHMQ/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
10-20 16:35:36 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%27159voMUgyvt7fkZImzUbeA2eXOeg3bHMQ%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-20 16:40:35 INFO [backup.ha.hasource] Downloading 'Full Snapshot 2020-10-08 14:52:46'
10-20 16:40:36 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/new/upload
10-20 16:40:36 ERROR [backup.ha.hasource] 
  addon/backup/ha/hasource.py:265 (save)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:67 (upload)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:213 (_postHassioData)
  addon/backup/ha/harequests.py:175 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:941 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://hassio/snapshots/new/upload')

10-20 16:43:41 INFO [backup.ha.hasource] Downloading 'Full Snapshot 2020-10-18 19:02:47'
10-20 16:43:45 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/new/upload
10-20 16:43:45 ERROR [backup.ha.hasource] 
  addon/backup/ha/hasource.py:265 (save)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:67 (upload)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:213 (_postHassioData)
  addon/backup/ha/harequests.py:175 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:941 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://hassio/snapshots/new/upload')

 ```
 ###### Supervisor Logs:
 ```
 [32m20-10-20 13:43:45 INFO (MainThread) [supervisor.api.security] /snapshots/new/upload access from cebe7a76_hassio_google_drive_backup[0m
[31m20-10-20 13:43:45 ERROR (MainThread) [aiohttp.server] Error handling request[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 110, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 55, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 100, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/security.py", line 172, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 59, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/snapshots.py", line 185, in upload
    reader = await request.multipart()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_request.py", line 588, in multipart
    return MultipartReader(self._headers, self._payload)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/multipart.py", line 530, in __init__
    self._boundary = ('--' + self._get_boundary()).encode()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/multipart.py", line 622, in _get_boundary
    assert mimetype.type == 'multipart', (
AssertionError: multipart/* content type expected[0m
[32m20-10-20 13:44:14 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[19:01:08] INFO: [32mUpdate udev information[0m
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Unable to find configuration. Creating default one in /config
2020-10-19 14:23:41 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook f69af5abf35c11f139122a77d1bdf4988961e006d989809c0761847d95bcb661 from 192.168.68.121
2020-10-19 14:23:41 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook f69af5abf35c11f139122a77d1bdf4988961e006d989809c0761847d95bcb661 from 192.168.68.121
2020-10-19 14:23:41 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook f69af5abf35c11f139122a77d1bdf4988961e006d989809c0761847d95bcb661 from 192.168.68.121
2020-10-19 14:23:41 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook f69af5abf35c11f139122a77d1bdf4988961e006d989809c0761847d95bcb661 from 192.168.68.121
2020-10-19 14:23:41 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook f69af5abf35c11f139122a77d1bdf4988961e006d989809c0761847d95bcb661 from 192.168.68.121
2020-10-19 14:23:44 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.68.121 (192.168.68.121) (Home Assistant/2020.6.2 (io.robbie.HomeAssistant; build:1; iOS 13.7.0) Alamofire/4.9.1)
2020-10-19 14:23:44 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.68.121 (192.168.68.121) (Home Assistant/2020.6.2 (io.robbie.HomeAssistant; build:1; iOS 13.7.0) Alamofire/4.9.1)
2020-10-19 14:23:44 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.68.121 (192.168.68.121) (Mozilla/5.0 (iPhone; CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2020.6.2 (io.robbie.HomeAssistant; build:1; iOS 13.7.0))
2020-10-19 17:28:16 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook f69af5abf35c11f139122a77d1bdf4988961e006d989809c0761847d95bcb661 from 192.168.68.121
2020-10-19 17:28:16 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook f69af5abf35c11f139122a77d1bdf4988961e006d989809c0761847d95bcb661 from 192.168.68.121
2020-10-20 14:10:23 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.68.132 (192.168.68.132) (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36)
2020-10-20 14:10:24 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.68.132 (192.168.68.132) (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36)
2020-10-20 14:32:20 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook f69af5abf35c11f139122a77d1bdf4988961e006d989809c0761847d95bcb661 from 192.168.68.121
2020-10-20 14:32:21 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook f69af5abf35c11f139122a77d1bdf4988961e006d989809c0761847d95bcb661 from 192.168.68.121

 ```
 Copy the info from the previous page here

**Comment by sabeechen** [comment]
Thanks for notifying me, I'll be fixing this in an update soon.  The supervisor's API changed without warning which unfortunately broke this part of the addon.
Duplicate #289
