### ISSUE TITLE
TypeError: setPending() missing 2 required positional arguments: 'retain_drive' and 'retain_ha'

### ISSUE THREAD

**Issue by sabeechen** [sabeechen/hassio-google-drive-backup#29]
Traceback (most recent call last):
  File "/app/backup/engine.py", line 150, in doBackupWorkflow
    self._checkForBackup()
  File "/app/backup/engine.py", line 382, in _checkForBackup
    self.startSnapshot()
  File "/app/backup/engine.py", line 291, in startSnapshot
    snapshot = self.hassio.newSnapshot(custom_name=custom_name, retain_drive=retain_drive, retain_ha=retain_ha)
  File "/app/backup/hassio.py", line 201, in newSnapshot
    self.pending_snapshot.setPending("Pending Snapshot", nowutc())
TypeError: setPending() missing 2 required positional arguments: 'retain_drive' and 'retain_ha'

**Comment by sabeechen** [comment]
This issue should only happen on v0.93 of the addon.  You'll see it if you've created a snapshot outside of the add-on (eg through the Hassio snapshots UI or from an automation) and then the add-on attempts to create a snapshot automatically or by you clicking the "Snapshot Now" button.  

The add-on will automatically recover from this once the snapshot is finished.  So it shouldn't result in any problems long-term or data loss.  I'll make a fix soon.
