### ISSUE TITLE
Problem - The Supervisor Returned an Unexpected Response

### ISSUE THREAD

**Issue by NickInManchester** [sabeechen/hassio-google-drive-backup#298]
Copy th
###### Description:
```
I seetup a new install of the backup tool in HA running on a 4G Raspberry Pi 4. Have close to 200G unused space on Google Drive, the link to Google seems OK. Also, I can hand upload using Samba share copied to Google with no problems. I have reduced the size of backup to almost nothing being included. Restarted, re-synced many times plus uninstalled and started again which seems to have made no difference. Everything is up to the very latest releases. System is rebooted several times per week as it is being actively used.

My HA install has one fault I have no idea where it comes from  - details pasted below - I do not think this is connected to the backup supervisor problem? 

Logger: homeassistant.setup
Source: setup.py:138
First occurred: 3:52:52 PM (1 occurrences)
Last logged: 3:52:52 PM

Setup failed for serial: No setup function defined.
```

 Addon version: `0.102.0`
 Home Assistant Version: `0.117.1`
 Supervisor Version: `2020.10.0`
 Supervisor Channel: `stable`
 Hassos Version: `4.15`
 Docker Version: `19.03.11`
 Architecture: `armv7`
 Machine: `raspberrypi4`
 Date: `2020-11-01T15:38:45.697639+00:00`
 Timezone: `Europe/London`
 Failure Time: `2020-11-01T15:38:36.069935+00:00`
 Last Good Sync: `2020-11-01T15:38:35.754741+00:00`
 ###### Exception:
 ```
 
  addon/backup/util/asynchttpgetter.py:142 (read)
  /site-packages/aiohttp/streams.py:431 (readexactly)
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
Whose handling caused:
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:165 (sync)
  addon/backup/drive/drivesource.py:150 (save)
  addon/backup/drive/driverequests.py:252 (create)
  addon/backup/util/asynchttpgetter.py:149 (read)
backup.exceptions.exceptions.SupervisorUnexpectedError

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 2,
        "retained": 0,
        "deletable": 2,
        "name": "HomeAssistant",
        "latest": "2020-11-01T01:55:25Z",
        "size": "15.8 GB"
    },
    "GoogleDrive": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "latest": null,
        "size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.EXCLUDE_FOLDERS": "media,share,addons/local",
    "Setting.EXCLUDE_ADDONS": "core_configurator,core_letsencrypt,core_deconz,core_mosquitto,core_samba,core_almond,core_ssh,core_check_config,a0d7b954_appdaemon,core_duckdns,core_dhcp_server,7ad98f9c_zigbee2mqtt,cebe7a76_hassio_google_drive_backup",
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 11-01 15:34:45 INFO [backup.drive.drivesource] Uploading 'HA Full Snapshot Sunday 01-11-2020 01:55:24' to Google Drive
11-01 15:34:45 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
11-01 15:34:45 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
11-01 15:34:46 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
11-01 15:34:46 INFO [backup.model.coordinator] I'll try again in an hour
11-01 15:35:10 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
11-01 15:35:10 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
11-01 15:35:10 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
11-01 15:35:10 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
11-01 15:38:26 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/options
11-01 15:38:26 INFO [backup.model.coordinator] Syncing Snapshots
11-01 15:38:26 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
11-01 15:38:26 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/18R4e0HkDh6ZBGDie-wMwgoRMHitVztbM/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
11-01 15:38:26 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%2718R4e0HkDh6ZBGDie-wMwgoRMHitVztbM%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
11-01 15:38:26 INFO [backup.drive.drivesource] Uploading 'HA Full Snapshot Sunday 01-11-2020 01:55:24' to Google Drive
11-01 15:38:26 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
11-01 15:38:26 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uwh_mx6GxsDkzwZpHrbucyhXIF6EmmiWWdzrvzMukFllCG6PuLhyZBXABLA0Xluri_ViVR5bRa2hvXxfXHzdnv9l3uPNQ
11-01 15:38:27 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 8488161280
11-01 15:38:27 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
11-01 15:38:27 INFO [backup.model.coordinator] I'll try again in an hour
11-01 15:38:35 INFO [backup.debugworker] Sending error report (see settings to disable)
11-01 15:38:35 INFO [backup.model.coordinator] Syncing Snapshots
11-01 15:38:35 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
11-01 15:38:35 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%2718R4e0HkDh6ZBGDie-wMwgoRMHitVztbM%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
11-01 15:38:36 INFO [backup.drive.drivesource] Uploading 'HA Full Snapshot Sunday 01-11-2020 01:55:24' to Google Drive
11-01 15:38:36 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
11-01 15:38:36 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-Uwh_mx6GxsDkzwZpHrbucyhXIF6EmmiWWdzrvzMukFllCG6PuLhyZBXABLA0Xluri_ViVR5bRa2hvXxfXHzdnv9l3uPNQ
11-01 15:38:36 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 8488161280
11-01 15:38:36 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
11-01 15:38:36 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [33m20-11-01 15:38:03 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:05 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:07 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:09 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:11 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:13 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:15 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:17 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:19 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:21 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:23 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:25 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[32m20-11-01 15:38:26 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-11-01 15:38:26 INFO (MainThread) [supervisor.api.security] /snapshots/da7041e3/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-11-01 15:38:26 INFO (MainThread) [supervisor.api.snapshots] Downloading snapshot da7041e3[0m
[33m20-11-01 15:38:27 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:29 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:31 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:33 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[32m20-11-01 15:38:35 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[33m20-11-01 15:38:35 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[32m20-11-01 15:38:36 INFO (MainThread) [supervisor.api.security] /snapshots/da7041e3/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-11-01 15:38:36 INFO (MainThread) [supervisor.api.snapshots] Downloading snapshot da7041e3[0m
[33m20-11-01 15:38:37 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:39 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[32m20-11-01 15:38:41 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[33m20-11-01 15:38:41 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[33m20-11-01 15:38:43 WARNING (MainThread) [supervisor.api.ingress] Ingress for Igw8reLIs8HVulIVAmVQAr5rcsrr_rDM2MRwme1Oc0o not available[0m
[32m20-11-01 15:38:45 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 2020-11-01 14:37:46 ERROR (MainThread) [homeassistant.setup] Setup failed for serial: No setup function defined.
2020-11-01 14:37:47 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2020-11-01 14:37:49 ERROR (MainThread) [homeassistant.components.media_player] Platform samsungtv does not generate unique IDs. ID 0bebc200-00c8-1000-87c7-50856978fdde already exists - ignoring media_player.samsung_ue39f5500
2020-11-01 14:37:51 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2020-11-01 14:37:51 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-11-01 14:37:51 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 5 seconds
2020-11-01 14:37:59 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up upnp platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 197, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/upnp/sensor.py", line 93, in async_setup_entry
    device: Device = hass.data[DOMAIN][DOMAIN_DEVICES][udn]
KeyError: 'uuid:ccd89e31-995f-4756-9398-d22d68671ffc'
2020-11-01 14:37:59 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-11-01 14:37:59 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 10 seconds
2020-11-01 14:38:12 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-11-01 14:38:12 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 20 seconds
2020-11-01 14:38:36 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-11-01 14:38:36 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 40 seconds
2020-11-01 14:39:19 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-11-01 14:39:19 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 80 seconds
2020-11-01 14:40:42 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-11-01 14:40:42 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 80 seconds
2020-11-01 14:42:05 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-11-01 14:42:05 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 80 seconds
2020-11-01 14:43:28 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-11-01 14:43:28 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 80 seconds
2020-11-01 14:44:51 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Error occurred while communicating with IPP server.
2020-11-01 14:44:51 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 80 seconds

 ```
 e info from the previous page here

**Comment by sabeechen** [comment]
You're seeing this issue, #226.  Its a bug in the supervisor, cause by a bug in python.  They're expecting to release a new version of the supervisor with a fix within the next week.

You'll see the problem so long as you're using the 32 bit version of home assistant and your snapshots are over 2 GB, both of which are true for you.

Duplicate #226

**Comment by NickInManchester** [comment]
Thank you. Reinstalled using 64 bit OS. Now backups running as hoped-for.

Nick
