### ISSUE TITLE
TypeError: replace() argument 2 must be str, not None

### ISSUE THREAD

**Issue by sabeechen** [sabeechen/hassio-google-drive-backup#30]
Traceback (most recent call last):
  File "/app/backup/engine.py", line 150, in doBackupWorkflow
    self._checkForBackup()
  File "/app/backup/engine.py", line 382, in _checkForBackup
    self.startSnapshot()
  File "/app/backup/engine.py", line 291, in startSnapshot
    snapshot = self.hassio.newSnapshot(custom_name=custom_name, retain_drive=retain_drive, retain_ha=retain_ha)
  File "/app/backup/hassio.py", line 204, in newSnapshot
    raise self.pending_snapshot_error  # pylint: disable-msg=E0702
  File "/app/backup/hassio.py", line 104, in _getSnapshot
    backup_name: str = self.getSnapshotName(snapshot_type, self._custom_name)
  File "/app/backup/hassio.py", line 160, in getSnapshotName
    template = template.replace("{version_hassos}", self.host_info.get('hassos', ''))
TypeError: replace() argument 2 must be str, not None

**Comment by sabeechen** [comment]
Working on a fix for this
