### ISSUE TITLE
uploading problem

### ISSUE THREAD

**Issue by Vooovan** [sabeechen/hassio-google-drive-backup#302]
11-05 13:26:50 ERROR 
Traceback (most recent call last):
  File "/app/backup/hasource.py", line 207, in save
    resp = self.harequests.upload(stream)
  File "/app/backup/harequests.py", line 41, in upload
    return self._postHassioData(url, data=stream)
  File "/app/backup/harequests.py", line 136, in _postHassioData
    return self._validateHassioReply(self._client.post(url, headers=self._getHassioHeaders(), json=json, data=data))
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

11-05 13:54:14 INFO Syncing Snapshots

**Comment by sabeechen** [comment]
Before digging any further into this I'd update the addon, you're using a pretty old version.

**Comment by sabeechen** [comment]
Once you do if you're still seeing an error, could you go to "Actions" -> "Report a Bug" and copy the bug report here?  It will contain a lot of logs and other information that can help me figure out whats going on.

**Comment by Vooovan** [comment]
so stupid of me, man
just didn't pay attention to version
works perfect
great thing by the way
thank you!

**Comment by sabeechen** [comment]
Great!
