### ISSUE TITLE
Read-only error.

### ISSUE THREAD

**Issue by Csepi** [sabeechen/hassio-google-drive-backup#304]
###### Description:
I've upgraded to 0.117.0and later the error appeared.
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.102.0`
 Home Assistant Version: `0.117.0`
 Supervisor Version: `2020.11.0`
 Supervisor Channel: `stable`
 Hassos Version: `4.15`
 Docker Version: `19.03.11`
 Architecture: `armv7`
 Machine: `raspberrypi4`
 Date: `2020-11-09T20:56:32.619620+00:00`
 Timezone: `UTC`
 Failure Time: `2020-11-09T19:57:04.193433+00:00`
 Last Good Sync: `2020-11-09T19:57:03.244987+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:147 (sync)
  addon/backup/model/model.py:181 (createSnapshot)
  addon/backup/ha/hasource.py:181 (create)
  addon/backup/ha/addon_stopper.py:85 (stopAddons)
  addon/backup/ha/addon_stopper.py:137 (_save)
OSError: [Errno 30] Read-only file system: '/data/stop_addon_state.json'

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 2,
        "retained": 0,
        "deletable": 2,
        "name": "HomeAssistant",
        "latest": "2020-11-04T06:07:00Z",
        "size": "383.2 MB"
    },
    "GoogleDrive": {
        "snapshots": 12,
        "retained": 0,
        "deletable": 12,
        "name": "GoogleDrive",
        "latest": "2020-11-04T06:07:00Z",
        "size": "2.2 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 3,
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 30,
    "Setting.SNAPSHOT_TIME_OF_DAY": "06:00"
}
 ```
 ###### Addon Logs:
 ```
 11-09 17:57:01 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
11-09 17:57:01 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
11-09 17:57:01 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
11-09 17:57:01 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
11-09 17:57:01 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:147 (sync)
  addon/backup/model/model.py:181 (createSnapshot)
  addon/backup/ha/hasource.py:181 (create)
  addon/backup/ha/addon_stopper.py:85 (stopAddons)
  addon/backup/ha/addon_stopper.py:137 (_save)
OSError: [Errno 30] Read-only file system: '/data/stop_addon_state.json'

11-09 17:57:01 INFO [backup.model.coordinator] I'll try again in an hour
11-09 18:57:02 DEBUG [backup.model.syncer] Sync requested by Coordinator
11-09 18:57:02 INFO [backup.model.coordinator] Syncing Snapshots
11-09 18:57:02 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
11-09 18:57:02 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
11-09 18:57:02 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/12KBbiYANnoqXe6b1QYfSrnyNh8KDdV5O/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
11-09 18:57:02 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%2712KBbiYANnoqXe6b1QYfSrnyNh8KDdV5O%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
11-09 18:57:03 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
11-09 18:57:03 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
11-09 18:57:03 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
11-09 18:57:03 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
11-09 18:57:03 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:147 (sync)
  addon/backup/model/model.py:181 (createSnapshot)
  addon/backup/ha/hasource.py:181 (create)
  addon/backup/ha/addon_stopper.py:85 (stopAddons)
  addon/backup/ha/addon_stopper.py:137 (_save)
OSError: [Errno 30] Read-only file system: '/data/stop_addon_state.json'

11-09 18:57:03 INFO [backup.model.coordinator] I'll try again in an hour
11-09 19:57:03 DEBUG [backup.model.syncer] Sync requested by Coordinator
11-09 19:57:03 INFO [backup.model.coordinator] Syncing Snapshots
11-09 19:57:03 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
11-09 19:57:03 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
11-09 19:57:03 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/12KBbiYANnoqXe6b1QYfSrnyNh8KDdV5O/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
11-09 19:57:03 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%2712KBbiYANnoqXe6b1QYfSrnyNh8KDdV5O%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
11-09 19:57:04 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
11-09 19:57:04 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
11-09 19:57:04 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
11-09 19:57:04 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
11-09 19:57:04 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:147 (sync)
  addon/backup/model/model.py:181 (createSnapshot)
  addon/backup/ha/hasource.py:181 (create)
  addon/backup/ha/addon_stopper.py:85 (stopAddons)
  addon/backup/ha/addon_stopper.py:137 (_save)
OSError: [Errno 30] Read-only file system: '/data/stop_addon_state.json'

11-09 19:57:04 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
   File "/usr/local/lib/python3.8/pathlib.py", line 1077, in _opener
    return self._accessor.open(self, flags, mode)
OSError: [Errno 30] Read-only file system: '/data/tmp/tmp4iant1du/snapshot.json'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/snapshots/snapshot.py", line 303, in __aexit__
    write_json_file(Path(self._tmp.name, "snapshot.json"), self._data)
  File "/usr/src/supervisor/supervisor/utils/json.py", line 24, in write_json_file
    raise JsonFileError() from err
supervisor.exceptions.JsonFileError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/snapshots/__init__.py", line 143, in do_snapshot_full
    await snapshot.store_folders()
  File "/usr/src/supervisor/supervisor/snapshots/snapshot.py", line 308, in __aexit__
    self._tmp.cleanup()
  File "/usr/local/lib/python3.8/tempfile.py", line 831, in cleanup
    self._rmtree(self.name)
  File "/usr/local/lib/python3.8/tempfile.py", line 813, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/usr/local/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/lib/python3.8/shutil.py", line 672, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/lib/python3.8/shutil.py", line 670, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 30] Read-only file system: 'core_samba.tar.gz'[0m
[33m20-11-09 00:42:39 WARNING (MainThread) [supervisor.core] Can't update the Supervisor state to CoreState.RUNNING: [Errno 30] Read-only file system: '/run/supervisor'[0m
[32m20-11-09 00:42:39 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 Call stack:
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
Message: 'Error executing query: %s'
Arguments: (OperationalError('(sqlite3.OperationalError) unable to open database file'),)
2020-11-09 00:42:45 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity during commit: (sqlite3.OperationalError) unable to open database file
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('state_changed', '{}', 'LOCAL', '2020-11-09 00:41:15.499266', '2020-11-09 00:41:15.499266', '4e05af86444629b41f1d5b853a997b80', None, None)]
(Background on this error at: http://sqlalche.me/e/13/e3q8). (retrying in 3 seconds)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
OSError: [Errno 30] Read-only file system
Call stack:
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
Message: 'Error in database connectivity during commit: %s. (retrying in %s seconds)'
Arguments: (OperationalError('(sqlite3.OperationalError) unable to open database file'), 3)

 ```

**Comment by sabeechen** [comment]
I've seen this error come up a few times from a few different people.  I suspect its a problem with the supervisor, since the supervisor is supposed to make the directory being complained about ("/data") availabel to the addon before it starts  up.  Mostl likely something bad happened transiently with your upgrade.  Could I have you try:

- Restarting  the addon, and if that doesn't work
- Restart your raspberry pi

One of those two things seems to have resolved it for everyone else.

**Comment by sabeechen** [comment]
If this didn't work please reopen this issue and I can work further with you.
