### ISSUE TITLE
Error while backing up

### ISSUE THREAD

**Issue by smitt04** [sabeechen/hassio-google-drive-backup#315]
###### Description:

 Addon version: `0.102.0`
 Home Assistant Version: `2020.12.0`
 Supervisor Version: `2020.12.6`
 Supervisor Channel: `beta`
 Hassos Version: `5.8`
 Docker Version: `19.03.13`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2020-12-15T15:42:39.791843+00:00`
 Timezone: `America/Los_Angeles`
 Failure Time: `2020-12-15T15:42:12.535344+00:00`
 Last Good Sync: `2020-12-15T15:42:11.794867+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:147 (sync)
  addon/backup/model/model.py:181 (createSnapshot)
  addon/backup/ha/hasource.py:181 (create)
  addon/backup/ha/addon_stopper.py:85 (stopAddons)
  addon/backup/ha/addon_stopper.py:137 (_save)
OSError: [Errno 30] Read-only file system: '/data/stop_addon_state.json'

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "latest": "2020-12-14T14:47:19Z",
        "size": "4.4 GB"
    },
    "GoogleDrive": {
        "snapshots": 12,
        "retained": 0,
        "deletable": 12,
        "name": "GoogleDrive",
        "latest": "2020-12-14T14:47:19Z",
        "size": "12.4 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 12,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 1.0,
    "Setting.SNAPSHOT_TIME_OF_DAY": "02:00",
    "Setting.GENERATIONAL_DAYS": 7,
    "Setting.GENERATIONAL_WEEKS": 2,
    "Setting.GENERATIONAL_MONTHS": 3,
    "Setting.USE_SSL": true,
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 12-15 05:47:27 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1n4ST16g7aYnNmTXhTF4VVlXmYZFuR06a/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
12-15 05:47:28 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271n4ST16g7aYnNmTXhTF4VVlXmYZFuR06a%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
12-15 05:47:28 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
12-15 05:47:28 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
12-15 05:47:28 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
12-15 05:47:28 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
12-15 05:47:28 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:147 (sync)
  addon/backup/model/model.py:181 (createSnapshot)
  addon/backup/ha/hasource.py:181 (create)
  addon/backup/ha/addon_stopper.py:85 (stopAddons)
  addon/backup/ha/addon_stopper.py:137 (_save)
OSError: [Errno 30] Read-only file system: '/data/stop_addon_state.json'

12-15 05:47:28 INFO [backup.model.coordinator] I'll try again in an hour
12-15 06:47:29 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-15 06:47:29 INFO [backup.model.coordinator] Syncing Snapshots
12-15 06:47:29 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
12-15 06:47:29 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
12-15 06:47:29 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1n4ST16g7aYnNmTXhTF4VVlXmYZFuR06a/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
12-15 06:47:29 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271n4ST16g7aYnNmTXhTF4VVlXmYZFuR06a%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
12-15 06:47:30 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
12-15 06:47:30 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
12-15 06:47:30 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
12-15 06:47:30 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
12-15 06:47:30 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:147 (sync)
  addon/backup/model/model.py:181 (createSnapshot)
  addon/backup/ha/hasource.py:181 (create)
  addon/backup/ha/addon_stopper.py:85 (stopAddons)
  addon/backup/ha/addon_stopper.py:137 (_save)
OSError: [Errno 30] Read-only file system: '/data/stop_addon_state.json'

12-15 06:47:30 INFO [backup.model.coordinator] I'll try again in an hour
12-15 07:42:11 INFO [backup.model.coordinator] Syncing Snapshots
12-15 07:42:11 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
12-15 07:42:11 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1n4ST16g7aYnNmTXhTF4VVlXmYZFuR06a/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
12-15 07:42:12 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271n4ST16g7aYnNmTXhTF4VVlXmYZFuR06a%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
12-15 07:42:12 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
12-15 07:42:12 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
12-15 07:42:12 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
12-15 07:42:12 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
12-15 07:42:12 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:147 (sync)
  addon/backup/model/model.py:181 (createSnapshot)
  addon/backup/ha/hasource.py:181 (create)
  addon/backup/ha/addon_stopper.py:85 (stopAddons)
  addon/backup/ha/addon_stopper.py:137 (_save)
OSError: [Errno 30] Read-only file system: '/data/stop_addon_state.json'

12-15 07:42:12 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m20-12-14 20:18:22 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-12-14 20:21:44 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-12-14 20:48:31 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-12-14 21:01:33 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m20-12-14 21:01:33 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m20-12-14 21:03:12 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/beta.json[0m
[32m20-12-14 21:03:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m20-12-14 21:03:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m20-12-14 21:03:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/jeremywillans/hass-addons repository[0m
[32m20-12-14 21:03:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m20-12-14 21:03:23 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove[0m
[32m20-12-14 21:03:23 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove[0m
[32m20-12-14 21:18:41 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-12-14 21:21:45 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-12-14 21:48:42 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-12-14 22:01:33 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m20-12-14 22:01:33 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m20-12-14 22:03:38 INFO (MainThread) [supervisor.host.info] Updating local host information[0m
[32m20-12-14 22:03:39 INFO (MainThread) [supervisor.host.services] Updating service information[0m
[32m20-12-14 22:03:39 INFO (MainThread) [supervisor.host.network] Updating local network information[0m
[32m20-12-14 22:03:42 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
[32m20-12-14 22:03:42 INFO (MainThread) [supervisor.host] Host information reload completed[0m
[32m20-12-14 22:18:49 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-12-14 22:21:47 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-12-14 22:48:57 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-12-14 23:01:33 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m20-12-14 23:01:33 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m20-12-14 23:03:11 INFO (MainThread) [supervisor.snapshots] Found 4 snapshot files[0m
[32m20-12-14 23:03:12 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/beta.json[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
Message: '[547249368320] Received %s'
Arguments: {'type': 'browser_mod/update', 'deviceID': '5d49c88f-e0692a51', 'data': {'browser': {'path': '/hassio/addon/core_mosquitto/logs', 'visibility': 'hidden', 'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0', 'currentUser': 'Kevin', 'fullyKiosk': False, 'width': 1920, 'height': 1101}}, 'id': 2932}
[36m2020-12-14 15:16:34 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.5d49c88f_e0692a51, old_state=<state sensor.5d49c88f_e0692a51=1; type=browser_mod, last_seen=2020-12-14T07:16:27.493979-08:00, deviceID=5d49c88f-e0692a51, path=/hassio/addon/core_mosquitto/logs, visibility=hidden, userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0, currentUser=Kevin, fullyKiosk=False, width=1920, height=1101 @ 2020-12-14T07:20:15.974027-08:00>, new_state=<state sensor.5d49c88f_e0692a51=1; type=browser_mod, last_seen=2020-12-14T07:16:34.607572-08:00, deviceID=5d49c88f-e0692a51, path=/hassio/addon/core_mosquitto/logs, visibility=hidden, userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0, currentUser=Kevin, fullyKiosk=False, width=1920, height=1101 @ 2020-12-14T07:20:15.974027-08:00>>[0m
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
OSError: [Errno 30] Read-only file system
Call stack:
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
Message: 'Bus:Handling %s'
Arguments: (<Event state_changed[L]: entity_id=sensor.5d49c88f_e0692a51, old_state=<state sensor.5d49c88f_e0692a51=1; type=browser_mod, last_seen=2020-12-14T07:16:27.493979-08:00, deviceID=5d49c88f-e0692a51, path=/hassio/addon/core_mosquitto/logs, visibility=hidden, userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0, currentUser=Kevin, fullyKiosk=False, width=1920, height=1101 @ 2020-12-14T07:20:15.974027-08:00>, new_state=<state sensor.5d49c88f_e0692a51=1; type=browser_mod, last_seen=2020-12-14T07:16:34.607572-08:00, deviceID=5d49c88f-e0692a51, path=/hassio/addon/core_mosquitto/logs, visibility=hidden, userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0, currentUser=Kevin, fullyKiosk=False, width=1920, height=1101 @ 2020-12-14T07:20:15.974027-08:00>>,)
[36m2020-12-14 15:16:34 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [548106446784] Sending {"id": 3, "type": "event", "event": {"event_type": "state_changed", "data": {"entity_id": "sensor.5d49c88f_e0692a51", "old_state": {"entity_id": "sensor.5d49c88f_e0692a51", "state": "1", "attributes": {"type": "browser_mod", "last_seen": "2020-12-14T15:16:27.493979", "deviceID": "5d49c88f-e0692a51", "path": "/hassio/addon/core_mosquitto/logs", "visibility": "hidden", "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0", "currentUser": "Kevin", "fullyKiosk": false, "width": 1920, "height": 1101}, "last_changed": "2020-12-14T15:20:15.974027+00:00", "last_updated": "2020-12-14T23:16:27.694765+00:00", "context": {"id": "793df67e9181c8ec59cc5f000251336b", "parent_id": null, "user_id": null}}, "new_state": {"entity_id": "sensor.5d49c88f_e0692a51", "state": "1", "attributes": {"type": "browser_mod", "last_seen": "2020-12-14T15:16:34.607572", "deviceID": "5d49c88f-e0692a51", "path": "/hassio/addon/core_mosquitto/logs", "visibility": "hidden", "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:84.0) Gecko/20100101 Firefox/84.0", "currentUser": "Kevin", "fullyKiosk": false, "width": 1920, "height": 1101}, "last_changed": "2020-12-14T15:20:15.974027+00:00", "last_updated": "2020-12-14T23:16:34.608981+00:00", "context": {"id": "20b37e10c6b5efa1d9468d653175e3c3", "parent_id": null, "user_id": null}}}, "origin": "LOCAL", "time_fired": "2020-12-14T23:16:34.608981+00:00", "context": {"id": "20b37e10c6b5efa1d9468d653175e3c3", "parent_id": null, "user_id": null}}}[0m
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()

 ```

**Comment by smitt04** [comment]
Turns out is was because my ssd decided to be read only. Fixed with a reboot.
