### ISSUE TITLE
Snapshot will not work because the sytem is in startup. for weeks.

### ISSUE THREAD

**Issue by jhiller227** [sabeechen/hassio-google-drive-backup#375]
Copy the info from the previous page here
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.103.1`
 Home Assistant Version: `2021.2.3`
 Supervisor Version: `2021.03.6`
 Supervisor Channel: `stable`
 Hassos Version: `5.12`
 Docker Version: `19.03.13`
 Architecture: `amd64`
 Machine: `intel-nuc`
 Date: `2021-04-04T03:01:03.665390+00:00`
 Timezone: `America/Chicago`
 Failure Time: `2021-04-04T02:59:27.818269+00:00`
 Last Good Sync: `2021-04-04T02:59:28.323033+00:00`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 2,
        "retained": 0,
        "deletable": 2,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-04-04T02:59:27Z",
        "max": 1,
        "enabled": true,
        "size": "343.4 MB",
        "free_space": "207.1 GB"
    },
    "GoogleDrive": {
        "snapshots": 20,
        "retained": 0,
        "deletable": 20,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2021-03-09T05:00:01Z",
        "max": 20,
        "enabled": true,
        "size": "6.7 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 1,
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 20,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 1.0,
    "Setting.SNAPSHOT_TIME_OF_DAY": "23:00",
    "Setting.EXCLUDE_FOLDERS": "media",
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 04-03 21:59:26 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
04-03 21:59:26 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
04-03 21:59:26 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
04-03 21:59:26 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
04-03 21:59:27 INFO [backup.ui.uiserver] Starting server on port 8099
04-03 21:59:27 INFO [backup.ui.uiserver] Server started
04-03 21:59:27 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-03 21:59:27 INFO [backup.model.coordinator] Syncing Snapshots
04-03 21:59:27 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
04-03 21:59:27 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/36e355c3/info
04-03 21:59:27 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-03 21:59:27 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1pZLBZb9nDTUSI_YDaNBratGG96RNxlA8/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
04-03 21:59:27 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271pZLBZb9nDTUSI_YDaNBratGG96RNxlA8%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
04-03 21:59:27 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
04-03 21:59:27 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
04-03 21:59:27 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
04-03 21:59:27 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
04-03 21:59:27 INFO [backup.ha.hasource] Requesting a new snapshot
04-03 21:59:27 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/new/partial
04-03 21:59:27 WARNING [backup.ha.hasource] A snapshot was already in progress
04-03 21:59:27 ERROR [backup.model.coordinator] A snapshot is already in progress
04-03 21:59:27 INFO [backup.model.coordinator] I'll try again right now
04-03 21:59:28 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-03 21:59:28 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-03 21:59:28 INFO [backup.model.coordinator] Syncing Snapshots
04-03 21:59:28 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
04-03 21:59:28 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271pZLBZb9nDTUSI_YDaNBratGG96RNxlA8%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
 ```
 ###### Supervisor Logs:
 ```
 [32m21-04-04 02:48:18 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-ssh with version 9.0.2[0m
[32m21-04-04 02:48:19 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-duckdns with version 1.12.5[0m
[32m21-04-04 02:48:24 INFO (MainThread) [supervisor.core] Start Home Assistant Core[0m
[32m21-04-04 02:48:24 INFO (SyncWorker_4) [supervisor.docker.interface] Starting homeassistant[0m
[32m21-04-04 02:48:24 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready[0m
[32m21-04-04 02:48:29 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[31m21-04-04 02:48:55 ERROR (MainThread) [supervisor.utils] Can't execute update while a task is in progress[0m
[32m21-04-04 02:49:21 INFO (MainThread) [supervisor.snapshots] Found 1 snapshot files[0m
[32m21-04-04 02:49:55 INFO (MainThread) [supervisor.snapshots] Found 1 snapshot files[0m
[32m21-04-04 02:50:20 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m21-04-04 02:50:20 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.STARTUP[0m
[32m21-04-04 02:50:20 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[33m21-04-04 02:50:28 WARNING (MainThread) [supervisor.jobs] 'Supervisor.restart' blocked from execution, system is not running - CoreState.STARTUP[0m
[32m21-04-04 02:51:00 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on esphome/esphome-hassio-amd64 with version 1.16.2[0m
[32m21-04-04 02:51:01 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_esphome[0m
[31m21-04-04 02:57:50 ERROR (MainThread) [supervisor.utils] Can't execute update while a task is in progress[0m
[33m21-04-04 02:58:11 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_partial' blocked from execution, system is not running - CoreState.STARTUP[0m
[32m21-04-04 02:58:35 INFO (MainThread) [supervisor.snapshots] Found 1 snapshot files[0m
[32m21-04-04 02:59:26 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on sabeechen/hassio-google-drive-backup-amd64 with version 0.103.1[0m
[32m21-04-04 02:59:26 INFO (MainThread) [supervisor.api.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-04-04 02:59:27 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-04-04 02:59:27 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-04-04 02:59:27 INFO (MainThread) [supervisor.api.security] /snapshots/36e355c3/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-04-04 02:59:27 INFO (MainThread) [supervisor.api.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-04-04 02:59:27 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-04-04 02:59:27 INFO (MainThread) [supervisor.api.security] /snapshots/new/partial access from cebe7a76_hassio_google_drive_backup[0m
[33m21-04-04 02:59:27 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_snapshot_partial' blocked from execution, system is not running - CoreState.STARTUP[0m
[32m21-04-04 02:59:28 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-04-04 03:01:03 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 [s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[21:48:24] INFO: [32mUsing udev information from host[0m
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[33m2021-04-03 21:48:26 WARNING (MainThread) [homeassistant.components.recorder] The 'purge_interval' option is deprecated, please remove it from your configuration[0m
[33m2021-04-03 21:48:27 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=22 from 2021-03-19 01:35:53.043018)[0m
[31m2021-04-03 21:48:43 ERROR (Thread-16) [pychromecast.socket_client] [Basement speaker(192.168.0.131):8009] Failed to connect to service Google-Home-Mini-a4d2807ec76d82388ec711daf0070a05._googlecast._tcp.local., retrying in 5.0s[0m
[31m2021-04-03 21:48:54 ERROR (Thread-17) [pychromecast.socket_client] [Bedroom speaker(192.168.0.136):8009] Failed to connect to service Google-Home-Mini-aeaa842613a42a31cbad064f98f219fa._googlecast._tcp.local., retrying in 5.0s[0m
[33m2021-04-03 21:49:06 WARNING (Thread-8) [pychromecast.socket_client] [Garage speaker(192.168.0.122):8009] Heartbeat timeout, resetting connection[0m
[33m2021-04-03 21:49:28 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 5: Requested entity was not found.[0m
[33m2021-04-03 21:49:47 WARNING (Thread-8) [pychromecast.socket_client] [Garage speaker(192.168.0.122):8009] Heartbeat timeout, resetting connection[0m
[33m2021-04-03 21:52:24 WARNING (zeroconf-Engine-239) [zeroconf] Choked at offset 157 while unpacking b'\x00\x00\x84\x00\x00\x00\x00\x01\x00\x00\x00\x03\x0b_esphomelib\x04_tcp\x05local\x00\x00\x0c\x00\x01\x00\x00\x00x\x00.\x15living_room_light_fan\x0b_esphomelib\x04_tcp\x05local\x00\x15living_room_light_fan\x0b_esphomelib\x04_tcp\x05local\x00\x00\x10\x80\x01\x00\x00\x11\x94\x00\t\x0eversion=1.15.3\x14address=192.168.0.26\x10mac=840d8e485872\x0eversion=1.15.3\x14address=192.168.0.26\x10mac=840d8e485872\x0eversion=1.15.3\x14address=192.168.0.26\x10mac=840d8e485872\x0eversion=1.15.3\x14address=192.168.0.26\x10mac=840d8e485872\x0eversion=1.15.3\x14address=192.168.0.26\x10mac=840d8e485872\x15living_room_light_fan\x0b_esphomelib\x04_tcp\x05local\x00\x00!\x80\x01\x00\x00\x00x\x00#\x00\x00\x00\x00\x17\xa5\x15living_room_light_fan\x05local\x00\x15living_room_light_fan\x05local\x00\x00\x01\x80\x01\x00\x00\x00x\x00\x04\xc0\xa8\x00\x1a'[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 745, in __init__
    self.read_others()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 816, in read_others
    domain = self.read_name()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 893, in read_name
    raise IncomingDecodeError("Bad domain name at %s" % (off,))
zeroconf.IncomingDecodeError: Bad domain name at 208[0m
[33m2021-04-03 21:53:56 WARNING (Thread-8) [pychromecast.socket_client] [Garage speaker(192.168.0.122):8009] Heartbeat timeout, resetting connection[0m

 ```

**Comment by sabeechen** [comment]
Sorry this took me so long to get back to you.  From the logs it doesn't actually look like anything is going wrong.  The addon appears to be in the middle of starting up, but it looks like the supervisor is trying to shut down.  Its difficult to tell from just the logs.  Could you describe what is going wrong or post a bug report that has the error you're seeing in it?

**Comment by jhiller227** [comment]
I have rebuilt my NUC server and it is working now. Thank you so much for
looking into it for me.

**Comment by sabeechen** [comment]
Great!
