### ISSUE TITLE
Reporting Google Drive Full 

### ISSUE THREAD

**Issue by sjmotew** [sabeechen/hassio-google-drive-backup#418]
I am receiving a Google Drive full warning, yet on Google Drive I have 6-7 GB free and my back-ups are only 3 GB?

**Comment by sabeechen** [comment]
Could I have you go to "Actions" - > "Report a bug" in the addon web-ui and paste the contents here?  That will answer a lot of questions I might have about this.

**Comment by sjmotew** [comment]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.104.3`
 Home Assistant Version: `2021.6.5`
 Supervisor Version: `2021.06.3`
 Supervisor Channel: `stable`
 Hassos Version: `6.0`
 Docker Version: `20.10.6`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2021-06-19T16:00:40.131393+00:00`
 Timezone: `America/New_York`
 Failure Time: `2021-06-19T15:40:29.335829+00:00`
 Last Good Sync: `2021-06-19T15:40:28.399459+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:200 (sync)
  addon/backup/drive/drivesource.py:180 (save)
  addon/backup/drive/driverequests.py:248 (create)
  addon/backup/drive/driverequests.py:351 (retryRequest)
  addon/backup/creds/driverequester.py:33 (request)
  addon/backup/creds/driverequester.py:108 (raiseForKnownErrors)
backup.exceptions.exceptions.DriveQuotaExceeded

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-06-18T06:30:00Z",
        "max": 2,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 1,
        "size": "14.7 GB",
        "ignored_size": "183.1 MB",
        "free_space": "7.5 GB"
    },
    "GoogleDrive": {
        "snapshots": 1,
        "retained": 0,
        "deletable": 1,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2021-06-15T07:09:11Z",
        "max": 1,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "3.8 GB",
        "ignored_size": "0.0 B",
        "free_space": "3.4 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 2,
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 1,
    "Setting.IGNORE_UPGRADE_SNAPSHOTS": true,
    "Setting.SNAPSHOT_TIME_OF_DAY": "02:30",
    "Setting.DELETE_AFTER_UPLOAD": true,
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 06-19 09:40:26 ERROR [backup.model.coordinator] Google Drive is out of space
06-19 09:40:26 INFO [backup.model.coordinator] I'll try again in an hour
06-19 10:40:27 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-19 10:40:27 INFO [backup.model.coordinator] Syncing Snapshots
06-19 10:40:27 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
06-19 10:40:27 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-19 10:40:27 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1kkRv2EZ3ObgG9HHAgEwdFX9H2jKwk4bX/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
06-19 10:40:27 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
06-19 10:40:27 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271kkRv2EZ3ObgG9HHAgEwdFX9H2jKwk4bX%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
06-19 10:40:27 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2021-06-18 02:30:00' to Google Drive
06-19 10:40:27 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
06-19 10:40:27 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
06-19 10:40:28 ERROR [backup.model.coordinator] Google Drive is out of space
06-19 10:40:28 INFO [backup.model.coordinator] I'll try again in an hour
06-19 10:58:42 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
06-19 10:58:42 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
06-19 10:58:43 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
06-19 10:58:43 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
06-19 11:40:28 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-19 11:40:28 INFO [backup.model.coordinator] Syncing Snapshots
06-19 11:40:28 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
06-19 11:40:28 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-19 11:40:28 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1kkRv2EZ3ObgG9HHAgEwdFX9H2jKwk4bX/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
06-19 11:40:28 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
06-19 11:40:28 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271kkRv2EZ3ObgG9HHAgEwdFX9H2jKwk4bX%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
06-19 11:40:29 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2021-06-18 02:30:00' to Google Drive
06-19 11:40:29 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
06-19 11:40:29 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
06-19 11:40:29 ERROR [backup.model.coordinator] Google Drive is out of space
06-19 11:40:29 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m21-06-19 14:53:33 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[31m21-06-19 14:57:06 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 400, message='Invalid response status', url=URL('http://172.30.33.2:8099/socket.io/?EIO=4&transport=websocket&sid=On3hdljETykgLBAxAAAM')[0m
[32m21-06-19 14:58:28 INFO (MainThread) [supervisor.snapshots] Found 6 snapshot files[0m
[31m21-06-19 14:58:28 ERROR (MainThread) [supervisor.snapshots.snapshot] Can't read snapshot tarfile /data/backup/0fa5339f.tar: unexpected end of data[0m
[32m21-06-19 14:58:29 INFO (MainThread) [supervisor.snapshots] Found 6 snapshot files[0m
[31m21-06-19 14:58:29 ERROR (MainThread) [supervisor.snapshots.snapshot] Can't read snapshot tarfile /data/backup/0fa5339f.tar: unexpected end of data[0m
[32m21-06-19 14:58:43 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-06-19 14:58:43 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-06-19 15:23:34 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-06-19 15:33:02 INFO (MainThread) [supervisor.host.info] Updating local host information[0m
[32m21-06-19 15:33:03 INFO (MainThread) [supervisor.host.services] Updating service information[0m
[32m21-06-19 15:33:03 INFO (MainThread) [supervisor.host.network] Updating local network information[0m
[32m21-06-19 15:33:11 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
[32m21-06-19 15:33:12 INFO (MainThread) [supervisor.host] Host information reload completed[0m
[32m21-06-19 15:40:28 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-06-19 15:40:29 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/0c66df9e/download access from cebe7a76_hassio_google_drive_backup[0m
[32m21-06-19 15:40:29 INFO (MainThread) [supervisor.api.snapshots] Downloading snapshot 0c66df9e[0m
[32m21-06-19 15:48:51 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m21-06-19 15:49:21 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[33m21-06-19 15:49:21 WARNING (MainThread) [supervisor.resolution.check] Skipping disabled check addon_pwned[0m
[32m21-06-19 15:49:21 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m21-06-19 15:49:21 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m21-06-19 15:49:21 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m21-06-19 15:49:21 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m21-06-19 15:49:22 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m21-06-19 15:49:22 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m21-06-19 15:49:22 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m21-06-19 15:53:36 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-06-19 16:00:40 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/recteq/device.py", line 127, in update
    self._cached_status = self._pytuya.status()['dps']
  File "/usr/local/lib/python3.8/site-packages/pytuya/__init__.py", line 281, in status
    data = self._send_receive(payload)
  File "/usr/local/lib/python3.8/site-packages/pytuya/__init__.py", line 177, in _send_receive
    s.connect((self.address, self.port))
OSError: [Errno 113] Host is unreachable[0m
[31m2021-06-19 12:00:25 ERROR (stream_worker) [libav.NULL] sps_id 32 out of range[0m
[33m2021-06-19 12:00:30 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated[0m
[33m2021-06-19 12:00:30 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated[0m
[31m2021-06-19 12:00:31 ERROR (MainThread) [custom_components.recteq.device] Unexpected error fetching MO2 Recteq Smoker data: [Errno 113] Host is unreachable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/recteq/device.py", line 145, in _async_update_data
    await self.async_update()
  File "/config/custom_components/recteq/device.py", line 140, in async_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/recteq/device.py", line 127, in update
    self._cached_status = self._pytuya.status()['dps']
  File "/usr/local/lib/python3.8/site-packages/pytuya/__init__.py", line 281, in status
    data = self._send_receive(payload)
  File "/usr/local/lib/python3.8/site-packages/pytuya/__init__.py", line 177, in _send_receive
    s.connect((self.address, self.port))
OSError: [Errno 113] Host is unreachable[0m
[33m2021-06-19 12:00:35 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated[0m

 ```

**Comment by sjmotew** [comment]
I figured it out, there were 4GB of files in my trash that cleared when empty, so I probably didn't have the space.  Thanks for this hard work and integration.

**Comment by sabeechen** [comment]
Glad I could help!
