### ISSUE TITLE
An unexpected error occurred: Server disconnected

### ISSUE THREAD

**Issue by mikepruett3** [sabeechen/hassio-google-drive-backup#429]
###### Description:
```
Just installed the addon, via HASSIO. Changed the upload directory, and got this error.
```

 Addon version: `0.104.3`
 Home Assistant Version: `2021.7.2`
 Supervisor Version: `2021.06.8`
 Supervisor Channel: `stable`
 Hassos Version: `6.1`
 Docker Version: `20.10.6`
 Architecture: `amd64`
 Machine: `generic-x86-64`
 Date: `2021-07-14T07:03:02.245592+00:00`
 Timezone: `America/Chicago`
 Failure Time: `2021-07-14T07:02:05.008962+00:00`
 Last Good Sync: `2021-07-14T07:02:03.604728+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:200 (sync)
  addon/backup/drive/drivesource.py:172 (save)
  addon/backup/util/asynchttpgetter.py:221 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:161 (_startReadRemoteAt)
  addon/backup/tracing_session.py:20 (_request)
  /site-packages/aiohttp/client.py:544 (_request)
  /site-packages/aiohttp/client_reqrep.py:890 (start)
  /site-packages/aiohttp/streams.py:604 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-07-14T05:00:00Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "51.5 MB",
        "ignored_size": "0.0 B",
        "free_space": "7.6 GB"
    },
    "GoogleDrive": {
        "snapshots": 2,
        "retained": 0,
        "deletable": 2,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2021-07-14T05:00:00Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "51.5 MB",
        "ignored_size": "0.0 B",
        "free_space": "12.7 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.SPECIFY_SNAPSHOT_FOLDER": true
}
 ```
 ###### Addon Logs:
 ```
 07-14 02:00:50 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
07-14 02:00:50 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
07-14 02:00:51 DEBUG [backup.drive.driverequests] Sending 262144 bytes to Google Drive
07-14 02:00:51 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdsfGJUOKxbeXN5qF6qEWlk3MzcLBTEN9U3CvdyrpqTLuCd1ri8AlbF_IsjicJDXElsvjsryQuVMKrV38V7beq8
07-14 02:00:51 DEBUG [backup.drive.drivesource] Uploading core_2021.7.1 1.03%
07-14 02:00:51 DEBUG [backup.drive.driverequests] Sending 8912896 bytes to Google Drive
07-14 02:00:51 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdsfGJUOKxbeXN5qF6qEWlk3MzcLBTEN9U3CvdyrpqTLuCd1ri8AlbF_IsjicJDXElsvjsryQuVMKrV38V7beq8
07-14 02:00:58 DEBUG [backup.drive.drivesource] Uploading core_2021.7.1 35.96%
07-14 02:00:58 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
07-14 02:00:58 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdsfGJUOKxbeXN5qF6qEWlk3MzcLBTEN9U3CvdyrpqTLuCd1ri8AlbF_IsjicJDXElsvjsryQuVMKrV38V7beq8
07-14 02:01:06 DEBUG [backup.drive.drivesource] Uploading core_2021.7.1 77.05%
07-14 02:01:06 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
07-14 02:01:06 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdsfGJUOKxbeXN5qF6qEWlk3MzcLBTEN9U3CvdyrpqTLuCd1ri8AlbF_IsjicJDXElsvjsryQuVMKrV38V7beq8
07-14 02:01:12 DEBUG [backup.drive.drivesource] Uploading core_2021.7.1 100.00%
07-14 02:01:12 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/15EbEOMoY-MNWwPOHJIXERwF-LK5Em3Wa/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
07-14 02:01:12 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/15uTwks6Sefdoq1b7rj-8xeCf9pJKfM2E/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
07-14 02:01:12 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:200 (sync)
  addon/backup/drive/drivesource.py:172 (save)
  addon/backup/util/asynchttpgetter.py:221 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:161 (_startReadRemoteAt)
  addon/backup/tracing_session.py:20 (_request)
  /site-packages/aiohttp/client.py:544 (_request)
  /site-packages/aiohttp/client_reqrep.py:890 (start)
  /site-packages/aiohttp/streams.py:604 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

07-14 02:01:12 INFO [backup.model.coordinator] I'll try again in an hour
07-14 02:01:39 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
07-14 02:01:39 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
07-14 02:01:39 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
07-14 02:01:39 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
07-14 02:02:03 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/options
07-14 02:02:03 INFO [backup.drive.folderfinder] Saving snapshot folder: 15uTwks6Sefdoq1b7rj-8xeCf9pJKfM2E
07-14 02:02:03 INFO [backup.model.coordinator] Syncing Snapshots
07-14 02:02:03 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-14 02:02:03 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
07-14 02:02:04 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%2715uTwks6Sefdoq1b7rj-8xeCf9pJKfM2E%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
07-14 02:02:05 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:200 (sync)
  addon/backup/drive/drivesource.py:172 (save)
  addon/backup/util/asynchttpgetter.py:221 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:161 (_startReadRemoteAt)
  addon/backup/tracing_session.py:20 (_request)
  /site-packages/aiohttp/client.py:544 (_request)
  /site-packages/aiohttp/client_reqrep.py:890 (start)
  /site-packages/aiohttp/streams.py:604 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

07-14 02:02:05 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m21-07-14 02:01:39 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-07-14 02:01:39 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-07-14 02:02:03 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-07-14 02:02:04 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/242f21fa/download access from cebe7a76_hassio_google_drive_backup[0m
[32m21-07-14 02:02:04 INFO (MainThread) [supervisor.api.snapshots] Downloading snapshot 242f21fa[0m
[31m21-07-14 02:02:05 ERROR (MainThread) [aiohttp.server] Unhandled exception[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 485, in start
    resp, reset = await task
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 440, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 591, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 115, in prepare
    st = await loop.run_in_executor(None, filepath.stat)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/pathlib.py", line 1222, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: '/data/backup/242f21fa.tar'[0m
[32m21-07-14 02:02:23 INFO (MainThread) [supervisor.api.middleware.security] /addons/core_mosquitto/icon access from cebe7a76_hassio_google_drive_backup[0m
[32m21-07-14 02:02:23 INFO (MainThread) [supervisor.api.middleware.security] /addons/core_samba/icon access from cebe7a76_hassio_google_drive_backup[0m
[32m21-07-14 02:02:23 INFO (MainThread) [supervisor.api.middleware.security] /addons/core_check_config/icon access from cebe7a76_hassio_google_drive_backup[0m
[32m21-07-14 02:02:23 INFO (MainThread) [supervisor.api.middleware.security] /addons/core_ssh/icon access from cebe7a76_hassio_google_drive_backup[0m
[32m21-07-14 02:02:23 INFO (MainThread) [supervisor.api.middleware.security] /addons/core_configurator/icon access from cebe7a76_hassio_google_drive_backup[0m
[32m21-07-14 02:02:23 INFO (MainThread) [supervisor.api.middleware.security] /addons/9409ee68_tasmobackup/icon access from cebe7a76_hassio_google_drive_backup[0m
[32m21-07-14 02:02:23 INFO (MainThread) [supervisor.api.middleware.security] /addons/a0d7b954_wireguard/icon access from cebe7a76_hassio_google_drive_backup[0m
[32m21-07-14 02:02:23 INFO (MainThread) [supervisor.api.middleware.security] /addons/a0d7b954_vscode/icon access from cebe7a76_hassio_google_drive_backup[0m
[32m21-07-14 02:03:02 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 [31m2021-07-13 17:30:08 ERROR (MainThread) [homeassistant.components.speedtestdotnet] Error fetching speedtestdotnet data: [0m
[33m2021-07-13 17:38:05 WARNING (SyncWorker_7) [homeassistant.components.ring] Error fetching Ring history data for device 50338bfc3184: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-13 17:39:05 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring device data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-13 17:40:05 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring device data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-13 17:41:05 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-13 17:44:05 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-13 17:48:05 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-13 17:50:05 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-13 18:26:05 WARNING (SyncWorker_6) [homeassistant.components.ring] Error fetching Ring history data for device 50338bfc3184: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-13 19:26:46 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 071-087-078-124.res.spectrum.com (71.87.78.124). (Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2021.6 (io.robbie.HomeAssistant; build:2021.158; iOS 14.6.0) Mobile/HomeAssistant, like Safari)[0m
[33m2021-07-13 19:28:48 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Disk Usage Alert' trigger: In 'numeric_state' condition: entity sensor.disk_use_percent state '%' cannot be processed as a number[0m
[33m2021-07-13 20:06:05 WARNING (SyncWorker_6) [homeassistant.components.ring] Error fetching Ring history data for device 50338bfc3184: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-13 20:29:49 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: 504 Server Error: Gateway Time-out for url: https://api.ring.com/clients_api/dings/active?api_version=9[0m
[33m2021-07-13 22:01:19 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Disk Usage Alert' trigger: In 'numeric_state' condition: entity sensor.disk_use_percent state '%' cannot be processed as a number[0m
[33m2021-07-14 00:00:20 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Disk Usage Alert' trigger: In 'numeric_state' condition: entity sensor.disk_use_percent state '%' cannot be processed as a number[0m
[33m2021-07-14 00:01:05 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Disk Usage Alert' trigger: In 'numeric_state' condition: entity sensor.disk_use_percent state '%' cannot be processed as a number[0m
[33m2021-07-14 00:27:05 WARNING (SyncWorker_1) [homeassistant.components.ring] Error fetching Ring history data for device 50338bfc3184: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-14 00:29:05 WARNING (SyncWorker_7) [homeassistant.components.ring] Error fetching Ring history data for device 50338bfc3184: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-14 00:30:05 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring device data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-14 00:31:05 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring device data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-14 00:34:05 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-14 00:36:05 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-14 00:37:05 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))[0m
[33m2021-07-14 00:41:05 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Disk Usage Alert' trigger: In 'numeric_state' condition: entity sensor.disk_use_percent state '%' cannot be processed as a number[0m
[33m2021-07-14 01:57:35 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Disk Usage Alert' trigger: In 'numeric_state' condition: entity sensor.disk_use_percent state '%' cannot be processed as a number[0m
[33m2021-07-14 01:57:50 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Disk Usage Alert' trigger: In 'numeric_state' condition: entity sensor.disk_use_percent state '%' cannot be processed as a number[0m
[33m2021-07-14 01:58:05 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Disk Usage Alert' trigger: In 'numeric_state' condition: entity sensor.disk_use_percent state '%' cannot be processed as a number[0m
[33m2021-07-14 01:58:20 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Disk Usage Alert' trigger: In 'numeric_state' condition: entity sensor.disk_use_percent state '%' cannot be processed as a number[0m
[33m2021-07-14 01:58:50 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error in 'Disk Usage Alert' trigger: In 'numeric_state' condition: entity sensor.disk_use_percent state '%' cannot be processed as a number[0m

 ```

**Comment by sabeechen** [comment]
Thanks for using the bug reporter, that gives me a lot of useful context.  It looks like whats happening is the supervisor (formerly Hass.io) is returning an error when the add-on attempts to read one of your snapshots.  You can see this in the supervisor logs where it says:
```
FileNotFoundError: [Errno 2] No such file or directory: '/data/backup/242f21fa.tar'
```
The supervisor is unexpectedly closing its connection to the addon when it gets this error, which is whay the addon complains about a "ServerDisconnectedError".  From the logs it looks like the the add-on ran into the same problem with the snapshot before you saved a new snapshot folder, so changing the snapshot folder is probably unrelated.  Its hard for me to say what could cause this to happen.  My guesses would be:
- Something deleted the snapshot file without the supervisor noticing.
- A bug in the supervisor has caused it to expect a file that doesn't exist to be there.
- Something is preventing the supervisor from reading the snapshot file, e.g. something else has a file lock on it.

I would try the following to resolve this:
- Restart the host machine running Home Assistant (this resolves most supervisor problems).
- Manually delete the problematic snapshot.  This should be the oldest snapshot the add-on hasn't uploaded to Google Drive yet.
  - You might be able to delete it from the add-on web-UI
  - You might be able to delete it form the supervisor's snapshot management page (```Supervisor``` > ```snapshots```)
  - If all else fails you should be able to delete it using the Samba add-on, it would be the file named ```/backup/242f21fa.tar```

As you might suspect from my suggestions, I strongly believe that this is a problem or bug in the supervisor and not the add-on.  Regardless, I'd like to provide better guidance if other users run into this problem, so if you figure out what works to resolve this or what caused it in the first place please let me know.

**Comment by sabeechen** [comment]
I'm going to close this issue for now, but please feel free to re-open it if you think there is something else I can help with.
