### ISSUE TITLE
Please add a title

### ISSUE THREAD

**Issue by BowenTheOne** [sabeechen/hassio-google-drive-backup#441]
Copy the info from the previous page here
Hi, i followed the instructions but i have a " 401 unauthorised " error. did i do a mistake ? Thanks in advance for your help

###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.104.3`
 Home Assistant Version: `2021.6.3`
 Supervisor Version: `2021.06.8`
 Supervisor Channel: `beta`
 Hassos Version: `6.0`
 Docker Version: `20.10.6`
 Architecture: `armv7`
 Machine: `raspberrypi4`
 Date: `2021-08-07T14:25:48.271805+00:00`
 Timezone: `Europe/Paris`
 Failure Time: `Never`
 Last Good Sync: `2021-08-07T14:24:37.148457+00:00`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 32,
        "retained": 0,
        "deletable": 32,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-06-11T14:57:28Z",
        "max": 10,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "1.1 GB",
        "ignored_size": "0.0 B",
        "free_space": "19.3 GB"
    },
    "GoogleDrive": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 10,
        "enabled": false,
        "icon": "google-drive",
        "ignored": 0,
        "size": "0.0 B",
        "ignored_size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 10,
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 10,
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/bd799085/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/1858e202/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/229f1dbb/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/6779a3a4/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/e46188ad/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/7dadfc99/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/3be6fac3/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/e285fe68/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/18b57c74/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/07546916/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/2474e1f5/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/36acccf0/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/b26ff1be/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/c995f2f6/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/31e76fc3/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/dc78489c/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/9d8a3d80/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/b6cece07/info
08-07 16:22:13 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/caacd816/info
08-07 16:23:35 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
08-07 16:23:35 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
08-07 16:23:35 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
08-07 16:23:35 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
08-07 16:24:36 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/options
08-07 16:24:37 INFO [backup.model.coordinator] Syncing Snapshots
08-07 16:24:37 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-07 16:24:56 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
08-07 16:24:56 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
08-07 16:24:56 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
08-07 16:24:56 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
 ```
 ###### Supervisor Logs:
 ```
 [32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/9c5904e7/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/bd799085/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/1858e202/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/229f1dbb/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/6779a3a4/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/e46188ad/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/7dadfc99/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/3be6fac3/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/e285fe68/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/18b57c74/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/07546916/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/2474e1f5/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/36acccf0/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/b26ff1be/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/c995f2f6/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/31e76fc3/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/dc78489c/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/9d8a3d80/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/b6cece07/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:22:13 INFO (MainThread) [supervisor.api.middleware.security] /snapshots/caacd816/info access from cebe7a76_hassio_google_drive_backup[0m
[33m21-08-07 16:22:50 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m21-08-07 16:23:19 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[32m21-08-07 16:23:35 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:23:35 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:24:37 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:24:56 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-07 16:24:56 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[33m21-08-07 16:25:26 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[32m21-08-07 16:25:48 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/local/lib/python3.8/site-packages/zigpy_znp/api.py", line 523, in request
    response = await response_future
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError[0m
[33m2021-08-07 16:25:35 WARNING (MainThread) [homeassistant.components.vacuum] Updating xiaomi_miio vacuum took longer than the scheduled update interval 0:00:20[0m
[31m2021-08-07 16:25:36 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: timed out[0m
[31m2021-08-07 16:25:47 ERROR (MainThread) [zigpy_znp.zigbee.application] Failed to reconnect
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zigpy_znp/api.py", line 523, in request
    response = await response_future
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zigpy_znp/zigbee/application.py", line 1139, in _reconnect
    await self._startup()
  File "/usr/local/lib/python3.8/site-packages/zigpy_znp/zigbee/application.py", line 210, in _startup
    await znp.connect()
  File "/usr/local/lib/python3.8/site-packages/zigpy_znp/api.py", line 254, in connect
    self.capabilities = (await self.request(c.SYS.Ping.Req())).Capabilities
  File "/usr/local/lib/python3.8/site-packages/zigpy_znp/api.py", line 523, in request
    response = await response_future
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError[0m

 ```

**Comment by sabeechen** [comment]
If you're seeing a 401 when you try to connect the addon with Google Drive, you'll need to copy the authorization string from the authentication website (habackup.io) manually into the addon.
You'll need to copy the string from this website (habackup.io):
![image](https://user-images.githubusercontent.com/21026774/128616293-19844ea6-4008-49f0-984c-7da94e9111fb.png)

And then paste it here (eg the addon "Web-UI"):
![image](https://user-images.githubusercontent.com/21026774/128616301-8f0d7375-f27d-492d-8c11-493dca5dfb32.png)


If that isn't what you're seeing, let me know where you're seeing the 401 more specifically.  From your logs it looks like everything else is working correctly.

**Comment by BowenTheOne** [comment]
Thanks, i just have follow a yt video, and i just follow like a sheep. 
Sorry
