### ISSUE TITLE
Plug in stopped working - Task exception was never retrieved

### ISSUE THREAD

**Issue by roopesh** [sabeechen/hassio-google-drive-backup#472]
Just started getting this error and the add-on never starts up.
HA: 2021.9.5 (thought this started while I was on 2021.8.x)
Add-on : 0.105.1

```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/lib/python3.9/site-packages/aiorun.py:221> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/aiorun.py", line 231, in new_coro
    await coro
  File "/app/backup/__main__.py", line 11, in main
    await Injector([BaseModule(), MainModule()]).get(Starter).start()
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 963, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 111, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 806, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 291, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 990, in create_object
    self.call_with_injection(cls.__init__, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1021, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 111, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1069, in args_to_inject
    instance = self.get(interface)  # type: Any
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 963, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 111, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 806, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 383, in get
    return [i for provider in self._providers for i in provider.get(injector)]
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 383, in <listcomp>
    return [i for provider in self._providers for i in provider.get(injector)]
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 329, in get
    return injector.call_with_injection(self._callable)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1021, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 111, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1069, in args_to_inject
    instance = self.get(interface)  # type: Any
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 963, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 111, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 806, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 291, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 990, in create_object
    self.call_with_injection(cls.__init__, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1021, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 111, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1069, in args_to_inject
    instance = self.get(interface)  # type: Any
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 963, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 291, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 990, in create_object
    self.call_with_injection(cls.__init__, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1021, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 111, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1069, in args_to_inject
    instance = self.get(interface)  # type: Any
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 963, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 111, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 806, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 291, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 990, in create_object
    self.call_with_injection(cls.__init__, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1030, in call_with_injection
    return callable(*full_args, **dependencies)
  File "/app/backup/util/data_cache.py", line 40, in __init__
    self._load()
  File "/app/backup/util/data_cache.py", line 47, in _load
    self._data = json.load(f)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by sabeechen** [comment]
The addon is having trouble loading a json file that it writes to every once in a while.  There are 3 ways I can think of this could happen:

1. The addon has a bug.
2. The file is corrupted because, for example the computer was shut down while the file was being written.
3. The disk has corruption.

I bring all these up because while lots of things can explain it 3 is the most likely.  If its a bug I would probably get a lot more reports about it and the file is written infrequently enough to make 2 unlikely.

The easiest fix is to uninstall and reinstall the addon, (you'll need to reconnect it with Google Drive).  If you save the setting YAML and just copy them back in when you reinstall, it should find you snapshots folder and work exactly as before.  If you're running this on a raspberry pi, I'd also consider replacing your SD card soon.

**Comment by roopesh** [comment]
@sabeechen Thanks!  Reinstalling worked.

**Comment by sabeechen** [comment]
If I can help with anything else, please feel free to reopen the issue.
