### ISSUE TITLE
The Supervisor Returned an Unexpected Response

### ISSUE THREAD

**Issue by DrPerryCoke** [sabeechen/hassio-google-drive-backup#497]
Reinstalling didn't help (

###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.105.2`
 Home Assistant Version: `2021.9.7`
 Supervisor Version: `2021.09.6`
 Supervisor Channel: `stable`
 Hassos Version: `None`
 Docker Version: `20.10.8`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2021-10-03T13:12:15.741218+00:00`
 Timezone: `Europe/Moscow`
 Failure Time: `2021-10-03T13:12:02.489534+00:00`
 Last Good Sync: `2021-10-03T13:10:51.211729+00:00`
 ###### Exception:
 ```
 
  addon/backup/util/asynchttpgetter.py:196 (read)
  /site-packages/aiohttp/streams.py:434 (readexactly)
  /site-packages/aiohttp/streams.py:380 (read)
  /site-packages/aiohttp/streams.py:306 (_wait)
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
Whose handling caused:
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:204 (sync)
  addon/backup/drive/drivesource.py:179 (save)
  addon/backup/drive/driverequests.py:267 (create)
  addon/backup/util/asynchttpgetter.py:203 (read)
backup.exceptions.exceptions.SupervisorUnexpectedError

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-10-03T01:34:20Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "2.2 GB",
        "ignored_size": "0.0 B",
        "free_space": "15.0 GB"
    },
    "GoogleDrive": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2021-10-03T01:34:20Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "2.2 GB",
        "ignored_size": "0.0 B",
        "free_space": "11.6 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 10-03 16:11:39 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycduMlAvSY8JPkDL--zETczO16-_MPCtt229sPTkTvs5tNOP28I7mMPRSTMXkQ9SCs6F0nb4z8MayWjFB08NwTMI
10-03 16:11:40 DEBUG [backup.drive.drivesource] Uploading Full Backup 2021-09-30 04:01:09 71.99%
10-03 16:11:40 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
10-03 16:11:40 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycduMlAvSY8JPkDL--zETczO16-_MPCtt229sPTkTvs5tNOP28I7mMPRSTMXkQ9SCs6F0nb4z8MayWjFB08NwTMI
10-03 16:11:41 DEBUG [backup.drive.drivesource] Uploading Full Backup 2021-09-30 04:01:09 73.79%
10-03 16:11:41 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
10-03 16:11:41 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycduMlAvSY8JPkDL--zETczO16-_MPCtt229sPTkTvs5tNOP28I7mMPRSTMXkQ9SCs6F0nb4z8MayWjFB08NwTMI
10-03 16:11:42 DEBUG [backup.drive.drivesource] Uploading Full Backup 2021-09-30 04:01:09 75.59%
10-03 16:11:42 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
10-03 16:11:42 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycduMlAvSY8JPkDL--zETczO16-_MPCtt229sPTkTvs5tNOP28I7mMPRSTMXkQ9SCs6F0nb4z8MayWjFB08NwTMI
10-03 16:11:43 DEBUG [backup.drive.drivesource] Uploading Full Backup 2021-09-30 04:01:09 77.38%
10-03 16:11:43 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
10-03 16:11:43 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycduMlAvSY8JPkDL--zETczO16-_MPCtt229sPTkTvs5tNOP28I7mMPRSTMXkQ9SCs6F0nb4z8MayWjFB08NwTMI
10-03 16:11:44 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/self/info
10-03 16:11:44 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/info
10-03 16:11:44 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/core/info
10-03 16:11:44 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
10-03 16:11:44 DEBUG [backup.drive.drivesource] Uploading Full Backup 2021-09-30 04:01:09 79.18%
10-03 16:11:44 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
10-03 16:11:44 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycduMlAvSY8JPkDL--zETczO16-_MPCtt229sPTkTvs5tNOP28I7mMPRSTMXkQ9SCs6F0nb4z8MayWjFB08NwTMI
10-03 16:11:45 DEBUG [backup.drive.drivesource] Uploading Full Backup 2021-09-30 04:01:09 80.98%
10-03 16:11:45 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
10-03 16:11:45 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycduMlAvSY8JPkDL--zETczO16-_MPCtt229sPTkTvs5tNOP28I7mMPRSTMXkQ9SCs6F0nb4z8MayWjFB08NwTMI
10-03 16:11:46 DEBUG [backup.drive.drivesource] Uploading Full Backup 2021-09-30 04:01:09 82.78%
10-03 16:11:47 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
10-03 16:11:47 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycduMlAvSY8JPkDL--zETczO16-_MPCtt229sPTkTvs5tNOP28I7mMPRSTMXkQ9SCs6F0nb4z8MayWjFB08NwTMI
10-03 16:11:48 DEBUG [backup.drive.drivesource] Uploading Full Backup 2021-09-30 04:01:09 84.58%
10-03 16:12:02 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
10-03 16:12:02 INFO [backup.model.coordinator] I'll try again in an hour
10-03 16:12:11 INFO [backup.debugworker] Sending error report (see settings to disable)
 ```
 ###### Supervisor Logs:
 ```
 [32m21-10-03 16:10:51 INFO (MainThread) [supervisor.api.backups] Downloading backup 4168a1a8[0m
[32m21-10-03 16:11:44 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-03 16:11:44 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[31m21-10-03 16:12:02 ERROR (MainThread) [aiohttp.server] Unhandled exception[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 485, in start
    resp, reset = await task
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 440, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 591, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 241, in prepare
    return await self._sendfile(request, fobj, offset, count)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 96, in _sendfile
    await loop.sendfile(transport, fobj, offset, count)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1151, in sendfile
    return await self._sendfile_native(transport, file,
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 586, in _sendfile_native
    return await self.sock_sendfile(transp._sock, file, offset, count,
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 869, in sock_sendfile
    return await self._sock_sendfile_native(sock, file,
  File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 351, in _sock_sendfile_native
    return await fut
  File "/usr/local/lib/python3.9/asyncio/unix_events.py", line 378, in _sock_sendfile_native_impl
    sent = os.sendfile(fd, fileno, offset, blocksize)
OSError: [Errno 5] I/O error
[32m21-10-03 16:12:14 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-03 16:12:15 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-03 16:12:15 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 [33m2021-10-03 14:56:14 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 14:59:45 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:03:15 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:06:45 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:10:15 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:13:45 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:17:15 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:20:45 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:24:15 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:27:45 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:31:15 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:34:45 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:38:15 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:38:35 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.red_dragon_gigabyte_990xa_ud3_ite_it8728f_voltages_voltage_1 is taking over 10 seconds[0m
[33m2021-10-03 15:38:55 WARNING (MainThread) [homeassistant.components.sensor] Updating openhardwaremonitor sensor took longer than the scheduled update interval 0:00:30[0m
[33m2021-10-03 15:41:45 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:45:15 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:45:24 WARNING (MainThread) [homeassistant.components.esphome] Can't connect to ESPHome API for h801led (192.168.1.9): Timeout while connecting to ('192.168.1.9', 6053)[0m
[33m2021-10-03 15:48:45 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:52:15 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:55:45 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 15:59:15 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[31m2021-10-03 16:00:54 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/cebe7a76_hassio_google_drive_backup/stats request[0m
[31m2021-10-03 16:00:54 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/cebe7a76_hassio_google_drive_backup/stats - [0m
[33m2021-10-03 16:02:45 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 16:06:15 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[33m2021-10-03 16:09:45 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m
[31m2021-10-03 16:11:57 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /ingress/validate_session request[0m
[31m2021-10-03 16:11:57 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/validate_session - [0m

 ```

**Comment by DrPerryCoke** [comment]
Deleted all backups, passed)
