### ISSUE TITLE
Read-only file is failing my sync

### ISSUE THREAD

**Issue by zarurc** [sabeechen/hassio-google-drive-backup#511]
An unexpected error occurred: [Errno 30] Read-only file system: '/data/data_cache.json'

  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:214 (sync)
  addon/backup/util/data_cache.py:97 (saveIfDirty)
  addon/backup/util/data_cache.py:68 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

Copy the info from the previous page here
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.105.2`
 Home Assistant Version: `2021.9.7`
 Supervisor Version: `2021.10.0`
 Supervisor Channel: `stable`
 Hassos Version: `6.4`
 Docker Version: `20.10.7`
 Architecture: `armv7`
 Machine: `raspberrypi3`
 Date: `2021-10-18T15:01:48.938339+00:00`
 Timezone: `America/New_York`
 Failure Time: `2021-10-18T15:01:36.619690+00:00`
 Last Good Sync: `2021-10-18T15:01:35.903188+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:214 (sync)
  addon/backup/util/data_cache.py:97 (saveIfDirty)
  addon/backup/util/data_cache.py:68 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 5,
        "retained": 0,
        "deletable": 5,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-10-17T04:01:00Z",
        "max": 5,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "583.9 MB",
        "ignored_size": "0.0 B",
        "free_space": "20.7 GB"
    },
    "GoogleDrive": {
        "backups": 2,
        "retained": 0,
        "deletable": 2,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2021-10-17T04:01:00Z",
        "max": 2,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "234.4 MB",
        "ignored_size": "0.0 B",
        "free_space": "16.0 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 5,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 2,
    "Setting.BACKUP_TIME_OF_DAY": "00:01"
}
 ```
 ###### Addon Logs:
 ```
 10-18 09:17:23 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
10-18 09:17:23 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271HmzaOnpZz4aVI1mvZj3ZsSyGeO-VQUpd%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-18 09:17:23 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:214 (sync)
  addon/backup/util/data_cache.py:97 (saveIfDirty)
  addon/backup/util/data_cache.py:68 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

10-18 09:17:23 INFO [backup.model.coordinator] I'll try again in an hour
10-18 10:17:24 DEBUG [backup.model.syncer] Sync requested by Coordinator
10-18 10:17:24 INFO [backup.model.coordinator] Syncing Backups
10-18 10:17:24 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
10-18 10:17:24 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
10-18 10:17:24 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
10-18 10:17:24 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1HmzaOnpZz4aVI1mvZj3ZsSyGeO-VQUpd/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
10-18 10:17:24 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
10-18 10:17:24 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271HmzaOnpZz4aVI1mvZj3ZsSyGeO-VQUpd%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-18 10:17:24 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:214 (sync)
  addon/backup/util/data_cache.py:97 (saveIfDirty)
  addon/backup/util/data_cache.py:68 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

10-18 10:17:24 INFO [backup.model.coordinator] I'll try again in an hour
10-18 10:25:11 INFO [backup.model.coordinator] Syncing Backups
10-18 10:25:11 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
10-18 10:25:11 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
10-18 10:25:11 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1HmzaOnpZz4aVI1mvZj3ZsSyGeO-VQUpd/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
10-18 10:25:11 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
10-18 10:25:12 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271HmzaOnpZz4aVI1mvZj3ZsSyGeO-VQUpd%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-18 10:25:12 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:214 (sync)
  addon/backup/util/data_cache.py:97 (saveIfDirty)
  addon/backup/util/data_cache.py:68 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

10-18 10:25:12 INFO [backup.model.coordinator] I'll try again in an hour
10-18 11:01:35 INFO [backup.model.coordinator] Syncing Backups
10-18 11:01:35 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
10-18 11:01:35 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
10-18 11:01:35 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1HmzaOnpZz4aVI1mvZj3ZsSyGeO-VQUpd/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
10-18 11:01:36 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
10-18 11:01:36 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271HmzaOnpZz4aVI1mvZj3ZsSyGeO-VQUpd%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-18 11:01:36 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:214 (sync)
  addon/backup/util/data_cache.py:97 (saveIfDirty)
  addon/backup/util/data_cache.py:68 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

10-18 11:01:36 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m21-10-18 04:49:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE[0m
[32m21-10-18 04:49:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m21-10-18 04:49:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m21-10-18 04:49:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m
[32m21-10-18 04:49:43 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m21-10-18 04:49:43 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m21-10-18 04:49:43 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m21-10-18 04:49:43 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m21-10-18 04:49:43 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m21-10-18 04:51:13 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m21-10-18 04:52:00 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-10-18 04:52:00 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-18 04:52:00 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-18 05:22:01 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-10-18 05:49:43 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m21-10-18 05:49:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m21-10-18 05:49:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN[0m
[32m21-10-18 05:49:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE[0m
[32m21-10-18 05:49:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m21-10-18 05:49:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m21-10-18 05:49:44 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m
[32m21-10-18 05:49:44 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m21-10-18 05:49:44 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m21-10-18 05:49:44 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m21-10-18 05:49:44 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m21-10-18 05:49:44 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m21-10-18 05:52:02 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-18 05:52:02 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-18 05:52:02 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1087, in emit
    self.flush()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1067, in flush
    self.stream.flush()
OSError: [Errno 30] Read-only file system
Call stack:
  File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
Message: 'Error in database connectivity during commit: Error executing query: (sqlite3.OperationalError) disk I/O error\n(Background on this error at: https://sqlalche.me/e/14/e3q8). (retrying in 3 seconds)'
Arguments: None
[31m2021-10-18 06:19:38 ERROR (Recorder) [homeassistant.components.recorder] SQLAlchemyError error processing event <Event time_changed[L]: now=2021-10-18T06:19:35.001557-04:00>: This connection is on an inactive transaction.  Please rollback() fully before proceeding. (Background on this error at: https://sqlalche.me/e/14/8s2a)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 657, in _process_one_event_or_recover
    self._process_one_event(event)
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 777, in _process_one_event
    self._commit_event_session_or_retry()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 840, in _commit_event_session_or_retry
    self._commit_event_session()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 866, in _commit_event_session
    self.event_session.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 836, in commit
    trans.commit()

 ```

**Comment by zarurc** [comment]
Yeah, looks like that's my issue.
My HA just crahed. thanks
