### ISSUE TITLE
Error in add-on

### ISSUE THREAD

**Issue by jcastro** [sabeechen/hassio-google-drive-backup#520]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.105.2`
 Home Assistant Version: `2021.11.2`
 Supervisor Version: `2021.10.8`
 Supervisor Channel: `stable`
 Hassos Version: `6.6`
 Docker Version: `20.10.8`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2021-11-11T05:40:46.040426+00:00`
 Timezone: `Europe/Madrid`
 Failure Time: `2021-11-11T05:38:59.342060+00:00`
 Last Good Sync: `2021-11-11T05:38:58.296534+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:204 (sync)
  addon/backup/drive/drivesource.py:171 (save)
  addon/backup/util/asynchttpgetter.py:221 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:161 (_startReadRemoteAt)
  addon/backup/tracing_session.py:35 (_request)
  /site-packages/aiohttp/client.py:544 (_request)
  /site-packages/aiohttp/client_reqrep.py:890 (start)
  /site-packages/aiohttp/streams.py:604 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 2,
        "retained": 0,
        "deletable": 2,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-11-11T05:37:29Z",
        "max": 2,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "0.0 B",
        "ignored_size": "0.0 B",
        "free_space": "10.7 GB"
    },
    "GoogleDrive": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 3,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "0.0 B",
        "ignored_size": "0.0 B",
        "free_space": "13.6 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 2,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 3,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.BACKUP_TIME_OF_DAY": "04:00",
    "Setting.SPECIFY_BACKUP_FOLDER": true
}
 ```
 ###### Addon Logs:
 ```
 11-11 06:37:30 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
11-11 06:37:30 INFO [backup.ha.hasource] Requesting a new backup
11-11 06:37:30 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/new/full
11-11 06:37:31 DEBUG [backup.model.syncer] Sync requested by Coordinator
11-11 06:37:35 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:204 (sync)
  addon/backup/drive/drivesource.py:171 (save)
  addon/backup/util/asynchttpgetter.py:221 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:161 (_startReadRemoteAt)
  addon/backup/tracing_session.py:35 (_request)
  /site-packages/aiohttp/client.py:544 (_request)
  /site-packages/aiohttp/client_reqrep.py:890 (start)
  /site-packages/aiohttp/streams.py:604 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

11-11 06:37:35 INFO [backup.model.coordinator] I'll try again in 40 seconds
11-11 06:37:37 INFO [backup.model.coordinator] Syncing Backups
11-11 06:37:37 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
11-11 06:37:37 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
11-11 06:37:37 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
11-11 06:37:37 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271KlokbXy63gBy57t7VR-ivtXIf0t2_mC9%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
11-11 06:37:38 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:204 (sync)
  addon/backup/drive/drivesource.py:171 (save)
  addon/backup/util/asynchttpgetter.py:221 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:161 (_startReadRemoteAt)
  addon/backup/tracing_session.py:35 (_request)
  /site-packages/aiohttp/client.py:544 (_request)
  /site-packages/aiohttp/client_reqrep.py:890 (start)
  /site-packages/aiohttp/streams.py:604 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

11-11 06:37:38 INFO [backup.model.coordinator] I'll try again in 1(ish) minutes
11-11 06:38:58 DEBUG [backup.model.syncer] Sync requested by Coordinator
11-11 06:38:58 INFO [backup.model.coordinator] Syncing Backups
11-11 06:38:58 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
11-11 06:38:58 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
11-11 06:38:58 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1KlokbXy63gBy57t7VR-ivtXIf0t2_mC9/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
11-11 06:38:58 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
11-11 06:38:59 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271KlokbXy63gBy57t7VR-ivtXIf0t2_mC9%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
11-11 06:38:59 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:204 (sync)
  addon/backup/drive/drivesource.py:171 (save)
  addon/backup/util/asynchttpgetter.py:221 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:161 (_startReadRemoteAt)
  addon/backup/tracing_session.py:35 (_request)
  /site-packages/aiohttp/client.py:544 (_request)
  /site-packages/aiohttp/client_reqrep.py:890 (start)
  /site-packages/aiohttp/streams.py:604 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

11-11 06:38:59 INFO [backup.model.coordinator] I'll try again in 2(ish) minutes
11-11 06:40:00 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/self/info
11-11 06:40:00 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/info
11-11 06:40:00 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/core/info
11-11 06:40:00 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
11-11 06:40:18 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/self/info
11-11 06:40:18 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/info
11-11 06:40:18 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/core/info
11-11 06:40:18 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
 ```
 ###### Supervisor Logs:
 ```
 [32m21-11-11 06:38:22 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on 45df7312_zigbee2mqtt[0m
[32m21-11-11 06:38:22 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon 45df7312_zigbee2mqtt[0m
[32m21-11-11 06:38:22 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_influxdb[0m
[32m21-11-11 06:38:58 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-11-11 06:38:58 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m21-11-11 06:38:59 INFO (MainThread) [supervisor.api.middleware.security] /backups/ab0c30b7/download access from cebe7a76_hassio_google_drive_backup[0m
[32m21-11-11 06:38:59 INFO (MainThread) [supervisor.api.backups] Downloading backup ab0c30b7[0m
[31m21-11-11 06:38:59 ERROR (MainThread) [aiohttp.server] Unhandled exception[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 485, in start
    resp, reset = await task
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 440, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 591, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 115, in prepare
    st = await loop.run_in_executor(None, filepath.stat)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: '/data/backup/Full Backup 2021-11-09 04_00_00.tar'
[33m21-11-11 06:39:46 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m21-11-11 06:39:50 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[32m21-11-11 06:40:00 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-11-11 06:40:00 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-11-11 06:40:18 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-11-11 06:40:18 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-11-11 06:40:46 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     return await func(self, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 700, in async_set_default
    await self._bulb.async_set_default()
  File "/usr/local/lib/python3.9/site-packages/yeelight/aio.py", line 36, in wrapper
    cmd = await self.async_send_command(
  File "/usr/local/lib/python3.9/site-packages/yeelight/aio.py", line 75, in async_send_command
    raise BulbException(response["error"])
yeelight.main.BulbException: {'code': -5006, 'message': 'illegal request'}
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1511, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 667, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 863, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 704, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 496, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 798, in async_turn_on
    await self.async_set_default()
  File "/usr/src/homeassistant/homeassistant/components/yeelight/light.py", line 271, in _async_wrap
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error when calling async_set_default for bulb Luz Escritorio at 10.0.1.28: {'code': -5006, 'message': 'illegal request'}[0m

 ```

**Comment by sabeechen** [comment]
My apologies this took me so long to reply on, this bug just completely slipped through my radar.

I think the issue is here in your supervisor logs:
```
FileNotFoundError: [Errno 2] No such file or directory: '/data/backup/Full Backup 2021-11-09 04_00_00.tar'
```

It seems like Home Assistant thinks there is a snapshot, but then its gone when it attempts to actually read the file.  I suspect that if you restart the supervisor ("Configuration" > "Add-ons Backups & Supervisor" > "System" > "Restart Supervisor" > "Reboot Host")

If that doesn't fix it and you're still seeing this problem, please feel free to re-open this and let me know.

**Comment by jcastro** [comment]
thank you!
