### ISSUE TITLE
Error encountered during backup

### ISSUE THREAD

**Issue by ryanhindinger** [sabeechen/hassio-google-drive-backup#529]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.104.3`
 Home Assistant Version: `2021.11.1`
 Supervisor Version: `2021.10.8`
 Supervisor Channel: `stable`
 Hassos Version: `6.6`
 Docker Version: `20.10.8`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2021-12-05T15:24:36.177958+00:00`
 Timezone: `America/New_York`
 Failure Time: `2021-12-05T14:34:16.199071+00:00`
 Last Good Sync: `2021-12-05T14:34:14.111049+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:210 (sync)
  addon/backup/util/data_cache.py:98 (saveIfDirty)
  addon/backup/util/data_cache.py:69 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-12-04T07:00:01Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "1.8 GB",
        "ignored_size": "0.0 B",
        "free_space": "17.4 GB"
    },
    "GoogleDrive": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2021-12-04T07:00:01Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "1.8 GB",
        "ignored_size": "0.0 B",
        "free_space": "3.6 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 4.0,
    "Setting.SNAPSHOT_TIME_OF_DAY": "02:00",
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 12-05 08:19:31 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1MgoSYah-Kt6gmgAlbnxSd5miGB4gsfJW/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
12-05 08:19:32 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
12-05 08:19:32 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271MgoSYah-Kt6gmgAlbnxSd5miGB4gsfJW%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
12-05 08:19:32 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:210 (sync)
  addon/backup/util/data_cache.py:98 (saveIfDirty)
  addon/backup/util/data_cache.py:69 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

12-05 08:19:32 INFO [backup.model.coordinator] I'll try again in 10(ish) minutes
12-05 08:30:12 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-05 08:30:12 INFO [backup.model.coordinator] Syncing Snapshots
12-05 08:30:12 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
12-05 08:30:12 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1MgoSYah-Kt6gmgAlbnxSd5miGB4gsfJW/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
12-05 08:30:12 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
12-05 08:30:12 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271MgoSYah-Kt6gmgAlbnxSd5miGB4gsfJW%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
12-05 08:30:13 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:210 (sync)
  addon/backup/util/data_cache.py:98 (saveIfDirty)
  addon/backup/util/data_cache.py:69 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

12-05 08:30:13 INFO [backup.model.coordinator] I'll try again in 21(ish) minutes
12-05 08:51:33 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-05 08:51:33 INFO [backup.model.coordinator] Syncing Snapshots
12-05 08:51:33 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
12-05 08:51:33 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1MgoSYah-Kt6gmgAlbnxSd5miGB4gsfJW/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
12-05 08:51:33 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
12-05 08:51:33 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271MgoSYah-Kt6gmgAlbnxSd5miGB4gsfJW%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
12-05 08:51:33 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:210 (sync)
  addon/backup/util/data_cache.py:98 (saveIfDirty)
  addon/backup/util/data_cache.py:69 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

12-05 08:51:33 INFO [backup.model.coordinator] I'll try again in 42(ish) minutes
12-05 09:34:14 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-05 09:34:14 INFO [backup.model.coordinator] Syncing Snapshots
12-05 09:34:14 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
12-05 09:34:14 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
12-05 09:34:14 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1MgoSYah-Kt6gmgAlbnxSd5miGB4gsfJW/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
12-05 09:34:14 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
12-05 09:34:15 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271MgoSYah-Kt6gmgAlbnxSd5miGB4gsfJW%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
12-05 09:34:16 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:210 (sync)
  addon/backup/util/data_cache.py:98 (saveIfDirty)
  addon/backup/util/data_cache.py:69 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

12-05 09:34:16 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 rm: can't remove '/data/addons/core/dnsmasq/rootfs/etc/services.d/dnsmasq/run': Read-only file system
rm: can't remove '/data/addons/core/dnsmasq/rootfs/etc/services.d/dnsmasq/finish': Read-only file system
rm: can't remove '/data/addons/core/dnsmasq/rootfs/etc/cont-init.d/config.sh': Read-only file system
rm: can't remove '/data/addons/core/dnsmasq/rootfs/usr/share/tempio/dnsmasq.config': Read-only file system
rm: can't remove '/data/addons/core/dnsmasq/icon.png': Read-only file system
rm: can't remove '/data/addons/core/dnsmasq/logo.png': Read-only file system
rm: can't remove '/data/addons/core/cec_scan/Dockerfile': Read-only file system
rm: can't remove '/data/addons/core/cec_scan/README.md': Read-only file system
rm: can't remove '/data/addons/core/cec_scan/build.yaml': Read-only file system
rm: can't remove '/data/addons/core/cec_scan/DOCS.md': Read-only file system
rm: can't remove '/data/addons/core/cec_scan/config.yaml': Read-only file system
rm: can't remove '/data/addons/core/cec_scan/CHANGELOG.md': Read-only file system
rm: can't remove '/data/addons/core/cec_scan/rootfs/etc/services.d/cec-scan/run': Read-only file system
rm: can't remove '/data/addons/core/cec_scan/rootfs/etc/services.d/cec-scan/finish': Read-only file system
rm: can't remove '/data/addons/core/cec_scan/icon.png': Read-only file system
rm: can't remove '/data/addons/core/cec_scan/logo.png': Read-only file system
[31m21-12-05 10:04:03 ERROR (MainThread) [supervisor.utils] Can't remove folder /data/addons/core: None[0m
[32m21-12-05 10:04:03 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository[0m
[32m21-12-05 10:04:05 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m21-12-05 10:04:13 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'homeassistant'[0m
[33m21-12-05 10:04:13 WARNING (MainThread) [supervisor.auth] Unauthorized login for 'homeassistant'[0m
[32m21-12-05 10:07:49 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-12-05 10:10:13 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'homeassistant'[0m
[33m21-12-05 10:10:13 WARNING (MainThread) [supervisor.auth] Unauthorized login for 'homeassistant'[0m
[32m21-12-05 10:16:13 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'homeassistant'[0m
[33m21-12-05 10:16:13 WARNING (MainThread) [supervisor.auth] Unauthorized login for 'homeassistant'[0m
[32m21-12-05 10:22:13 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'homeassistant'[0m
[33m21-12-05 10:22:13 WARNING (MainThread) [supervisor.auth] Unauthorized login for 'homeassistant'[0m
[32m21-12-05 10:24:36 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     self.stream.flush()
OSError: [Errno 30] Read-only file system
Call stack:
  File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
Message: 'SQLAlchemyError error processing event <Event time_changed[L]: now=2021-12-05T10:24:36.002006-05:00>: This connection is on an inactive transaction.  Please rollback() fully before proceeding. (Background on this error at: https://sqlalche.me/e/14/8s2a)\nTraceback (most recent call last):\n  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 697, in _process_one_event_or_recover\n    self._process_one_event(event)\n  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 835, in _process_one_event\n    self._commit_event_session_or_retry()\n  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 898, in _commit_event_session_or_retry\n    self._commit_event_session()\n  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 924, in _commit_event_session\n    self.event_session.commit()\n  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1428, in commit\n    self._transaction.commit(_to_root=self.future)\n  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 836, in commit\n    trans.commit()\n  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2330, in commit\n    self._do_commit()\n  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2529, in _do_commit\n    self.connection._invalid_transaction()\n  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 544, in _invalid_transaction\n    raise exc.PendingRollbackError(\nsqlalchemy.exc.PendingRollbackError: This connection is on an inactive transaction.  Please rollback() fully before proceeding. (Background on this error at: https://sqlalche.me/e/14/8s2a)'
Arguments: None
[31m2021-12-05 10:24:39 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity during commit: Error executing query: (sqlite3.OperationalError) disk I/O error
(Background on this error at: https://sqlalche.me/e/14/e3q8). (retrying in 3 seconds)[0m
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1087, in emit
    self.flush()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1067, in flush
    self.stream.flush()
OSError: [Errno 30] Read-only file system
Call stack:
  File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
Message: 'Error in database connectivity during commit: Error executing query: (sqlite3.OperationalError) disk I/O error\n(Background on this error at: https://sqlalche.me/e/14/e3q8). (retrying in 3 seconds)'
Arguments: None

 ```

**Comment by sabeechen** [comment]
Sorry this took me a while to get back to you.  This is usually the result of something going wrong on your host machine's hard drive. I've had a few users report this problem in the past, and the fix has always been to restart the machine. You can see in the Home Assistant logs its having trouble writing to other places in the file system, so its likely that nothing on your HA machine is able to write to your SD card. This isn't a problem with the addon, its a problem with your whole machine.

Linux will sometimes switch a hard disk into read-only mode if it thinks it needs to do so to prevent damage to the hardware. This can happen for a number of reasons:

- Its out of space
- The hard drive stopped responding
- It detected corrupt data on your hard drive
- Etc.

Restarting your host machine will probably make the problem stop for now, but I would recommend looking at the supervisor logs to see if it lists any problems when it starts up.  There isn't anything I can do as an addon developer to fix this problem, something is wrong with the machine you're running home assistant on.
