### ISSUE TITLE
Google Backup error

### ISSUE THREAD

**Issue by psheridan050** [sabeechen/hassio-google-drive-backup#530]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.105.2`
 Home Assistant Version: `2021.11.5`
 Supervisor Version: `2021.10.8`
 Supervisor Channel: `stable`
 Hassos Version: `6.6`
 Docker Version: `20.10.8`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2021-12-08T19:22:43.648724+00:00`
 Timezone: `America/Denver`
 Failure Time: `2021-12-08T19:06:46.137875+00:00`
 Last Good Sync: `2021-12-08T19:06:44.959169+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:214 (sync)
  addon/backup/util/data_cache.py:97 (saveIfDirty)
  addon/backup/util/data_cache.py:68 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-12-08T12:00:00Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 42,
        "size": "20.3 GB",
        "ignored_size": "9.6 GB",
        "free_space": "220.2 GB"
    },
    "GoogleDrive": {
        "backups": 20,
        "retained": 0,
        "deletable": 20,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2021-12-08T12:00:00Z",
        "max": 20,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "82.1 GB",
        "ignored_size": "0.0 B",
        "free_space": "1.7 TB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 20,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.IGNORE_OTHER_BACKUPS": true,
    "Setting.IGNORE_UPGRADE_BACKUPS": true,
    "Setting.BACKUP_TIME_OF_DAY": "05:00",
    "Setting.GENERATIONAL_DAYS": 4,
    "Setting.GENERATIONAL_MONTHS": 1,
    "Setting.GENERATIONAL_DAY_OF_YEAR": 30,
    "Setting.IGNORE_IPV6_ADDRESSES": true,
    "Setting.ALTERNATE_DNS_SERVERS": "172.25.100.100,172.25.100.101"
}
 ```
 ###### Addon Logs:
 ```
 12-08 10:02:42 INFO [backup.model.coordinator] I'll try again in 21(ish) minutes
12-08 10:24:02 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-08 10:24:02 INFO [backup.model.coordinator] Syncing Backups
12-08 10:24:02 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
12-08 10:24:02 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
12-08 10:24:02 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1sOj2N8LT-h2HMXi4nI45t3Xx7aRIvsJ5/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
12-08 10:24:02 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
12-08 10:24:02 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271sOj2N8LT-h2HMXi4nI45t3Xx7aRIvsJ5%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
12-08 10:24:03 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:214 (sync)
  addon/backup/util/data_cache.py:97 (saveIfDirty)
  addon/backup/util/data_cache.py:68 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

12-08 10:24:03 INFO [backup.model.coordinator] I'll try again in 42(ish) minutes
12-08 11:06:43 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-08 11:06:43 INFO [backup.model.coordinator] Syncing Backups
12-08 11:06:43 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
12-08 11:06:43 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
12-08 11:06:43 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
12-08 11:06:43 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1sOj2N8LT-h2HMXi4nI45t3Xx7aRIvsJ5/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
12-08 11:06:44 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
12-08 11:06:44 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271sOj2N8LT-h2HMXi4nI45t3Xx7aRIvsJ5%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
12-08 11:06:44 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:214 (sync)
  addon/backup/util/data_cache.py:97 (saveIfDirty)
  addon/backup/util/data_cache.py:68 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

12-08 11:06:44 INFO [backup.model.coordinator] I'll try again in an hour
12-08 12:06:44 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-08 12:06:44 INFO [backup.model.coordinator] Syncing Backups
12-08 12:06:44 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
12-08 12:06:44 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
12-08 12:06:44 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
12-08 12:06:45 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1sOj2N8LT-h2HMXi4nI45t3Xx7aRIvsJ5/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
12-08 12:06:45 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
12-08 12:06:45 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271sOj2N8LT-h2HMXi4nI45t3Xx7aRIvsJ5%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
12-08 12:06:46 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:214 (sync)
  addon/backup/util/data_cache.py:97 (saveIfDirty)
  addon/backup/util/data_cache.py:68 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

12-08 12:06:46 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [31m21-12-08 09:39:23 ERROR (MainThread) [supervisor.addons.addon] Add-on core_zwave_js can't write options[0m
[31m21-12-08 09:39:23 ERROR (MainThread) [supervisor.misc.tasks] core_zwave_js watchdog reanimation failed with [0m
[33m21-12-08 09:39:53 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with core_zwave_js![0m
[31m21-12-08 09:39:53 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons.json: [Errno 30] Read-only file system: '/data/tmpim0bdufa'[0m
[31m21-12-08 09:39:53 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons/data/core_zwave_js/options.json: [Errno 30] Read-only file system: '/data/addons/data/core_zwave_js/tmp5611gjfv'[0m
[31m21-12-08 09:39:53 ERROR (MainThread) [supervisor.addons.addon] Add-on core_zwave_js can't write options[0m
[31m21-12-08 09:39:53 ERROR (MainThread) [supervisor.misc.tasks] core_zwave_js watchdog reanimation failed with [0m
[31m21-12-08 09:40:20 ERROR (SyncWorker_8) [supervisor.docker.interface] Container addon_core_zwave_js is not running[0m
[33m21-12-08 09:40:23 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with core_zwave_js![0m
[31m21-12-08 09:40:23 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons.json: [Errno 30] Read-only file system: '/data/tmpzdhf6ikk'[0m
[31m21-12-08 09:40:23 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons/data/core_zwave_js/options.json: [Errno 30] Read-only file system: '/data/addons/data/core_zwave_js/tmpdlaxqv69'[0m
[31m21-12-08 09:40:23 ERROR (MainThread) [supervisor.addons.addon] Add-on core_zwave_js can't write options[0m
[31m21-12-08 09:40:23 ERROR (MainThread) [supervisor.misc.tasks] core_zwave_js watchdog reanimation failed with [0m
[33m21-12-08 09:40:53 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with core_zwave_js![0m
[31m21-12-08 09:40:53 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons.json: [Errno 30] Read-only file system: '/data/tmp8yhl9el7'[0m
[31m21-12-08 09:40:53 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons/data/core_zwave_js/options.json: [Errno 30] Read-only file system: '/data/addons/data/core_zwave_js/tmploikqqcw'[0m
[31m21-12-08 09:40:53 ERROR (MainThread) [supervisor.addons.addon] Add-on core_zwave_js can't write options[0m
[31m21-12-08 09:40:53 ERROR (MainThread) [supervisor.misc.tasks] core_zwave_js watchdog reanimation failed with [0m
[32m21-12-08 09:41:23 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-12-08 09:41:23 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[33m21-12-08 09:41:24 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with core_zwave_js![0m
[31m21-12-08 09:41:24 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons.json: [Errno 30] Read-only file system: '/data/tmptbzpusb1'[0m
[31m21-12-08 09:41:24 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons/data/core_zwave_js/options.json: [Errno 30] Read-only file system: '/data/addons/data/core_zwave_js/tmpci9zt8hc'[0m
[31m21-12-08 09:41:24 ERROR (MainThread) [supervisor.addons.addon] Add-on core_zwave_js can't write options[0m
[31m21-12-08 09:41:24 ERROR (MainThread) [supervisor.misc.tasks] core_zwave_js watchdog reanimation failed with [0m
[32m21-12-08 09:41:25 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-12-08 09:41:25 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m21-12-08 09:41:36 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-12-08 09:41:36 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/local/lib/python3.9/logging/__init__.py", line 1067, in flush
    self.stream.flush()
OSError: [Errno 30] Read-only file system
Call stack:
  File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
Message: 'DTS 0 < 149320 out of order'
Arguments: None
[33m2021-12-08 09:18:44 WARNING (stream_worker) [libav.flv] DTS 4294967296 < 4295116558 out of order[0m
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1087, in emit
    self.flush()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1067, in flush
    self.stream.flush()
OSError: [Errno 30] Read-only file system
Call stack:
  File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
Message: 'DTS 4294967296 < 4295116558 out of order'
Arguments: None

 ```

**Comment by mofongox** [comment]
I'm having a similar issue.

I don't have a single backup in my G-Drive folder to date:

[home-assistant-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/7706676/home-assistant-google-drive-backup.log)

![image](https://user-images.githubusercontent.com/4171096/145881496-5edbeb7e-9d64-4d57-991d-7cf56f37221a.png)

Any ideas?

**Comment by sabeechen** [comment]
@psheridan050 
This is usually the result of something going wrong on your host machine's hard drive. I've had a few users report this problem in the past, and the fix has always been to restart the machine. You can see in the Home Assistant logs its having trouble writing to other places in the file system, so its likely that nothing on your HA machine is able to write to your SD card. This isn't a problem with the addon, its a problem with your whole machine.

Linux will sometimes switch a hard disk into read-only mode if it thinks it needs to do so to prevent damage to the hardware. This can happen for a number of reasons:

- Its out of space
- The hard drive stopped responding
- It detected corrupt data on your hard drive
- Etc.

Restarting your host machine will probably make the problem stop for now, but I would recommend looking at the supervisor logs to see if it lists any problems when it starts up.  There isn't anything I can do as an addon developer to fix this problem, something is wrong with the machine you're running home assistant on.

@mofongox 
You're definitely seeing a different problem from the one @psheridan050 posted.  Could I have you create a new issue and post the results of going to "Actions" > "Report a bug" in the addon web-ui?

**Comment by mofongox** [comment]
Sure thing. First I'm going to uninstall>reboot (whole Pi)>reinstall and give it another shot.

If it happens again, I'll create the new issue.

Thank you so much, this is actually a great solution.
