### ISSUE TITLE
Unable to restore backup

### ISSUE THREAD

**Issue by Rrapa** [sabeechen/hassio-google-drive-backup#566]
Hey 

I'm unable to download backup to HA and restore

###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.105.2`
 Home Assistant Version: `2022.3.0`
 Supervisor Version: `2022.03.1`
 Supervisor Channel: `stable`
 Hassos Version: `7.4`
 Docker Version: `20.10.9`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2022-03-03T21:37:10.404083+00:00`
 Timezone: `Europe/Warsaw`
 Failure Time: `2022-03-03T20:23:10.419451+00:00`
 Last Good Sync: `2022-03-03T21:34:43.568802+00:00`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 1,
        "retained": 0,
        "deletable": 1,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2022-03-02T15:58:45Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "10.2 kB",
        "ignored_size": "0.0 B",
        "free_space": "198.8 GB"
    },
    "GoogleDrive": {
        "backups": 5,
        "retained": 2,
        "deletable": 3,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2022-03-03T20:32:35Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "3.6 GB",
        "ignored_size": "0.0 B",
        "free_space": "11.3 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 03-03 22:34:35 DEBUG [backup.worker.watcher] Backup directory modified event
03-03 22:34:35 DEBUG [backup.worker.watcher] Backup directory changed
03-03 22:34:35 DEBUG [backup.worker.watcher] Backup directory modified event
03-03 22:34:35 DEBUG [backup.worker.watcher] Backup directory changed
03-03 22:34:35 DEBUG [backup.worker.watcher] Backup directory modified event
03-03 22:34:35 DEBUG [backup.worker.watcher] Backup directory changed
03-03 22:34:35 DEBUG [backup.worker.watcher] Backup directory modified event
03-03 22:34:35 DEBUG [backup.worker.watcher] Backup directory changed
03-03 22:34:35 DEBUG [backup.worker.watcher] Backup directory modified event
03-03 22:34:35 DEBUG [backup.worker.watcher] Backup directory changed
03-03 22:34:35 DEBUG [backup.worker.watcher] Backup directory modified event
03-03 22:34:35 DEBUG [backup.worker.watcher] Backup directory changed
03-03 22:34:35 DEBUG [backup.worker.watcher] Backup directory modified event
03-03 22:34:38 DEBUG [backup.worker.watcher] Backup directory changed
03-03 22:34:38 DEBUG [backup.worker.watcher] Backup directory modified event
03-03 22:34:38 DEBUG [backup.worker.watcher] Backup directory changed
03-03 22:34:38 DEBUG [backup.worker.watcher] Backup directory changed
03-03 22:34:38 DEBUG [backup.worker.watcher] Backup directory modified event
03-03 22:34:38 DEBUG [backup.worker.watcher] Backup directory changed
03-03 22:34:38 DEBUG [backup.worker.watcher] Backup directory modified event
03-03 22:34:38 DEBUG [backup.worker.watcher] Backup directory changed
03-03 22:34:38 DEBUG [backup.worker.watcher] Backup directory modified event
03-03 22:34:43 INFO [backup.worker.watcher] Backup directory changed
03-03 22:34:43 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
03-03 22:34:43 INFO [backup.model.coordinator] Syncing Backups
03-03 22:34:43 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
03-03 22:34:43 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
03-03 22:34:43 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1jhpYHAd4CTSLvWBYLWj5kQUs78EpMcMb/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
03-03 22:34:43 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
03-03 22:34:44 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271jhpYHAd4CTSLvWBYLWj5kQUs78EpMcMb%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
 ```
 ###### Supervisor Logs:
 ```
 [31m22-03-03 22:19:21 ERROR (MainThread) [supervisor.backups.backup] Can't validate data for /data/tmp/tmpozqmupmz/backup.tar: expected boolean for dictionary value @ data['protected']. Got '9'[0m
[32m22-03-03 22:25:23 INFO (SyncWorker_1) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/raspberrypi4-64-homeassistant[0m
[32m22-03-03 22:25:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str[0m
[32m22-03-03 22:25:23 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed[0m
[32m22-03-03 22:25:52 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready[0m
[32m22-03-03 22:31:06 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m22-03-03 22:31:07 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m22-03-03 22:31:51 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m22-03-03 22:31:51 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance[0m
[32m22-03-03 22:31:51 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_appdaemon[0m
[32m22-03-03 22:31:53 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m22-03-03 22:32:34 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mariadb with version 2.4.0[0m
[32m22-03-03 22:32:39 INFO (MainThread) [supervisor.services.modules.mysql] Set core_mariadb as service provider for MySQL[0m
[32m22-03-03 22:33:09 INFO (SyncWorker_0) [supervisor.docker.interface] Removing image ghcr.io/hassio-addons/ssh/aarch64 with latest and 10.0.2[0m
[32m22-03-03 22:33:11 INFO (MainThread) [supervisor.addons.addon] Removing add-on data folder /data/addons/data/a0d7b954_ssh[0m
[32m22-03-03 22:33:11 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for a0d7b954_ssh[0m
[32m22-03-03 22:33:12 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_ssh' successfully removed[0m
[32m22-03-03 22:33:21 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for core_ssh[0m
[32m22-03-03 22:34:09 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-03-03 22:34:09 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-03-03 22:34:11 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-03-03 22:34:11 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-03-03 22:34:16 INFO (MainThread) [supervisor.api.middleware.security] /backups access from core_ssh[0m
[32m22-03-03 22:34:43 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-03-03 22:34:43 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-03-03 22:34:46 INFO (MainThread) [supervisor.api.middleware.security] /backups/reload access from core_ssh[0m
[32m22-03-03 22:34:46 INFO (MainThread) [supervisor.backups.manager] Found 2 backup files[0m
[32m22-03-03 22:34:54 INFO (MainThread) [supervisor.api.middleware.security] /backups access from core_ssh[0m
[32m22-03-03 22:37:10 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.2.253', 7000)[0m
[31m2022-03-03 22:36:16 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 567, in update_info_data
    await hass.data[ADDONS_COORDINATOR].async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 543, in _stringify_state
    if not self.available:
  File "/usr/src/homeassistant/homeassistant/components/hassio/entity.py", line 37, in available
    in self.coordinator.data[DATA_KEY_ADDONS][self._addon_slug]
KeyError: 'a0d7b954_ssh'[0m

 ```

**Comment by sabeechen** [comment]
Sorry this took me a while to get back to you on, I've been out of reach for some time.

The critical error message in what you provided is from the top of the supervisor logs:
```
Can't validate data for /data/tmp/tmpozqmupmz/backup.tar: expected boolean for dictionary value @ data['protected']. Got '9'
```

It looks like this is a [known supervisor bug](https://github.com/home-assistant/supervisor/issues/3499), and that [a fix has been written](https://github.com/home-assistant/supervisor/commit/c67317571cd5391c71e3102fca8fbfed384b8b36).  I don't have any influence on supervisor deveopment, so I think you'll have to wait for them to release the fix.
