### ISSUE TITLE
Moved and now HA / google drive backups are failing. HA was boxed up for 4+months

### ISSUE THREAD

**Issue by kylewilliams321** [sabeechen/hassio-google-drive-backup#616]
Copy the info from the previous page here

###### Description:

```

If you have anything else that could help explain what happened, click "Markdown" above and write it here.

 

I actually relocated to a new city and spent about 4 months away from Home Assistant. All my smart devices and my Raspberry Pi were boxed up.  We purchased a new home (new internet provider and modem/router and all that jazz). I finally got around to unboxing my stuff and plugging back in.

 

Now I'm just trying to troubleshoot my way through some issues, this being one of them.

 

Haven't updated HA in a few months obviously so running an older version.

 

Thanks!

 

```

 

Addon version: `0.105.2`

Home Assistant Version: `2021.12.4`

Supervisor Version: `2021.12.2`

Supervisor Channel: `stable`

Hassos Version: `7.0`

Docker Version: `20.10.9`

Architecture: `aarch64`

Machine: `raspberrypi4-64`

Date: `2022-05-18T14:28:51.880837+00:00`

Timezone: `America/Chicago`

Failure Time: `2022-05-18T14:28:40.562406+00:00`

Last Good Sync: `2022-05-18T14:28:36.665998+00:00`

###### Exception:

```

  addon/backup/model/coordinator.py:176 (_sync)

  addon/backup/model/model.py:167 (sync)

  addon/backup/model/model.py:265 (_syncBackups)

  addon/backup/drive/drivesource.py:100 (get)

  addon/backup/drive/drivesource.py:219 (getFolderId)

  addon/backup/drive/folderfinder.py:65 (get)

  addon/backup/drive/folderfinder.py:117 (_readFolderId)

  addon/backup/drive/folderfinder.py:158 (_verify)

  addon/backup/drive/driverequests.py:150 (get)

  addon/backup/drive/driverequests.py:338 (retryRequest)

  addon/backup/drive/driverequests.py:94 (_getHeaders)

  addon/backup/drive/driverequests.py:139 (getToken)

  addon/backup/creds/exchanger.py:85 (refresh)

  addon/backup/creds/exchanger.py:158 (_refresh_default)

backup.exceptions.exceptions.CredRefreshMyError: Couldn't communicate with [habackup.io](http://habackup.io/)

 

```

Backups:

```

{

    "HomeAssistant": {

        "backups": 17,

        "retained": 0,

        "deletable": 17,

        "name": "HomeAssistant",

        "title": "Home Assistant",

        "latest": "2022-05-17T12:43:26Z",

        "max": 4,

        "enabled": true,

        "icon": "home-assistant",

        "ignored": 0,

        "size": "284.9 MB",

        "ignored_size": "0.0 B",

        "free_space": "45.9 GB"

    },

    "GoogleDrive": {

        "backups": 0,

        "retained": 0,

        "deletable": 0,

        "name": "GoogleDrive",

        "title": "Google Drive",

        "latest": null,

        "max": 4,

        "enabled": true,

        "icon": "google-drive",

        "ignored": 0,

        "size": "0.0 B",

        "ignored_size": "0.0 B"

    }

}

```

###### Config:

```

{

    "Setting.CALL_BACKUP_SNAPSHOT": true,

    "Setting.SEND_ERROR_REPORTS": true

}

```

###### Addon Logs:

```

05-18 06:44:57 INFO [backup.model.coordinator] I'll try again in an hour

05-18 07:44:58 DEBUG [backup.model.syncer] Sync requested by Coordinator

05-18 07:44:58 INFO [backup.model.coordinator] Syncing Backups

05-18 07:44:58 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info

05-18 07:44:58 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups

05-18 07:44:58 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials

05-18 07:45:00 WARNING [backup.creds.exchanger] Unable to reach [token1.habackup.io](http://token1.habackup.io/), trying alternate server(s)...

05-18 07:45:01 WARNING [backup.creds.exchanger] Unable to reach [habackup.io](http://habackup.io/), trying alternate server(s)...

05-18 07:45:01 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive

05-18 07:45:01 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Couldn't communicate with [habackup.io](http://habackup.io/)

05-18 07:45:01 INFO [backup.model.coordinator] I'll try again in an hour

05-18 08:45:01 DEBUG [backup.model.syncer] Sync requested by Coordinator

05-18 08:45:01 INFO [backup.model.coordinator] Syncing Backups

05-18 08:45:01 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info

05-18 08:45:01 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups

05-18 08:45:01 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials

05-18 08:45:03 WARNING [backup.creds.exchanger] Unable to reach [token1.habackup.io](http://token1.habackup.io/), trying alternate server(s)...

05-18 08:45:04 WARNING [backup.creds.exchanger] Unable to reach [habackup.io](http://habackup.io/), trying alternate server(s)...

05-18 08:45:04 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive

05-18 08:45:04 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Couldn't communicate with [habackup.io](http://habackup.io/)

05-18 08:45:04 INFO [backup.model.coordinator] I'll try again in an hour

05-18 09:28:36 INFO [backup.model.coordinator] Syncing Backups

05-18 09:28:36 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info

05-18 09:28:36 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups

05-18 09:28:36 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials

05-18 09:28:38 WARNING [backup.creds.exchanger] Unable to reach [token1.habackup.io](http://token1.habackup.io/), trying alternate server(s)...

05-18 09:28:40 WARNING [backup.creds.exchanger] Unable to reach [habackup.io](http://habackup.io/), trying alternate server(s)...

05-18 09:28:40 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive

05-18 09:28:40 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Couldn't communicate with [habackup.io](http://habackup.io/)

05-18 09:28:40 INFO [backup.model.coordinator] I'll try again in an hour

```

###### Supervisor Logs:

```

[32m22-05-18 08:45:01 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m

[32m22-05-18 08:45:01 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m

[32m22-05-18 08:46:23 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m

[32m22-05-18 08:46:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m

[32m22-05-18 08:46:23 INFO (MainThread) [[supervisor.jobs](http://supervisor.jobs/)] 'CheckAddonPwned.run_check' blocked from execution, no supervisor internet connection[0m

[32m22-05-18 08:46:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN[0m

[32m22-05-18 08:46:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m

[32m22-05-18 08:46:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m

[32m22-05-18 08:46:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE[0m

[32m22-05-18 08:46:23 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m

[32m22-05-18 08:46:23 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m

[32m22-05-18 08:46:23 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m

[32m22-05-18 08:46:23 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m

[32m22-05-18 08:46:23 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m

[32m22-05-18 08:46:23 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m

[32m22-05-18 08:46:25 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m

[32m22-05-18 09:06:26 INFO (MainThread) [[supervisor.host.info](http://supervisor.host.info/)] Updating local host information[0m

[32m22-05-18 09:06:28 INFO (MainThread) [supervisor.host.services] Updating service information[0m

[32m22-05-18 09:06:28 INFO (MainThread) [supervisor.host.network] Updating local network information[0m

[32m22-05-18 09:06:28 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m

[32m22-05-18 09:06:28 INFO (MainThread) [supervisor.host.manager] Host information reload completed[0m

[32m22-05-18 09:16:25 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m

[32m22-05-18 09:27:12 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed[0m

[32m22-05-18 09:27:20 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m

[32m22-05-18 09:27:20 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_vscode[0m

[32m22-05-18 09:27:20 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m

[32m22-05-18 09:28:36 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m

[32m22-05-18 09:28:36 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m

[32m22-05-18 09:28:51 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 

```

###### Home Assistant Core Logs:

```

     raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='[statsapi.web.nhl.com](http://statsapi.web.nhl.com/)', port=443): Max retries exceeded with url: /api/v1/teams/16?expand=team.schedule.next (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d9bf2b0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state

    await self.async_device_update()

  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update

    raise exc

  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/config/custom_components/nhl_api/sensor.py", line 206, in update

    self.set_state()

  File "/config/custom_components/nhl_api/sensor.py", line 161, in set_state

    all_attr = self.get_game_data()[0]

  File "/config/custom_components/nhl_api/sensor.py", line 105, in get_game_data

    games = Schedule(self._team_id).game_info()

  File "/usr/local/lib/python3.9/site-packages/pynhl/classes.py", line 34, in __init__

    self.response = requests.get(url)

  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get

    return request('get', url, params=params, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request

    return session.request(method=method, url=url, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request

    resp = self.send(prep, **send_kwargs)

  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send

    r = adapter.send(request, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send

    raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='[statsapi.web.nhl.com](http://statsapi.web.nhl.com/)', port=443): Max retries exceeded with url: /api/v1/teams/16?expand=team.schedule.next (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d9bf2b0>: Failed to establish a new connection: [Errno -3] Try again'))[0m

 

```

**Comment by sabeechen** [comment]
Sorry this took me a while to get back to you on.

This looks a like the addon is simply unable to reach the internet.  For redundancy and reliability I maintain two isolated endpoints for addons to reach out to in case one goes down and the addon is unable to reach both of them.  I can see from the Home Assistant logs that other integrations are also having trouble reaching their external endpoints (eg http://statsapi.web.nhl.com/).  Are you sure the machine has a connection to the outside?

**Comment by sabeechen** [comment]
I'm closing this issue for now but if there is any other way you think I can help please feel free to reopen it and let me know.
