### ISSUE TITLE
Add on fails to start after upgrade to HA Core 2022.6.5

### ISSUE THREAD

**Issue by rpitera** [sabeechen/hassio-google-drive-backup#632]
Add on version: 0.108.2
Home Assistant Core 2022.6.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

No issues prior to this restart after the upgrade. (Ever, in fact - this is the first issue I've ever had with the add on.)

Configuration (in YAML to make it easier to read)

```
max_backups_in_ha: 2
max_backups_in_google_drive: 5
days_between_backups: 1
ignore_upgrade_backups: true
backup_time_of_day: '05:00'
send_error_reports: true
call_backup_snapshot: true
stop_addons: core_mariadb
background_color: '#000000'
accent_color: '#00ffff'
```

Errors in add on log:

```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/lib/python3.9/site-packages/aiorun.py:221> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/aiorun.py", line 231, in new_coro
    await coro
  File "/app/backup/__main__.py", line 11, in main
    await Injector([BaseModule(), MainModule()]).get(Starter).start()
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 961, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 109, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 803, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 283, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 984, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1017, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 109, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1065, in args_to_inject
    instance: Any = self.get(interface)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 961, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 109, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 803, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 377, in get
    return [i for provider in self._providers for i in provider.get(injector)]
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 377, in <listcomp>
    return [i for provider in self._providers for i in provider.get(injector)]
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 321, in get
    return injector.call_with_injection(self._callable)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1017, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 109, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1065, in args_to_inject
    instance: Any = self.get(interface)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 961, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 109, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 803, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 283, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 984, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1017, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 109, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1065, in args_to_inject
    instance: Any = self.get(interface)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 961, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 283, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 984, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1017, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 109, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1065, in args_to_inject
    instance: Any = self.get(interface)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 961, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 109, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 803, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 283, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 984, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.9/site-packages/injector/__init__.py", line 1026, in call_with_injection
    return callable(*full_args, **dependencies)
  File "/app/backup/util/data_cache.py", line 46, in __init__
    self._load()
  File "/app/backup/util/data_cache.py", line 53, in _load
    self._data = json.load(f)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by rpitera** [comment]
This seems to be related to a file system issue on my setup, so not a bug or valid issue.  Closing.

**Comment by sabeechen** [comment]
I really should give a better error message when this happens though.  There are a lot of Hard drive problems (corrupt, out of space) that I think I could make clearer and have the add-on start in a kind of "safe-mode" when it can't use the disk.

**Comment by rpitera** [comment]
Thank you for considering this - every bit helps.  I don't know where I would be without this add on; saved me so many tons of aggravation.

**Comment by sabeechen** [comment]
In the latest version, 0.110.1, I've added some redundancy to the addon's config files that should make it able to avoid losing its config when:
- The device is shut down while writing files
- The HD runs out of space
- The sd card is just a little corrupt
Hopefully it will avoid the problem for everyone, but if not please let me know and I'll try to figure something else out.
