### ISSUE TITLE
Error while backing up

### ISSUE THREAD

**Issue by zee-shany** [sabeechen/hassio-google-drive-backup#648]
Copy the info from the previous page here
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.104.3`
 Home Assistant Version: `2022.6.7`
 Supervisor Version: `2022.05.3`
 Supervisor Channel: `stable`
 Hassos Version: `8.2`
 Docker Version: `20.10.14`
 Architecture: `amd64`
 Machine: `generic-x86-64`
 Date: `2022-07-06T11:57:36.743675+00:00`
 Timezone: `Asia/Dubai`
 Failure Time: `2022-07-06T11:19:24.473153+00:00`
 Last Good Sync: `2022-07-06T11:19:24.463489+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2022-07-05T03:46:11Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 15,
        "size": "2.5 GB",
        "ignored_size": "157.9 MB",
        "free_space": "93.6 GB"
    },
    "GoogleDrive": {
        "snapshots": 2,
        "retained": 0,
        "deletable": 2,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2022-07-05T03:46:11Z",
        "max": 2,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "1.3 GB",
        "ignored_size": "0.0 B",
        "free_space": "11.6 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 2,
    "Setting.IGNORE_OTHER_SNAPSHOTS": true
}
 ```
 ###### Addon Logs:
 ```
 07-06 12:59:23 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-06 12:59:23 INFO [backup.model.coordinator] Syncing Snapshots
07-06 12:59:23 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-06 12:59:23 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-06 12:59:23 INFO [backup.model.coordinator] I'll try again in 5(ish) minutes
07-06 13:04:43 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-06 13:04:43 INFO [backup.model.coordinator] Syncing Snapshots
07-06 13:04:43 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-06 13:04:43 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-06 13:04:43 INFO [backup.model.coordinator] I'll try again in 10(ish) minutes
07-06 13:15:23 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-06 13:15:23 INFO [backup.model.coordinator] Syncing Snapshots
07-06 13:15:23 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-06 13:15:23 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-06 13:15:23 INFO [backup.model.coordinator] I'll try again in 21(ish) minutes
07-06 13:36:43 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-06 13:36:43 INFO [backup.model.coordinator] Syncing Snapshots
07-06 13:36:43 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-06 13:36:44 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-06 13:36:44 INFO [backup.model.coordinator] I'll try again in 42(ish) minutes
07-06 14:19:24 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-06 14:19:24 INFO [backup.model.coordinator] Syncing Snapshots
07-06 14:19:24 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-06 14:19:24 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-06 14:19:24 INFO [backup.model.coordinator] I'll try again in an hour
07-06 15:19:24 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-06 15:19:24 INFO [backup.model.coordinator] Syncing Snapshots
07-06 15:19:24 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-06 15:19:24 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-06 15:19:24 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m22-07-06 15:48:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository[0m
[32m22-07-06 15:48:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m22-07-06 15:48:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/blakeblackshear/frigate-hass-addons repository[0m
[32m22-07-06 15:48:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/jakowenko/double-take-hassio-addons repository[0m
[32m22-07-06 15:48:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/brenner-tobias/ha-addons repository[0m
[32m22-07-06 15:48:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m22-07-06 15:48:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m22-07-06 15:48:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/snowzach/hassio-addons repository[0m
[32m22-07-06 15:48:45 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m22-07-06 15:48:45 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m22-07-06 15:48:45 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m
[32m22-07-06 15:48:46 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m22-07-06 15:48:46 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER[0m
[32m22-07-06 15:48:46 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m22-07-06 15:48:46 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER[0m
[32m22-07-06 15:48:46 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m22-07-06 15:48:46 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m22-07-06 15:48:46 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m22-07-06 15:48:46 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m22-07-06 15:48:46 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[33m22-07-06 15:48:46 WARNING (SyncWorker_5) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR (Full Access)[0m
[33m22-07-06 15:48:46 WARNING (SyncWorker_2) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR (Full Access)[0m
[32m22-07-06 15:48:46 INFO (MainThread) [supervisor.store] Loading add-ons from store: 87 all - 0 new - 0 remove[0m
[32m22-07-06 15:48:46 INFO (MainThread) [supervisor.store] Loading add-ons from store: 87 all - 0 new - 0 remove[0m
[32m22-07-06 15:48:46 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[33m22-07-06 15:53:10 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[33m22-07-06 15:53:10 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)[0m
[33m22-07-06 15:53:10 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)[0m
[32m22-07-06 15:57:36 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
              'headers': {'Content-Type': 'application/json'},
             'status': 200}}
[0m
[31m2022-07-06 15:54:46 ERROR (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud WS exception
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 316, in connect
    raise Exception(resp)
Exception: {'error': 406, 'apikey': '39227180-68f0-4e9b-b21f-6731a8d4cfeb', 'sequence': '1657108486632', 'actionName': 'userOnline'}[0m
[33m2022-07-06 15:55:45 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.anas_iphone_11_2 or it is/they are currently not available[0m
[33m2022-07-06 15:56:27 WARNING (MainThread) [bellows.zigbee.application] Watchdog heartbeat timeout: [0m
[31m2022-07-06 15:56:30 ERROR (MainThread) [bellows.ezsp] NCP entered failed state. Requesting APP controller restart[0m
[31m2022-07-06 15:56:30 ERROR (bellows.thread_0) [homeassistant] Error doing job: Exception in callback SerialTransport._call_connection_lost(None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/serial_asyncio/__init__.py", line 417, in _call_connection_lost
    self._serial.close()
  File "/usr/local/lib/python3.9/site-packages/serial/urlhandler/protocol_socket.py", line 104, in close
    time.sleep(0.3)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 180, in protected_loop_func
    check_loop(func, strict=strict)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 141, in check_loop
    raise RuntimeError(
RuntimeError: Detected blocking call to sleep inside the event loop. Use `await hass.async_add_executor_job()`; This is causing stability issues. Please report issue[0m
[32m2022-07-06 15:56:47 INFO (MainThread) [bellows.zigbee.application] EZSP Radio manufacturer: [0m
[32m2022-07-06 15:56:47 INFO (MainThread) [bellows.zigbee.application] EZSP Radio board name: [0m
[32m2022-07-06 15:56:47 INFO (MainThread) [bellows.zigbee.application] EmberZNet version: 6.7.6.0 build 327[0m
[32m2022-07-06 15:56:48 INFO (MainThread) [bellows.zigbee.application] Node type: EmberNodeType.COORDINATOR, Network parameters: EmberNetworkParameters(extendedPanId=cc:cc:cc:cc:e3:ab:f4:98, panId=0x3498, radioTxPower=20, radioChannel=11, joinMethod=<EmberJoinMethod.USE_MAC_ASSOCIATION: 0>, nwkManagerId=0x0000, nwkUpdateId=0, channels=<Channels.ALL_CHANNELS: 134215680>)[0m
[32m2022-07-06 15:56:51 INFO (MainThread) [zigpy.application] Device 0x0000 (60:a4:23:ff:fe:1d:af:22) joined the network[0m

 ```

**Comment by sabeechen** [comment]
You'll need update the addon.  The version of the addon you're using is over a year old and doesn't know how to talk to the new version of the Home Assistant you have installed.

**Comment by zee-shany** [comment]
Thank you. Don't know how I didn't notice it.
