### ISSUE TITLE
An unexpected error occurred: 404 Client Error: Not Found for url: http://hassio/snapshots

### ISSUE THREAD

**Issue by cgalagaza** [sabeechen/hassio-google-drive-backup#650]
Please add some information about your configuration and the problem you ran into here. 
More info really helps speed up debugging, if you don't even read this and help me understand what happened, I probably won't help you.  
Remember that its just one guy back here doing all of this.  
If english isn't your first language, don't sweat it.  Just try to be clear and I'll do the same for you.  Some things you might consider including:
 * What were you doing when the problem happened?
 * A screenshot if its something visual.
 * What configuration options are you using with the add-on?
 * What logs is the add-on printing out?  You can see the detailed logs by clicking "Logs" at the right of the web-UI.
 * Are there any problematic looking logs from the Hassio supervisor?  You can get to them from the Home Assistant Interface from "Hass.io" > "System" > "System Log"
 

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 109, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 127, in sync
    self._syncSnapshots([self.source, self.dest])
  File "/app/backup/model.py", line 205, in _syncSnapshots
    from_source: Dict[str, AbstractSnapshot] = source.get()
  File "/app/backup/hasource.py", line 174, in get
    for snapshot in self.harequests.snapshots()['snapshots']:
  File "/app/backup/harequests.py", line 63, in snapshots
    return self._getHassioData(self.config.get(Setting.HASSIO_URL) + "snapshots")
  File "/app/backup/harequests.py", line 132, in _getHassioData
    return self._validateHassioReply(self._client.get(url, headers=self._getHassioHeaders()))
  File "/app/backup/harequests.py", line 98, in _validateHassioReply
    resp.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://hassio/snapshots

An unexpected error occurred: 404 Client Error: Not Found for url: http://hassio/snapshots

**Comment by harfordhawk** [comment]
same issue, just started ....

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 109, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 127, in sync
    self._syncSnapshots([self.source, self.dest])
  File "/app/backup/model.py", line 205, in _syncSnapshots
    from_source: Dict[str, AbstractSnapshot] = source.get()
  File "/app/backup/hasource.py", line 174, in get
    for snapshot in self.harequests.snapshots()['snapshots']:
  File "/app/backup/harequests.py", line 63, in snapshots
    return self._getHassioData(self.config.get(Setting.HASSIO_URL) + "snapshots")
  File "/app/backup/harequests.py", line 132, in _getHassioData
    return self._validateHassioReply(self._client.get(url, headers=self._getHassioHeaders()))
  File "/app/backup/harequests.py", line 98, in _validateHassioReply
    resp.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://hassio/snapshots

**Comment by lefebp** [comment]
Exact same error for me as well, 4 hours ago.

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 103, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 120, in sync
    self._syncSnapshots([self.source, self.dest])
File "/app/backup/model.py", line 192, in _syncSnapshots
    from_source: Dict[str, AbstractSnapshot] = source.get()
  File "/app/backup/hasource.py", line 174, in get
    for snapshot in self.harequests.snapshots()['snapshots']:
  File "/app/backup/harequests.py", line 61, in snapshots
    return self._getHassioData(self.config.get(Setting.HASSIO_URL) + "snapshots")
  File "/app/backup/harequests.py", line 130, in _getHassioData
    return self._validateHassioReply(self._client.get(url, headers=self._getHassioHeaders()))
  File "/app/backup/harequests.py", line 96, in _validateHassioReply
    resp.raise_for_status()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://hassio/snapshots

**Comment by OldSystemMan** [comment]
Same problem here. It started about 4 hours ago. Logs say:

sync_problem Error while backing up

The add-on got the error below while trying to sync your snapshots. Some transient errors are expected (eg an upload could fail if the internet is down) but if this persist for more than a few minutes your snapshots won't get backed up and the information you see on this page may be stale. If you file an issue on GitHub with the link below, it could be helpful to provide the logs downloaded from the "Download Logs" link below

An unexpected error occurred: 404 Client Error: Not Found for url: http://hassio/snapshots
[arrow_drop_down View Exception Details](https://terryrobotic.duckdns.org/api/hassio_ingress/kNnLcMVEe17XRSkZlVFd6HTgYquDMCPFRCZb38D-m3c/#!)

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 109, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 127, in sync
    self._syncSnapshots([self.source, self.dest])
  File "/app/backup/model.py", line 205, in _syncSnapshots
    from_source: Dict[str, AbstractSnapshot] = source.get()
  File "/app/backup/hasource.py", line 174, in get
    for snapshot in self.harequests.snapshots()['snapshots']:
  File "/app/backup/harequests.py", line 63, in snapshots
    return self._getHassioData(self.config.get(Setting.HASSIO_URL) + "snapshots")
  File "/app/backup/harequests.py", line 132, in _getHassioData
    return self._validateHassioReply(self._client.get(url, headers=self._getHassioHeaders()))
  File "/app/backup/harequests.py", line 98, in _validateHassioReply
    resp.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://hassio/snapshots

**Comment by xbmcnut** [comment]
FYI, my addoon was stuck on  0.100.0 and when I went to the add-on store, GDB repo was not showing. I added it again and it still did not show until I did a CTRL + F5.. After that, it appeared and showed there was an update even though the add-on had been set to auto-update so it seems something was broken?

P.S I'm still running 2022.6.7

**Comment by albelem** [comment]
Hey @sabeechen, I just ran into this same problem and came here to have a look.
Mine was also stuck in version 0.99
Not sure if it could be related, but in my case the URL for the repo simply wasn't listed in the add-on repositories.
I've never removed it, but somehow it wasn't there.
I had to uninstall it, re-add the URL and install it again.
