### ISSUE TITLE
Home Assistant Snapshots Backup ~ 404 Error after upgrade to 2022.6.7

### ISSUE THREAD

**Issue by superq1** [sabeechen/hassio-google-drive-backup#651]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.104.3`
 Home Assistant Version: `2022.6.7`
 Supervisor Version: `2022.06.2`
 Supervisor Channel: `stable`
 Hassos Version: `8.2`
 Docker Version: `20.10.14`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2022-07-06T15:37:17.965845+00:00`
 Timezone: `Africa/Johannesburg`
 Failure Time: `2022-07-06T15:36:29.145043+00:00`
 Last Good Sync: `2022-07-06T15:36:29.139630+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 3,
        "retained": 0,
        "deletable": 3,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2022-07-06T10:00:03Z",
        "max": 3,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "482.3 MB",
        "ignored_size": "0.0 B",
        "free_space": "39.1 GB"
    },
    "GoogleDrive": {
        "snapshots": 5,
        "retained": 0,
        "deletable": 5,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2022-07-06T10:00:03Z",
        "max": 5,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "794.9 MB",
        "ignored_size": "0.0 B",
        "free_space": "13.4 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 3,
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 5,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 1.0,
    "Setting.SNAPSHOT_TIME_OF_DAY": "12:00",
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 07-06 14:27:33 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-06 14:27:33 INFO [backup.model.coordinator] Syncing Snapshots
07-06 14:27:33 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-06 14:27:33 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-06 14:27:33 INFO [backup.model.coordinator] I'll try again in an hour
07-06 15:27:33 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-06 15:27:33 INFO [backup.model.coordinator] Syncing Snapshots
07-06 15:27:33 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-06 15:27:33 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-06 15:27:33 INFO [backup.model.coordinator] I'll try again in an hour
07-06 16:27:33 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-06 16:27:33 INFO [backup.model.coordinator] Syncing Snapshots
07-06 16:27:33 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-06 16:27:33 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-06 16:27:33 INFO [backup.model.coordinator] I'll try again in an hour
07-06 17:27:33 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-06 17:27:33 INFO [backup.model.coordinator] Syncing Snapshots
07-06 17:27:33 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-06 17:27:33 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-06 17:27:33 INFO [backup.model.coordinator] I'll try again in an hour
07-06 17:35:17 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
07-06 17:35:17 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
07-06 17:35:17 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
07-06 17:35:17 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
07-06 17:36:29 INFO [backup.drive.drivesource] Saving new Google Drive credentials
07-06 17:36:29 DEBUG [backup.model.syncer] Sync requested by GoogleDrive
07-06 17:36:29 INFO [backup.model.coordinator] Syncing Snapshots
07-06 17:36:29 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-06 17:36:29 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-06 17:36:29 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m22-07-06 17:34:38 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/tasmoadmin/amd64 with version 0.20.0[0m
[32m22-07-06 17:34:38 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m22-07-06 17:34:38 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m22-07-06 17:34:38 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m22-07-06 17:34:38 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m22-07-06 17:34:41 INFO (MainThread) [supervisor.store] Loading add-ons from store: 65 all - 0 new - 0 remove[0m
[32m22-07-06 17:34:41 INFO (MainThread) [supervisor.store] Loading add-ons from store: 65 all - 0 new - 0 remove[0m
[31m22-07-06 17:34:42 ERROR (SyncWorker_0) [supervisor.docker.interface] Container addon_core_ssh is not running[0m
[33m22-07-06 17:34:44 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with core_ssh![0m
[32m22-07-06 17:34:44 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_core_ssh application[0m
[33m22-07-06 17:34:45 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[32m22-07-06 17:34:47 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-ssh with version 9.5.0[0m
[33m22-07-06 17:35:17 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with core_ssh![0m
[32m22-07-06 17:35:17 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_core_ssh application[0m
[32m22-07-06 17:35:17 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-06 17:35:17 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-06 17:35:19 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-ssh with version 9.5.0[0m
[33m22-07-06 17:35:49 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with core_ssh![0m
[32m22-07-06 17:35:50 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_core_ssh application[0m
[32m22-07-06 17:35:52 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-ssh with version 9.5.0[0m
[33m22-07-06 17:36:22 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with core_ssh![0m
[32m22-07-06 17:36:22 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_core_ssh application[0m
[32m22-07-06 17:36:24 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-ssh with version 9.5.0[0m
[32m22-07-06 17:36:29 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[33m22-07-06 17:36:37 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m22-07-06 17:36:54 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with core_ssh![0m
[32m22-07-06 17:36:54 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_ssh application[0m
[32m22-07-06 17:36:56 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-ssh with version 9.5.0[0m
[32m22-07-06 17:37:17 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 bluetooth.btcommon.BluetoothError: error accessing bluetooth device[0m
[31m2022-07-06 17:37:12 ERROR (SyncWorker_2) [homeassistant.components.bluetooth_tracker.device_tracker] Couldn't discover bluetooth devices: [Errno 19] No such device[0m
[31m2022-07-06 17:37:12 ERROR (MainThread) [homeassistant.components.bluetooth_tracker.device_tracker] Error looking up Bluetooth device
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bluetooth/bluez.py", line 289, in _gethcisock
    sock = _bt.hci_open_dev (device_id)
_bluetooth.error: no available bluetoot devices
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 167, in perform_bluetooth_update
    friendly_name = await hass.async_add_executor_job(lookup_name, mac)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 127, in lookup_name
    return bluetooth.lookup_name(mac, timeout=5)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/site-packages/bluetooth/bluez.py", line 61, in lookup_name
    sock = _gethcisock ()
  File "/usr/local/lib/python3.9/site-packages/bluetooth/bluez.py", line 291, in _gethcisock
    raise BluetoothError ("error accessing bluetooth device")
bluetooth.btcommon.BluetoothError: error accessing bluetooth device[0m
[31m2022-07-06 17:37:16 ERROR (MainThread) [homeassistant.components.poolsense] Unexpected error fetching poolsense data: 'waterTemp'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/poolsense/__init__.py", line 95, in _async_update_data
    data = await self.poolsense.get_poolsense_data()
  File "/usr/local/lib/python3.9/site-packages/poolsense/__init__.py", line 77, in get_poolsense_data
    "Water Temp": data["waterTemp"],
KeyError: 'waterTemp'[0m

 ```

**Comment by sabeechen** [comment]
You need to update the addon. The supervisor has been planning to make a change to their API that affects the addon for around 6 months now, and the latest version finally did it. 

This addon has been updated to handle this for a while now, you just need to update it.  The latest version of the addon is currently 0.108.2.

**Comment by kylehase** [comment]
My HA is not finding any updates for this add-on available, and based on the many duplicate reports I assume the same is true for others.

Do we need to completely uninstall and reinstall the add-on?

**Comment by sabeechen** [comment]
Please try what I've posted [here](https://github.com/sabeechen/hassio-google-drive-backup/issues/652#issuecomment-1177943877)

Duplicate #652

**Comment by superq1** [comment]
I managed to upgrade by re-adding the add-on repository to my addons in HA. (Follow the first time install instructions – the repo details are in there)
It then saw/found the update and updated without any issue.

Been working perfectly since…


Kindest regards,

Cuan

From: Kyle Hasegawa ***@***.***>
Date: Thursday, 07 July 2022 at 00:55
To: sabeechen/hassio-google-drive-backup ***@***.***>
Cc: Cuan Parker ***@***.***>, Author ***@***.***>
Subject: Re: [sabeechen/hassio-google-drive-backup] Home Assistant Snapshots Backup ~ 404 Error after upgrade to 2022.6.7 (Issue #651)

My HA is not finding any updates for this add-on available, and based on the many duplicate reports I assume the same is true for others.

Do we need to completely uninstall and reinstall the add-on?
