### ISSUE TITLE
Stopped working.. cannot find url

### ISSUE THREAD

**Issue by Davecl** [sabeechen/hassio-google-drive-backup#659]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.103.1`
 Home Assistant Version: `2022.6.7`
 Supervisor Version: `2022.07.0`
 Supervisor Channel: `stable`
 Hassos Version: `8.2`
 Docker Version: `20.10.14`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2022-07-07T17:21:42.463119+00:00`
 Timezone: `Europe/London`
 Failure Time: `2022-07-07T17:21:32.642651+00:00`
 Last Good Sync: `2022-07-07T17:21:32.627820+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:224 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:102 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/ha/harequests.py:174 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": null,
        "max": 10,
        "enabled": true,
        "size": "0.0 B",
        "free_space": "198.8 GB"
    },
    "GoogleDrive": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 5,
        "enabled": true,
        "size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 10,
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 5,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 7.0
}
 ```
 ###### Addon Logs:
 ```
 07-07 17:26:29 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-07 17:26:29 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:224 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:102 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/ha/harequests.py:174 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-07 17:26:29 INFO [backup.model.coordinator] I'll try again in 10(ish) minutes
07-07 17:28:38 ERROR [backup.ha.haupdater] Unable to reach Home Assistant (HTTP 502).  This is normal if Home Assistant is restarting.  You will probably see some errors in the supervisor logs until it comes back online.
07-07 17:33:48 ERROR [backup.ha.haupdater] Unable to reach Home Assistant (HTTP 502).  This is normal if Home Assistant is restarting.  You will probably see some errors in the supervisor logs until it comes back online.
07-07 17:37:10 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-07 17:37:10 INFO [backup.model.coordinator] Syncing Snapshots
07-07 17:37:10 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-07 17:37:10 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:224 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:102 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/ha/harequests.py:174 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-07 17:37:10 INFO [backup.model.coordinator] I'll try again in 21(ish) minutes
07-07 17:58:30 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-07 17:58:30 INFO [backup.model.coordinator] Syncing Snapshots
07-07 17:58:30 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-07 17:58:30 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:224 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:102 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/ha/harequests.py:174 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-07 17:58:30 INFO [backup.model.coordinator] I'll try again in 42(ish) minutes
07-07 18:20:08 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
07-07 18:20:08 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
07-07 18:20:08 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
07-07 18:20:08 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
07-07 18:20:18 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/options
07-07 18:20:18 INFO [backup.model.coordinator] Syncing Snapshots
07-07 18:20:18 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-07 18:20:18 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:224 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:102 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/ha/harequests.py:174 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-07 18:20:18 INFO [backup.model.coordinator] I'll try again in an hour
07-07 18:21:32 INFO [backup.drive.drivesource] Saving new Google Drive credentials
07-07 18:21:32 DEBUG [backup.model.syncer] Sync requested by GoogleDrive
07-07 18:21:32 INFO [backup.model.coordinator] Syncing Snapshots
07-07 18:21:32 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-07 18:21:32 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:224 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:102 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/ha/harequests.py:174 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-07 18:21:32 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m22-07-07 18:16:00 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m22-07-07 18:16:00 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m
[32m22-07-07 18:16:00 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER[0m
[32m22-07-07 18:16:00 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER[0m
[32m22-07-07 18:16:00 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m22-07-07 18:16:00 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m22-07-07 18:16:00 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m22-07-07 18:16:00 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m22-07-07 18:16:00 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m22-07-07 18:16:00 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m22-07-07 18:16:01 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m22-07-07 18:16:01 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m22-07-07 18:16:01 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[33m22-07-07 18:18:25 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[33m22-07-07 18:18:25 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)[0m
[33m22-07-07 18:18:25 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)[0m
[33m22-07-07 18:18:25 WARNING (MainThread) [supervisor.addons.options] Option 'snapshot_mode' does not exist in the schema for Ring-MQTT with Video Streaming (03cabcc9_ring_mqtt)[0m
[33m22-07-07 18:18:25 WARNING (MainThread) [supervisor.addons.options] Option 'enable_volume' does not exist in the schema for Ring-MQTT with Video Streaming (03cabcc9_ring_mqtt)[0m
[33m22-07-07 18:18:25 WARNING (MainThread) [supervisor.addons.options] Option 'mqtt_host' does not exist in the schema for Ring-MQTT with Video Streaming (03cabcc9_ring_mqtt)[0m
[33m22-07-07 18:18:25 WARNING (MainThread) [supervisor.addons.options] Option 'mqtt_port' does not exist in the schema for Ring-MQTT with Video Streaming (03cabcc9_ring_mqtt)[0m
[33m22-07-07 18:18:25 WARNING (MainThread) [supervisor.addons.options] Option 'mqtt_user' does not exist in the schema for Ring-MQTT with Video Streaming (03cabcc9_ring_mqtt)[0m
[33m22-07-07 18:18:25 WARNING (MainThread) [supervisor.addons.options] Option 'mqtt_password' does not exist in the schema for Ring-MQTT with Video Streaming (03cabcc9_ring_mqtt)[0m
[33m22-07-07 18:18:25 WARNING (MainThread) [supervisor.addons.options] Option 'ring_token' does not exist in the schema for Ring-MQTT with Video Streaming (03cabcc9_ring_mqtt)[0m
[32m22-07-07 18:20:08 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-07 18:20:08 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-07 18:20:18 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[33m22-07-07 18:21:14 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[32m22-07-07 18:21:32 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-07 18:21:42 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 499, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 534, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.4.82', 6668)[0m
[31m2022-07-07 18:20:55 ERROR (MainThread) [custom_components.localtuya.common] [810...015] Connect to 192.168.4.82 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 160, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 499, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 534, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.4.82', 6668)[0m

 ```

**Comment by sabeechen** [comment]
Please see my comments [here](https://github.com/sabeechen/hassio-google-drive-backup/issues/652#issuecomment-1177943877)

Duplicate #652
