### ISSUE TITLE
Error while backing up

### ISSUE THREAD

**Issue by Volodey777** [sabeechen/hassio-google-drive-backup#662]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.103.1`
 Home Assistant Version: `2022.7.1`
 Supervisor Version: `2022.07.0`
 Supervisor Channel: `stable`
 Hassos Version: `None`
 Docker Version: `20.10.17`
 Architecture: `armv7`
 Machine: `raspberrypi4`
 Date: `2022-07-08T20:19:49.375992+00:00`
 Timezone: `Europe/Kiev`
 Failure Time: `2022-07-08T20:19:49.059808+00:00`
 Last Good Sync: `2022-07-08T20:19:49.036970+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:224 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:102 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/ha/harequests.py:174 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": null,
        "max": 5,
        "enabled": true,
        "size": "0.0 B",
        "free_space": "42.2 GB"
    },
    "GoogleDrive": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 5,
        "enabled": true,
        "size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 5,
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 5,
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 07-08 23:19:46 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
07-08 23:19:46 INFO [backup.model.coordinator] Syncing Snapshots
07-08 23:19:46 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-08 23:19:46 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:224 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:102 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/ha/harequests.py:174 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-08 23:19:46 INFO [backup.model.coordinator] I'll try again in an hour
07-08 23:19:46 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
07-08 23:19:46 INFO [backup.model.coordinator] Syncing Snapshots
07-08 23:19:46 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-08 23:19:46 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:224 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:102 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/ha/harequests.py:174 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-08 23:19:46 INFO [backup.model.coordinator] I'll try again in an hour
07-08 23:19:47 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
07-08 23:19:47 INFO [backup.model.coordinator] Syncing Snapshots
07-08 23:19:47 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-08 23:19:47 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:224 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:102 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/ha/harequests.py:174 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-08 23:19:47 INFO [backup.model.coordinator] I'll try again in an hour
07-08 23:19:47 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
07-08 23:19:47 INFO [backup.model.coordinator] Syncing Snapshots
07-08 23:19:47 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-08 23:19:47 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:224 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:102 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/ha/harequests.py:174 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-08 23:19:47 INFO [backup.model.coordinator] I'll try again in an hour
07-08 23:19:48 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
07-08 23:19:48 INFO [backup.model.coordinator] Syncing Snapshots
07-08 23:19:48 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-08 23:19:48 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:224 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:102 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/ha/harequests.py:174 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-08 23:19:48 INFO [backup.model.coordinator] I'll try again in an hour
07-08 23:19:49 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
07-08 23:19:49 INFO [backup.model.coordinator] Syncing Snapshots
07-08 23:19:49 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-08 23:19:49 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:224 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:102 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/ha/harequests.py:174 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

07-08 23:19:49 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m22-07-08 23:19:34 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:35 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:35 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:36 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:36 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:37 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:38 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:38 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:39 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:39 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:40 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:40 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:41 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:41 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:42 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:42 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:43 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:43 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:44 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:44 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:45 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:45 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:46 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:46 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:47 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:47 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:48 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:49 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-07-08 23:19:49 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/qnap/sensor.py", line 304, in update
    self.data["system_stats"] = self._api.get_system_stats()
  File "/usr/local/lib/python3.10/site-packages/qnapstats/qnap_stats.py", line 217, in get_system_stats
    resp = self._get_url(
  File "/usr/local/lib/python3.10/site-packages/qnapstats/qnap_stats.py", line 74, in _get_url
    self._init_session()
  File "/usr/local/lib/python3.10/site-packages/qnapstats/qnap_stats.py", line 50, in _init_session
    if self._login() is False:
  File "/usr/local/lib/python3.10/site-packages/qnapstats/qnap_stats.py", line 58, in _login
    result = self._execute_post_url("authLogin.cgi", data, False)
  File "/usr/local/lib/python3.10/site-packages/qnapstats/qnap_stats.py", line 104, in _execute_post_url
    resp = self._session.post(url, data, timeout=self._timeout, verify=self._verify_ssl)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.10.250', port=8080): Max retries exceeded with url: /cgi-bin/authLogin.cgi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x9c55f598>: Failed to establish a new connection: [Errno 113] Host is unreachable'))[0m
[31m2022-07-08 23:17:52 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.fan.xiaomi_air_humidifier.attributes.temperature }}'[0m
[31m2022-07-08 23:17:52 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.fan.xiaomi_air_humidifier.attributes.humidity }}'[0m
[31m2022-07-08 23:17:52 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.fan.xiaomi_air_humidifier.attributes.motor_speed }}'[0m
[31m2022-07-08 23:18:52 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.fan.xiaomi_air_humidifier.attributes.temperature }}'[0m
[31m2022-07-08 23:18:52 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.fan.xiaomi_air_humidifier.attributes.humidity }}'[0m
[31m2022-07-08 23:18:52 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.fan.xiaomi_air_humidifier.attributes.motor_speed }}'[0m

 ```

**Comment by sabeechen** [comment]
Please see my comment [here](https://github.com/sabeechen/hassio-google-drive-backup/issues/652#issuecomment-1177943877)

Duplicate #652
