### ISSUE TITLE
Plugin stopped working :(

### ISSUE THREAD

**Issue by ssypchenko** [sabeechen/hassio-google-drive-backup#687]
Copy the info from the previous page here
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.101.3`
 Home Assistant Version: `2022.7.7`
 Supervisor Version: `2022.07.0`
 Supervisor Channel: `stable`
 Hassos Version: `8.4`
 Docker Version: `20.10.14`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2022-08-06T15:39:29.941995+00:00`
 Timezone: `Europe/London`
 Failure Time: `2022-08-06T15:31:11.301438+00:00`
 Last Good Sync: `2022-08-06T15:31:11.280377+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:133 (sync)
  addon/backup/model/model.py:216 (_syncSnapshots)
  addon/backup/ha/hasource.py:221 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:103 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:208 (_getHassioData)
  addon/backup/ha/harequests.py:175 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:941 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "HomeAssistant",
        "latest": null,
        "size": "0.0 B"
    },
    "GoogleDrive": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "latest": null,
        "size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.SPECIFY_SNAPSHOT_FOLDER": true
}
 ```
 ###### Addon Logs:
 ```
 08-06 16:22:05 INFO [backup.model.coordinator] I'll try again in 40 seconds
08-06 16:22:46 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-06 16:22:46 INFO [backup.model.coordinator] Syncing Snapshots
08-06 16:22:46 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-06 16:22:46 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:133 (sync)
  addon/backup/model/model.py:216 (_syncSnapshots)
  addon/backup/ha/hasource.py:221 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:103 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:208 (_getHassioData)
  addon/backup/ha/harequests.py:175 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:941 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

08-06 16:22:46 INFO [backup.model.coordinator] I'll try again in 1(ish) minutes
08-06 16:22:54 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
08-06 16:22:54 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
08-06 16:22:54 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
08-06 16:22:54 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
08-06 16:24:06 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-06 16:24:06 INFO [backup.model.coordinator] Syncing Snapshots
08-06 16:24:06 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-06 16:24:06 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:133 (sync)
  addon/backup/model/model.py:216 (_syncSnapshots)
  addon/backup/ha/hasource.py:221 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:103 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:208 (_getHassioData)
  addon/backup/ha/harequests.py:175 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:941 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

08-06 16:24:06 INFO [backup.model.coordinator] I'll try again in 2(ish) minutes
08-06 16:26:46 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-06 16:26:46 INFO [backup.model.coordinator] Syncing Snapshots
08-06 16:26:46 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-06 16:26:46 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:133 (sync)
  addon/backup/model/model.py:216 (_syncSnapshots)
  addon/backup/ha/hasource.py:221 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:103 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:208 (_getHassioData)
  addon/backup/ha/harequests.py:175 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:941 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

08-06 16:26:46 INFO [backup.model.coordinator] I'll try again in 5(ish) minutes
08-06 16:29:39 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
08-06 16:29:39 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
08-06 16:29:39 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
08-06 16:29:39 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
08-06 16:31:10 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/options
08-06 16:31:11 INFO [backup.drive.folderfinder] Saving snapshot folder: 1VDR1CFq1uFcbweZNycRAG7sbNDKG8DZ1
08-06 16:31:11 INFO [backup.model.coordinator] Syncing Snapshots
08-06 16:31:11 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-06 16:31:11 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:133 (sync)
  addon/backup/model/model.py:216 (_syncSnapshots)
  addon/backup/ha/hasource.py:221 (get)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:103 (snapshots)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:208 (_getHassioData)
  addon/backup/ha/harequests.py:175 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:941 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

08-06 16:31:11 INFO [backup.model.coordinator] I'll try again in 10(ish) minutes
 ```
 ###### Supervisor Logs:
 ```
 [33m22-08-06 16:32:44 WARNING (MainThread) [supervisor.addons.options] Option 'vnc_password' does not exist in the schema for deCONZ (core_deconz)[0m
[33m22-08-06 16:32:44 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)[0m
[33m22-08-06 16:32:44 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m22-08-06 16:32:44 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m22-08-06 16:32:44 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m22-08-06 16:32:44 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[32m22-08-06 16:32:48 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[33m22-08-06 16:33:04 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)[0m
[33m22-08-06 16:33:04 WARNING (MainThread) [supervisor.addons.options] Option 'vnc_password' does not exist in the schema for deCONZ (core_deconz)[0m
[32m22-08-06 16:33:13 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m22-08-06 16:33:13 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered[0m
[32m22-08-06 16:33:13 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance[0m
[32m22-08-06 16:33:14 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m22-08-06 16:34:52 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m22-08-06 16:34:52 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m22-08-06 16:34:52 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m22-08-06 16:34:52 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository[0m
[32m22-08-06 16:34:55 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove[0m
[32m22-08-06 16:34:55 INFO (MainThread) [supervisor.store] Loading add-ons from store: 68 all - 0 new - 0 remove[0m
[32m22-08-06 16:37:48 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret red_password[0m
[33m22-08-06 16:37:48 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)[0m
[33m22-08-06 16:37:48 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)[0m
[33m22-08-06 16:37:48 WARNING (MainThread) [supervisor.addons.options] Option 'vnc_password' does not exist in the schema for deCONZ (core_deconz)[0m
[33m22-08-06 16:37:48 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)[0m
[33m22-08-06 16:37:48 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m22-08-06 16:37:48 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m22-08-06 16:37:48 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m22-08-06 16:37:48 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[32m22-08-06 16:39:29 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 829, in validator
    raise vol.Invalid(warning % arguments)
voluptuous.error.Invalid: The 'value_template' option has been removed, please remove it from your configuration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 309, in async_discover
    config = schema(discovery_payload)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 232, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 351, in _exec
    v = func(v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 49, in validate_mqtt_light_discovery
    return schemas[value[CONF_SCHEMA]](value)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 232, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 351, in _exec
    v = func(v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: The 'value_template' option has been removed, please remove it from your configuration
[0m

 ```

**Comment by sabeechen** [comment]
Please see my comment [here](https://github.com/sabeechen/hassio-google-drive-backup/issues/652#issuecomment-1177943877)

duplicate #652
