### ISSUE TITLE
Error while backing up

### ISSUE THREAD

**Issue by suyashrai** [sabeechen/hassio-google-drive-backup#693]
###### Description:
```
 An unexpected error occurred: 404, message='Not Found', url=URL('http://hassio/snapshots')
```

 Addon version: `0.104.3`
 Home Assistant Version: `2022.8.1`
 Supervisor Version: `2022.08.3`
 Supervisor Channel: `stable`
 Hassos Version: `8.4`
 Docker Version: `20.10.14`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2022-08-15T11:29:32.005538+00:00`
 Timezone: `Asia/Kolkata`
 Failure Time: `2022-08-15T11:29:26.856044+00:00`
 Last Good Sync: `2022-08-15T11:29:26.843606+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": null,
        "max": 7,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "0.0 B",
        "ignored_size": "0.0 B",
        "free_space": "19.4 GB"
    },
    "GoogleDrive": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 7,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "0.0 B",
        "ignored_size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 7,
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 7,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 1.0,
    "Setting.SNAPSHOT_TIME_OF_DAY": "04:00",
    "Setting.SPECIFY_SNAPSHOT_FOLDER": true
}
 ```
 ###### Addon Logs:
 ```
 08-15 13:42:53 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-15 13:42:53 INFO [backup.model.coordinator] Syncing Snapshots
08-15 13:42:53 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-15 13:42:53 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

08-15 13:42:53 INFO [backup.model.coordinator] I'll try again in an hour
08-15 14:42:53 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-15 14:42:53 INFO [backup.model.coordinator] Syncing Snapshots
08-15 14:42:53 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-15 14:42:53 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

08-15 14:42:53 INFO [backup.model.coordinator] I'll try again in an hour
08-15 15:42:54 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-15 15:42:54 INFO [backup.model.coordinator] Syncing Snapshots
08-15 15:42:54 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-15 15:42:54 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

08-15 15:42:54 INFO [backup.model.coordinator] I'll try again in an hour
08-15 16:42:54 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-15 16:42:54 INFO [backup.model.coordinator] Syncing Snapshots
08-15 16:42:54 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-15 16:42:54 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

08-15 16:42:54 INFO [backup.model.coordinator] I'll try again in an hour
08-15 16:59:06 INFO [backup.model.coordinator] Syncing Snapshots
08-15 16:59:06 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-15 16:59:06 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

08-15 16:59:06 INFO [backup.model.coordinator] I'll try again in an hour
08-15 16:59:26 INFO [backup.drive.drivesource] Saving new Google Drive credentials
08-15 16:59:26 DEBUG [backup.model.syncer] Sync requested by GoogleDrive
08-15 16:59:26 INFO [backup.model.coordinator] Syncing Snapshots
08-15 16:59:26 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-15 16:59:26 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/ha/hasource.py:246 (get)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:108 (snapshots)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:221 (_getHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://hassio/snapshots')

08-15 16:59:26 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m22-08-15 16:16:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER[0m
[32m22-08-15 16:16:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER[0m
[32m22-08-15 16:16:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m22-08-15 16:16:53 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m22-08-15 16:16:53 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m22-08-15 16:16:53 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m22-08-15 16:16:54 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m22-08-15 16:16:54 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m22-08-15 16:16:54 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m22-08-15 16:17:32 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m22-08-15 16:17:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/blakeblackshear/frigate-hass-addons repository[0m
[32m22-08-15 16:17:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m22-08-15 16:17:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m22-08-15 16:17:54 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[33m22-08-15 16:17:56 WARNING (SyncWorker_7) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR (Full Access)[0m
[33m22-08-15 16:17:57 WARNING (SyncWorker_6) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of Frigate NVR (Full Access)[0m
[32m22-08-15 16:17:57 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 0 remove[0m
[32m22-08-15 16:17:57 INFO (MainThread) [supervisor.store] Loading add-ons from store: 71 all - 0 new - 0 remove[0m
[32m22-08-15 16:19:55 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m22-08-15 16:31:09 INFO (MainThread) [supervisor.host.info] Updating local host information[0m
[32m22-08-15 16:31:10 INFO (MainThread) [supervisor.host.services] Updating service information[0m
[32m22-08-15 16:31:10 INFO (MainThread) [supervisor.host.network] Updating local network information[0m
[32m22-08-15 16:31:11 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
[32m22-08-15 16:31:11 INFO (MainThread) [supervisor.host.manager] Host information reload completed[0m
[32m22-08-15 16:42:54 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-08-15 16:49:56 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m22-08-15 16:59:06 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-08-15 16:59:26 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m22-08-15 16:59:32 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.143', 6668)[0m
[31m2022-08-15 16:58:58.327 ERROR (MainThread) [custom_components.localtuya.common] [787...034] Connect to 192.168.0.143 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 145, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 669, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.143', 6668)[0m
[33m2022-08-15 16:59:30.278 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform openhardwaremonitor is taking over 10 seconds.[0m

 ```

**Comment by sabeechen** [comment]
Please see the [answer here](https://github.com/sabeechen/hassio-google-drive-backup/issues/652#issuecomment-1177943877).

Duplicate #652
