### ISSUE TITLE
Authentification problem when using option "require_login"

### ISSUE THREAD

**Issue by m23l** [sabeechen/hassio-google-drive-backup#695]
Hi, I have a problem with authentification to WebUI when using option:

`require_login`

username + password to my home assistant is not working. Also worth mentioning is that I have 2FA enabled, but other add-ons don't have this problem when they have a similar option to authenticate to  WebUI - f.e.: Glances is working just fine with that combination login and password.

Log:

`08-17 15:50:08 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/auth
08-17 15:50:08 ERROR [backup.ui.uiserver]    
  addon/backup/ui/uiserver.py:876 (check_credentials)   
  addon/backup/ha/harequests.py:31 (wrap_and_call)   
  addon/backup/ha/harequests.py:84 (auth)   
  addon/backup/ha/harequests.py:245 (_postHassioData)   
  addon/backup/ha/harequests.py:31 (wrap_and_call)   
  addon/backup/ha/harequests.py:250 (_sendHassioData)   
  addon/backup/ha/harequests.py:202 (_validateHassioReply)   
  /site-packages/aiohttp/client_reqrep.py:1004 (raise_for_status)   
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('http://supervisor/auth')  `

**Comment by sabeechen** [comment]
It looks like there is a problem with user/pass authentication unrelated to 2FA.  In my supervisor logs I get this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/aiohttp.py", line 121, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/aiohttp.py", line 111, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 138, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 204, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 60, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/auth.py", line 64, in auth
    if not await self._process_basic(request, addon):
  File "/usr/src/supervisor/supervisor/api/auth.py", line 39, in _process_basic
    auth = BasicAuth.decode(request.headers[AUTHORIZATION])
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 155, in decode
    raise ValueError("Unknown authorization method %s" % auth_type)
ValueError: Unknown authorization method Bearer
```

Maybe home assistant changed its authentication endpoints recently? Bearer headers have worked fine for years.  I'll need to look into this.

**Comment by m23l** [comment]
my HA instance on RaspPi 4versions:

HA: 2022.08.5
supervisor: 2022.08.3
OS: 8.4

**Comment by sabeechen** [comment]
I'm not sure how long this has been broken, but I just released a fix that changes how the addon communicates with Home Assistant to fix it.  Things should work properly with with addon version 0.108.4, please feel free to re-open this if you continue to have trouble.
