### ISSUE TITLE
The addon has made too many requests to Google Drive, and will back off

### ISSUE THREAD

**Issue by fabro21** [sabeechen/hassio-google-drive-backup#709]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.105.2`
 Home Assistant Version: `2022.8.7`
 Supervisor Version: `2022.08.5`
 Supervisor Channel: `stable`
 Hassos Version: `None`
 Docker Version: `20.10.14`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2022-09-05T20:57:18.982850+00:00`
 Timezone: `America/Argentina/Buenos_Aires`
 Failure Time: `2022-09-05T20:56:59.315252+00:00`
 Last Good Sync: `2022-09-05T20:56:59.979632+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:204 (sync)
  addon/backup/drive/drivesource.py:179 (save)
  addon/backup/drive/driverequests.py:280 (create)
  addon/backup/drive/driverequests.py:361 (retryRequest)
  addon/backup/util/backoff.py:37 (backoff)
  addon/backup/drive/driverequests.py:349 (retryRequest)
  addon/backup/creds/driverequester.py:39 (request)
backup.exceptions.exceptions.GoogleRateLimitError

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 10,
        "retained": 0,
        "deletable": 10,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2022-09-05T20:55:10Z",
        "max": 10,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "521.5 MB",
        "ignored_size": "0.0 B",
        "free_space": "189.9 GB"
    },
    "GoogleDrive": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 3,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "0.0 B",
        "ignored_size": "0.0 B",
        "free_space": "15.0 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 10,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 3,
    "Setting.DELETE_BEFORE_NEW_BACKUP": true,
    "Setting.CONFIRM_MULTIPLE_DELETES": false
}
 ```
 ###### Addon Logs:
 ```
 09-05 17:55:53 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
09-05 17:55:53 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdujoJ85jMXrLmf5HoqLijo6a9EVzzMZhctN7DfNs2tAXxWNp-Cd1FhXV2NaaWzjNPUEKmZP4uHRdjZmLackNM3z2A
09-05 17:55:54 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 2 seconds
09-05 17:55:56 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdujoJ85jMXrLmf5HoqLijo6a9EVzzMZhctN7DfNs2tAXxWNp-Cd1FhXV2NaaWzjNPUEKmZP4uHRdjZmLackNM3z2A
09-05 17:55:56 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 4 seconds
09-05 17:56:00 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdujoJ85jMXrLmf5HoqLijo6a9EVzzMZhctN7DfNs2tAXxWNp-Cd1FhXV2NaaWzjNPUEKmZP4uHRdjZmLackNM3z2A
09-05 17:56:01 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 8 seconds
09-05 17:56:09 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdujoJ85jMXrLmf5HoqLijo6a9EVzzMZhctN7DfNs2tAXxWNp-Cd1FhXV2NaaWzjNPUEKmZP4uHRdjZmLackNM3z2A
09-05 17:56:09 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 16 seconds
09-05 17:56:25 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdujoJ85jMXrLmf5HoqLijo6a9EVzzMZhctN7DfNs2tAXxWNp-Cd1FhXV2NaaWzjNPUEKmZP4uHRdjZmLackNM3z2A
09-05 17:56:26 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 32 seconds
09-05 17:56:58 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdujoJ85jMXrLmf5HoqLijo6a9EVzzMZhctN7DfNs2tAXxWNp-Cd1FhXV2NaaWzjNPUEKmZP4uHRdjZmLackNM3z2A
09-05 17:56:59 ERROR [backup.model.coordinator] The addon has made too many requests to Google Drive, and will back off
09-05 17:56:59 INFO [backup.model.coordinator] I'll try again in an hour
09-05 17:56:59 INFO [backup.model.coordinator] Syncing Backups
09-05 17:56:59 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
09-05 17:57:00 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
09-05 17:57:00 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1mJXAnABe7KAXkHLN1xq3RfGdbGzMHN8-/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
09-05 17:57:00 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
09-05 17:57:00 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271mJXAnABe7KAXkHLN1xq3RfGdbGzMHN8-%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
09-05 17:57:01 INFO [backup.drive.drivesource] Uploading 'core_2022.8.6' to Google Drive
09-05 17:57:01 DEBUG [backup.drive.driverequests] Attempting to resume a previously failed upload where we left off
09-05 17:57:01 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdujoJ85jMXrLmf5HoqLijo6a9EVzzMZhctN7DfNs2tAXxWNp-Cd1FhXV2NaaWzjNPUEKmZP4uHRdjZmLackNM3z2A
09-05 17:57:01 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 2 seconds
09-05 17:57:03 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdujoJ85jMXrLmf5HoqLijo6a9EVzzMZhctN7DfNs2tAXxWNp-Cd1FhXV2NaaWzjNPUEKmZP4uHRdjZmLackNM3z2A
09-05 17:57:03 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 4 seconds
09-05 17:57:07 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdujoJ85jMXrLmf5HoqLijo6a9EVzzMZhctN7DfNs2tAXxWNp-Cd1FhXV2NaaWzjNPUEKmZP4uHRdjZmLackNM3z2A
09-05 17:57:07 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 8 seconds
09-05 17:57:15 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdujoJ85jMXrLmf5HoqLijo6a9EVzzMZhctN7DfNs2tAXxWNp-Cd1FhXV2NaaWzjNPUEKmZP4uHRdjZmLackNM3z2A
09-05 17:57:15 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 16 seconds
 ```
 ###### Supervisor Logs:
 ```
 [32m22-09-05 17:55:12 INFO (MainThread) [supervisor.api.middleware.security] /backups/new/full access from cebe7a76_hassio_google_drive_backup[0m
[32m22-09-05 17:55:12 INFO (MainThread) [supervisor.backups.manager] Creating new full backup with slug a305075c[0m
[32m22-09-05 17:55:12 INFO (MainThread) [supervisor.backups.manager] Backing up a305075c store Add-ons[0m
[32m22-09-05 17:55:12 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_vscode[0m
[32m22-09-05 17:55:17 INFO (MainThread) [supervisor.api.middleware.security] /backups/b8186393/download access from cebe7a76_hassio_google_drive_backup[0m
[32m22-09-05 17:55:17 INFO (MainThread) [supervisor.api.backups] Downloading backup b8186393[0m
[32m22-09-05 17:55:35 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-09-05 17:55:35 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[31m22-09-05 17:55:53 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Server disconnected[0m
[32m22-09-05 17:55:56 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_vscode[0m
[32m22-09-05 17:55:57 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_configurator[0m
[32m22-09-05 17:55:57 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_configurator[0m
[32m22-09-05 17:55:57 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_influxdb[0m
[32m22-09-05 17:56:20 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_influxdb[0m
[32m22-09-05 17:56:20 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_grafana[0m
[32m22-09-05 17:56:20 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_grafana[0m
[32m22-09-05 17:56:21 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_nodered[0m
[32m22-09-05 17:56:21 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_nodered[0m
[32m22-09-05 17:56:21 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_check_config[0m
[32m22-09-05 17:56:21 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_check_config[0m
[32m22-09-05 17:56:21 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on a0d7b954_spotify[0m
[32m22-09-05 17:56:21 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon a0d7b954_spotify[0m
[32m22-09-05 17:56:21 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_ssh[0m
[32m22-09-05 17:56:21 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_ssh[0m
[32m22-09-05 17:56:59 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-09-05 17:57:00 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-09-05 17:57:01 INFO (MainThread) [supervisor.api.middleware.security] /backups/b8186393/download access from cebe7a76_hassio_google_drive_backup[0m
[32m22-09-05 17:57:01 INFO (MainThread) [supervisor.api.backups] Downloading backup b8186393[0m
[32m22-09-05 17:57:19 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.1.112/cgi-bin/luci/;stok=2b155f5be805a8c40641910269814298/admin/device?form=device_list')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tplink_deco/coordinator.py", line 159, in _async_update_data
    new_decos = await async_call_with_retry(self.api.async_list_devices)
  File "/config/custom_components/tplink_deco/coordinator.py", line 42, in async_call_with_retry
    return await func(*args)
  File "/config/custom_components/tplink_deco/api.py", line 142, in async_list_devices
    response_json = await self._async_post(
  File "/config/custom_components/tplink_deco/api.py", line 394, in _async_post
    raise AuthException from err
custom_components.tplink_deco.exceptions.AuthException[0m
[31m2022-09-05 17:56:30.947 ERROR (MainThread) [pydroid_ipcam] Failed to communicate with IP Webcam: Cannot connect to host 192.168.1.145:8080 ssl:default [Connect call failed ('192.168.1.145', 8080)][0m
[31m2022-09-05 17:56:43.232 ERROR (MainThread) [pydroid_ipcam] Failed to communicate with IP Webcam: Cannot connect to host 192.168.1.145:8080 ssl:default [Connect call failed ('192.168.1.145', 8080)][0m
[31m2022-09-05 17:56:43.290 ERROR (MainThread) [pydroid_ipcam] Failed to communicate with IP Webcam: Cannot connect to host 192.168.1.170:8080 ssl:default [Connect call failed ('192.168.1.170', 8080)][0m
[31m2022-09-05 17:56:43.307 ERROR (MainThread) [pydroid_ipcam] Failed to communicate with IP Webcam: Cannot connect to host 192.168.1.175:8080 ssl:default [Connect call failed ('192.168.1.175', 8080)][0m
[31m2022-09-05 17:56:55.519 ERROR (MainThread) [pydroid_ipcam] Failed to communicate with IP Webcam: Cannot connect to host 192.168.1.145:8080 ssl:default [Connect call failed ('192.168.1.145', 8080)][0m
[31m2022-09-05 17:56:56.383 ERROR (MainThread) [pydroid_ipcam] Failed to communicate with IP Webcam: Cannot connect to host 192.168.1.175:8080 ssl:default [Connect call failed ('192.168.1.175', 8080)][0m
[31m2022-09-05 17:56:56.391 ERROR (MainThread) [pydroid_ipcam] Failed to communicate with IP Webcam: Cannot connect to host 192.168.1.170:8080 ssl:default [Connect call failed ('192.168.1.170', 8080)][0m
[31m2022-09-05 17:57:07.807 ERROR (MainThread) [pydroid_ipcam] Failed to communicate with IP Webcam: Cannot connect to host 192.168.1.145:8080 ssl:default [Connect call failed ('192.168.1.145', 8080)][0m
[31m2022-09-05 17:57:09.475 ERROR (MainThread) [pydroid_ipcam] Failed to communicate with IP Webcam: Cannot connect to host 192.168.1.170:8080 ssl:default [Connect call failed ('192.168.1.170', 8080)][0m
[31m2022-09-05 17:57:09.490 ERROR (MainThread) [pydroid_ipcam] Failed to communicate with IP Webcam: Cannot connect to host 192.168.1.175:8080 ssl:default [Connect call failed ('192.168.1.175', 8080)][0m
[31m2022-09-05 17:57:20.097 ERROR (MainThread) [pydroid_ipcam] Failed to communicate with IP Webcam: Cannot connect to host 192.168.1.145:8080 ssl:default [Connect call failed ('192.168.1.145', 8080)][0m
[31m2022-09-05 17:57:22.719 ERROR (MainThread) [pydroid_ipcam] Failed to communicate with IP Webcam: Cannot connect to host 192.168.1.175:8080 ssl:default [Connect call failed ('192.168.1.175', 8080)][0m
[31m2022-09-05 17:57:22.732 ERROR (MainThread) [pydroid_ipcam] Failed to communicate with IP Webcam: Cannot connect to host 192.168.1.170:8080 ssl:default [Connect call failed ('192.168.1.170', 8080)][0m

 ```
 Copy the info from the previous page here

**Comment by sabeechen** [comment]
Its likely this error is being misreported.  The backoff its doing should work.  Could I have you restart the addon, then inside the web-ui go to <kbd>Actions</kbd > > <kbd>Reauthorize Google Drive</kbd> to reconnect Google Drive?  Its possible this is caused by a permissions problem.

**Comment by fabro21** [comment]
Hi, thanks for the reply, have followed the instructions but still getting
the same error. The upload initially is close to 100% upload and then
backoff starts with no end.

Cordialmente,
Fabricio Campione Ascuénaga

**Comment by fabro21** [comment]
Unninstalling and re authorization has solved the problem, thanks!

Cordialmente,
Fabricio Campione Ascuénaga
