### ISSUE TITLE
An unexpected error occurred: ('Connection aborted.', timeout('The write operation timed out',))

### ISSUE THREAD

**Issue by PrathikGopal** [sabeechen/hassio-google-drive-backup#73]
Please add some information about your configuration and the problem you ran into here. More info really helps speed up debugging, and if you don't make it clear whats happening you're much more likely to get snarky comment from the dev before he helps.  Remember that its just one guy back here doing all of this and he's not *really* under any obligation to put up with your shit if you're disrespectful.  If english isn't your first language, don't sweat it.  Just try to be clear and I'll do the same for you.  Some things you might consider including:
 * What were you doing when the problem happened?
 * A screenshot if its something visual.
 * What configuration options are you using with the add-on?
 * What logs is the add-on printing out?  You can see the detailed logs by clicking "Logs" at the top right of the web-UI.
 * Are there any problematic logs from the Hassio supervisor?  You can get to them from the Home Assistant Interface from "Hass.io" > "System" > "System Log"
 

Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 102, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 142, in sync
    upload.addSource(self.dest.save(upload, self.source.read(upload)))
  File "/app/backup/drivesource.py", line 114, in save
    for progress in self.drivebackend.create(bytes, file_metadata, MIME_TYPE):
  File "/app/backup/driverequests.py", line 188, in create
    partial = self.retryRequest("PUT", location, headers=headers, data=data, patch_url=False)
  File "/app/backup/driverequests.py", line 241, in retryRequest
    raise e
  File "/app/backup/driverequests.py", line 230, in retryRequest
    response = self._request_client.request(method, url, headers=send_headers, json=json, timeout=self.config.get(Setting.GOOGLE_DRIVE_TIMEOUT_SECONDS), data=data, stream=stream)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out',))

An unexpected error occurred: ('Connection aborted.', timeout('The write operation timed out',))

**Comment by PrathikGopal** [comment]
Will update with more details , closing for now
