### ISSUE TITLE
Crash on starup, json parsing

### ISSUE THREAD

**Issue by anverx** [sabeechen/hassio-google-drive-backup#742]
I've reset configuration to default in case config was corrupt but no change.
Which file is causing this?
version: 0.109.1

```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/lib/python3.10/site-packages/aiorun.py:221> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aiorun.py", line 231, in new_coro
    await coro
  File "/app/backup/__main__.py", line 11, in main
    await Injector([BaseModule(), MainModule()]).get(Starter).start()
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 785, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 966, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 999, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1047, in args_to_inject
    instance: Any = self.get(interface)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 785, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 358, in get
    return [i for provider in self._providers for i in provider.get(injector)]
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 358, in <listcomp>
    return [i for provider in self._providers for i in provider.get(injector)]
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 302, in get
    return injector.call_with_injection(self._callable)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 999, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1047, in args_to_inject
    instance: Any = self.get(interface)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 785, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 966, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 999, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1047, in args_to_inject
    instance: Any = self.get(interface)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 966, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 999, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1047, in args_to_inject
    instance: Any = self.get(interface)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 785, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 966, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1008, in call_with_injection
    return callable(*full_args, **dependencies)
  File "/app/backup/util/data_cache.py", line 46, in __init__
    self._load()
  File "/app/backup/util/data_cache.py", line 53, in _load
    self._data = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jgruiz68** [comment]
Any idea what's causing this? I have the same issue.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 783, in get
    return self._context[key]
KeyError: <class 'backup.util.data_cache.DataCache'>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aiorun.py", line 237, in new_coro
    await coro
  File "/app/backup/__main__.py", line 11, in main
    await Injector([BaseModule(), MainModule()]).get(Starter).start()
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 785, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 966, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 999, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1047, in args_to_inject
    instance: Any = self.get(interface)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 785, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 358, in get
    return [i for provider in self._providers for i in provider.get(injector)]
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 358, in <listcomp>
    return [i for provider in self._providers for i in provider.get(injector)]
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 302, in get
    return injector.call_with_injection(self._callable)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 999, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1047, in args_to_inject
    instance: Any = self.get(interface)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 785, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 966, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 999, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1047, in args_to_inject
    instance: Any = self.get(interface)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 966, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 999, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1047, in args_to_inject
    instance: Any = self.get(interface)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 785, in get
    provider = InstanceProvider(provider.get(self.injector))
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 966, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1008, in call_with_injection
    return callable(*full_args, **dependencies)
  File "/app/backup/util/data_cache.py", line 46, in __init__
    self._load()
  File "/app/backup/util/data_cache.py", line 53, in _load
    self._data = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 333 column 26 (char 12288)
```

**Comment by sabeechen** [comment]
Sorry it took me while to get back to you guys on this.

This is very likely caused by hard drive (eg SD Card) corruption.  It is most likely that either:

- The machine was powered off while writing its state to disk
- The SD card has bad sectors.

Its worth considering using a new SD card (If you're using a pi), though I can't say for certain the SD card is bad.  The only way to recover is to reinstall the addon (don't restore it from a backup).

In the future the addon will write to several files and use whichever one isn't corrupted to avoid this problem, but I haven't had time to implement that feature yet.

**Comment by anverx** [comment]
Hi @sabeechen in my case it was likely the first cause, i've had a few sponatneous reboots on the host, reason still unknown.  Reinstallation has helped and a new backup is in progress.  Will be huge anexiety relief once it's complete.

**Comment by sabeechen** [comment]
I see users report this error quite often, and I think I might have found the cause.  Obviously SD card corruption could cause this, as well as if the machine is powered off at just the right time, but I think the most common cause is simply _running out of disk space_.

Here is what I think happens:

- HA attempts to create an unusually large backup
- The backup fails because it runs out of disk space
- (some time later) This addon attempts to save its configuration to disk.
  - Saving config involves overwriting the config file's contents. Because the system is out of space its able to truncate the file but unable to create a new one, so the config file is empty.
- (some time later) The system reboots
- Temporary files created from the backup get deleted, so there is free disk space again.
- The addon attempts to run and chokes on its empty config files.

Version 0.110.1, which I just released, implements writing its config to more than one files.  This ensures at least one copy of the config is available if one of them gets corrupted.  I believe this will resolve the "power off" and "no-free-disk" types of corruption as well as making SD card corruption very unlikely because it would have to affect both file sectors at the same time.

If you continue to run into problems after installing the new version, please let me know.  If you're already getting the error (ie your config is already corrupt) you'll need to remove and reinstall the addon to get past the error.
