### ISSUE TITLE
Backups Add-on no longer syncing (despite no other changes to configuration)

### ISSUE THREAD

**Issue by mattyp26** [sabeechen/hassio-google-drive-backup#752]
My instance of Home Assistant has essentially been in a live state and running away in the background, with no alterations to the configuration recently - as such I have not opened the instance in a few weeks.

Upon opening today just to double check all was well, i noticed that the Google Drive backups add-on has not synced since 4th November (mean to sync weekly) - and will not let me sync manually.

Below screenshot taken from the UI:
![image](https://user-images.githubusercontent.com/108742765/203068105-f9a0da7b-9370-4702-8cf0-1167421f1d1c.png)
I have followed the re-authentication process, but no change.

Below is a copy of the details from the report issue screen - any support you can provide would be much appreciated.

###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.108.4`
 Home Assistant Version: `2022.10.5`
 Supervisor Version: `2022.10.2`
 Supervisor Channel: `stable`
 Hassos Version: `9.2`
 Docker Version: `20.10.17`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2022-11-21T13:27:16.434590+00:00`
 Timezone: `Europe/London`
 Failure Time: `2022-11-21T13:27:02.534309+00:00`
 Last Good Sync: `2022-11-21T13:27:12.574444+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:177 (_sync)
  addon/backup/model/model.py:177 (sync)
  addon/backup/model/model.py:285 (_syncBackups)
  addon/backup/drive/drivesource.py:118 (get)
  addon/backup/drive/drivesource.py:269 (getFolderId)
  addon/backup/drive/folderfinder.py:65 (get)
  addon/backup/drive/folderfinder.py:117 (_readFolderId)
  addon/backup/drive/folderfinder.py:158 (_verify)
  addon/backup/drive/driverequests.py:165 (get)
  addon/backup/drive/driverequests.py:356 (retryRequest)
  addon/backup/drive/driverequests.py:95 (_getHeaders)
  addon/backup/drive/driverequests.py:154 (getToken)
  addon/backup/creds/exchanger.py:85 (refresh)
  addon/backup/creds/exchanger.py:159 (_refresh_default)
backup.exceptions.exceptions.CredRefreshMyError: Timed out communicating with habackup.io

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 5,
        "retained": 1,
        "deletable": 4,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2022-11-04T18:16:13Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 28,
        "detail": "",
        "size": "121.9 MB",
        "ignored_size": "69.1 MB",
        "free_space": "95.2 GB"
    },
    "GoogleDrive": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 10,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "",
        "size": "0.0 B",
        "ignored_size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 10,
    "Setting.BACKUP_TIME_OF_DAY": "02:00",
    "Setting.SEND_ERROR_REPORTS": true,
    "Setting.MAXIMUM_UPLOAD_CHUNK_BYTES": 104857600.0
}
 ```
 ###### Addon Logs:
 ```
 11-21 13:26:19 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/e837796b/info
11-21 13:26:19 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/c72358a6/info
11-21 13:26:19 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/4fc4c0f6/info
11-21 13:26:19 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/0fe88a52/info
11-21 13:26:19 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/11cbd91e/info
11-21 13:26:19 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/65cf317a/info
11-21 13:26:19 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/525358a7/info
11-21 13:26:19 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/9f4ddb6d/info
11-21 13:26:19 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/4e7a52b8/info
11-21 13:26:19 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
11-21 13:26:29 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
11-21 13:26:40 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
11-21 13:26:40 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
11-21 13:26:40 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
11-21 13:26:40 INFO [backup.model.coordinator] I'll try again right now
11-21 13:26:41 DEBUG [backup.model.syncer] Sync requested by Coordinator
11-21 13:26:41 INFO [backup.model.coordinator] Syncing Backups
11-21 13:26:41 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
11-21 13:26:41 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
11-21 13:26:41 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
11-21 13:26:51 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
11-21 13:27:02 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
11-21 13:27:02 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
11-21 13:27:02 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
11-21 13:27:02 INFO [backup.model.coordinator] I'll try again in 10 seconds
11-21 13:27:12 DEBUG [backup.model.syncer] Sync requested by Coordinator
11-21 13:27:12 INFO [backup.model.coordinator] Syncing Backups
11-21 13:27:12 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
11-21 13:27:12 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
11-21 13:27:12 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
 ```
 ###### Supervisor Logs:
 ```
 [32m22-11-21 13:26:18 INFO (MainThread) [supervisor.api.middleware.security] /backups/efd75455/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:18 INFO (MainThread) [supervisor.api.middleware.security] /backups/34fccf68/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:18 INFO (MainThread) [supervisor.api.middleware.security] /backups/d5573d27/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:18 INFO (MainThread) [supervisor.api.middleware.security] /backups/a3630e6c/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:18 INFO (MainThread) [supervisor.api.middleware.security] /backups/7c7503fa/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/62fe989f/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/58dbe24b/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/d9ea8b44/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/cc0f7963/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/db13b5cb/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/10a0640c/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/6d5c28aa/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/e837796b/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/c72358a6/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/4fc4c0f6/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/0fe88a52/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/11cbd91e/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/65cf317a/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/525358a7/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/9f4ddb6d/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups/4e7a52b8/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:41 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:26:41 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[33m22-11-21 13:27:02 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad5fbb80>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m22-11-21 13:27:07 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faf791120>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m22-11-21 13:27:12 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fab7a95d0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[32m22-11-21 13:27:12 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:27:12 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-21 13:27:16 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 [31m2022-11-21 12:54:47.026 ERROR (MainThread) [kasa.discover] Got error: [Errno 101] Network unreachable[0m
[31m2022-11-21 12:54:47.029 ERROR (MainThread) [kasa.discover] Got error: [Errno 101] Network unreachable[0m
[31m2022-11-21 12:59:52.171 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 457, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 511, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again][0m
[31m2022-11-21 13:09:47.022 ERROR (MainThread) [kasa.discover] Got error: [Errno 101] Network unreachable[0m
[31m2022-11-21 13:09:47.025 ERROR (MainThread) [kasa.discover] Got error: [Errno 101] Network unreachable[0m
[31m2022-11-21 13:09:47.028 ERROR (MainThread) [kasa.discover] Got error: [Errno 101] Network unreachable[0m
[31m2022-11-21 13:09:52.170 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 457, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 511, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again][0m
[31m2022-11-21 13:19:52.174 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 457, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 511, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again][0m
[31m2022-11-21 13:24:47.022 ERROR (MainThread) [kasa.discover] Got error: [Errno 101] Network unreachable[0m
[31m2022-11-21 13:24:47.027 ERROR (MainThread) [kasa.discover] Got error: [Errno 101] Network unreachable[0m
[31m2022-11-21 13:24:47.029 ERROR (MainThread) [kasa.discover] Got error: [Errno 101] Network unreachable[0m

 ```

**Comment by mattyp26** [comment]
sorted after hard reboot of Pi
