### ISSUE TITLE
Still have a. Google drive backup problem 

### ISSUE THREAD

**Issue by michaelthompson1991** [sabeechen/hassio-google-drive-backup#758]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.109.2`
 Home Assistant Version: `2022.11.4`
 Supervisor Version: `2022.11.2`
 Supervisor Channel: `stable`
 Hassos Version: `9.3`
 Docker Version: `20.10.18`
 Architecture: `aarch64`
 Machine: `raspberrypi3-64`
 Date: `2022-11-27T08:55:47.149446+00:00`
 Timezone: `Europe/London`
 Failure Time: `2022-11-27T08:55:12.325403+00:00`
 Last Good Sync: `2022-11-27T08:55:04.213707+00:00`
 ###### Exception:
 ```
 
  addon/backup/creds/driverequester.py:30 (request)
  addon/backup/tracing_session.py:35 (_request)
  /site-packages/aiohttp/client.py:536 (_request)
  [2 hidden frames]
  /site-packages/aiohttp/connector.py:1166 (_create_direct_connection)
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.googleapis.com:443 ssl:default [None]
Whose handling caused:
  addon/backup/model/coordinator.py:177 (_sync)
  addon/backup/model/model.py:196 (sync)
  addon/backup/model/model.py:304 (_syncBackups)
  addon/backup/drive/drivesource.py:118 (get)
  addon/backup/drive/drivesource.py:269 (getFolderId)
  addon/backup/drive/folderfinder.py:65 (get)
  addon/backup/drive/folderfinder.py:117 (_readFolderId)
  addon/backup/drive/folderfinder.py:158 (_verify)
  addon/backup/drive/driverequests.py:165 (get)
  addon/backup/drive/driverequests.py:367 (retryRequest)
  addon/backup/creds/driverequester.py:49 (request)
backup.exceptions.exceptions.GoogleCantConnect

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 8,
        "retained": 2,
        "deletable": 6,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2022-11-26T19:44:57Z",
        "max": 5,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "detail": "",
        "size": "63.1 MB",
        "ignored_size": "0.0 B",
        "free_space": "18.4 GB"
    },
    "GoogleDrive": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 5,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "",
        "size": "0.0 B",
        "ignored_size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 5,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 5,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.IGNORE_UPGRADE_BACKUPS": false,
    "Setting.DELETE_BEFORE_NEW_BACKUP": true,
    "Setting.BACKUP_TIME_OF_DAY": "00:00"
}
 ```
 ###### Addon Logs:
 ```
 11-27 08:50:04 INFO [backup.model.coordinator] I'll try again in 1(ish) minutes
11-27 08:50:07 INFO [backup.model.coordinator] Syncing Backups
11-27 08:50:07 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
11-27 08:50:07 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
11-27 08:50:07 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1uAu8Qp4BZExx4es_rwYOwZOZRZvFLALE/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
11-27 08:50:07 DEBUG [backup.creds.driverequester] Ran into trouble reaching Google Drive's servers.  We'll use alternate DNS servers on the next attempt.
11-27 08:50:07 ERROR [backup.model.coordinator] Unable to connect to www.googleapis.com
11-27 08:50:07 INFO [backup.model.coordinator] I'll try again in 2(ish) minutes
11-27 08:52:47 DEBUG [backup.model.syncer] Sync requested by Coordinator
11-27 08:52:47 INFO [backup.model.coordinator] Syncing Backups
11-27 08:52:47 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
11-27 08:52:47 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
11-27 08:52:47 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1uAu8Qp4BZExx4es_rwYOwZOZRZvFLALE/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
11-27 08:52:55 DEBUG [backup.creds.driverequester] Ran into trouble reaching Google Drive's servers.  We'll use alternate DNS servers on the next attempt.
11-27 08:52:55 ERROR [backup.model.coordinator] Unable to connect to www.googleapis.com
11-27 08:52:55 INFO [backup.model.coordinator] I'll try again in 5(ish) minutes
11-27 08:55:01 INFO [backup.model.coordinator] Syncing Backups
11-27 08:55:01 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
11-27 08:55:01 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
11-27 08:55:01 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1uAu8Qp4BZExx4es_rwYOwZOZRZvFLALE/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
11-27 08:55:01 DEBUG [backup.creds.driverequester] Ran into trouble reaching Google Drive's servers.  We'll use alternate DNS servers on the next attempt.
11-27 08:55:01 ERROR [backup.model.coordinator] Unable to connect to www.googleapis.com
11-27 08:55:01 INFO [backup.model.coordinator] I'll try again in 10(ish) minutes
11-27 08:55:04 INFO [backup.model.coordinator] Syncing Backups
11-27 08:55:04 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
11-27 08:55:04 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
11-27 08:55:04 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1uAu8Qp4BZExx4es_rwYOwZOZRZvFLALE/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
11-27 08:55:12 DEBUG [backup.creds.driverequester] Ran into trouble reaching Google Drive's servers.  We'll use alternate DNS servers on the next attempt.
11-27 08:55:12 ERROR [backup.model.coordinator] Unable to connect to www.googleapis.com
11-27 08:55:12 INFO [backup.model.coordinator] I'll try again in 21(ish) minutes
 ```
 ###### Supervisor Logs:
 ```
 [32m22-11-27 08:49:03 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:03 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:03 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:03 INFO (MainThread) [supervisor.api.middleware.security] /backups/154248d1/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:03 INFO (MainThread) [supervisor.api.middleware.security] /backups/d6880c69/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:03 INFO (MainThread) [supervisor.api.middleware.security] /backups/d73caef4/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:03 INFO (MainThread) [supervisor.api.middleware.security] /backups/bac9be85/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:03 INFO (MainThread) [supervisor.api.middleware.security] /backups/91e9714b/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:03 INFO (MainThread) [supervisor.api.middleware.security] /backups/c88b8e31/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:03 INFO (MainThread) [supervisor.api.middleware.security] /backups/9cbaa1c2/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:03 INFO (MainThread) [supervisor.api.middleware.security] /backups/2b79513a/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:12 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:12 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:22 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:22 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:50 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:50 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:56 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:49:56 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:50:07 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:50:07 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:52:47 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:52:47 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:55:01 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:55:01 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:55:04 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:55:04 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-11-27 08:55:45 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m22-11-27 08:55:47 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 [31m2022-11-27 08:35:46.956 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2022-11-27 08:36:00.715 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 457, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 511, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again][0m
[31m2022-11-27 08:37:11.977 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2022-11-27 08:38:36.998 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2022-11-27 08:40:02.021 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2022-11-27 08:41:27.048 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2022-11-27 08:42:52.064 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2022-11-27 08:44:17.085 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2022-11-27 08:45:42.109 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2022-11-27 08:46:00.714 ERROR (MainThread) [custom_components.hacs] Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again]
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 457, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
  File "/config/custom_components/hacs/base.py", line 511, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Request exception for 'https://api.github.com/rate_limit' with - Cannot connect to host api.github.com:443 ssl:default [Try again][0m
[31m2022-11-27 08:47:07.130 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2022-11-27 08:48:32.152 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2022-11-27 08:49:57.175 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2022-11-27 08:51:22.198 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2022-11-27 08:52:47.219 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2022-11-27 08:54:12.242 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2022-11-27 08:55:37.264 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m

 ```

**Comment by sabeechen** [comment]
Duplicate #756

This also looks like a bad or flaky internet connection.   Your home assistant logs are still full of errors connecting to github, weather apis, etc.

I don't intend to be rude, but how do you expect me to help you with this?  The addon needs an internet connection to do anything useful.

**Comment by michaelthompson1991** [comment]
I apologise, I’m very new to all this.I think the problem arose last night when my pi couldn’t access the internet for some reason, which I’m still trying to figure out. I’ve managed to get the backup on now and it seems to be working, I think.I’ll try everything else, I apologise for any inconvenience Sent from my iPhoneOn 27 Nov 2022, at 15:23, Stephen Beechen ***@***.***> wrote:﻿
Duplicate #756
This also looks like a bad or flaky internet connection.   Your home assistant logs are still full of errors connecting to github, weather apis, etc.
I don't intend to be rude, but how do you expect me to help you with this?  The addon needs an internet connection to do anything useful.
