### ISSUE TITLE
Google drive Returned an Unexpected Response

### ISSUE THREAD

**Issue by felisida** [sabeechen/hassio-google-drive-backup#763]
Copy the info from the previous page here
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.109.2`
 Home Assistant Version: `2022.11.5`
 Supervisor Version: `2022.11.2`
 Supervisor Channel: `stable`
 Hassos Version: `9.3`
 Docker Version: `20.10.18`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2022-12-05T09:07:03.529880+00:00`
 Timezone: `Europe/Rome`
 Failure Time: `2022-12-05T09:06:57.279397+00:00`
 Last Good Sync: `2022-12-05T09:06:32.570216+00:00`
 ###### Exception:
 ```
 
  addon/backup/creds/driverequester.py:30 (request)
  addon/backup/tracing_session.py:35 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ClientOSError: [Errno 1] [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2548)
Whose handling caused:
  addon/backup/model/coordinator.py:177 (_sync)
  addon/backup/model/model.py:243 (sync)
  addon/backup/drive/drivesource.py:202 (save)
  addon/backup/drive/driverequests.py:295 (create)
  addon/backup/drive/driverequests.py:367 (retryRequest)
  addon/backup/creds/driverequester.py:65 (request)
backup.exceptions.exceptions.GoogleUnexpectedError

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 1,
        "retained": 0,
        "deletable": 1,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2022-12-05T04:35:08Z",
        "max": 5,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "detail": "",
        "size": "623.5 MB",
        "ignored_size": "0.0 B",
        "free_space": "855.3 GB"
    },
    "GoogleDrive": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 10,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "servizioprenotazione@gmail.com",
        "size": "0.0 B",
        "ignored_size": "0.0 B",
        "free_space": "15.0 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 5,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 10,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.EXCLUDE_FOLDERS": "media",
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 12-05 09:58:50 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:177 (_sync)
  addon/backup/model/model.py:243 (sync)
  addon/backup/drive/drivesource.py:202 (save)
  addon/backup/drive/driverequests.py:295 (create)
  addon/backup/drive/driverequests.py:367 (retryRequest)
  addon/backup/creds/driverequester.py:30 (request)
  addon/backup/tracing_session.py:35 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe

12-05 09:58:50 INFO [backup.model.coordinator] I'll try again in an hour
12-05 09:58:57 INFO [backup.debugworker] Sending error report (see settings to disable)
12-05 10:06:27 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/self/info
12-05 10:06:27 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/info
12-05 10:06:27 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/core/info
12-05 10:06:27 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
12-05 10:06:27 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons
12-05 10:06:32 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/self/options
12-05 10:06:32 INFO [backup.model.coordinator] Syncing Backups
12-05 10:06:32 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
12-05 10:06:32 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
12-05 10:06:32 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/11fSnKeBY1rskvkR8Prl5y3KwBi1b-JL6/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
12-05 10:06:32 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota%2Cuser
12-05 10:06:33 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%2711fSnKeBY1rskvkR8Prl5y3KwBi1b-JL6%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
12-05 10:06:33 INFO [backup.drive.drivesource] Uploading '5 dicembre 2022' to Google Drive
12-05 10:06:33 DEBUG [backup.drive.driverequests] Attempting to resume a previously failed upload where we left off
12-05 10:06:33 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdtkwYLKlDgzURDYVhvM80B3EV9clSuJwpF9y1FXh91sEh55NNaBYaRW1p5gPGnECSYe_3ijO2ykGpEY_pDsC8wtWg
12-05 10:06:33 DEBUG [backup.drive.driverequests] Resuming upload at byte 85458944 of 653793280
12-05 10:06:33 DEBUG [backup.drive.driverequests] Sending 262144 bytes to Google Drive
12-05 10:06:33 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdtkwYLKlDgzURDYVhvM80B3EV9clSuJwpF9y1FXh91sEh55NNaBYaRW1p5gPGnECSYe_3ijO2ykGpEY_pDsC8wtWg
12-05 10:06:33 DEBUG [backup.drive.drivesource] Uploading 5 dicembre 2022 13.11%
12-05 10:06:33 DEBUG [backup.drive.driverequests] Sending 9437184 bytes to Google Drive
12-05 10:06:33 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdtkwYLKlDgzURDYVhvM80B3EV9clSuJwpF9y1FXh91sEh55NNaBYaRW1p5gPGnECSYe_3ijO2ykGpEY_pDsC8wtWg
12-05 10:06:37 DEBUG [backup.drive.drivesource] Uploading 5 dicembre 2022 14.55%
12-05 10:06:37 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
12-05 10:06:37 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdtkwYLKlDgzURDYVhvM80B3EV9clSuJwpF9y1FXh91sEh55NNaBYaRW1p5gPGnECSYe_3ijO2ykGpEY_pDsC8wtWg
12-05 10:06:57 ERROR [backup.model.coordinator] Google gave an unexpected response
12-05 10:06:57 INFO [backup.model.coordinator] I'll try again in an hour
12-05 10:06:58 INFO [backup.debugworker] Sending error report (see settings to disable)
 ```
 ###### Supervisor Logs:
 ```
 [33m22-12-05 09:49:36 WARNING (MainThread) [supervisor.addons.options] Unknown option 'langid_fix' for Network UPS Tools (a0d7b954_nut)[0m
[33m22-12-05 09:49:36 WARNING (MainThread) [supervisor.addons.options] Unknown option 'desc' for Network UPS Tools (a0d7b954_nut)[0m
[33m22-12-05 09:54:38 WARNING (MainThread) [supervisor.addons.options] Unknown option 'langid_fix' for Network UPS Tools (a0d7b954_nut)[0m
[33m22-12-05 09:54:38 WARNING (MainThread) [supervisor.addons.options] Unknown option 'desc' for Network UPS Tools (a0d7b954_nut)[0m
[32m22-12-05 09:58:24 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-12-05 09:58:24 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-12-05 09:58:25 INFO (MainThread) [supervisor.api.middleware.security] /backups/7c66597a/download access from cebe7a76_hassio_google_drive_backup[0m
[32m22-12-05 09:58:25 INFO (MainThread) [supervisor.api.backups] Downloading backup 7c66597a[0m
[32m22-12-05 09:58:25 INFO (MainThread) [supervisor.api.middleware.security] /backups/7c66597a/download access from cebe7a76_hassio_google_drive_backup[0m
[32m22-12-05 09:58:25 INFO (MainThread) [supervisor.api.backups] Downloading backup 7c66597a[0m
[33m22-12-05 09:59:40 WARNING (MainThread) [supervisor.addons.options] Unknown option 'langid_fix' for Network UPS Tools (a0d7b954_nut)[0m
[33m22-12-05 09:59:40 WARNING (MainThread) [supervisor.addons.options] Unknown option 'desc' for Network UPS Tools (a0d7b954_nut)[0m
[33m22-12-05 10:04:42 WARNING (MainThread) [supervisor.addons.options] Unknown option 'langid_fix' for Network UPS Tools (a0d7b954_nut)[0m
[33m22-12-05 10:04:42 WARNING (MainThread) [supervisor.addons.options] Unknown option 'desc' for Network UPS Tools (a0d7b954_nut)[0m
[33m22-12-05 10:06:17 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m22-12-05 10:06:20 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session cd8e8f34753bf5c6f9d338dfc5a8d00d8f6ef09ba04575114ebbf2dbda60f6f001d8353d05e83c643cc94f68f6693b074fe72ce79a86886a33abb7f41102b35c[0m
[33m22-12-05 10:06:20 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session e0f5ee82bfbfbb80bb4fe6cabcd71f289ebba9565befceec34be61b53fb5ed85e94dd37594c8393e52cdd43406a07a32aac4bb27cd58c4b0bc9ff69761982b46[0m
[33m22-12-05 10:06:20 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session f77bd32cf1a86a74bc2bc6a0afe830b7ad4d4e89b88be0e44bb87bd1d5ed3975723c91caa8053fa33a1b094e1a20af8087ccc07624dbf863d9e8cb790803d9e7[0m
[32m22-12-05 10:06:27 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-12-05 10:06:27 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-12-05 10:06:27 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup[0m
[32m22-12-05 10:06:32 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-12-05 10:06:32 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-12-05 10:06:33 INFO (MainThread) [supervisor.api.middleware.security] /backups/7c66597a/download access from cebe7a76_hassio_google_drive_backup[0m
[32m22-12-05 10:06:33 INFO (MainThread) [supervisor.api.backups] Downloading backup 7c66597a[0m
[32m22-12-05 10:06:33 INFO (MainThread) [supervisor.api.middleware.security] /backups/7c66597a/download access from cebe7a76_hassio_google_drive_backup[0m
[32m22-12-05 10:06:33 INFO (MainThread) [supervisor.api.backups] Downloading backup 7c66597a[0m
[32m22-12-05 10:07:02 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m22-12-05 10:07:03 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.86.164', port=8080): Max retries exceeded with url: /callback/list?token=Bn3FDt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f58f9d05db0>, 'Connection to 192.168.86.164 timed out. (connect timeout=10)'))[0m
[33m2022-12-05 09:58:41.221 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.studio or it is/they are currently not available[0m
[33m2022-12-05 09:58:44.487 WARNING (Thread-16) [pychromecast.socket_client] [Nest Soggiorno(192.168.86.188):8009] Heartbeat timeout, resetting connection[0m
[31m2022-12-05 09:58:51.762 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'[0m
[33m2022-12-05 10:01:33.060 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.studio or it is/they are currently not available[0m
[33m2022-12-05 10:03:16.310 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities media_player.studio or it is/they are currently not available[0m
[31m2022-12-05 10:06:20.572 ERROR (MainThread) [homeassistant.components.hassio.handler] /ingress/validate_session return code 401[0m
[31m2022-12-05 10:06:20.685 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/validate_session - [0m
[31m2022-12-05 10:06:20.692 ERROR (MainThread) [homeassistant.components.hassio.handler] /ingress/validate_session return code 401[0m
[31m2022-12-05 10:06:20.694 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/validate_session - [0m
[31m2022-12-05 10:06:20.696 ERROR (MainThread) [homeassistant.components.hassio.handler] /ingress/validate_session return code 401[0m
[31m2022-12-05 10:06:20.696 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/validate_session - [0m
[31m2022-12-05 10:06:47.019 ERROR (SyncWorker_0) [custom_components.vimar.vimarlink.vimarlink] HTTP timeout occurred[0m
[31m2022-12-05 10:06:47.021 ERROR (MainThread) [custom_components.vimar] Error fetching vimar data: Error communicating with API: cannot unpack non-iterable NoneType object[0m
[33m2022-12-05 10:06:49.145 WARNING (Thread-17) [pychromecast.socket_client] [Google Ospiti(192.168.86.212):8009] Heartbeat timeout, resetting connection[0m
[31m2022-12-05 10:06:51.003 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching RM4 Pro (RM4 pro at 192.168.86.165) data: [Errno -4000] Network timeout: No response received within 10s[0m
[33m2022-12-05 10:06:51.010 WARNING (MainThread) [custom_components.smartthinq_sensors.wideq.device] Connection to ThinQ failed. Network connection error - Device: Frigo[0m
[33m2022-12-05 10:06:53.710 WARNING (Thread-15) [pychromecast.socket_client] [Camera matrimoniale(192.168.86.184):8009] Heartbeat timeout, resetting connection[0m

 ```

**Comment by sabeechen** [comment]
Sorry it took me a while to get back to you, I've been out of town.  I've seen this error come up a few times before, though no one has ever been able to figure out what causes it.  Some good theories are:

- The clock on the computer is off by more than a few minutes (this can cause a lot of SSL authentication problems)
- Unreliable internet connection.  If you're using anything like a VPN, HTTP Proxy or network wide adblock consider disabling it and try again.
- File system corruption (eg from power loss).

Most of the people who have run into this were able to resolve it by rebooting the machine running Home Assistant.  Please let me know if any of this works for you.

**Comment by sabeechen** [comment]
Consolidating issues showing this same error.

Duplicate #790
