### ISSUE TITLE
Unable to back up to shared folder

### ISSUE THREAD

**Issue by marc115uk** [sabeechen/hassio-google-drive-backup#769]
Have been backing up to a google shard folder for around a year, just recently getting the following error. Have tried deleting app and reinstalling then re authorising, have tried different google accounts with different shared folders all producing the same error 

###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.109.2`
 Home Assistant Version: `2022.12.8`
 Supervisor Version: `2022.11.2`
 Supervisor Channel: `stable`
 Hassos Version: `9.4`
 Docker Version: `20.10.19`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2022-12-27T16:15:08.840914+00:00`
 Timezone: `Europe/London`
 Failure Time: `2022-12-27T15:40:23.952215+00:00`
 Last Good Sync: `2022-12-27T15:39:17.998784+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:177 (_sync)
  addon/backup/model/model.py:243 (sync)
  addon/backup/drive/drivesource.py:202 (save)
  addon/backup/drive/driverequests.py:261 (create)
  addon/backup/drive/driverequests.py:379 (retryRequest)
  addon/backup/util/backoff.py:37 (backoff)
  addon/backup/drive/driverequests.py:367 (retryRequest)
  addon/backup/creds/driverequester.py:39 (request)
backup.exceptions.exceptions.GoogleRateLimitError

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 6,
        "retained": 0,
        "deletable": 6,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2022-12-27T03:20:15Z",
        "max": 10,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 6,
        "detail": "",
        "size": "29.6 GB",
        "ignored_size": "360.5 MB",
        "free_space": "361.0 GB"
    },
    "GoogleDrive": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 10,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "REDACTED",
        "size": "0.0 B",
        "ignored_size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 10,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 10,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.BACKUP_TIME_OF_DAY": "03:00",
    "Setting.SPECIFY_BACKUP_FOLDER": true,
    "Setting.BACKUP_PASSWORD": "REDACTED"
}
 ```
 ###### Addon Logs:
 ```
 12-27 14:38:28 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
12-27 14:38:29 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 16 seconds
12-27 14:38:45 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
12-27 14:38:45 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 32 seconds
12-27 14:39:17 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
12-27 14:39:17 ERROR [backup.model.coordinator] The addon has made too many requests to Google Drive, and will back off
12-27 14:39:17 INFO [backup.model.coordinator] I'll try again in an hour
12-27 15:39:17 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-27 15:39:17 INFO [backup.model.coordinator] Syncing Backups
12-27 15:39:18 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
12-27 15:39:18 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
12-27 15:39:18 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
12-27 15:39:18 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1jTbY6E8Oo-Ria7iuaMazqW5P_UgVaxnv/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
12-27 15:39:18 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota%2Cuser
12-27 15:39:18 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271jTbY6E8Oo-Ria7iuaMazqW5P_UgVaxnv%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
12-27 15:39:19 INFO [backup.drive.drivesource] Uploading 'Full Backup 2022-12-27 03:20:14' to Google Drive
12-27 15:39:19 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
12-27 15:39:19 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
12-27 15:39:19 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 2 seconds
12-27 15:39:21 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
12-27 15:39:21 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 4 seconds
12-27 15:39:25 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
12-27 15:39:26 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 8 seconds
12-27 15:39:34 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
12-27 15:39:34 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 16 seconds
12-27 15:39:50 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
12-27 15:39:51 ERROR [backup.drive.driverequests] The addon has made too many requests to Google Drive, and will back off: we'll retry in 32 seconds
12-27 15:40:23 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
12-27 15:40:23 ERROR [backup.model.coordinator] The addon has made too many requests to Google Drive, and will back off
12-27 15:40:23 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m22-12-27 16:08:21 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m22-12-27 16:08:21 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER[0m
[32m22-12-27 16:08:21 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER[0m
[32m22-12-27 16:08:21 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m22-12-27 16:08:21 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM[0m
[32m22-12-27 16:08:21 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m
[32m22-12-27 16:08:21 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m22-12-27 16:08:21 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m22-12-27 16:08:22 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m22-12-27 16:08:22 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m22-12-27 16:08:22 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m22-12-27 16:09:09 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt'[0m
[32m22-12-27 16:09:09 INFO (MainThread) [supervisor.auth] Successful login for 'mqtt'[0m
[32m22-12-27 16:11:38 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_user[0m
[32m22-12-27 16:11:38 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_password[0m
[32m22-12-27 16:11:38 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_user[0m
[32m22-12-27 16:11:38 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_password[0m
[32m22-12-27 16:12:47 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m22-12-27 16:12:47 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository[0m
[32m22-12-27 16:12:47 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m22-12-27 16:12:47 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/MikeJMcGuire/HASSAddons repository[0m
[32m22-12-27 16:12:47 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m22-12-27 16:12:48 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/CoolKit-Technologies/ha-addon repository[0m
[32m22-12-27 16:12:48 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m22-12-27 16:12:51 INFO (MainThread) [supervisor.store] Loading add-ons from store: 78 all - 0 new - 0 remove[0m
[32m22-12-27 16:12:51 INFO (MainThread) [supervisor.store] Loading add-ons from store: 78 all - 0 new - 0 remove[0m
[32m22-12-27 16:14:31 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt'[0m
[32m22-12-27 16:14:32 INFO (MainThread) [supervisor.auth] Successful login for 'mqtt'[0m
[32m22-12-27 16:15:08 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/formulaone_api/formulaonesensor.py", line 60, in update
    self.set_state()
  File "/config/custom_components/formulaone_api/lastresultsensor.py", line 31, in set_state
    all_attr = self.get_race_data()
  File "/config/custom_components/formulaone_api/lastresultsensor.py", line 19, in get_race_data
    races = f1.last_result().json
  File "/config/custom_components/formulaone_api/ergast.py", line 39, in json
    return self._json.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)[0m
[33m2022-12-27 16:15:16.711 WARNING (MainThread) [homeassistant.components.esphome] Name of device outside-fre changed to outside-freezer, potentially due to IP reassignment[0m

 ```

**Comment by sabeechen** [comment]
It looks like Google has decided to rate limit you, the reasons for this could be many, but the most common are:
- You are accessing google services through a VPN and someone else on that VPN (ie someone having the same IP from Google's perspective) is abusing their services and getting everyone else blocked.
- Your account is "hot" for another reason (eg you have a lot of other services writing to your Google Drive account).  Google Drive has a rather small global write limit per account.

Could either of these apply?

**Comment by sabeechen** [comment]
I discovered in #772 that Google was globally rate limiting all users of this project for some periods of the day, which is very likely the problem you were seeing.  I just got Google to back off (they approved a request to increase my quota), are you still seeing this issue if you ask the addon to sync now?

**Comment by sabeechen** [comment]
I'm going to close this issue for now, but if you think there is something else I can help with please reopen and let me know.
