### ISSUE TITLE
Issue syncing to GDrive, Timed out communicating with habackup.io

### ISSUE THREAD

**Issue by rudma** [sabeechen/hassio-google-drive-backup#774]
Sync stopped working on December 27th. Tried reauthenticating, but that didn't solve the problem.

###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.109.2`
 Home Assistant Version: `2022.12.8`
 Supervisor Version: `2022.12.1`
 Supervisor Channel: `stable`
 Hassos Version: `9.4`
 Docker Version: `20.10.19`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2023-01-03T08:30:15.902581+00:00`
 Timezone: `Europe/Amsterdam`
 Failure Time: `2023-01-03T08:29:53.826671+00:00`
 Last Good Sync: `2023-01-03T08:29:32.100210+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:177 (_sync)
  addon/backup/model/model.py:196 (sync)
  addon/backup/model/model.py:304 (_syncBackups)
  addon/backup/drive/drivesource.py:118 (get)
  addon/backup/drive/drivesource.py:269 (getFolderId)
  addon/backup/drive/folderfinder.py:65 (get)
  addon/backup/drive/folderfinder.py:117 (_readFolderId)
  addon/backup/drive/folderfinder.py:158 (_verify)
  addon/backup/drive/driverequests.py:165 (get)
  addon/backup/drive/driverequests.py:356 (retryRequest)
  addon/backup/drive/driverequests.py:95 (_getHeaders)
  addon/backup/drive/driverequests.py:154 (getToken)
  addon/backup/creds/exchanger.py:85 (refresh)
  addon/backup/creds/exchanger.py:159 (_refresh_default)
backup.exceptions.exceptions.CredRefreshMyError: Timed out communicating with habackup.io

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 5,
        "retained": 0,
        "deletable": 5,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2022-12-31T10:53:13Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 10,
        "detail": "",
        "size": "214.7 MB",
        "ignored_size": "225.4 MB",
        "free_space": "19.6 GB"
    },
    "GoogleDrive": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2022-12-27T14:35:11Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "rudi.maassen@gmail.com",
        "size": "171.2 MB",
        "ignored_size": "0.0 B",
        "free_space": "54.8 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.DELETE_BEFORE_NEW_BACKUP": true,
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 01-03 08:08:22 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
01-03 08:08:22 INFO [backup.model.coordinator] I'll try again in an hour
01-03 09:08:22 DEBUG [backup.model.syncer] Sync requested by Coordinator
01-03 09:08:22 INFO [backup.model.coordinator] Syncing Backups
01-03 09:08:22 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
01-03 09:08:23 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
01-03 09:08:23 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
01-03 09:08:27 WARNING [backup.creds.exchanger] Unable to reach token1.habackup.io, trying alternate server(s)...
01-03 09:08:38 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
01-03 09:08:38 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
01-03 09:08:38 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
01-03 09:08:38 INFO [backup.model.coordinator] I'll try again in an hour
01-03 09:28:32 INFO [backup.model.coordinator] Syncing Backups
01-03 09:28:32 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
01-03 09:28:32 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
01-03 09:28:32 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
01-03 09:28:42 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
01-03 09:28:53 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
01-03 09:28:53 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
01-03 09:28:53 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
01-03 09:28:53 INFO [backup.model.coordinator] I'll try again in an hour
01-03 09:29:32 INFO [backup.model.coordinator] Syncing Backups
01-03 09:29:32 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
01-03 09:29:32 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
01-03 09:29:32 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
01-03 09:29:42 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
01-03 09:29:53 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
01-03 09:29:53 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
01-03 09:29:53 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
01-03 09:29:53 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [33m23-01-03 09:23:07 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2f97880>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:23:12 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2f979a0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:23:17 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1b064a0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:24:07 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1b062c0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:24:12 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1bb2e60>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:24:17 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1b58130>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:25:07 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1b46020>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:25:12 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1b45810>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:25:17 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1bdb5e0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:26:07 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1b45360>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:26:12 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1b46590>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:26:17 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1b44040>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:27:07 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fae248940>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:27:12 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1bc7c40>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:27:17 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1b44790>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:28:07 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1bed390>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:28:12 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb21e5060>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:28:17 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb2f960e0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[32m23-01-03 09:28:32 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-01-03 09:28:32 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[33m23-01-03 09:29:07 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1bc48e0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:29:12 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1b461d0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:29:17 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1bc5e40>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[32m23-01-03 09:29:32 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-01-03 09:29:32 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-01-03 09:29:40 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[33m23-01-03 09:30:07 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1bed000>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-01-03 09:30:12 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb30e9630>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[32m23-01-03 09:30:15 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/usr/local/lib/python3.10/site-packages/forecast_solar/__init__.py", line 148, in estimate
    data = await self._request(
  File "/usr/local/lib/python3.10/site-packages/forecast_solar/__init__.py", line 77, in _request
    raise ForecastSolarConnectionError(
forecast_solar.exceptions.ForecastSolarConnectionError: Error while resolving Forecast.Solar API address[0m
[31m2023-01-03 09:28:34.329 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m
[31m2023-01-03 09:29:07.592 ERROR (MainThread) [homeassistant.components.forecast_solar] Unexpected error fetching forecast_solar data: Error while resolving Forecast.Solar API address
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/forecast_solar/__init__.py", line 75, in _request
    result = await dns.query("api.forecast.solar", "A")
aiodns.error.DNSError: (11, 'Could not contact DNS servers')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/usr/local/lib/python3.10/site-packages/forecast_solar/__init__.py", line 148, in estimate
    data = await self._request(
  File "/usr/local/lib/python3.10/site-packages/forecast_solar/__init__.py", line 77, in _request
    raise ForecastSolarConnectionError(
forecast_solar.exceptions.ForecastSolarConnectionError: Error while resolving Forecast.Solar API address[0m
[31m2023-01-03 09:29:59.350 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'[0m

 ```

**Comment by lucasfr** [comment]
I am having similar issues, my last backup was on December 30th.

**Comment by sabeechen** [comment]
The addon is having trouble communicating with habackup.io, which is necessary for it to authenticate with Google Drive, but [it is up](https://isitup.org/habackup.io). 
![image](https://user-images.githubusercontent.com/21026774/210395338-8ac06f44-557f-49fe-b61f-8d5d6321c7db.png)

I can see there are communication failures in the Home Assistant logs, are you sure your Home Assistant machine isn't just having trouble with its internet connection?  If you're reaching out through a VPN or other specialized hardware, consider turning it off to test.  If you're using a custom DNS setup (eg pihole) ensure its also able to reliably resolve addresses like https://habackup.io and https://token1.habackup.io .   Reaching out to those addresses is the first thing on the internet the addon reaches out to when its ready to upload a backup.

**Comment by rudma** [comment]
Thanks @sabeechen , I saw that too. For some reason all my internet dependent devices are failing, really weird because I am not experiencing any internet issues. 
My HA is using Google DNS (8.8.8.8 and 8.8.4.4), so don't expect an issue there.
I will look into this a bit further.

**Comment by rudma** [comment]
Did a restart of my Pi and slowly all devices came online.

**Comment by lucasfr** [comment]
Upon further investigation I discovered that my issue was actually with the backup functionality of Home Assistant. 

https://github.com/home-assistant/core/issues/85219
