### ISSUE TITLE
Backup doesn’t work

### ISSUE THREAD

**Issue by tomergt45** [sabeechen/hassio-google-drive-backup#795]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.110.1`
 Home Assistant Version: `2023.2.2`
 Supervisor Version: `2023.01.1`
 Supervisor Channel: `stable`
 Hassos Version: `9.5`
 Docker Version: `20.10.22`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2023-02-07T18:37:43.948153+00:00`
 Timezone: `Asia/Jerusalem`
 Failure Time: `2023-02-07T18:37:19.481326+00:00`
 Last Good Sync: `2023-02-07T18:37:19.492276+00:00`
 Next Sync: `2023-02-07T20:37:19.481326+00:00`
 Next Backup: `2023-02-08T22:00:00.235230+00:00`
 Next Cache Warm: `2023-02-07T20:31:27.812525+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
backup.exceptions.exceptions.UserCancelledError

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 1,
        "retained": 0,
        "deletable": 1,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-02-05T22:00:00Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "detail": "",
        "size": "1.2 GB",
        "ignored_size": "0.0 B",
        "free_space": "98.4 GB"
    },
    "GoogleDrive": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "tomerh2001@gmail.com",
        "size": "0.0 B",
        "ignored_size": "0.0 B",
        "free_space": "107.1 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.DELETE_BEFORE_NEW_BACKUP": true,
    "Setting.DELETE_AFTER_UPLOAD": true,
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 02-07 20:36:35 DEBUG [backup.drive.driverequests] Sending 262144 bytes to Google Drive
02-07 20:36:35 DEBUG [backup.drive.drivesource] Uploading  0.02%
02-07 20:36:35 DEBUG [backup.drive.driverequests] Sending 4194304 bytes to Google Drive
02-07 20:36:39 DEBUG [backup.drive.drivesource] Uploading  0.36%
02-07 20:36:39 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
02-07 20:36:48 DEBUG [backup.drive.drivesource] Uploading  1.20%
02-07 20:36:48 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
02-07 20:36:58 DEBUG [backup.drive.drivesource] Uploading  2.04%
02-07 20:36:59 DEBUG [backup.drive.driverequests] Sending 9699328 bytes to Google Drive
02-07 20:37:06 DEBUG [backup.drive.drivesource] Uploading  2.82%
02-07 20:37:07 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
02-07 20:37:15 DEBUG [backup.drive.drivesource] Uploading  3.66%
02-07 20:37:15 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
02-07 20:37:19 ERROR [backup.model.coordinator] Sync was cancelled by you
02-07 20:37:19 INFO [backup.model.coordinator] I'll try again in 2 hours
02-07 20:37:19 INFO [backup.model.coordinator] Syncing Backups
02-07 20:37:19 DEBUG [backup.model.syncer] Sync requested by UI Server
02-07 20:37:20 INFO [backup.drive.drivesource] Uploading '' to Google Drive
02-07 20:37:20 DEBUG [backup.drive.driverequests] Attempting to resume a previously failed upload where we left off
02-07 20:37:20 DEBUG [backup.drive.driverequests] Resuming upload at byte 51380224 of 1244672000
02-07 20:37:20 DEBUG [backup.drive.driverequests] Sending 262144 bytes to Google Drive
02-07 20:37:21 DEBUG [backup.drive.drivesource] Uploading  4.15%
02-07 20:37:21 DEBUG [backup.drive.driverequests] Sending 5767168 bytes to Google Drive
02-07 20:37:27 DEBUG [backup.drive.drivesource] Uploading  4.61%
02-07 20:37:27 DEBUG [backup.drive.driverequests] Sending 8912896 bytes to Google Drive
02-07 20:37:28 INFO [backup.debugworker] Sending error report (see settings to disable)
02-07 20:37:34 DEBUG [backup.drive.drivesource] Uploading  5.33%
02-07 20:37:34 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
02-07 20:37:43 DEBUG [backup.drive.drivesource] Uploading  6.17%
02-07 20:37:43 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
 ```
 ###### Supervisor Logs:
 ```
 [32m23-02-07 20:33:28 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 5c53de3b_esphome[0m
[32m23-02-07 20:33:28 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 5c53de3b_esphome[0m
[32m23-02-07 20:33:31 INFO (SyncWorker_6) [supervisor.docker.interface] Stopping addon_5c53de3b_esphome application[0m
[32m23-02-07 20:33:34 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 5c53de3b_esphome[0m
[32m23-02-07 20:33:39 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_5c53de3b_esphome application[0m
[32m23-02-07 20:33:47 INFO (SyncWorker_0) [supervisor.docker.interface] Removing image homeassistant/amd64-addon-duckdns with latest and 1.15.0[0m
[32m23-02-07 20:33:47 INFO (MainThread) [supervisor.addons.addon] Removing add-on data folder /data/addons/data/core_duckdns[0m
[32m23-02-07 20:33:48 INFO (MainThread) [supervisor.addons] Add-on 'core_duckdns' successfully removed[0m
[32m23-02-07 20:33:53 INFO (SyncWorker_5) [supervisor.docker.interface] Removing image homeassistant/amd64-addon-dnsmasq with latest and 1.5.1[0m
[32m23-02-07 20:33:54 INFO (MainThread) [supervisor.addons.addon] Removing add-on data folder /data/addons/data/core_dnsmasq[0m
[32m23-02-07 20:33:54 INFO (MainThread) [supervisor.host.apparmor] Removing AppArmor profile: core_dnsmasq[0m
[32m23-02-07 20:33:54 INFO (MainThread) [supervisor.addons] Add-on 'core_dnsmasq' successfully removed[0m
[33m23-02-07 20:35:51 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[32m23-02-07 20:36:32 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-02-07 20:36:32 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-02-07 20:36:34 INFO (MainThread) [supervisor.api.middleware.security] /backups/cc47020a/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-02-07 20:36:34 INFO (MainThread) [supervisor.api.backups] Downloading backup cc47020a[0m
[32m23-02-07 20:36:52 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-02-07 20:36:53 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-02-07 20:36:53 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup[0m
[32m23-02-07 20:37:19 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-02-07 20:37:19 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-02-07 20:37:20 INFO (MainThread) [supervisor.api.middleware.security] /backups/cc47020a/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-02-07 20:37:20 INFO (MainThread) [supervisor.api.backups] Downloading backup cc47020a[0m
[32m23-02-07 20:37:20 INFO (MainThread) [supervisor.api.middleware.security] /backups/cc47020a/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-02-07 20:37:20 INFO (MainThread) [supervisor.api.backups] Downloading backup cc47020a[0m
[33m23-02-07 20:37:21 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[33m23-02-07 20:37:32 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[32m23-02-07 20:37:43 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 548, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_device_update
    raise exc
  File "/config/custom_components/smartsleep/light.py", line 171, in async_update
    self._state, self._brightness = self._data.somneo.sunset_status()
AttributeError: 'Somneo' object has no attribute 'sunset_status'[0m
[31m2023-02-07 20:36:53.134 ERROR (SyncWorker_1) [JELLYFIN.jellyfin_apiclient_python.connection_manager] connect_to_address http://192.168.86.100:8096 failed[0m
[32m2023-02-07 20:36:56.913 INFO (SyncWorker_3) [roombapy.remote_client] Connecting to 192.168.86.55, attempt 1 of 3[0m
[32m2023-02-07 20:37:02.630 INFO (Thread-133 (_thread_main)) [roombapy.roomba] Connecting to Roomba 192.168.86.55[0m
[31m2023-02-07 20:37:02.630 ERROR (Thread-133 (_thread_main)) [roombapy.roomba] Roomba 192.168.86.55 connection error, code Bad username or password[0m
[33m2023-02-07 20:37:02.632 WARNING (Thread-133 (_thread_main)) [roombapy.roomba] Unexpectedly disconnected from Roomba 192.168.86.55, code Not authorised[0m
[31m2023-02-07 20:37:04.216 ERROR (MainThread) [homeassistant.core] Connection to SABnzbd API failed: SABnzbd API request timed out[0m
[32m2023-02-07 20:37:06.917 INFO (Thread-133 (_thread_main)) [roombapy.roomba] Disconnected from Roomba 192.168.86.55[0m
[31m2023-02-07 20:37:20.887 ERROR (MainThread) [homeassistant.helpers.entity] Update for light.smartsleep_sunset fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 548, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_device_update
    raise exc
  File "/config/custom_components/smartsleep/light.py", line 171, in async_update
    self._state, self._brightness = self._data.somneo.sunset_status()
AttributeError: 'Somneo' object has no attribute 'sunset_status'[0m
[32m2023-02-07 20:37:25.385 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [139896729228704] Connection closed by client[0m
[32m2023-02-07 20:37:25.385 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [139896729228464] Connection closed by client[0m
[32m2023-02-07 20:37:43.307 INFO (MainThread) [custom_components.petkit] Update petkit device data: {'mode': 1, 'createdAt': '2022-12-22T10:33:46.000Z', 'settings': {'disturbConfig': 2, 'disturbMultiTime': [{'repeats': '1,2,3,4,5,6,7', 'time': [1320, 360]}], 'lampRingBrightness': 3, 'lampRingGoOutTime': 1440, 'lampRingLightUpTime': 0, 'lampRingSwitch': 1, 'lightConfig': 1, 'lightMultiTime': [{'repeats': '1,2,3,4,5,6,7', 'time': [0, 1440]}], 'noDisturbingEndTime': 360, 'noDisturbingStartTime': 1320, 'noDisturbingSwitch': 0, 'smartSleepTime': 3, 'smartWorkingTime': 3}, 'name': 'Water Fountain', 'id': 100031791, 'filterWarning': 0, 'lackWarning': 0, 'runStatus': 1, 'relation': {'userId': '100479189'}, 'typeCode': 4, 'type': 'W5'}[0m
[33m2023-02-07 20:37:43.533 WARNING (MainThread) [custom_components.petkit] Got petkit device detail for Water Fountain failed: {'error': {'code': 97, 'msg': 'App is out of date, please upgrade'}}[0m
[32m2023-02-07 20:37:43.534 INFO (MainThread) [custom_components.petkit] Update petkit device data: {'createdAt': '2023-01-03T10:27:52.649+0000', 'dailyFeed': {'eatAmountTotal': 106, 'realAmountTotal': 0, 'planRealAmountTotal': 0, 'eatTimes': [29598, 32541, 34061, 35257, 36352, 39172, 43834, 59730, 59933, 65638, 67380, 67503, 67855, 67998, 68177, 20580, 29152], 'planAmountTotal': 0, 'feedTimes': [0, 0, 0, 0, 0, 0, 0]}, 'name': 'Smart Pet Feeder', 'id': 100008943, 'state': 1, 'status': {'broadcast': {'duration': 5, 'start_time': 1675789414}, 'door': 0, 'wifi': {'rsq': -50, 'bssid': 'bcdf58feb5aa', 'ssid': "Tomer's Wifi"}, 'charge': 0, 'desiccantLeftDays': 0, 'runtime': 0, 'weight': 134, 'eating': 0, 'food': 2, 'pim': 1, 'batteryStatus': 0, 'feeding': 0, 'overall': 1, 'block': 0, 'desiccantTime': 0, 'ota': 0, 'batteryPower': 4}, 'desc': '下次出粮时间: 23:00', 'relation': {'userId': '100479189'}, 'type': 'D3'}[0m

 ```

**Comment by sabeechen** [comment]
From the logs here it looks like the addon is just busy uploading a backup.  Can you help me understand what isn't working?
