### ISSUE TITLE
The add-on does not back up to Google drive for 25 days

### ISSUE THREAD

**Issue by Krainer81** [sabeechen/hassio-google-drive-backup#804]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.110.1`
 Home Assistant Version: `2023.2.2`
 Supervisor Version: `2023.01.1`
 Supervisor Channel: `stable`
 Hassos Version: `9.5`
 Docker Version: `20.10.22`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2023-02-28T17:55:45.550625+00:00`
 Timezone: `Europe/Prague`
 Failure Time: `2023-02-28T16:55:51.425466+00:00`
 Last Good Sync: `2023-02-28T16:55:29.742154+00:00`
 Next Sync: `2023-02-28T18:55:51.425466+00:00`
 Next Backup: `2023-02-27T02:00:00+00:00`
 Next Cache Warm: `2259-08-27T15:14:41.432418+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:199 (sync)
  addon/backup/model/model.py:312 (_syncBackups)
  addon/backup/drive/drivesource.py:118 (get)
  addon/backup/drive/drivesource.py:269 (getFolderId)
  addon/backup/drive/folderfinder.py:63 (get)
  addon/backup/drive/folderfinder.py:113 (_readFolderId)
  addon/backup/drive/folderfinder.py:154 (_verify)
  addon/backup/drive/driverequests.py:163 (get)
  addon/backup/drive/driverequests.py:354 (retryRequest)
  addon/backup/drive/driverequests.py:94 (_getHeaders)
  addon/backup/drive/driverequests.py:152 (getToken)
  addon/backup/creds/exchanger.py:85 (refresh)
  addon/backup/creds/exchanger.py:159 (_refresh_default)
backup.exceptions.exceptions.CredRefreshMyError: Timed out communicating with habackup.io

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 12,
        "retained": 2,
        "deletable": 10,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-02-26T18:17:25Z",
        "max": 10,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 58,
        "detail": "",
        "size": "2.7 GB",
        "ignored_size": "4.5 GB",
        "free_space": "203.5 GB"
    },
    "GoogleDrive": {
        "backups": 21,
        "retained": 1,
        "deletable": 20,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-02-05T02:00:00Z",
        "max": 20,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "KrainerPetr@seznam.cz",
        "size": "4.8 GB",
        "ignored_size": "0.0 B",
        "free_space": "4.3 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 10,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 20,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.BACKUP_TIME_OF_DAY": "03:00",
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 02-28 11:54:29 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
02-28 11:54:40 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
02-28 11:54:51 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
02-28 11:54:51 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
02-28 11:54:51 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
02-28 11:54:51 INFO [backup.model.coordinator] I'll try again in 2 hours
02-28 13:54:51 DEBUG [backup.model.syncer] Sync requested by Coordinator
02-28 13:54:51 INFO [backup.model.coordinator] Syncing Backups
02-28 13:54:51 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
02-28 13:54:56 WARNING [backup.creds.exchanger] Unable to reach token1.habackup.io, trying alternate server(s)...
02-28 13:55:07 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
02-28 13:55:07 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
02-28 13:55:07 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
02-28 13:55:07 INFO [backup.model.coordinator] I'll try again in 2 hours
02-28 15:55:07 DEBUG [backup.model.syncer] Sync requested by Coordinator
02-28 15:55:07 INFO [backup.model.coordinator] Syncing Backups
02-28 15:55:07 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
02-28 15:55:18 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
02-28 15:55:29 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
02-28 15:55:29 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
02-28 15:55:29 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
02-28 15:55:29 INFO [backup.model.coordinator] I'll try again in 2 hours
02-28 17:55:29 DEBUG [backup.model.syncer] Sync requested by Coordinator
02-28 17:55:29 INFO [backup.model.coordinator] Syncing Backups
02-28 17:55:29 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
02-28 17:55:40 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
02-28 17:55:51 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
02-28 17:55:51 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
02-28 17:55:51 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
02-28 17:55:51 INFO [backup.model.coordinator] I'll try again in 2 hours
 ```
 ###### Supervisor Logs:
 ```
 [33m23-02-28 18:51:24 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-02-28 18:51:24 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-02-28 18:51:24 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-02-28 18:51:24 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-02-28 18:51:24 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-02-28 18:51:24 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-02-28 18:51:24 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-02-28 18:51:24 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-02-28 18:51:24 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-02-28 18:51:24 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-02-28 18:51:24 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-02-28 18:51:24 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-02-28 18:51:24 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-02-28 18:51:24 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2MQTT (45df7312_zigbee2mqtt)[0m
[33m23-02-28 18:51:39 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa398f790>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-02-28 18:51:44 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa40795d0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-02-28 18:51:49 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa40a9420>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-02-28 18:52:39 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa7db70a0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-02-28 18:52:44 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa7728df0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-02-28 18:52:49 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa7db75e0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-02-28 18:53:39 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa40797b0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-02-28 18:53:44 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa8bc0e50>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-02-28 18:53:49 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa8bc1300>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-02-28 18:54:39 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4079510>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-02-28 18:54:44 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa4079330>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-02-28 18:54:49 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa8b878b0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-02-28 18:55:39 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa398edd0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-02-28 18:55:44 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa407ba00>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[32m23-02-28 18:55:45 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/forecast_solar/coordinator.py", line 65, in _async_update_data
    return await self.forecast.estimate()
  File "/usr/local/lib/python3.10/site-packages/forecast_solar/__init__.py", line 148, in estimate
    data = await self._request(
  File "/usr/local/lib/python3.10/site-packages/forecast_solar/__init__.py", line 77, in _request
    raise ForecastSolarConnectionError(
forecast_solar.exceptions.ForecastSolarConnectionError: Error while resolving Forecast.Solar API address[0m
[31m2023-02-28 18:53:45.126 ERROR (SyncWorker_1) [homeassistant.components.influxdb] InfluxDB database is not accessible due to '401: {"error":"authorization failed"}'. Please check that the database, username and password are correct and that the specified user has the correct permissions set. Retrying in 60 seconds.[0m
[31m2023-02-28 18:54:45.145 ERROR (SyncWorker_2) [homeassistant.components.influxdb] InfluxDB database is not accessible due to '401: {"error":"authorization failed"}'. Please check that the database, username and password are correct and that the specified user has the correct permissions set. Retrying in 60 seconds.[0m
[31m2023-02-28 18:55:19.695 ERROR (MainThread) [homeassistant.components.forecast_solar] Unexpected error fetching forecast_solar data: Error while resolving Forecast.Solar API address
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/forecast_solar/__init__.py", line 75, in _request
    result = await dns.query("api.forecast.solar", "A")
aiodns.error.DNSError: (11, 'Could not contact DNS servers')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/forecast_solar/coordinator.py", line 65, in _async_update_data
    return await self.forecast.estimate()
  File "/usr/local/lib/python3.10/site-packages/forecast_solar/__init__.py", line 148, in estimate
    data = await self._request(
  File "/usr/local/lib/python3.10/site-packages/forecast_solar/__init__.py", line 77, in _request
    raise ForecastSolarConnectionError(
forecast_solar.exceptions.ForecastSolarConnectionError: Error while resolving Forecast.Solar API address[0m
[31m2023-02-28 18:55:45.159 ERROR (SyncWorker_4) [homeassistant.components.influxdb] InfluxDB database is not accessible due to '401: {"error":"authorization failed"}'. Please check that the database, username and password are correct and that the specified user has the correct permissions set. Retrying in 60 seconds.[0m

 ```

**Comment by sabeechen** [comment]
From your home assistant logs it looks like you're having dns errors that prevent you from connecting to the internet.
```
Traceback (most recent call last):
 File "/usr/local/lib/python3.10/site-packages/forecast_solar/__init__.py", line 75, in _request
   result = await dns.query("api.forecast.solar", "A")
aiodns.error.DNSError: (11, 'Could not contact DNS servers')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
 File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
   self.data = await self._async_update_data()
 File "/usr/src/homeassistant/homeassistant/components/forecast_solar/coordinator.py", line 65, in _async_update_data
   return await self.forecast.estimate()
 File "/usr/local/lib/python3.10/site-packages/forecast_solar/__init__.py", line 148, in estimate
   data = await self._request(
 File "/usr/local/lib/python3.10/site-packages/forecast_solar/__init__.py", line 77, in _request
   raise ForecastSolarConnectionError(
forecast_solar.exceptions.ForecastSolarConnectionError: Error while resolving Forecast.Solar API address
```

Is your home assistant computer able to reach the internet?

**Comment by sabeechen** [comment]
I'm going to close this issue for now, but if you think there is something else I can help with please reopen and let me know.
