### ISSUE TITLE
Unable to communicate with Google Drive

### ISSUE THREAD

**Issue by CommanderStarhump** [sabeechen/hassio-google-drive-backup#808]
###### Description:
```
I’ve been having this issue on and off for a few weeks. Eventually resorted to reinstalling the add-on but it’s not seemed to resolve the issue. 

```

 Addon version: `0.110.1`
 Home Assistant Version: `2023.3.1`
 Supervisor Version: `2023.03.1`
 Supervisor Channel: `stable`
 Hassos Version: `9.5`
 Docker Version: `20.10.22`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2023-03-09T14:45:50.474074+00:00`
 Timezone: `Europe/London`
 Failure Time: `2023-03-09T14:45:37.187330+00:00`
 Last Good Sync: `2023-03-09T14:45:13.288352+00:00`
 Next Sync: `2023-03-09T16:45:37.187330+00:00`
 Next Backup: `2023-03-12T03:00:00+00:00`
 Next Cache Warm: `2023-03-09T16:36:00.952799+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/creds/driverequester.py:30 (request)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ClientOSError: [Errno 1] [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2548)
Whose handling caused:
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:246 (sync)
  addon/backup/drive/drivesource.py:202 (save)
  addon/backup/drive/driverequests.py:293 (create)
  addon/backup/drive/driverequests.py:366 (retryRequest)
  addon/backup/creds/driverequester.py:65 (request)
backup.exceptions.exceptions.GoogleUnexpectedError

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-03-09T03:00:37Z",
        "max": 5,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 163,
        "detail": "",
        "size": "921.5 MB",
        "ignored_size": "12.1 GB",
        "free_space": "25.2 GB"
    },
    "GoogleDrive": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-03-06T03:00:40Z",
        "max": 10,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "andrewnile@outlook.com",
        "size": "898.0 MB",
        "ignored_size": "0.0 B",
        "free_space": "85.9 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 5,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 10,
    "Setting.BACKUP_TIME_OF_DAY": "03:00",
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 03-09 14:40:10 INFO [backup.model.coordinator] Syncing Backups
03-09 14:40:11 INFO [backup.drive.drivesource] Uploading 'Full Backup 2023-03-09 03:00:00' to Google Drive
03-09 14:40:11 DEBUG [backup.drive.driverequests] Attempting to resume a previously failed upload where we left off
03-09 14:40:11 DEBUG [backup.drive.driverequests] Resuming upload at byte 184287232 of 247367680
03-09 14:40:11 DEBUG [backup.drive.driverequests] Sending 262144 bytes to Google Drive
03-09 14:40:12 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-03-09 03:00:00 74.61%
03-09 14:40:12 DEBUG [backup.drive.driverequests] Sending 6029312 bytes to Google Drive
03-09 14:40:13 INFO [backup.debugworker] Sending error report (see settings to disable)
03-09 14:40:13 ERROR [backup.model.coordinator] Google gave an unexpected response
03-09 14:40:13 INFO [backup.model.coordinator] I'll try again in 2 hours
03-09 14:42:38 INFO [backup.model.coordinator] Syncing Backups
03-09 14:42:38 INFO [backup.drive.drivesource] Uploading 'Full Backup 2023-03-09 03:00:00' to Google Drive
03-09 14:42:38 DEBUG [backup.drive.driverequests] Attempting to resume a previously failed upload where we left off
03-09 14:42:38 DEBUG [backup.drive.driverequests] Resuming upload at byte 184549376 of 247367680
03-09 14:42:39 DEBUG [backup.drive.driverequests] Sending 262144 bytes to Google Drive
03-09 14:42:39 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-03-09 03:00:00 74.71%
03-09 14:42:39 DEBUG [backup.drive.driverequests] Sending 6291456 bytes to Google Drive
03-09 14:42:47 ERROR [backup.model.coordinator] Google gave an unexpected response
03-09 14:42:47 INFO [backup.model.coordinator] I'll try again in 2 hours
03-09 14:45:13 INFO [backup.model.coordinator] Syncing Backups
03-09 14:45:13 INFO [backup.drive.drivesource] Uploading 'Full Backup 2023-03-09 03:00:00' to Google Drive
03-09 14:45:13 DEBUG [backup.drive.driverequests] Attempting to resume a previously failed upload where we left off
03-09 14:45:14 DEBUG [backup.drive.driverequests] Resuming upload at byte 186122240 of 247367680
03-09 14:45:14 DEBUG [backup.drive.driverequests] Sending 262144 bytes to Google Drive
03-09 14:45:15 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-03-09 03:00:00 75.35%
03-09 14:45:15 DEBUG [backup.drive.driverequests] Sending 1572864 bytes to Google Drive
03-09 14:45:34 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-03-09 03:00:00 75.98%
03-09 14:45:34 DEBUG [backup.drive.driverequests] Sending 786432 bytes to Google Drive
03-09 14:45:37 ERROR [backup.model.coordinator] Google gave an unexpected response
03-09 14:45:37 INFO [backup.model.coordinator] I'll try again in 2 hours
 ```
 ###### Supervisor Logs:
 ```
 [32m23-03-09 14:42:49 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered[0m
[32m23-03-09 14:42:49 INFO (SyncWorker_3) [supervisor.docker.interface] Cleanup images: ['ghcr.io/home-assistant/qemux86-64-homeassistant:2023.3.1'][0m
[32m23-03-09 14:42:49 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[31m23-03-09 14:43:18 ERROR (MainThread) [supervisor.utils] Can't execute restart while a task is in progress[0m
[32m23-03-09 14:43:43 INFO (SyncWorker_1) [supervisor.docker.interface] Restarting ghcr.io/home-assistant/qemux86-64-homeassistant[0m
[32m23-03-09 14:43:43 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str[0m
[32m23-03-09 14:43:43 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed[0m
[32m23-03-09 14:44:00 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready[0m
[32m23-03-09 14:44:02 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m23-03-09 14:44:02 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-03-09 14:44:03 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m23-03-09 14:44:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m23-03-09 14:44:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/brenner-tobias/ha-addons repository[0m
[32m23-03-09 14:44:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-03-09 14:44:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m23-03-09 14:44:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m23-03-09 14:44:04 INFO (MainThread) [supervisor.store] Loading add-ons from store: 70 all - 0 new - 0 remove[0m
[32m23-03-09 14:44:04 INFO (MainThread) [supervisor.store] Loading add-ons from store: 70 all - 0 new - 0 remove[0m
[32m23-03-09 14:45:12 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance[0m
[32m23-03-09 14:45:13 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-09 14:45:13 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-09 14:45:13 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m23-03-09 14:45:13 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered[0m
[32m23-03-09 14:45:13 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m23-03-09 14:45:13 INFO (MainThread) [supervisor.api.middleware.security] /backups/9dfd7cd2/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-09 14:45:13 INFO (MainThread) [supervisor.api.backups] Downloading backup 9dfd7cd2[0m
[32m23-03-09 14:45:14 INFO (MainThread) [supervisor.api.middleware.security] /backups/9dfd7cd2/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-09 14:45:14 INFO (MainThread) [supervisor.api.backups] Downloading backup 9dfd7cd2[0m
[32m23-03-09 14:45:50 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 576, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 460, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% set state = states('sensor.average_temperature')|float %}
  {% if state >= 0 and state < 18 %} blue
  {% elif state >= 18 and state < 20 %} yellow
  {% elif state >= 20 and state < 23 %} orange
  {% elif state >= 23 and state < 50 %} red
  {% else %} grey
  {% endif %}' but no default was specified[0m
[31m2023-03-09 14:45:10.900 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{% set state = states('sensor.average_temperature')|float %}
  {% if state >= 0 and state < 18 %} blue
  {% elif state >= 18 and state < 20 %} yellow
  {% elif state >= 20 and state < 23 %} orange
  {% elif state >= 23 and state < 50 %} red
  {% else %} grey
  {% endif %}' but no default was specified') while processing template 'Template("{% set state = states('sensor.average_temperature')|float %}
  {% if state >= 0 and state < 18 %} blue
  {% elif state >= 18 and state < 20 %} yellow
  {% elif state >= 20 and state < 23 %} orange
  {% elif state >= 23 and state < 50 %} red
  {% else %} grey
  {% endif %}")' for attribute '_attr_native_value' in entity 'sensor.average_temp_color_no_rgb'[0m
[31m2023-03-09 14:45:12.597 ERROR (MainThread) [homeassistant.components.alexa.state_report] Timeout sending report to Alexa for sensor.octoprint_target_w_temp[0m
[33m2023-03-09 14:45:13.775 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.home_precipitation (mm/h) cannot be converted to the unit of previously compiled statistics (mm). Generation of long term statistics will be suppressed unless the unit changes back to mm or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this[0m
[33m2023-03-09 14:45:13.789 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.watchman_missing_entities (None) cannot be converted to the unit of previously compiled statistics (items). Generation of long term statistics will be suppressed unless the unit changes back to items or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this[0m
[33m2023-03-09 14:45:14.912 WARNING (Recorder) [homeassistant.components.recorder.db_schema] State attributes for sensor.watchman_missing_entities exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored[0m

 ```

**Comment by pickonedev** [comment]
I get this error as well, in the logs

`State attributes for sensor.watchman_missing_entities exceed maximum size of 16384 bytes`

**Comment by sabeechen** [comment]
I've had this bug come up many times in the future and assumed it was outside of my control, but taking a fresh look at it recently I think it might be caused by how the addon handles its connections.  I found a place where certain kinds of errors can prevent a connection from getting cleaned up, which eventually exhausts the connection pool available forcing the use of a connection that was never closed.

I've made a fix in v0.110.2, which I released last night.  Due to the transient nature of the problem (its _very_ hard to reproduce), its difficult for me to tell if the fix actually worked.  Could you tell me if you still see this problem after updating to the addon to 0.110.2?

**Comment by CommanderStarhump** [comment]
Thanks for looking into this. I’ve updated and will report back if I see the issue again
