### ISSUE TITLE
Last version 0.110.2 don't work

### ISSUE THREAD

**Issue by Gferretta** [sabeechen/hassio-google-drive-backup#813]
Not get up

**Comment by sabeechen** [comment]
How do you mean?  I need to know what you're seeing to help.  Is there anything in the logs?

**Comment by Gferretta** [comment]
Sorry but dont know why not copy/paste in my previous post

Log

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/backup/__main__.py", line 6, in <module>
    from backup.module import MainModule, BaseModule
  File "/app/backup/module.py", line 10, in <module>
    from backup.drive import DriveSource
  File "/app/backup/drive/__init__.py", line 2, in <module>
    from .driverequests import DriveRequests, RETRY_SESSION_ATTEMPTS, UPLOAD_SESSION_EXPIRATION_DURATION, URL_START_UPLOAD, OOB_CRED_CUTOFF
  File "/app/backup/drive/driverequests.py", line 12, in <module>
    from ..util import AsyncHttpGetter
  File "/app/backup/util/__init__.py", line 2, in <module>
    from .asynchttpgetter import AsyncHttpGetter
  File "/app/backup/util/asynchttpgetter.py", line 12, in <module>
    from ..time import Time
  File "/app/backup/time.py", line 18, in <module>
    class Time(object):
  File "/app/backup/time.py", line 20, in Time
    def __init__(self, local_tz=timezone(get_localzone_name())):
  File "/usr/lib/python3.10/site-packages/pytz/__init__.py", line 168, in timezone
    raise UnknownTimeZoneError(None)
pytz.exceptions.UnknownTimeZoneError: None

**Comment by sabeechen** [comment]
It looks like your timezone isn't recognized by the timezone library I'm using (I had to update it in the latest release).  Do you know what timezone Home Assistant thinks you're in?  You should be able to see it in Home Assistant at Settings > System > General

**Comment by Gferretta** [comment]
Time zone GMT - 3 Buenos Aires Argentina

**Comment by sabeechen** [comment]
I'll work getting a fix for this ASAP

**Comment by sabeechen** [comment]
I just released v0.110.3, which should fix this.  If you continue to see a problem after updating please reopen this issue and let me know.
