### ISSUE TITLE
Problem with version 0.110.2

### ISSUE THREAD

**Issue by rizkypr** [sabeechen/hassio-google-drive-backup#814]
After updating to version 0.110.2, it is now doing backup every 24 Hours,  in the setting it supposed to do backup every 10 days. Work without problem using previous version.

**Comment by sabeechen** [comment]
Can you post the output of going to "Actions" > "Report a Bug" in the web-ui?

**Comment by rizkypr** [comment]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.110.2`
 Home Assistant Version: `2023.3.6`
 Supervisor Version: `2023.03.2`
 Supervisor Channel: `stable`
 Hassos Version: `9.4`
 Docker Version: `20.10.19`
 Architecture: `aarch64`
 Machine: `raspberrypi3-64`
 Date: `2023-03-24T21:39:23.654431+00:00`
 Timezone: `Asia/Jakarta`
 Failure Time: `Never`
 Last Good Sync: `2023-03-24T21:35:11.754894+00:00`
 Next Sync: `2023-03-24T23:37:42.638621+00:00`
 Next Backup: `2023-03-25T21:00:00+00:00`
 Next Cache Warm: `2023-03-24T23:31:11.767900+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 8,
        "retained": 1,
        "deletable": 7,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-03-24T21:00:00Z",
        "max": 10,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "detail": "",
        "size": "1.0 GB",
        "ignored_size": "0.0 B",
        "free_space": "45.7 GB"
    },
    "GoogleDrive": {
        "backups": 9,
        "retained": 1,
        "deletable": 8,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-03-24T21:00:00Z",
        "max": 10,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "rizky@gmail.com",
        "size": "1.1 GB",
        "ignored_size": "0.0 B",
        "free_space": "6.2 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 10,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 10,
    "Setting.DAYS_BETWEEN_BACKUPS": 9.0,
    "Setting.BACKUP_TIME_OF_DAY": "04:00",
    "Setting.USE_SSL": true
}
 ```
 ###### Addon Logs:
 ```
 03-25 04:35:11 INFO [backup.ui.uiserver] Starting server on port 8099
03-25 04:35:11 INFO [backup.ui.uiserver] Server started
03-25 04:35:11 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-25 04:35:11 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
03-25 04:35:11 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-25 04:35:11 INFO [backup.model.coordinator] Syncing Backups
03-25 04:35:11 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
 ```
 ###### Supervisor Logs:
 ```
 [32m23-03-25 04:25:54 INFO (MainThread) [supervisor.api.middleware.security] /backups/8b583c17/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:25:54 INFO (MainThread) [supervisor.api.middleware.security] /backups/d6012b46/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:25:54 INFO (MainThread) [supervisor.api.middleware.security] /backups/500f054d/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:25:54 INFO (MainThread) [supervisor.api.middleware.security] /backups/2785c0df/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:25:54 INFO (MainThread) [supervisor.api.middleware.security] /backups/85d5166f/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:25:55 INFO (MainThread) [supervisor.api.middleware.security] /backups/b5e179fd/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:25:55 INFO (MainThread) [supervisor.api.middleware.security] /backups/f3d57c9b/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:26:36 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:26:37 INFO (MainThread) [supervisor.api.middleware.security] /core/logs access from cebe7a76_hassio_google_drive_backup[0m
[33m23-03-25 04:28:21 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)[0m
[33m23-03-25 04:33:23 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)[0m
[32m23-03-25 04:34:44 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_cebe7a76_hassio_google_drive_backup application[0m
[32m23-03-25 04:34:50 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_cebe7a76_hassio_google_drive_backup application[0m
[32m23-03-25 04:35:04 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on sabeechen/hassio-google-drive-backup-aarch64 with version 0.110.2[0m
[32m23-03-25 04:35:11 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:35:11 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:35:11 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:35:11 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:35:11 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:35:11 INFO (MainThread) [supervisor.api.middleware.security] /backups/ca9d3786/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:35:11 INFO (MainThread) [supervisor.api.middleware.security] /backups/8b583c17/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:35:11 INFO (MainThread) [supervisor.api.middleware.security] /backups/d6012b46/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:35:11 INFO (MainThread) [supervisor.api.middleware.security] /backups/500f054d/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:35:11 INFO (MainThread) [supervisor.api.middleware.security] /backups/2785c0df/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:35:11 INFO (MainThread) [supervisor.api.middleware.security] /backups/85d5166f/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:35:11 INFO (MainThread) [supervisor.api.middleware.security] /backups/b5e179fd/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-25 04:35:11 INFO (MainThread) [supervisor.api.middleware.security] /backups/f3d57c9b/info access from cebe7a76_hassio_google_drive_backup[0m
[33m23-03-25 04:38:25 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)[0m
[32m23-03-25 04:39:23 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     color = tuple(int(val) for val in str(payload).split(","))
ValueError: invalid literal for int() with base 10: '#000000'
[0m
[33m2023-03-25 04:35:59.523 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.wifi_remote_1 or it is/they are currently not available[0m
[31m2023-03-25 04:38:22.023 ERROR (MainThread) [homeassistant.util.logging] Exception in rgb_received when handling msg on 'espurna5/rgb': '#FF00FF'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
    msg_callback(msg)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_basic.py", line 510, in rgb_received
    rgb = _rgbx_received(
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_basic.py", line 493, in _rgbx_received
    color = tuple(int(val) for val in str(payload).split(","))
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_basic.py", line 493, in <genexpr>
    color = tuple(int(val) for val in str(payload).split(","))
ValueError: invalid literal for int() with base 10: '#FF00FF'
[0m
[31m2023-03-25 04:38:47.258 ERROR (MainThread) [homeassistant.util.logging] Exception in rgb_received when handling msg on 'espurna8/rgb': '#000000'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
    msg_callback(msg)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_basic.py", line 510, in rgb_received
    rgb = _rgbx_received(
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_basic.py", line 493, in _rgbx_received
    color = tuple(int(val) for val in str(payload).split(","))
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_basic.py", line 493, in <genexpr>
    color = tuple(int(val) for val in str(payload).split(","))
ValueError: invalid literal for int() with base 10: '#000000'
[0m
[33m2023-03-25 04:39:20.209 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.wifi_remote_1 or it is/they are currently not available[0m

 ```

**Comment by sabeechen** [comment]
Yup this is my mistake, I'll release a fix soon.

**Comment by rizkypr** [comment]
Awesome thanks.

**Comment by sabeechen** [comment]
I just released v0.110.3, which should fix this.  If you continue to see a problem after updating please reopen this issue and let me know.
