### ISSUE TITLE
Please add a title

### ISSUE THREAD

**Issue by rdperkins** [sabeechen/hassio-google-drive-backup#816]
Co
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.110.3`
 Home Assistant Version: `2023.3.6`
 Supervisor Version: `2023.03.2`
 Supervisor Channel: `stable`
 Hassos Version: `9.5`
 Docker Version: `20.10.22`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2023-03-26T21:25:19.084586+00:00`
 Timezone: `America/New_York`
 Failure Time: `2023-03-26T21:15:42.132804+00:00`
 Last Good Sync: `2023-03-26T21:15:20.697795+00:00`
 Next Sync: `2023-03-26T23:15:42.132804+00:00`
 Next Backup: `2023-03-26T21:20:38.345681+00:00`
 Next Cache Warm: `2259-10-15T21:11:00.133420+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:199 (sync)
  addon/backup/model/model.py:312 (_syncBackups)
  addon/backup/drive/drivesource.py:118 (get)
  addon/backup/drive/drivesource.py:269 (getFolderId)
  addon/backup/drive/folderfinder.py:63 (get)
  addon/backup/drive/folderfinder.py:113 (_readFolderId)
  addon/backup/drive/folderfinder.py:154 (_verify)
  addon/backup/drive/driverequests.py:163 (get)
  addon/backup/drive/driverequests.py:351 (retryRequest)
  addon/backup/drive/driverequests.py:94 (_getHeaders)
  addon/backup/drive/driverequests.py:152 (getToken)
  addon/backup/creds/exchanger.py:81 (refresh)
  addon/backup/creds/exchanger.py:150 (_refresh_default)
backup.exceptions.exceptions.CredRefreshMyError: Timed out communicating with habackup.io

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 11,
        "retained": 7,
        "deletable": 4,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-03-23T21:15:22Z",
        "max": 8,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "detail": "",
        "size": "1.2 GB",
        "ignored_size": "0.0 B",
        "free_space": "18.3 GB"
    },
    "GoogleDrive": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 8,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "",
        "size": "0.0 B",
        "ignored_size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 8,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 8,
    "Setting.IGNORE_UPGRADE_BACKUPS": false,
    "Setting.DELETE_BEFORE_NEW_BACKUP": true,
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 03-26 17:11:49 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
03-26 17:11:49 INFO [backup.model.coordinator] I'll try again in 20 seconds
03-26 17:12:09 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-26 17:12:09 INFO [backup.model.coordinator] Syncing Backups
03-26 17:12:09 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-26 17:12:19 INFO [backup.debugworker] Sending error report (see settings to disable)
03-26 17:12:20 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
03-26 17:12:26 ERROR [backup.model.coordinator] Sync was cancelled by you
03-26 17:12:26 INFO [backup.model.coordinator] I'll try again in 2 hours
03-26 17:12:26 INFO [backup.model.coordinator] Syncing Backups
03-26 17:12:26 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-26 17:12:37 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
03-26 17:12:37 WARNING [backup.creds.exchanger] Unable to reach habackup.io, trying alternate server(s)...
03-26 17:12:37 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
03-26 17:12:37 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Couldn't communicate with habackup.io
03-26 17:12:37 INFO [backup.model.coordinator] I'll try again in 2 hours
03-26 17:12:45 INFO [backup.model.coordinator] Syncing Backups
03-26 17:12:45 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-26 17:12:56 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
03-26 17:13:07 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
03-26 17:13:07 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
03-26 17:13:07 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
03-26 17:13:07 INFO [backup.model.coordinator] I'll try again in 2 hours
03-26 17:15:20 INFO [backup.model.coordinator] Syncing Backups
03-26 17:15:20 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-26 17:15:31 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
03-26 17:15:42 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
03-26 17:15:42 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
03-26 17:15:42 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
03-26 17:15:42 INFO [backup.model.coordinator] I'll try again in 2 hours
 ```
 ###### Supervisor Logs:
 ```
 [33m23-03-26 17:16:50 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b94742da0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:17:40 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b928d0f70>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:17:45 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b9452a830>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:17:50 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b94528f40>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[32m23-03-26 17:17:52 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[33m23-03-26 17:18:40 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b9477dba0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:18:45 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b9477e2f0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:18:50 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b9477d600>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:19:40 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b94d764a0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:19:45 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b92834760>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:19:50 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b92836860>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:19:53 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[33m23-03-26 17:20:40 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b91bc91b0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:20:45 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b94d380d0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:20:50 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b9477d600>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:21:40 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b91bc89d0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:21:45 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b91bcb490>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:21:50 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b91bc9e10>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:22:40 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b928d3370>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:22:45 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b91c28280>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:22:50 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b91c2af50>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:23:40 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b91bc9000>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:23:45 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b91c2bbe0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:23:50 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b91c29480>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:24:40 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b91bc91b0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:24:45 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b94d740a0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:24:50 WARNING (raven-sentry.BackgroundWorker) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b94d174c0>: Failed to establish a new connection: [Errno -3] Try again')': /api/5370612/envelope/[0m
[33m23-03-26 17:24:57 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[32m23-03-26 17:25:19 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/honeywell/climate.py", line 430, in async_update
    await self._data.client.login()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.mytotalconnectcomfort.com:443 ssl:default [Try again][0m
[31m2023-03-26 17:25:09.237 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=37 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=37, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 52877)>[0m
[33m2023-03-26 17:25:10.435 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: HTTPSConnectionPool(host='oauth.ring.com', port=443): Max retries exceeded with url: /oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdd04fd7160>: Failed to establish a new connection: [Errno -3] Try again'))[0m
[33m2023-03-26 17:25:11.938 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring device data: HTTPSConnectionPool(host='oauth.ring.com', port=443): Max retries exceeded with url: /oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdd04fd61d0>: Failed to establish a new connection: [Errno -3] Try again'))[0m
[33m2023-03-26 17:25:12.510 WARNING (SyncWorker_42) [homeassistant.components.ring] Error fetching Ring history data for device 3ce1a1aeae22: HTTPSConnectionPool(host='oauth.ring.com', port=443): Max retries exceeded with url: /oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdd1ab848b0>: Failed to establish a new connection: [Errno -3] Try again'))[0m
[33m2023-03-26 17:25:15.436 WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring active dings data: HTTPSConnectionPool(host='oauth.ring.com', port=443): Max retries exceeded with url: /oauth/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdd1ab860e0>: Failed to establish a new connection: [Errno -3] Try again'))[0m

 ```
 py the info from the previous page here

**Comment by sabeechen** [comment]
Based on your logs in Home Assistant, it looks like your Home Assistant machine can't reach the internet for some reason.

**Comment by rdperkins** [comment]
Thanks, duh.
