### ISSUE TITLE
OSError: [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by wildoracle** [sabeechen/hassio-google-drive-backup#819]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.110.3`
 Home Assistant Version: `2023.3.6`
 Supervisor Version: `2023.03.2`
 Supervisor Channel: `stable`
 Hassos Version: `9.5`
 Docker Version: `20.10.22`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2023-03-28T16:32:33.072873+00:00`
 Timezone: `America/Los_Angeles`
 Failure Time: `2023-03-28T16:32:13.866038+00:00`
 Last Good Sync: `2023-03-28T16:32:12.349568+00:00`
 Next Sync: `2023-03-28T18:32:13.866038+00:00`
 Next Backup: `2023-04-07T22:19:13.308320+00:00`
 Next Cache Warm: `2023-03-28T18:31:35.244226+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:256 (sync)
  addon/backup/util/data_cache.py:115 (saveIfDirty)
  addon/backup/util/data_cache.py:87 (save)
  addon/backup/file/jsonfilesaver.py:52 (write)
  addon/backup/file/jsonfilesaver.py:46 (_write)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json.backup'

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 3,
        "retained": 0,
        "deletable": 3,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-03-24T22:19:13Z",
        "max": 3,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 172,
        "detail": "",
        "size": "735.8 MB",
        "ignored_size": "12.0 GB",
        "free_space": "89.2 GB"
    },
    "GoogleDrive": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-03-24T22:19:13Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "ahoeveler@gmail.com",
        "size": "896.3 MB",
        "ignored_size": "0.0 B",
        "free_space": "40.2 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 3,
    "Setting.DAYS_BETWEEN_BACKUPS": 14.0,
    "Setting.CONFIRM_MULTIPLE_DELETES": false
}
 ```
 ###### Addon Logs:
 ```
 03-28 03:47:07 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-28 03:47:07 INFO [backup.model.coordinator] Syncing Backups
03-28 03:47:08 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:256 (sync)
  addon/backup/util/data_cache.py:115 (saveIfDirty)
  addon/backup/util/data_cache.py:87 (save)
  addon/backup/file/jsonfilesaver.py:52 (write)
  addon/backup/file/jsonfilesaver.py:46 (_write)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json.backup'

03-28 03:47:08 INFO [backup.model.coordinator] I'll try again in 21 minutes, 20 seconds
03-28 04:08:28 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-28 04:08:28 INFO [backup.model.coordinator] Syncing Backups
03-28 04:08:29 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:256 (sync)
  addon/backup/util/data_cache.py:115 (saveIfDirty)
  addon/backup/util/data_cache.py:87 (save)
  addon/backup/file/jsonfilesaver.py:52 (write)
  addon/backup/file/jsonfilesaver.py:46 (_write)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json.backup'

03-28 04:08:29 INFO [backup.model.coordinator] I'll try again in 42 minutes, 40 seconds
03-28 04:39:33 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
03-28 04:39:33 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-28 04:51:09 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-28 04:51:09 INFO [backup.model.coordinator] Syncing Backups
03-28 04:51:10 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:256 (sync)
  addon/backup/util/data_cache.py:115 (saveIfDirty)
  addon/backup/util/data_cache.py:87 (save)
  addon/backup/file/jsonfilesaver.py:52 (write)
  addon/backup/file/jsonfilesaver.py:46 (_write)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json.backup'

03-28 04:51:10 INFO [backup.model.coordinator] I'll try again in 1 hours, 25 minutes, 20 seconds
03-28 06:05:34 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
03-28 06:05:34 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-28 06:16:30 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-28 06:16:30 INFO [backup.model.coordinator] Syncing Backups
03-28 06:16:30 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:256 (sync)
  addon/backup/util/data_cache.py:115 (saveIfDirty)
  addon/backup/util/data_cache.py:87 (save)
  addon/backup/file/jsonfilesaver.py:52 (write)
  addon/backup/file/jsonfilesaver.py:46 (_write)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json.backup'

03-28 06:16:30 INFO [backup.model.coordinator] I'll try again in 2 hours
03-28 08:13:35 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
03-28 08:13:35 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-28 08:16:30 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-28 08:16:30 INFO [backup.model.coordinator] Syncing Backups
03-28 08:16:30 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:256 (sync)
  addon/backup/util/data_cache.py:115 (saveIfDirty)
  addon/backup/util/data_cache.py:87 (save)
  addon/backup/file/jsonfilesaver.py:52 (write)
  addon/backup/file/jsonfilesaver.py:46 (_write)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json.backup'

03-28 08:16:30 INFO [backup.model.coordinator] I'll try again in 2 hours
03-28 09:32:12 INFO [backup.model.coordinator] Syncing Backups
03-28 09:32:12 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-28 09:32:13 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:256 (sync)
  addon/backup/util/data_cache.py:115 (saveIfDirty)
  addon/backup/util/data_cache.py:87 (save)
  addon/backup/file/jsonfilesaver.py:52 (write)
  addon/backup/file/jsonfilesaver.py:46 (_write)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json.backup'

03-28 09:32:13 INFO [backup.model.coordinator] I'll try again in 2 hours
 ```
 ###### Supervisor Logs:
 ```
 rm: can't remove '/data/addons/git/6a3d001f/assistant_relay_beta/README.md': Read-only file system
rm: can't remove '/data/addons/git/6a3d001f/assistant_relay_beta/icon.png': Read-only file system
rm: can't remove '/data/addons/git/6a3d001f/assistant_relay_beta/Dockerfile': Read-only file system
rm: can't remove '/data/addons/git/6a3d001f/assistant_relay_beta/logo.png': Read-only file system
rm: can't remove '/data/addons/git/6a3d001f/assistant_relay_beta/CHANGELOG.md': Read-only file system
rm: can't remove '/data/addons/git/6a3d001f/assistant_relay_beta/config.json': Read-only file system
[31m23-03-28 08:53:44 ERROR (MainThread) [supervisor.utils] Can't remove folder /data/addons/git/6a3d001f: None[0m
[32m23-03-28 08:53:44 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/6a3d001f repository[0m
[32m23-03-28 08:53:44 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m23-03-28 08:54:02 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_username[0m
[32m23-03-28 08:54:02 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_password[0m
[32m23-03-28 08:59:08 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_username[0m
[32m23-03-28 08:59:08 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_password[0m
[32m23-03-28 09:04:10 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-03-28 09:04:14 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_username[0m
[32m23-03-28 09:04:14 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_password[0m
[32m23-03-28 09:09:21 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_username[0m
[32m23-03-28 09:09:21 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_password[0m
[32m23-03-28 09:14:27 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_username[0m
[32m23-03-28 09:14:27 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_password[0m
[32m23-03-28 09:19:34 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_username[0m
[32m23-03-28 09:19:34 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_password[0m
[32m23-03-28 09:24:40 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_username[0m
[32m23-03-28 09:24:40 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_password[0m
[32m23-03-28 09:29:46 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_username[0m
[32m23-03-28 09:29:46 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_password[0m
[32m23-03-28 09:32:12 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-28 09:32:12 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-28 09:32:33 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 [36m2023-03-28 04:19:40.101 DEBUG (SyncWorker_45) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device[0m
[36m2023-03-28 04:19:45.210 DEBUG (SyncWorker_45) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device[0m
[33m2023-03-28 04:19:48.793 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:10[0m
[33m2023-03-28 04:19:48.795 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.live_vacuum_map is taking over 10 seconds[0m
[36m2023-03-28 04:19:50.319 DEBUG (SyncWorker_45) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device[0m
[36m2023-03-28 04:19:55.425 DEBUG (SyncWorker_45) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device[0m
[33m2023-03-28 04:19:58.794 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:10[0m
[36m2023-03-28 04:20:00.532 DEBUG (SyncWorker_45) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device[0m
[36m2023-03-28 04:20:05.642 DEBUG (SyncWorker_45) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device[0m
[33m2023-03-28 04:20:08.796 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:10[0m
[36m2023-03-28 04:20:10.749 DEBUG (SyncWorker_45) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device[0m
[36m2023-03-28 04:20:15.855 DEBUG (SyncWorker_45) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device[0m
[33m2023-03-28 04:20:18.797 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:10[0m
[36m2023-03-28 04:20:20.960 DEBUG (SyncWorker_45) [custom_components.xiaomi_cloud_map_extractor.camera] Retrieving map name from device[0m
[31m2023-03-28 04:20:24.253 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/components/hunterdouglas_powerview/cover.py", line 333, in _async_update_shade_from_group
    self.data.update_from_group_data(self._shade.id)
  File "/usr/src/homeassistant/homeassistant/components/hunterdouglas_powerview/shade_data.py", line 74, in update_from_group_data
    self.update_shade_positions(self._group_data_by_id[shade_id])
  File "/usr/src/homeassistant/homeassistant/components/hunterdouglas_powerview/shade_data.py", line 110, in update_shade_positions
    position_data = data[ATTR_POSITION_DATA]
KeyError: 'positions'[0m

 ```

**Comment by sabeechen** [comment]
The operating system does this, makes the system read-only, when it needs to protect the hard drive.  Usually they s is because either:
- You're out of space
- There is corruption(ie an sd card is dying)

You're probably not out of space from the looks of it, with 89 GB free, though it's still possible the latest backup was much bigger than normal and ran out of space before completing (the temporary files would have been cleaned up making ng more free space again)

If it's corruption, that is much harder to detect.  You can reboot the machine and see if anything shows up in the supervisor logs.

On a separate note you have 172 backups "ignored" by the addon, which are most likely from upgrades.  You may want to configure the addon to delete them automatically (see the settings).  I doubt this has anything to do with the error, but it's possible.

**Comment by wildoracle** [comment]
Thank you for the detailed clarification. The error went away after a restart - I will configure the addon to delete the "ignored" backups.

**Comment by sabeechen** [comment]
In case it was corruption, you may want to pop the SD card into another computer and check it for errors (there are guides on the internet) or potentially just replace it.  HA tends to chew through SD cards.
