### ISSUE TITLE
Backup abnormally long

### ISSUE THREAD

**Issue by Christianb233** [sabeechen/hassio-google-drive-backup#839]
Hello, 
Home Assistant warms be that there was a trouble in the add-on Google Drive Backup and advises to check the status page.
I the status page, I have seen that there was a pending backcup, while my ~250Mo daily backup starting at 10:00 am usually ends before 12:00.
In the logs, it seems that the issue lasts for several days = do what I can do to solve it ?
Here are the logs : 
`04-25 20:58:23 INFO [backup.ui.uiserver] Starting server on port 8099
04-25 20:58:23 INFO [backup.ui.uiserver] Server started
04-25 20:58:23 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-25 20:58:23 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-25 20:58:23 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-25 20:58:23 INFO [backup.model.coordinator] Syncing Backups
04-25 20:58:36 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
04-25 20:58:51 DEBUG [backup.watcher] Checking backup source for changes...
04-25 21:01:08 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
04-25 21:01:19 DEBUG [backup.watcher] Checking backup source for changes...
04-25 22:20:28 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-25 22:20:28 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-25 22:32:04 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-25 22:32:04 INFO [backup.model.coordinator] Syncing Backups
04-26 01:19:35 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-26 01:19:35 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-26 01:26:04 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-26 01:26:04 INFO [backup.model.coordinator] Syncing Backups
04-26 02:59:40 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-26 02:59:40 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-26 03:00:00 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-26 03:00:00 INFO [backup.model.coordinator] Syncing Backups
04-26 03:00:00 INFO [backup.ha.hasource] Requesting a new backup
04-26 03:02:52 WARNING [backup.ha.hasource] A backup was already in progress
04-26 03:02:52 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-26 03:02:52 INFO [backup.model.coordinator] Syncing Backups
04-26 04:54:45 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-26 04:54:45 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-26 05:04:21 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-26 05:04:21 INFO [backup.model.coordinator] Syncing Backups
04-26 06:00:01 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-26 06:00:01 INFO [backup.model.coordinator] Syncing Backups
04-26 06:00:01 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-26 06:00:03 INFO [backup.ha.hasource] Requesting a new backup
04-26 06:03:14 WARNING [backup.ha.hasource] A backup was already in progress
04-26 06:03:14 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-26 06:03:14 INFO [backup.model.coordinator] Syncing Backups
04-26 07:42:52 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-26 07:42:52 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-26 07:54:49 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-26 07:54:49 INFO [backup.model.coordinator] Syncing Backups
04-26 09:00:03 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-26 09:00:03 INFO [backup.model.coordinator] Syncing Backups
04-26 09:00:03 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-26 09:00:05 INFO [backup.ha.hasource] Requesting a new backup
04-26 09:03:06 WARNING [backup.ha.hasource] A backup was already in progress
04-26 09:03:06 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-26 09:03:06 INFO [backup.model.coordinator] Syncing Backups
04-26 10:00:47 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
04-26 10:00:59 DEBUG [backup.watcher] Checking backup source for changes...
04-26 10:04:13 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
04-26 10:04:33 DEBUG [backup.watcher] Checking backup source for changes...
04-26 10:24:58 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-26 10:24:58 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-26 10:38:26 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-26 10:38:26 INFO [backup.model.coordinator] Syncing Backups
04-26 12:00:06 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-26 12:00:06 INFO [backup.model.coordinator] Syncing Backups
04-26 12:00:06 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-26 12:00:08 INFO [backup.ha.hasource] Requesting a new backup
04-26 12:04:46 WARNING [backup.ha.hasource] A backup was already in progress
04-26 12:04:47 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-26 12:04:47 INFO [backup.model.coordinator] Syncing Backups
04-26 13:00:45 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
04-26 13:00:56 DEBUG [backup.watcher] Checking backup source for changes...
04-26 13:00:56 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
04-26 13:00:56 INFO [backup.model.coordinator] Syncing Backups
04-26 13:00:56 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-26 13:00:58 INFO [backup.ha.hasource] Requesting a new backup
04-26 13:01:47 WARNING [backup.ha.hasource] A backup was already in progress
04-26 13:01:47 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-26 13:01:47 INFO [backup.model.coordinator] Syncing Backups
04-26 15:37:09 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-26 15:37:09 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-26 15:40:47 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-26 15:40:47 INFO [backup.model.coordinator] Syncing Backups
04-26 16:00:58 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-26 16:00:58 INFO [backup.model.coordinator] Syncing Backups
04-26 16:01:00 INFO [backup.ha.hasource] Requesting a new backup
04-26 16:03:47 WARNING [backup.ha.hasource] A backup was already in progress
04-26 16:03:47 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-26 16:03:47 INFO [backup.model.coordinator] Syncing Backups
04-26 16:58:27 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
04-26 16:58:48 DEBUG [backup.watcher] Checking backup source for changes...
04-26 18:25:17 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-26 18:25:17 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-26 18:34:20 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-26 18:34:20 INFO [backup.model.coordinator] Syncing Backups

04-26 19:01:00 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-26 19:01:00 INFO [backup.model.coordinator] Syncing Backups
04-26 19:01:01 INFO [backup.ha.hasource] Requesting a new backup
04-26 19:03:59 WARNING [backup.ha.hasource] A backup was already in progress
04-26 19:04:00 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-26 19:04:00 INFO [backup.model.coordinator] Syncing Backups
04-26 20:58:23 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-26 20:58:23 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-26 21:02:16 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-26 21:02:16 INFO [backup.model.coordinator] Syncing Backups
04-26 22:01:02 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-26 22:01:02 INFO [backup.model.coordinator] Syncing Backups
04-26 22:01:02 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-26 22:01:04 INFO [backup.ha.hasource] Requesting a new backup
04-26 22:03:43 WARNING [backup.ha.hasource] A backup was already in progress
04-26 22:03:43 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-26 22:03:43 INFO [backup.model.coordinator] Syncing Backups
04-27 00:21:32 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-27 00:21:32 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-27 00:36:12 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-27 00:36:12 INFO [backup.model.coordinator] Syncing Backups
04-27 01:01:05 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-27 01:01:05 INFO [backup.model.coordinator] Syncing Backups
04-27 01:01:07 INFO [backup.ha.hasource] Requesting a new backup
04-27 01:04:26 WARNING [backup.ha.hasource] A backup was already in progress
04-27 01:04:26 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-27 01:04:26 INFO [backup.model.coordinator] Syncing Backups
04-27 02:40:38 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-27 02:40:38 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-27 02:49:14 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-27 02:49:14 INFO [backup.model.coordinator] Syncing Backups
04-27 02:57:41 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-27 03:00:00 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-27 03:00:00 INFO [backup.model.coordinator] Syncing Backups
04-27 03:00:00 INFO [backup.ha.hasource] A backup was already in progress
04-27 03:00:00 ERROR [backup.model.coordinator] A backup is already in progress
04-27 03:00:00 INFO [backup.model.coordinator] I'll try again in 0 seconds
04-27 03:00:00 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-27 03:00:00 INFO [backup.model.coordinator] Syncing Backups
04-27 03:00:01 INFO [backup.ha.hasource] A backup was already in progress
04-27 03:00:01 ERROR [backup.model.coordinator] A backup is already in progress
04-27 03:00:01 INFO [backup.model.coordinator] I'll try again in 10 seconds
04-27 03:00:11 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-27 03:00:11 INFO [backup.model.coordinator] Syncing Backups
04-27 03:00:12 INFO [backup.ha.hasource] A backup was already in progress
04-27 03:00:12 ERROR [backup.model.coordinator] A backup is already in progress
04-27 03:00:12 INFO [backup.model.coordinator] I'll try again in 20 seconds
04-27 03:00:33 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-27 03:00:33 INFO [backup.model.coordinator] Syncing Backups
04-27 03:00:34 INFO [backup.ha.hasource] A backup was already in progress
04-27 03:00:34 ERROR [backup.model.coordinator] A backup is already in progress
04-27 03:00:34 INFO [backup.model.coordinator] I'll try again in 40 seconds
04-27 03:00:42 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-27 03:01:14 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-27 03:01:14 INFO [backup.model.coordinator] Syncing Backups
04-27 03:01:14 INFO [backup.ha.hasource] A backup was already in progress
04-27 03:01:14 ERROR [backup.model.coordinator] A backup is already in progress
04-27 03:01:14 INFO [backup.model.coordinator] I'll try again in 1 minutes, 20 seconds
04-27 03:01:42 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-27 03:02:34 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-27 03:02:34 INFO [backup.model.coordinator] Syncing Backups
04-27 03:02:35 INFO [backup.ha.hasource] A backup was already in progress
04-27 03:02:35 ERROR [backup.model.coordinator] A backup is already in progress
04-27 03:02:35 INFO [backup.model.coordinator] I'll try again in 2 minutes, 40 seconds
04-27 03:04:44 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-27 03:05:15 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-27 03:05:15 INFO [backup.model.coordinator] Syncing Backups
04-27 03:05:15 INFO [backup.ha.hasource] A backup was already in progress
04-27 03:05:15 ERROR [backup.model.coordinator] A backup is already in progress
04-27 03:05:15 INFO [backup.model.coordinator] I'll try again in 5 minutes, 20 seconds
04-27 03:06:45 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-27 03:10:35 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-27 03:10:35 INFO [backup.model.coordinator] Syncing Backups
04-27 03:10:35 INFO [backup.ha.hasource] A backup was already in progress
04-27 03:10:35 ERROR [backup.model.coordinator] A backup is already in progress
04-27 03:10:35 INFO [backup.model.coordinator] I'll try again in 10 minutes, 40 seconds
04-27 03:10:46 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-27 03:21:16 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-27 03:21:16 INFO [backup.model.coordinator] Syncing Backups
04-27 03:21:16 INFO [backup.ha.hasource] A backup was already in progress
04-27 03:21:16 ERROR [backup.model.coordinator] A backup is already in progress
04-27 03:21:16 INFO [backup.model.coordinator] I'll try again in 21 minutes, 20 seconds
04-27 03:29:46 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-27 03:42:36 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-27 03:42:36 INFO [backup.model.coordinator] Syncing Backups
04-27 03:42:36 INFO [backup.ha.hasource] A backup was already in progress
04-27 03:42:36 ERROR [backup.model.coordinator] A backup is already in progress
04-27 03:42:36 INFO [backup.model.coordinator] I'll try again in 42 minutes, 40 seconds
04-27 04:01:07 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-27 04:01:07 INFO [backup.model.coordinator] Syncing Backups
04-27 04:01:07 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-27 04:01:09 INFO [backup.ha.hasource] Requesting a new backup
04-27 04:04:35 WARNING [backup.ha.hasource] A backup was already in progress
04-27 04:04:36 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-27 04:04:36 INFO [backup.model.coordinator] Syncing Backups
04-27 05:03:37 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
04-27 05:03:48 DEBUG [backup.watcher] Checking backup source for changes...
04-27 05:03:48 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
04-27 05:03:48 INFO [backup.model.coordinator] Syncing Backups
04-27 05:03:48 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-27 05:03:54 INFO [backup.ha.hasource] Requesting a new backup
04-27 05:07:05 WARNING [backup.ha.hasource] A backup was already in progress
04-27 05:07:05 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-27 05:07:05 INFO [backup.model.coordinator] Syncing Backups
04-27 07:54:56 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-27 07:54:56 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-27 08:03:54 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-27 08:03:54 INFO [backup.model.coordinator] Syncing Backups
04-27 08:03:54 INFO [backup.ha.hasource] Requesting a new backup
04-27 08:07:44 WARNING [backup.ha.hasource] A backup was already in progress
04-27 08:07:45 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-27 08:07:45 INFO [backup.model.coordinator] Syncing Backups
04-27 10:00:34 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
04-27 10:00:45 DEBUG [backup.watcher] Checking backup source for changes...
04-27 10:01:01 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-27 10:01:01 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-27 10:03:38 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
04-27 10:03:58 DEBUG [backup.watcher] Checking backup source for changes...
04-27 10:10:53 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-27 10:10:53 INFO [backup.model.coordinator] Syncing Backups
04-27 11:03:54 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-27 11:03:54 INFO [backup.model.coordinator] Syncing Backups
04-27 11:03:54 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-27 11:03:56 INFO [backup.ha.hasource] Requesting a new backup
04-27 11:06:51 WARNING [backup.ha.hasource] A backup was already in progress
04-27 11:06:52 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
04-27 11:06:52 INFO [backup.model.coordinator] Syncing Backups
04-27 12:58:39 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
04-27 12:58:55 DEBUG [backup.watcher] Checking backup source for changes...
04-27 13:08:08 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
04-27 13:08:08 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
04-27 13:17:23 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-27 13:17:23 INFO [backup.model.coordinator] Syncing Backups`

**Comment by sabeechen** [comment]
I suspect there is something in the Supervisor logs that could explain whats happening.  The supervisor is a part of Home Assistant, most importantly its what actually creates the backup.  To see its logs you'll need to:

- Enable "Advanced Mode" in your Home Assistant user profile (you might already have turned it on in the past).  You can get to the profile page by clicking your user icon in the bottom left of the Home Assistant UI.
- Restart the add-on, and wait for the ```A backup was already in progress``` error to show up in the logs again.
- Navigate to ```Settings``` > ```System``` > ```Logs``` > ```Supervisor``` (top right drop down)
Its very likely there is a warning or error on that logs page that will explain whats going wrong.

**Comment by Christianb233** [comment]
Hello @sabeechen thank you for your reply.
Here is the log of the supervisor (right now I meet a "netatmo integration" issue but I don't understand why it could block a snapshot which should not start in the afternoon 

`23-04-28 18:58:22 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon 75a80a57_rtsp_simple_server
23-04-28 18:58:23 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on 15d21743_samba_backup
23-04-28 18:58:23 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon 15d21743_samba_backup
23-04-28 18:58:24 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on ba124dcc_samba
23-04-28 18:58:24 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon ba124dcc_samba
23-04-28 18:58:25 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_ssh
23-04-28 18:58:25 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_ssh
23-04-28 18:58:26 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on 45df7312_zigbee2mqtt
23-04-28 18:58:26 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon 45df7312_zigbee2mqtt
23-04-28 18:58:33 INFO (SyncWorker_1) [supervisor.docker.addon] Export image ec247e54/aarch64-addon-ha_enoceanmqtt to /data/tmp/tmpe2etdcit/image.tar
23-04-28 18:58:34 INFO (SyncWorker_1) [supervisor.docker.addon] Export image ec247e54/aarch64-addon-ha_enoceanmqtt done
23-04-28 18:58:35 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on ec247e54_ha_enoceanmqtt
23-04-28 19:00:19 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon ec247e54_ha_enoceanmqtt
23-04-28 19:00:21 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on ccab4aaf_frigate-fa
23-04-28 19:00:21 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon ccab4aaf_frigate-fa
23-04-28 19:00:25 INFO (MainThread) [supervisor.homeassistant.module] Backing up Home Assistant Core config folder
23-04-28 19:00:27 ERROR (MainThread) [supervisor.homeassistant.module] Can't backup Home Assistant Core config folder: [Errno 74] Bad message: '/data/homeassistant/www/netatmo/bouton_fond-300x98.png'
23-04-28 19:00:28 ERROR (MainThread) [supervisor.backups.manager] Backup aeca3f6c error
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 341, in backup
    await self.sys_run_in_executor(_write_tarfile)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 332, in _write_tarfile
    atomic_contents_add(
  File "/usr/local/lib/python3.10/site-packages/securetar/__init__.py", line 188, in atomic_contents_add
    atomic_contents_add(tar_file, directory_item, excludes, arcpath)
  File "/usr/local/lib/python3.10/site-packages/securetar/__init__.py", line 188, in atomic_contents_add
    atomic_contents_add(tar_file, directory_item, excludes, arcpath)
  File "/usr/local/lib/python3.10/site-packages/securetar/__init__.py", line 187, in atomic_contents_add
    if directory_item.is_dir() and not directory_item.is_symlink():
  File "/usr/local/lib/python3.10/pathlib.py", line 1305, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/usr/local/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
OSError: [Errno 74] Bad message: '/data/homeassistant/www/netatmo/bouton_fond-300x98.png'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 167, in _do_backup
    await backup.store_homeassistant()
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 497, in store_homeassistant
    await self.sys_homeassistant.backup(homeassistant_file)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 156, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 344, in backup
    raise HomeAssistantBackupError(
supervisor.exceptions.HomeAssistantBackupError: Can't backup Home Assistant Core config folder: [Errno 74] Bad message: '/data/homeassistant/www/netatmo/bouton_fond-300x98.png'
23-04-28 19:00:28 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-04-28 19:00:28 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
23-04-28 19:03:43 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-04-28 19:33:44 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-04-28 19:45:37 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'Christian1'
23-04-28 19:45:37 INFO (MainThread) [supervisor.auth] Successful login for 'Christian1'
23-04-28 19:50:03 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
23-04-28 19:50:03 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM
23-04-28 19:50:03 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
23-04-28 19:50:04 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
23-04-28 19:50:04 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
23-04-28 19:50:04 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
23-04-28 19:51:19 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
23-04-28 19:51:19 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.MULTIPLE_DATA_DISKS/ContextType.SYSTEM
23-04-28 19:52:34 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
23-04-28 19:52:34 INFO (MainThread) [supervisor.resolution.check] System checks complete
23-04-28 19:52:34 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
23-04-28 19:52:34 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
23-04-28 19:52:34 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
23-04-28 19:52:34 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
23-04-28 20:03:44 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-04-28 20:33:44 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
23-04-28 20:45:59 INFO (MainThread) [supervisor.host.info] Updating local host information
23-04-28 20:45:59 INFO (MainThread) [supervisor.host.services] Updating service information
23-04-28 20:45:59 INFO (MainThread) [supervisor.host.network] Updating local network information
23-04-28 20:46:00 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
23-04-28 20:46:00 INFO (MainThread) [supervisor.host.manager] Host information reload completed`

**Comment by sabeechen** [comment]
The error here is the cause (formatted for clarity):
```
23-04-28 19:00:25 INFO (MainThread) [supervisor.homeassistant.module] Backing up Home Assistant Core config folder
23-04-28 19:00:27 ERROR (MainThread) [supervisor.homeassistant.module] Can't backup Home Assistant Core config folder: [Errno 74] Bad message: '/data/homeassistant/www/netatmo/bouton_fond-300x98.png' 
23-04-28 19:00:28 ERROR (MainThread) [supervisor.backups.manager] Backup aeca3f6c error Traceback (most recent call last): 
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 341, in backup await self.sys_run_in_executor(_write_tarfile) 
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) 
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 332, in _write_tarfile atomic_contents_add( 
  File "/usr/local/lib/python3.10/site-packages/securetar/__init__.py", line 188, in atomic_contents_add atomic_contents_add(tar_file, directory_item, excludes, arcpath) 
  File "/usr/local/lib/python3.10/site-packages/securetar/__init__.py", line 188, in atomic_contents_add atomic_contents_add(tar_file, directory_item, excludes, arcpath) 
  File "/usr/local/lib/python3.10/site-packages/securetar/__init__.py", line 187, in atomic_contents_add if directory_item.is_dir() and not directory_item.is_symlink(): 
  File "/usr/local/lib/python3.10/pathlib.py", line 1305, in is_dir return S_ISDIR(self.stat().st_mode) 
  File "/usr/local/lib/python3.10/pathlib.py", line 1097, in stat return self._accessor.stat(self, follow_symlinks=follow_symlinks) 
  OSError: [Errno 74] Bad message: '/data/homeassistant/www/netatmo/bouton_fond-300x98.png' 

  The above exception was the direct cause of the following exception: Traceback (most recent call last): 
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 167, in _do_backup await backup.store_homeassistant() 
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 497, in store_homeassistant await self.sys_homeassistant.backup(homeassistant_file) 
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 156, in wrapper raise err 
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper return await self._method(*args, **kwargs) 
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 344, in backup raise HomeAssistantBackupError( supervisor.exceptions.HomeAssistantBackupError: Can't backup Home Assistant Core config folder: [Errno 74] Bad message: '/data/homeassistant/www/netatmo/bouton_fond-300x98.png' 23-04-28 19:00:28 INFO (MainThread) 
```

It looks like the backup fails on the file ```/data/homeassistant/www/netatmo/bouton_fond-300x98.png``` with the error ```[Errno 74] Bad message```.  Due to some limitations in Home Assistant's API, this addon can't tell the difference between a backup that errors out and one that is already in progress (Home Assistant always says the same thing back), which is why the addon just assumes one is in progress.

As for what ```[Errno 74]  Bad message``` means, I'm not familiar with it but some Google searching leads me to think you might have disk corruption (ie a corrupt SD card).  Do you have a good backup you could restore from on a fresh SD card?  If its corruption, then you're likely to lose more and more data as the card continues to die.
