### ISSUE TITLE
Google Drive is Full Error, when I have enough free space

### ISSUE THREAD

**Issue by andordavoti** [sabeechen/hassio-google-drive-backup#841]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.110.4`
 Home Assistant Version: `2023.4.4`
 Supervisor Version: `2023.04.1`
 Supervisor Channel: `stable`
 Hassos Version: `10.1`
 Docker Version: `23.0.3`
 Architecture: `amd64`
 Machine: `generic-x86-64`
 Date: `2023-04-29T14:39:29.597532+00:00`
 Timezone: `Europe/Oslo`
 Failure Time: `2023-04-29T14:39:09.922485+00:00`
 Last Good Sync: `2023-04-29T14:39:08.864168+00:00`
 Next Sync: `2023-04-29T16:39:09.922485+00:00`
 Next Backup: `2023-04-30T03:00:00+00:00`
 Next Cache Warm: `2023-04-29T16:38:49.158126+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:246 (sync)
  addon/backup/drive/drivesource.py:202 (save)
  addon/backup/drive/driverequests.py:259 (create)
  addon/backup/drive/driverequests.py:363 (retryRequest)
  addon/backup/creds/driverequester.py:32 (request)
  addon/backup/creds/driverequester.py:111 (raiseForKnownErrors)
backup.exceptions.exceptions.DriveQuotaExceeded

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 15,
        "retained": 0,
        "deletable": 15,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-04-29T03:41:52Z",
        "max": 15,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 87,
        "detail": "",
        "size": "71.6 GB",
        "ignored_size": "999.4 MB",
        "free_space": "115.7 GB"
    },
    "GoogleDrive": {
        "backups": 3,
        "retained": 0,
        "deletable": 3,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-04-16T03:00:00Z",
        "max": 3,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "andor.davoti@gmail.com",
        "size": "105.0 MB",
        "ignored_size": "0.0 B",
        "free_space": "5.1 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 15,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 3,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.BACKUP_TIME_OF_DAY": "05:00",
    "Setting.SPECIFY_BACKUP_FOLDER": true,
    "Setting.SEND_ERROR_REPORTS": true,
    "Setting.BACKGROUND_COLOR": "#000000",
    "Setting.ACCENT_COLOR": "#4e7a27"
}
 ```
 ###### Addon Logs:
 ```
 04-29 16:37:08 INFO [backup.model.coordinator] Syncing Backups
04-29 16:37:09 INFO [backup.drive.drivesource] Uploading 'Full Backup 2023-04-29 05:41:52' to Google Drive
04-29 16:37:09 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
04-29 16:37:09 ERROR [backup.model.coordinator] Google Drive is out of space
04-29 16:37:09 INFO [backup.model.coordinator] I'll try again in 2 hours
04-29 16:37:09 INFO [backup.model.coordinator] Syncing Backups
04-29 16:37:10 INFO [backup.drive.drivesource] Uploading 'Full Backup 2023-04-29 05:41:52' to Google Drive
04-29 16:37:10 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
04-29 16:37:10 ERROR [backup.model.coordinator] Google Drive is out of space
04-29 16:37:10 INFO [backup.model.coordinator] I'll try again in 2 hours
04-29 16:37:21 DEBUG [backup.watcher] Checking backup source for changes...
04-29 16:38:09 INFO [backup.model.coordinator] Syncing Backups
04-29 16:38:10 INFO [backup.drive.drivesource] Uploading 'Full Backup 2023-04-29 05:41:52' to Google Drive
04-29 16:38:10 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
04-29 16:38:10 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
04-29 16:38:10 ERROR [backup.model.coordinator] Google Drive is out of space
04-29 16:38:10 INFO [backup.model.coordinator] I'll try again in 2 hours
04-29 16:38:17 INFO [backup.model.coordinator] Syncing Backups
04-29 16:38:17 INFO [backup.drive.drivesource] Uploading 'Full Backup 2023-04-29 05:41:52' to Google Drive
04-29 16:38:17 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
04-29 16:38:18 ERROR [backup.model.coordinator] Google Drive is out of space
04-29 16:38:18 INFO [backup.model.coordinator] I'll try again in 2 hours
04-29 16:38:27 DEBUG [backup.watcher] Checking backup source for changes...
04-29 16:39:08 INFO [backup.model.coordinator] Syncing Backups
04-29 16:39:09 INFO [backup.drive.drivesource] Uploading 'Full Backup 2023-04-29 05:41:52' to Google Drive
04-29 16:39:09 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
04-29 16:39:09 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
04-29 16:39:09 ERROR [backup.model.coordinator] Google Drive is out of space
04-29 16:39:09 INFO [backup.model.coordinator] I'll try again in 2 hours
04-29 16:39:19 DEBUG [backup.watcher] Checking backup source for changes...
 ```
 ###### Supervisor Logs:
 ```
 [32m23-04-29 16:37:08 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:37:09 INFO (MainThread) [supervisor.api.middleware.security] /backups/ae33660a/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:37:09 INFO (MainThread) [supervisor.api.backups] Downloading backup ae33660a[0m
[32m23-04-29 16:37:09 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:37:09 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:37:10 INFO (MainThread) [supervisor.api.middleware.security] /backups/ae33660a/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:37:10 INFO (MainThread) [supervisor.api.backups] Downloading backup ae33660a[0m
[32m23-04-29 16:37:21 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:37:21 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:38:09 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:38:09 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:38:10 INFO (MainThread) [supervisor.api.middleware.security] /backups/ae33660a/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:38:10 INFO (MainThread) [supervisor.api.backups] Downloading backup ae33660a[0m
[32m23-04-29 16:38:17 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:38:17 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:38:17 INFO (MainThread) [supervisor.api.middleware.security] /backups/ae33660a/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:38:17 INFO (MainThread) [supervisor.api.backups] Downloading backup ae33660a[0m
[32m23-04-29 16:38:27 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:38:27 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:39:08 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:39:08 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:39:09 INFO (MainThread) [supervisor.api.middleware.security] /backups/ae33660a/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:39:09 INFO (MainThread) [supervisor.api.backups] Downloading backup ae33660a[0m
[32m23-04-29 16:39:19 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:39:19 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:39:22 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:39:22 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:39:22 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup[0m
[32m23-04-29 16:39:29 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/src/homeassistant/homeassistant/components/sonos/switch.py", line 258, in name
    f"{self.alarm.recurrence.capitalize()} alarm"
AttributeError: 'NoneType' object has no attribute 'recurrence'
[0m
[31m2023-04-29 16:35:37.298 ERROR (MainThread) [homeassistant.util.logging] Exception in async_write_ha_state when dispatching 'sonos_state_updated-RINCON_542A1B5BA7B401400': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in _async_write_ha_state
    name := (entry and entry.name) or self._friendly_name_internal()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in _friendly_name_internal
    if not (name := self.name):
  File "/usr/src/homeassistant/homeassistant/components/sonos/switch.py", line 258, in name
    f"{self.alarm.recurrence.capitalize()} alarm"
AttributeError: 'NoneType' object has no attribute 'recurrence'
[0m
[31m2023-04-29 16:35:37.304 ERROR (MainThread) [homeassistant.util.logging] Exception in async_write_ha_state when dispatching 'sonos_state_updated-RINCON_542A1B5BA7B401400': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in _async_write_ha_state
    name := (entry and entry.name) or self._friendly_name_internal()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in _friendly_name_internal
    if not (name := self.name):
  File "/usr/src/homeassistant/homeassistant/components/sonos/switch.py", line 258, in name
    f"{self.alarm.recurrence.capitalize()} alarm"
AttributeError: 'NoneType' object has no attribute 'recurrence'
[0m
[33m2023-04-29 16:35:56.186 WARNING (MainThread) [homeassistant.components.media_player] Error retrieving proxied image from http://192.168.1.4:1400/getaa?u=x-file-cifs://homeassistant/media/Mac%2520Miller%2520-%2520Swimming/01-mac_miller-come_back_to_earth.flac&v=2[0m

 ```

**Comment by sabeechen** [comment]
How big is you're most recent backup in Home Asisstant?    If its bigger than the 5.1 GB you have in Google Drive, thats the problem.

**Comment by andordavoti** [comment]
> How big is you're most recent backup in Home Asisstant?    If its bigger than the 5.1 GB you have in Google Drive, thats the problem.

Yeah, sorry about that, my bad. Of course that's the issue. Thank you for developing this addon:)

**Comment by andordavoti** [comment]
I see that this is because I recently filled up my media folder with music. I read in the readme that excluding folders is not possible today with this addon. However it is possible from the web ui now, not sure if that's new and would make it easier to implement for this addon now?

**Comment by sabeechen** [comment]
You can exclude the /media folder from backups, check the settings under "Partial Backups".  What it *can't* do is exclude only *part* of the /media folder.  You can either include or exclude the whole thing, which is a Home Assistant limitation.

**Comment by andordavoti** [comment]
Awesome! Thanks for the help sorting this out, much appreciated:)
