### ISSUE TITLE
Please add a title

### ISSUE THREAD

**Issue by thatslolo** [sabeechen/hassio-google-drive-backup#853]
###### Description:

When starting a backup with 2023.06b, the backup doesn't get made and I get the following errors in supervisor logs.

I already tried rebooting and reinstalling of the addon.
When triggering the backup through HA core it gets made and can be accessed through the addon to upload it.

```

23-06-04 12:03:22 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret pw_backups
23-06-04 12:03:22 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup
23-06-04 12:03:22 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-06-04 12:03:22 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup
23-06-04 12:03:22 INFO (MainThread) [supervisor.api.middleware.security] /backups/new/full access from cebe7a76_hassio_google_drive_backup
23-06-04 12:03:22 ERROR (MainThread) [supervisor.jobs] Unhandled exception: OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 234, in do_backup_full
    backup = self._create_backup(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 108, in _create_backup
    backup.new(slug, name, date_str, sys_type, password, compressed)
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 192, in new
    self._init_password(password)
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 212, in _init_password
    backend=default_backend(),
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/backends/__init__.py", line 11, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 27, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 167, in <module>
    Binding.init_static_locks()
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 134, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 123, in _ensure_ffi_initialized
    _legacy_provider_error(cls._legacy_provider_loaded)
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 43, in _legacy_provider_error
    raise RuntimeError(
RuntimeError: OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.
23-06-04 12:03:23 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-06-04 12:03:23 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
23-06-04 12:05:13 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret pw_backups
23-06-04 12:05:17 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret pw_backups
23-06-04 12:07:30 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret pw_backups
23-06-04 12:08:21 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Set of Tasks/Futures is empty.
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/mounts/manager.py", line 145, in reload
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 408, in wait
    raise ValueError('Set of Tasks/Futures is empty.')
ValueError: Set of Tasks/Futures is empty.
```

 Addon version: `0.110.4`
 Home Assistant Version: `2023.6.0b4`
 Supervisor Version: `2023.06.0`
 Supervisor Channel: `beta`
 Hassos Version: `10.2`
 Docker Version: `23.0.6`
 Architecture: `aarch64`
 Machine: `yellow`
 Date: `2023-06-04T10:14:40.117547+00:00`
 Timezone: `Europe/Berlin`
 Failure Time: `2023-06-04T10:03:22.970303+00:00`
 Last Good Sync: `2023-06-04T10:03:23.490635+00:00`
 Next Sync: `2023-06-04T12:11:21.701888+00:00`
 Next Backup: `2023-06-05T01:00:00+00:00`
 Next Cache Warm: `2023-06-04T11:58:19.621506+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 12,
        "retained": 0,
        "deletable": 12,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-06-04T10:03:22Z",
        "max": 15,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 20,
        "detail": "",
        "size": "16.8 GB",
        "ignored_size": "2.5 GB",
        "free_space": "406.4 GB"
    },
    "GoogleDrive": {
        "backups": 3,
        "retained": 0,
        "deletable": 3,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-05-31T01:00:00Z",
        "max": 3,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "lorenz.spenger@googlemail.com",
        "size": "4.8 GB",
        "ignored_size": "0.0 B",
        "free_space": "10.1 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 15,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 3,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.IGNORE_OTHER_BACKUPS": true,
    "Setting.DELETE_IGNORED_AFTER_DAYS": 14.0,
    "Setting.BACKUP_TIME_OF_DAY": "03:00",
    "Setting.BACKUP_PASSWORD": "REDACTED",
    "Setting.GENERATIONAL_DAYS": 3,
    "Setting.GENERATIONAL_WEEKS": 2,
    "Setting.GENERATIONAL_MONTHS": 2,
    "Setting.GENERATIONAL_YEARS": 2,
    "Setting.MAXIMUM_UPLOAD_CHUNK_BYTES": 20971520.0
}
 ```
 ###### Addon Logs:
 ```
 06-04 11:53:23 INFO [backup.ui.uiserver] Starting server on port 8099
06-04 11:53:23 INFO [backup.ui.uiserver] Server started
06-04 11:53:23 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-04 11:53:23 INFO [backup.model.coordinator] Syncing Backups
06-04 11:53:23 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-04 12:01:23 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
06-04 12:03:22 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-04 12:03:22 INFO [backup.model.coordinator] Syncing Backups
06-04 12:03:22 INFO [backup.ha.hasource] Requesting a new backup
06-04 12:03:22 WARNING [backup.ha.hasource] A backup was already in progress
06-04 12:03:22 ERROR [backup.model.coordinator] A backup is already in progress
06-04 12:03:22 INFO [backup.model.coordinator] I'll try again in 0 seconds
06-04 12:03:23 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-04 12:03:23 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
06-04 12:03:23 INFO [backup.model.coordinator] Syncing Backups
 ```
 ###### Supervisor Logs:
 ```
     from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 27, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 167, in <module>
    Binding.init_static_locks()
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 134, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 123, in _ensure_ffi_initialized
    _legacy_provider_error(cls._legacy_provider_loaded)
  File "/usr/local/lib/python3.11/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 43, in _legacy_provider_error
    raise RuntimeError(
RuntimeError: OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.
[32m23-06-04 12:03:23 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-06-04 12:03:23 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-06-04 12:05:13 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret pw_backups[0m
[32m23-06-04 12:05:17 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret pw_backups[0m
[32m23-06-04 12:07:30 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret pw_backups[0m
[31m23-06-04 12:08:21 ERROR (MainThread) [supervisor.jobs] Unhandled exception: Set of Tasks/Futures is empty.[0m
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/mounts/manager.py", line 145, in reload
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 408, in wait
    raise ValueError('Set of Tasks/Futures is empty.')
ValueError: Set of Tasks/Futures is empty.
[32m23-06-04 12:12:36 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret pw_backups[0m
[32m23-06-04 12:14:40 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     metadata_ids = _extract_metadata_and_discard_impossible_columns(metadata, types)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 1526, in _extract_metadata_and_discard_impossible_columns
    types.discard("mean")
    ^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'discard'[0m
[31m2023-06-04 12:14:31.689 ERROR (MainThread) [frontend.js.latest.202306011] :0:0 Script error.[0m

 ```

**Comment by Poshy163** [comment]
Hey mate, just checking if its related at all my issue #852, as removing the network storage seemed to resolve the issue.

**Comment by sabeechen** [comment]
In the unreleased next version of the supervisor it looks like the cryptography library [was updated to 41](https://github.com/home-assistant/supervisor/commit/fe5705b35b8e8a94e5dddfff7bd814c0340b7374).  This version introduced some [backwards incompatible changes](https://cryptography.io/en/latest/changelog/#v41-0-0), though I don't know enough the supervisor build environment to be sure its the problem.  If it is I don't think disabling mounts will fix it, the error happens initializing encryption parameters to create a password protected backup.

This looks to me like an internal problem with a beta version of the supervisor, so I'm going to close it.  If there is something you think I can do to help from this addon's side of things or I'm misunderstanding, please reopen and let me know how I can help.

**Comment by thatslolo** [comment]
Issue has been resolved on HA side.
home-assistant/supervisor#4339
