### ISSUE TITLE
Unable to access web ui with 0.98.1

### ISSUE THREAD

**Issue by sabeechen** [sabeechen/hassio-google-drive-backup#86]
From a thread on the forum:

> Hi @sabeechen just updated to the latest version.
> I receive this error when opening the web ui.
> 401 Unauthorized

```
You are not authorized to access that resource

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 684, in _do_respond
    self.hooks.run('before_handler')
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/usr/lib/python3.7/site-packages/cherrypy/lib/auth_basic.py", line 111, in basic_auth
    401, 'You are not authorized to access that resource')
cherrypy._cperror.HTTPError: (401, 'You are not authorized to access that resource')
Powered by CherryPy 18.1.2
```
> 
> 
> When navigating to http:\hass.io-ip:1627 or https:\hass.io-ip:1627 the website cannot be reached.
> If i enable ingress by removing the port from the add-on settings page i receive the same error when opening the addon via the sidebar.

**Comment by sabeechen** [comment]
Could anyone getting this error get me a copy of their add-on configuration?

**Comment by sabeechen** [comment]
Ah actually someone already opened an issue for this, #83
