### ISSUE TITLE
An unexpected error occurred: Server disconnected

### ISSUE THREAD

**Issue by dlasher** [sabeechen/hassio-google-drive-backup#860]
Backup appears to have been failing since the 2023.6 upgrade.

###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.110.4`
 Home Assistant Version: `2023.6.1`
 Supervisor Version: `2023.06.1`
 Supervisor Channel: `stable`
 Hassos Version: `None`
 Docker Version: `24.0.2`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2023-06-11T18:53:59.569463+00:00`
 Timezone: `America/Los_Angeles`
 Failure Time: `2023-06-11T17:03:58.076458+00:00`
 Last Good Sync: `2023-06-11T17:03:56.706019+00:00`
 Next Sync: `2023-06-11T19:03:58.076458+00:00`
 Next Backup: `2023-06-14T11:00:00+00:00`
 Next Cache Warm: `2023-06-11T18:57:08.277116+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:246 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 10,
        "retained": 0,
        "deletable": 10,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-06-11T12:45:54Z",
        "max": 10,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "detail": "",
        "size": "4.2 GB",
        "ignored_size": "0.0 B",
        "free_space": "8.3 GB"
    },
    "GoogleDrive": {
        "backups": 25,
        "retained": 0,
        "deletable": 25,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-06-07T22:00:12Z",
        "max": 25,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "*********@gmail.com",
        "size": "11.7 GB",
        "ignored_size": "0.0 B",
        "free_space": "3.3 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 10,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 25,
    "Setting.IGNORE_UPGRADE_BACKUPS": false,
    "Setting.BACKUP_TIME_OF_DAY": "04:00",
    "Setting.IGNORE_IPV6_ADDRESSES": true
}
 ```
 ###### Addon Logs:
 ```
 06-11 05:38:39 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
06-11 05:38:39 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-11 05:45:54 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-11 05:45:54 INFO [backup.model.coordinator] Syncing Backups
06-11 05:45:54 INFO [backup.ha.hasource] Requesting a new backup
06-11 05:45:59 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:246 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-11 05:45:59 INFO [backup.model.coordinator] I'll try again in 2 hours
06-11 06:03:44 INFO [backup.ha.hasource] Backup finished
06-11 06:03:45 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
06-11 06:03:45 INFO [backup.model.coordinator] Syncing Backups
06-11 06:03:45 INFO [backup.ha.hasource] Deleting 'Full Backup 2023-05-24 04:00:00' from Home Assistant
06-11 06:03:45 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
06-11 06:03:45 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:246 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-11 06:03:45 INFO [backup.model.coordinator] I'll try again in 2 hours
06-11 06:03:55 DEBUG [backup.watcher] Checking backup source for changes...
06-11 06:03:55 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
06-11 06:03:55 INFO [backup.model.coordinator] Syncing Backups
06-11 06:03:56 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:246 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-11 06:03:56 INFO [backup.model.coordinator] I'll try again in 2 hours
06-11 07:57:41 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
06-11 07:57:41 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-11 08:03:56 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-11 08:03:56 INFO [backup.model.coordinator] Syncing Backups
06-11 08:03:56 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:246 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-11 08:03:56 INFO [backup.model.coordinator] I'll try again in 2 hours
06-11 10:03:56 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-11 10:03:56 INFO [backup.model.coordinator] Syncing Backups
06-11 10:03:56 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-11 10:03:58 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:246 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-11 10:03:58 INFO [backup.model.coordinator] I'll try again in 2 hours
 ```
 ###### Supervisor Logs:
 ```
 [32m23-06-11 10:55:52 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m23-06-11 10:55:52 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.MULTIPLE_DATA_DISKS/ContextType.SYSTEM[0m
[32m23-06-11 10:55:52 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER[0m
[32m23-06-11 10:55:52 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m
[32m23-06-11 10:55:52 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM[0m
[32m23-06-11 10:55:52 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DOCKER_CONFIG/ContextType.SYSTEM[0m
[32m23-06-11 10:55:52 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM[0m
[32m23-06-11 10:56:02 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER[0m
[32m23-06-11 10:56:02 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m23-06-11 10:56:02 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m23-06-11 10:56:02 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m23-06-11 10:56:02 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-06-11 10:56:02 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m23-06-11 10:56:02 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m




[32m23-06-11 11:13:01 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m






[32m23-06-11 11:43:02 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m


[32m23-06-11 11:53:59 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 [32m2023-06-11 11:50:03.524 INFO (MainThread) [AIOAladdinConnect.session_manager] Updating door status[0m
[32m2023-06-11 11:50:03.526 INFO (MainThread) [AIOAladdinConnect.session_manager] Updating door status[0m
[32m2023-06-11 11:50:04.416 INFO (MainThread) [custom_components.winix.manager] Updating devices[0m
[32m2023-06-11 11:50:07.612 INFO (MainThread) [homeassistant.components.automation.motion_front_rpi_day_off] Motion.Front.RPI.Day.Off: Executing step call service[0m
[32m2023-06-11 11:50:07.641 INFO (MainThread) [homeassistant.components.automation.motion_front_rpi_day_off] Motion.Front.RPI.Day.Off: Executing step call service[0m
[32m2023-06-11 11:50:07.672 INFO (MainThread) [homeassistant.components.automation.motion_front_rpi_day_off] Motion.Front.RPI.Day.Off: Executing step call service[0m
[32m2023-06-11 11:50:07.705 INFO (MainThread) [homeassistant.components.automation.motion_front_rpi_day_off] Motion.Front.RPI.Day.Off: Executing step call service[0m
[32m2023-06-11 11:50:07.739 INFO (MainThread) [homeassistant.components.automation.motion_front_rpi_day_off] Motion.Front.RPI.Day.Off: Executing step call service[0m
[31m2023-06-11 11:50:07.758 ERROR (MainThread) [homeassistant.components.shell_command] Error running command: `/usr/bin/curl {{ url }}`, return code: 7
NoneType: None[0m
[32m2023-06-11 11:50:07.759 INFO (MainThread) [homeassistant.components.automation.motion_front_rpi_day_off] Motion.Front.RPI.Day.Off: Executing step call service[0m
[32m2023-06-11 11:50:34.415 INFO (MainThread) [custom_components.winix.manager] Updating devices[0m
[32m2023-06-11 11:51:04.415 INFO (MainThread) [custom_components.winix.manager] Updating devices[0m
[32m2023-06-11 11:51:34.415 INFO (MainThread) [custom_components.winix.manager] Updating devices[0m
[32m2023-06-11 11:52:04.415 INFO (MainThread) [custom_components.winix.manager] Updating devices[0m
[32m2023-06-11 11:52:34.416 INFO (MainThread) [custom_components.winix.manager] Updating devices[0m
[32m2023-06-11 11:52:40.090 INFO (MainThread) [AIOAladdinConnect.eventsocket] Stopping receiving. Message type: 257[0m
[32m2023-06-11 11:52:40.090 INFO (MainThread) [AIOAladdinConnect.eventsocket] Reconnecting...[0m
[32m2023-06-11 11:52:40.090 INFO (MainThread) [AIOAladdinConnect.eventsocket] Started the web socket[0m
[32m2023-06-11 11:52:40.434 INFO (MainThread) [AIOAladdinConnect.eventsocket] Opened the web socket with header {'Authorization': 'Bearer A212FF48CB221C93'}[0m
[32m2023-06-11 11:52:40.434 INFO (MainThread) [AIOAladdinConnect.eventsocket] waiting for message[0m
[32m2023-06-11 11:53:01.222 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: sensor Acurite-606TX-162 Acurite-606TX-162-UTC[0m
[32m2023-06-11 11:53:01.223 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor Acurite-606TX-162 Acurite-606TX-162-B, sending update[0m
[32m2023-06-11 11:53:01.223 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor Acurite-606TX-162 Acurite-606TX-162-T, sending update[0m
[32m2023-06-11 11:53:01.223 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor Acurite-606TX-162 Acurite-606TX-162-rssi, sending update[0m
[32m2023-06-11 11:53:01.223 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor Acurite-606TX-162 Acurite-606TX-162-snr, sending update[0m
[32m2023-06-11 11:53:01.224 INFO (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor Acurite-606TX-162 Acurite-606TX-162-noise, sending update[0m
[32m2023-06-11 11:53:04.416 INFO (MainThread) [custom_components.winix.manager] Updating devices[0m
[32m2023-06-11 11:53:34.416 INFO (MainThread) [custom_components.winix.manager] Updating devices[0m

 ```

**Comment by MTrab** [comment]
+1

**Comment by mweedon** [comment]
+1

**Comment by dselzle** [comment]
@sabeechen Getting the same issue here after updating to 2023.6 and adding a Network Storage mount as my default backup location for HA. Supervisor logs when I sync:

```
23-06-12 15:26:36 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-06-12 15:26:36 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
23-06-12 15:26:36 INFO (MainThread) [supervisor.api.middleware.security] /backups/d6c8be18/download access from cebe7a76_hassio_google_drive_backup
23-06-12 15:26:36 INFO (MainThread) [supervisor.api.backups] Downloading backup d6c8be18
23-06-12 15:26:36 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 512, in start
    resp, reset = await task
                  ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 458, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 611, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_fileresponse.py", line 142, in prepare
    st: os.stat_result = await loop.run_in_executor(None, filepath.stat)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/mounts/MyMountName/d6c8be18.tar'
```

That mounted directory is empty. I don't see a .tar with that filename in the local /backup directory either.

**Comment by sabeechen** [comment]
I think you're seeing a different issue, I'd guess its caused by either:
 - HA is having trouble reading your share.
 - The backup file HA created got deleted by something else.

But whatever it is, its not something the addon has control over.  If HA can't retrieve the backup, then the addon isn't going to be able to.

**Comment by nukleuz80** [comment]
I had the same error. Sorry for double post. 

I deletet the network storage and the backups runs again.

**Comment by MTrab** [comment]
Go to the `Google Drive add-on web-ui > Settings`
Change `Home Assistant Backup Location` to the specified backup location you use, rather than the default.
This has solved the issue for me at least, even when using network storage.

**Comment by dlasher** [comment]
Can confirm that deleting the network "backup" storage allows Google Drive backup to complete.

Will try changing backup location next.

**Comment by dselzle** [comment]
I found that I had a permissions issue with my network share. HA didn't show me any errors when configuring it, but after some _chmod_ work, the addon worked fine.

**Comment by sabeechen** [comment]
I suspect that when Home Assistant has trouble with backups on a network share there are a range of errors it will return, everything from rejecting the addon's API call outright to accepting it but then terminating the connection abruptly (as was seen here a couple times).  I'm not sure if I can do anything about this from the addon's side except provide some better help information, since the supervisor logs is the only place you're going to get any useful information about what went wrong.

Its worse because the supervisor logs aren't visible to users by default unless they enable "advanced mode" in their user profile, its not a great situation for the average user to be in.

**Comment by smytangel** [comment]
I had the same error.

I deletet the network storage and the backups runs again.

**Comment by IanMajor12** [comment]
Same solution for me, delete the network share and the backups started running again. I'll test the network share again someday soon.
