### ISSUE TITLE
Error: An unexpected error occurred: Server disconnected

### ISSUE THREAD

**Issue by nukleuz80** [sabeechen/hassio-google-drive-backup#875]
Hi there,

i have an issue since a few days and don´t know how to solve it.

###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.111.1`
 Home Assistant Version: `2023.6.2`
 Supervisor Version: `2023.06.2`
 Supervisor Channel: `stable`
 Hassos Version: `10.3`
 Docker Version: `23.0.6`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2023-06-23T07:13:22.431414+00:00`
 Timezone: `Europe/Berlin`
 Failure Time: `2023-06-23T05:20:44.894237+00:00`
 Last Good Sync: `2023-06-23T05:20:44.841846+00:00`
 Next Sync: `2023-06-23T07:20:44.894237+00:00`
 Next Backup: `2023-06-25T20:11:28.433016+00:00`
 Next Cache Warm: `2023-06-23T07:18:50.200763+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 3,
        "retained": 0,
        "deletable": 3,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-06-22T20:11:28Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 6,
        "detail": "",
        "size": "4.3 GB",
        "ignored_size": "1.2 GB"
    },
    "GoogleDrive": {
        "backups": 2,
        "retained": 0,
        "deletable": 2,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-06-07T16:27:44Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "xxx@gmail.com",
        "size": "4.3 GB",
        "ignored_size": "0.0 B",
        "free_space": "8.4 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 06-22 23:12:42 INFO [backup.model.coordinator] I'll try again in 42 minutes, 40 seconds
06-22 23:50:22 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
06-22 23:50:22 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-22 23:55:22 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-22 23:55:22 INFO [backup.model.coordinator] Syncing Backups
06-22 23:55:22 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-22 23:55:22 INFO [backup.model.coordinator] I'll try again in 1 hours, 25 minutes, 20 seconds
06-23 01:20:42 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-23 01:20:42 INFO [backup.model.coordinator] Syncing Backups
06-23 01:20:42 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-23 01:20:44 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-23 01:20:44 INFO [backup.model.coordinator] I'll try again in 2 hours
06-23 03:20:24 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
06-23 03:20:24 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-23 03:20:44 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-23 03:20:44 INFO [backup.model.coordinator] Syncing Backups
06-23 03:20:44 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-23 03:20:44 INFO [backup.model.coordinator] I'll try again in 2 hours
06-23 05:13:25 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
06-23 05:13:25 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-23 05:20:44 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-23 05:20:44 INFO [backup.model.coordinator] Syncing Backups
06-23 05:20:44 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-23 05:20:44 INFO [backup.model.coordinator] I'll try again in 2 hours
06-23 07:19:26 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
06-23 07:19:26 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-23 07:20:44 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-23 07:20:44 INFO [backup.model.coordinator] Syncing Backups
06-23 07:20:44 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

06-23 07:20:44 INFO [backup.model.coordinator] I'll try again in 2 hours
 ```
 ###### Supervisor Logs:
 ```
 [32m23-06-23 08:14:09 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[33m23-06-23 08:14:11 WARNING (SyncWorker_4) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of DeskPi Pro Active Cooling[0m
[33m23-06-23 08:14:13 WARNING (SyncWorker_6) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of DeskPi Pro Active Cooling[0m
[32m23-06-23 08:14:14 INFO (MainThread) [supervisor.store] Loading add-ons from store: 104 all - 0 new - 0 remove[0m
[32m23-06-23 08:14:14 INFO (MainThread) [supervisor.store] Loading add-ons from store: 104 all - 0 new - 0 remove[0m
[32m23-06-23 08:21:25 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-06-23 08:51:33 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-06-23 08:59:06 INFO (MainThread) [supervisor.host.info] Updating local host information[0m
[32m23-06-23 08:59:07 INFO (MainThread) [supervisor.host.services] Updating service information[0m
[32m23-06-23 08:59:07 INFO (MainThread) [supervisor.host.network] Updating local network information[0m
[32m23-06-23 08:59:07 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
[32m23-06-23 08:59:07 INFO (MainThread) [supervisor.host.manager] Host information reload completed[0m
[32m23-06-23 09:09:28 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m23-06-23 09:09:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER[0m
[32m23-06-23 09:09:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m23-06-23 09:09:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DOCKER_CONFIG/ContextType.SYSTEM[0m
[32m23-06-23 09:09:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m23-06-23 09:09:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER[0m
[32m23-06-23 09:09:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.MULTIPLE_DATA_DISKS/ContextType.SYSTEM[0m
[32m23-06-23 09:09:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m
[32m23-06-23 09:09:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m23-06-23 09:09:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM[0m
[32m23-06-23 09:09:28 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM[0m
[32m23-06-23 09:09:28 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m23-06-23 09:09:28 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m23-06-23 09:09:29 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-06-23 09:09:29 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m23-06-23 09:09:29 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m23-06-23 09:13:22 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 585, in state
    raise ValueError(
ValueError: Sensor sensor.tile_device has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Tile Tracker' (<class 'str'>)[0m
[31m2023-06-23 09:13:19.589 ERROR (MainThread) [homeassistant.components.mqtt.models] Exception raised when updating state of sensor.tile_device_3, topic: 'home/TheengsGateway/BTtoMQTT/FE1160FEDD11' with payload: b'{"id": "FE:11:60:FE:DD:11", "rssi": -78, "brand": "Tile", "model": "Smart Tracker", "model_id": "TILE", "type": "TRACK", "device": "Tile Tracker", "distance": 7.852880042745979}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'Tile Tracker'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 585, in state
    raise ValueError(
ValueError: Sensor sensor.tile_device_3 has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Tile Tracker' (<class 'str'>)[0m

 ```

**Comment by nukleuz80** [comment]
Closed because double...

**Comment by nukleuz80** [comment]
Closed
