### ISSUE TITLE
Couldn't refresh Google drive credentials 

### ISSUE THREAD

**Issue by hartmood** [sabeechen/hassio-google-drive-backup#880]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.111.1`
 Home Assistant Version: `2023.7.0b0`
 Supervisor Version: `2023.06.4`
 Supervisor Channel: `beta`
 Hassos Version: `10.3`
 Docker Version: `23.0.6`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2023-06-29T18:09:53.511514+00:00`
 Timezone: `Europe/Madrid`
 Failure Time: `2023-06-29T18:04:49.361229+00:00`
 Last Good Sync: `2023-06-29T18:04:28.126497+00:00`
 Next Sync: `2023-06-29T20:04:49.361229+00:00`
 Next Backup: `2023-06-30T01:55:00+00:00`
 Next Cache Warm: `2260-01-18T12:42:54.373723+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:203 (sync)
  addon/backup/model/model.py:317 (_syncBackups)
  addon/backup/drive/drivesource.py:118 (get)
  addon/backup/drive/drivesource.py:269 (getFolderId)
  addon/backup/drive/folderfinder.py:63 (get)
  addon/backup/drive/folderfinder.py:113 (_readFolderId)
  addon/backup/drive/folderfinder.py:154 (_verify)
  addon/backup/drive/driverequests.py:163 (get)
  addon/backup/drive/driverequests.py:360 (retryRequest)
  addon/backup/drive/driverequests.py:94 (_getHeaders)
  addon/backup/drive/driverequests.py:152 (getToken)
  addon/backup/creds/exchanger.py:81 (refresh)
  addon/backup/creds/exchanger.py:150 (_refresh_default)
backup.exceptions.exceptions.CredRefreshMyError: Timed out communicating with habackup.io

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 15,
        "retained": 0,
        "deletable": 15,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-06-29T01:55:00Z",
        "max": 15,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 2,
        "detail": "",
        "size": "1.5 GB",
        "ignored_size": "20.5 kB",
        "free_space": "45.6 GB"
    },
    "GoogleDrive": {
        "backups": 10,
        "retained": 0,
        "deletable": 10,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-06-29T01:55:00Z",
        "max": 10,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "bernd@bube.net",
        "size": "1.0 GB",
        "ignored_size": "0.0 B",
        "free_space": "15.8 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 15,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 10,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.BACKUP_TIME_OF_DAY": "03:55",
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 06-29 15:29:29 INFO [backup.model.coordinator] I'll try again in 42 minutes, 40 seconds
06-29 16:12:09 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-29 16:12:09 INFO [backup.model.coordinator] Syncing Backups
06-29 16:12:09 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-29 16:12:20 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
06-29 16:12:31 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
06-29 16:12:31 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
06-29 16:12:31 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
06-29 16:12:31 INFO [backup.model.coordinator] I'll try again in 1 hours, 25 minutes, 20 seconds
06-29 17:37:27 INFO [backup.model.coordinator] Syncing Backups
06-29 17:37:27 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-29 17:37:38 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
06-29 17:37:49 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
06-29 17:37:49 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
06-29 17:37:49 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
06-29 17:37:49 INFO [backup.model.coordinator] I'll try again in 2 hours
06-29 19:10:25 INFO [backup.model.coordinator] Syncing Backups
06-29 19:10:25 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-29 19:10:36 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
06-29 19:10:47 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
06-29 19:10:47 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
06-29 19:10:47 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
06-29 19:10:47 INFO [backup.model.coordinator] I'll try again in 2 hours
06-29 20:04:28 INFO [backup.model.coordinator] Syncing Backups
06-29 20:04:28 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-29 20:04:38 WARNING [backup.creds.exchanger] Timed out communicating with token1.habackup.io, trying alternate server(s)...
06-29 20:04:49 WARNING [backup.creds.exchanger] Timed out communicating with habackup.io, trying alternate server(s)...
06-29 20:04:49 ERROR [backup.creds.exchanger] Unable to refresh credentials with Google Drive
06-29 20:04:49 ERROR [backup.model.coordinator] Couldn't refresh Google Drive credentials because: Timed out communicating with habackup.io
06-29 20:04:49 INFO [backup.model.coordinator] I'll try again in 2 hours
 ```
 ###### Supervisor Logs:
 ```
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/store.py", line 219, in addons_addon_info
    return await self.addons_addon_info_wrapped(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/store.py", line 225, in addons_addon_info_wrapped
    return self._generate_addon_information(addon, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/store.py", line 114, in _generate_addon_information
    ATTR_ADVANCED: addon.advanced,
                   ^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/addons/model.py", line 227, in advanced
    return self.data[ATTR_ADVANCED]
           ^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/addon.py", line 19, in data
    return self.sys_store.data.addons[self.slug]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'core_matter_server'
[32m23-06-29 19:53:00 INFO (MainThread) [supervisor.store] Loading add-ons from store: 74 all - 0 new - 0 remove[0m
[32m23-06-29 19:53:00 INFO (MainThread) [supervisor.store] Loading add-ons from store: 74 all - 0 new - 0 remove[0m
[32m23-06-29 20:04:28 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-06-29 20:04:28 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[33m23-06-29 20:09:10 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[32m23-06-29 20:09:53 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     self._state = float(self._data["data"]["iaqi"]['t']["v"])
                        ~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable[0m
[31m2023-06-29 20:09:50.724 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.wind_speed fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 695, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/worlds_air_quality_index/sensor.py", line 210, in update
    self._state = float(self._data["data"]["iaqi"][self._resType]["v"])
                        ~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable[0m
[31m2023-06-29 20:09:50.732 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.wind_direction fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 695, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/worlds_air_quality_index/sensor.py", line 210, in update
    self._state = float(self._data["data"]["iaqi"][self._resType]["v"])
                        ~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable[0m

 ```
 
![Bildschirmfoto 2023-06-29 um 20 09 17](https://github.com/sabeechen/hassio-google-drive-backup/assets/50808701/f638eee2-7b74-4949-9d7b-3070a032ae93)

**Comment by sabeechen** [comment]
Are you sure the machine has a connection to the internet?  habackup.io has had almost 100% uptime over the last week, and its the first internet request the addon makes while syncing.

**Comment by FSHelgeland** [comment]
Happened to me also today, tried to sync again, tried to reconnect again. But no luck so far.

**Comment by sabeechen** [comment]
I looked into the server logs and noticed they were getting somewhat frequent http 502 (bad gateway) responses when trying to relay the request to google (relaying the request is more-or-less all the server does).  Ive restarted the servers manually and the problem doesn't seem to have come back up.  I'm not sure what could cause that, they've been running untouched with no problems for months now.

Could one of you see if the problem has resolved on your end by re-syncing?

**Comment by mpgoebel** [comment]
I just tried to resync with the same error popping up.

**Comment by hartmood** [comment]
You are right. My connection disappeared around noon European time zone.  The only error message received was the Google backup addon. I am on the beta channel, auto-update, and wifi.  After re-establishing the wifi connection with adding another time the wifi password, it now works perfectly.
