### ISSUE TITLE
 Home Assistant Google Drive Backup : Error while backing up sync with googledrive not working

### ISSUE THREAD

**Issue by dperrier69** [sabeechen/hassio-google-drive-backup#883]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.111.1`
 Home Assistant Version: `2023.6.3`
 Supervisor Version: `2023.06.4`
 Supervisor Channel: `stable`
 Hassos Version: `10.3`
 Docker Version: `23.0.6`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2023-07-05T14:40:03.363907+00:00`
 Timezone: `Europe/Paris`
 Failure Time: `2023-07-05T14:39:47.863068+00:00`
 Last Good Sync: `2023-07-05T14:39:47.382605+00:00`
 Next Sync: `2023-07-05T14:40:07.863068+00:00`
 Next Backup: `2023-07-06T01:00:00+00:00`
 Next Cache Warm: `2023-07-05T14:38:14.686846+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:40 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 7,
        "retained": 0,
        "deletable": 7,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-07-05T14:38:37Z",
        "max": 17,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 10,
        "detail": "",
        "size": "1.4 GB",
        "ignored_size": "2.6 GB"
    },
    "GoogleDrive": {
        "backups": 6,
        "retained": 0,
        "deletable": 6,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-07-03T01:00:01Z",
        "max": 6,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "denis.perrierp@gmail.com",
        "size": "1.4 GB",
        "ignored_size": "0.0 B",
        "free_space": "3.2 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 17,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 6,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.IGNORE_OTHER_BACKUPS": true,
    "Setting.BACKUP_NAME": "REDACTED",
    "Setting.BACKUP_TIME_OF_DAY": "03:00",
    "Setting.SPECIFY_BACKUP_FOLDER": true,
    "Setting.BACKUP_PASSWORD": "REDACTED",
    "Setting.GENERATIONAL_DAYS": 7,
    "Setting.GENERATIONAL_WEEKS": 5,
    "Setting.GENERATIONAL_MONTHS": 3,
    "Setting.VERBOSE": true,
    "Setting.TRACE_REQUESTS": true,
    "Setting.IGNORE_IPV6_ADDRESSES": true
}
 ```
 ###### Addon Logs:
 ```
 07-05 16:18:12 INFO [backup.ui.uiserver] Starting server on port 8099
07-05 16:18:12 INFO [backup.ui.uiserver] Server started
07-05 16:18:12 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-05 16:18:12 INFO [backup.model.coordinator] Syncing Backups
07-05 16:37:06 INFO [backup.drive.drivesource] Saving new Google Drive credentials
07-05 16:37:06 DEBUG [backup.model.syncer] Sync requested by GoogleDrive
07-05 16:37:06 INFO [backup.model.coordinator] Syncing Backups
07-05 16:37:06 ERROR [backup.model.coordinator] Please visit the add-on Web UI to select where to backup.
07-05 16:37:06 INFO [backup.model.coordinator] I'll try again in 2 hours
07-05 16:38:20 INFO [backup.drive.folderfinder] Saving backup folder: 1wlgupHmjZbxhWUJs9FY7jZlbiDawuF2h
07-05 16:38:20 DEBUG [backup.model.syncer] Sync requested by UI Server
07-05 16:38:20 INFO [backup.model.coordinator] Syncing Backups
07-05 16:38:36 INFO [backup.model.coordinator] Syncing Backups
07-05 16:38:37 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-05 16:38:37 INFO [backup.ha.hasource] Requesting a new backup
07-05 16:38:43 INFO [backup.model.coordinator] Syncing Backups
07-05 16:39:35 INFO [backup.ha.hasource] Backup finished
07-05 16:39:35 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
07-05 16:39:35 INFO [backup.model.coordinator] Syncing Backups
07-05 16:39:36 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:40 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

07-05 16:39:36 INFO [backup.model.coordinator] I'll try again in 0 seconds
07-05 16:39:36 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-05 16:39:36 INFO [backup.model.coordinator] Syncing Backups
07-05 16:39:37 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:40 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

07-05 16:39:37 INFO [backup.model.coordinator] I'll try again in 10 seconds
07-05 16:39:47 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-05 16:39:47 INFO [backup.model.coordinator] Syncing Backups
07-05 16:39:47 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:228 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:40 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

07-05 16:39:47 INFO [backup.model.coordinator] I'll try again in 20 seconds
 ```
 ###### Supervisor Logs:
 ```
   File "/usr/local/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/mounts/NFS/e687dbd5.tar'
[32m23-07-05 16:39:47 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-07-05 16:39:47 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-07-05 16:39:47 INFO (MainThread) [supervisor.api.middleware.security] /backups/e687dbd5/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-07-05 16:39:47 INFO (MainThread) [supervisor.api.backups] Downloading backup e687dbd5[0m
[31m23-07-05 16:39:47 ERROR (MainThread) [aiohttp.server] Unhandled exception[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 512, in start
    resp, reset = await task
                  ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 458, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 611, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_fileresponse.py", line 142, in prepare
    st: os.stat_result = await loop.run_in_executor(None, filepath.stat)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/mounts/NFS/e687dbd5.tar'
[32m23-07-05 16:40:03 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 431, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/nuki_ng/sensor.py", line 141, in state
    return str(self.get_state())
               ^^^^^^^^^^^^^^^^
  File "/config/custom_components/nuki_ng/sensor.py", line 144, in get_state
    lock_state = LockStates(self.last_state.get("state"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 711, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: None is not a valid LockStates[0m
[32m2023-07-05 16:38:58.662 INFO (MainThread) [homeassistant.components.recorder] Backup start notification, locking database for writes[0m
[32m2023-07-05 16:39:35.787 INFO (MainThread) [homeassistant.components.recorder] Backup end notification, releasing write lock[0m
[32m2023-07-05 16:39:35.788 INFO (Recorder) [homeassistant.components.recorder.core] Database queue backlog reached 2 entries during backup[0m

 ```

**Comment by dperrier69** [comment]
It worked till 2 days ago,don'twork anymore (bakup works, sync with google drive does not work)
