### ISSUE TITLE
Addon for Home Assistant Google Drive Backup times out during Start

### ISSUE THREAD

**Issue by JohnMacHeli** [sabeechen/hassio-google-drive-backup#893]
I installed Google Drive Backup.  Installed OK, but clicking Start just spins and eventually goes back to Start.

This is from the Supervisor Log every time I do it:

23-07-25 17:08:02 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Home Assistant Google Drive Backup to start, took more then 120 seconds

I never get to view in UI, nor setup Google Drive

**Comment by JohnMacHeli** [comment]
I wanted to give more info on my problem starting over.  I uninstalled Google drive Backup in the addon window.  Then clicked Install  again.  After it completed here is the Supervisor log, the Addon Log had nothing:

Supervisor after install:

23-07-26 07:10:43 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/cebe7a76_hassio_google_drive_backup
23-07-26 07:10:43 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image sabeechen/hassio-google-drive-backup-aarch64 with tag 0.111.1.
23-07-26 07:12:03 INFO (MainThread) [supervisor.addons] Add-on 'cebe7a76_hassio_google_drive_backup' successfully installed
23-07-26 07:13:26 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for cebe7a76_hassio_google_drive_backup

I then Clicked Start.  It circled for a couple minutes then returned to Start.  No link for UI page, red dot (still stopped).  
Here is what was in the Addon and Supervisor Logs:

Addon:

07-26 07:17:39 INFO Starting server on port 8099
07-26 07:17:39 INFO Server started
07-26 07:17:39 INFO Syncing Backups

Supervisor:

23-07-26 07:10:43 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/cebe7a76_hassio_google_drive_backup
23-07-26 07:10:43 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image sabeechen/hassio-google-drive-backup-aarch64 with tag 0.111.1.
23-07-26 07:12:03 INFO (MainThread) [supervisor.addons] Add-on 'cebe7a76_hassio_google_drive_backup' successfully installed
23-07-26 07:13:26 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for cebe7a76_hassio_google_drive_backup
23-07-26 07:15:43 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
23-07-26 07:15:43 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
23-07-26 07:15:43 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
23-07-26 07:15:43 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
23-07-26 07:15:43 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
23-07-26 07:15:45 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 185, in block_bad_requests
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 201, in system_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 268, in token_validation
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 280, in core_proxy
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/utils.py", line 62, in wrap_api
    answer = await method(api, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/api/store.py", line 178, in store_info
    ATTR_ADDONS: [
                 ^
  File "/usr/src/supervisor/supervisor/api/store.py", line 179, in <listcomp>
    self._generate_addon_information(self.sys_addons.store[addon])
  File "/usr/src/supervisor/supervisor/api/store.py", line 114, in _generate_addon_information
    ATTR_ADVANCED: addon.advanced,
                   ^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/addons/model.py", line 227, in advanced
    return self.data[ATTR_ADVANCED]
           ^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/addon.py", line 19, in data
    return self.sys_store.data.addons[self.slug]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'core_openthread_border_router'
23-07-26 07:15:48 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
23-07-26 07:15:48 INFO (MainThread) [supervisor.store] Loading add-ons from store: 72 all - 0 new - 0 remove
23-07-26 07:17:37 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on sabeechen/hassio-google-drive-backup-aarch64 with version 0.111.1
23-07-26 07:17:39 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup
23-07-26 07:17:39 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-07-26 07:17:39 INFO (MainThread) [supervisor.api.middleware.security] /mounts access from cebe7a76_hassio_google_drive_backup
23-07-26 07:17:39 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup
23-07-26 07:17:39 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-07-26 07:17:39 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
23-07-26 07:17:39 INFO (MainThread) [supervisor.api.middleware.security] /backups/50602fa5/info access from cebe7a76_hassio_google_drive_backup
23-07-26 07:17:39 INFO (MainThread) [supervisor.api.middleware.security] /backups/630aa4bc/info access from cebe7a76_hassio_google_drive_backup
23-07-26 07:17:39 INFO (MainThread) [supervisor.api.middleware.security] /backups/117ce5fa/info access from cebe7a76_hassio_google_drive_backup
23-07-26 07:17:39 INFO (MainThread) [supervisor.api.middleware.security] /backups/61f556bc/info access from cebe7a76_hassio_google_drive_backup
23-07-26 07:17:39 INFO (MainThread) [supervisor.api.middleware.security] /backups/6a87079c/info access from cebe7a76_hassio_google_drive_backup
23-07-26 07:19:37 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Home Assistant Google Drive Backup to start, took more then 120 seconds
23-07-26 07:20:09 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token

The "Backups"  entry is on the sidebar, but clicking it simply goes to the same Google Backup screen as before.
No place to open UI, go to Settings, connect to Google Drive ect.

Hope you can help.  thanks

**Comment by JohnMacHeli** [comment]
I think I need to provide better info starting from a clean install.  Closing this and Starting new issue
