### ISSUE TITLE
Google Drive Backup error

### ISSUE THREAD

**Issue by tptking2675** [sabeechen/hassio-google-drive-backup#895]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.111.1`
 Home Assistant Version: `2023.7.3`
 Supervisor Version: `2023.07.1`
 Supervisor Channel: `stable`
 Hassos Version: `10.3`
 Docker Version: `23.0.6`
 Architecture: `aarch64`
 Machine: `raspberrypi3-64`
 Date: `2023-07-28T21:20:04.582185+00:00`
 Timezone: `America/New_York`
 Failure Time: `2023-07-28T20:59:00.901657+00:00`
 Last Good Sync: `2023-07-28T20:59:00.496165+00:00`
 Next Sync: `2023-07-28T22:59:00.901657+00:00`
 Next Backup: `2023-08-01T07:00:00+00:00`
 Next Cache Warm: `2023-07-28T22:49:35.287450+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:260 (sync)
  addon/backup/util/data_cache.py:115 (saveIfDirty)
  addon/backup/util/data_cache.py:87 (save)
  addon/backup/file/jsonfilesaver.py:52 (write)
  addon/backup/file/jsonfilesaver.py:46 (_write)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json.backup'

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": null,
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 82,
        "detail": "",
        "size": "0.0 B",
        "ignored_size": "12.5 GB",
        "free_space": "154.7 GB"
    },
    "GoogleDrive": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-07-25T07:00:00Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "josh.willis2675@gmail.com",
        "size": "352.7 MB",
        "ignored_size": "0.0 B",
        "free_space": "11.3 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.DAYS_BETWEEN_BACKUPS": 7.0,
    "Setting.DELETE_BEFORE_NEW_BACKUP": true,
    "Setting.BACKUP_TIME_OF_DAY": "03:00",
    "Setting.SPECIFY_BACKUP_FOLDER": true,
    "Setting.DELETE_AFTER_UPLOAD": true,
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 07-28 12:19:54 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
07-28 12:29:37 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-28 12:29:37 INFO [backup.model.coordinator] Syncing Backups
07-28 12:29:37 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:260 (sync)
  addon/backup/util/data_cache.py:115 (saveIfDirty)
  addon/backup/util/data_cache.py:87 (save)
  addon/backup/file/jsonfilesaver.py:52 (write)
  addon/backup/file/jsonfilesaver.py:46 (_write)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json.backup'

07-28 12:29:37 INFO [backup.model.coordinator] I'll try again in 21 minutes, 20 seconds
07-28 12:50:55 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
07-28 12:50:58 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-28 12:50:58 INFO [backup.model.coordinator] Syncing Backups
07-28 12:50:58 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:260 (sync)
  addon/backup/util/data_cache.py:115 (saveIfDirty)
  addon/backup/util/data_cache.py:87 (save)
  addon/backup/file/jsonfilesaver.py:52 (write)
  addon/backup/file/jsonfilesaver.py:46 (_write)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json.backup'

07-28 12:50:58 INFO [backup.model.coordinator] I'll try again in 42 minutes, 40 seconds
07-28 13:29:57 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
07-28 13:29:57 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
07-28 13:33:38 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-28 13:33:38 INFO [backup.model.coordinator] Syncing Backups
07-28 13:33:39 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:260 (sync)
  addon/backup/util/data_cache.py:115 (saveIfDirty)
  addon/backup/util/data_cache.py:87 (save)
  addon/backup/file/jsonfilesaver.py:52 (write)
  addon/backup/file/jsonfilesaver.py:46 (_write)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json.backup'

07-28 13:33:39 INFO [backup.model.coordinator] I'll try again in 1 hours, 25 minutes, 20 seconds
07-28 14:47:00 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
07-28 14:47:00 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
07-28 14:58:59 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-28 14:58:59 INFO [backup.model.coordinator] Syncing Backups
07-28 14:59:00 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:260 (sync)
  addon/backup/util/data_cache.py:115 (saveIfDirty)
  addon/backup/util/data_cache.py:87 (save)
  addon/backup/file/jsonfilesaver.py:52 (write)
  addon/backup/file/jsonfilesaver.py:46 (_write)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json.backup'

07-28 14:59:00 INFO [backup.model.coordinator] I'll try again in 2 hours
07-28 16:51:02 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
07-28 16:51:02 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
07-28 16:59:00 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-28 16:59:00 INFO [backup.model.coordinator] Syncing Backups
07-28 16:59:00 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:260 (sync)
  addon/backup/util/data_cache.py:115 (saveIfDirty)
  addon/backup/util/data_cache.py:87 (save)
  addon/backup/file/jsonfilesaver.py:52 (write)
  addon/backup/file/jsonfilesaver.py:46 (_write)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json.backup'

07-28 16:59:00 INFO [backup.model.coordinator] I'll try again in 2 hours
07-28 17:18:54 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
07-28 17:19:09 DEBUG [backup.watcher] Checking backup source for changes...
 ```
 ###### Supervisor Logs:
 ```
 [32m23-07-28 09:40:14 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m23-07-28 09:40:14 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m23-07-28 09:52:18 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-07-28 10:21:50 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m23-07-28 10:22:19 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-07-28 10:22:58 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-07-28 10:22:58 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-07-28 10:40:14 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m23-07-28 10:40:14 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DOCKER_CONFIG/ContextType.SYSTEM[0m
[32m23-07-28 10:40:14 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m
[32m23-07-28 10:40:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m23-07-28 10:40:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER[0m
[32m23-07-28 10:40:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m23-07-28 10:40:25 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER[0m
[32m23-07-28 10:40:25 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m23-07-28 10:40:25 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM[0m
[32m23-07-28 10:40:25 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.MULTIPLE_DATA_DISKS/ContextType.SYSTEM[0m
[32m23-07-28 10:40:25 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m23-07-28 10:40:25 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m23-07-28 10:40:27 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-07-28 10:40:27 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m23-07-28 10:40:27 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m23-07-28 17:18:54 INFO (MainThread) [supervisor.backups.manager] Found 83 backup files[0m
[31m23-07-28 17:18:55 ERROR (MainThread) [supervisor.backups.backup] Can't read backup tarfile /data/backup/8f2ecb04.tar: unexpected end of data[0m
[32m23-07-28 17:18:58 INFO (MainThread) [supervisor.backups.manager] Found 83 backup files[0m
[31m23-07-28 17:18:58 ERROR (MainThread) [supervisor.backups.backup] Can't read backup tarfile /data/backup/8f2ecb04.tar: unexpected end of data[0m
[32m23-07-28 17:19:09 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-07-28 17:19:09 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-07-28 17:20:04 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/config/custom_components/fordpass/sensor.py", line 64, in get_value
    if self.fordoptions[DISTANCE_CONVERSION_DISABLED] == True:
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'distance_conversion'[0m
[31m2023-07-28 10:49:49.265 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 431, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 429, in state
    return self.get_value("state")
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fordpass/sensor.py", line 64, in get_value
    if self.fordoptions[DISTANCE_CONVERSION_DISABLED] == True:
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'distance_conversion'[0m

 ```

**Comment by sabeechen** [comment]
The most common reasons to get this error are:

- Hard drive ran out of space
- SD card corruption

Its caused by the operating system going in to protection mode because it thinks it needs to do that to prevent dying.  You'll probably also see Home  Assistant fail to work if you do anything that requires writing to disk.

It could be that:
- this is a false alarm, and things work fine after restarting the system.  
- its just part of an SD  that card dies and everything works fine afterward.
- The last backup got really large for some reason, and there wasn't enough space to finish creating it.

In any case I'd consider replacing the SD card if its practical for you, or at least make sure you've got a good backup ready if things go bad.

**Comment by tptking2675** [comment]
I am not running it on an SD. I use a 1TB drive for the system. I did
notice I had a number of ignores backups.

**Comment by sabeechen** [comment]
This is an operating-system level problem, there isn't much the addon can do about it if the OS has decided the filesystem needs to be protected from changes.  If there is more you think I can help with, please re-open this issue and let me know.
