### ISSUE TITLE
mqtt problems after backup

### ISSUE THREAD

**Issue by RobertDeserranno** [sabeechen/hassio-google-drive-backup#900]
The backup is working fine, but after the backup mosquitto broker is not working anymore.
Restarting HA is not  helping, I have to power off and on again to solve this probleem.
Is there a solution for this?
Robert
 
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.111.1`
 Home Assistant Version: `2023.7.3`
 Supervisor Version: `2023.08.1`
 Supervisor Channel: `stable`
 Hassos Version: `10.4`
 Docker Version: `23.0.6`
 Architecture: `aarch64`
 Machine: `odroid-c4`
 Date: `2023-08-09T09:26:44.648625+00:00`
 Timezone: `Europe/Brussels`
 Failure Time: `Never`
 Last Good Sync: `2023-08-09T09:26:38.620270+00:00`
 Next Sync: `2023-08-09T12:21:03.041175+00:00`
 Next Backup: `2023-08-09T23:00:00+00:00`
 Next Cache Warm: `2023-08-09T12:06:27.156538+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-08-08T23:00:40Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "detail": "",
        "size": "364.7 MB",
        "ignored_size": "0.0 B",
        "free_space": "5.8 GB"
    },
    "GoogleDrive": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-08-08T23:00:40Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "rdeserranno@gmail.com",
        "size": "364.7 MB",
        "ignored_size": "0.0 B",
        "free_space": "10.2 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.BACKUP_TIME_OF_DAY": "01:00",
    "Setting.STOP_ADDONS": "5c53de3b_esphome,core_mosquitto"
}
 ```
 ###### Addon Logs:
 ```
 08-09 03:47:09 INFO [backup.ui.uiserver] Starting server on port 8099
08-09 03:47:09 INFO [backup.ui.uiserver] Server started
08-09 03:47:09 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-09 03:47:09 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
08-09 03:47:09 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-09 03:47:09 INFO [backup.model.coordinator] Syncing Backups
08-09 03:47:09 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-09 06:39:11 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
08-09 06:39:11 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-09 06:45:47 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-09 06:45:47 INFO [backup.model.coordinator] Syncing Backups
08-09 09:23:14 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
08-09 09:23:14 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-09 09:23:54 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-09 09:23:54 INFO [backup.model.coordinator] Syncing Backups
08-09 11:26:28 INFO [backup.ha.hasource] Deleting 'addon_a0d7b954_sqlite-web_3.9.0' from Home Assistant
08-09 11:26:28 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
08-09 11:26:38 DEBUG [backup.watcher] Checking backup source for changes...
08-09 11:26:38 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
08-09 11:26:38 INFO [backup.model.coordinator] Syncing Backups
08-09 11:26:38 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
 ```
 ###### Supervisor Logs:
 ```
 [32m23-08-09 10:44:14 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m23-08-09 10:44:14 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m23-08-09 10:45:02 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'Mqttuser'[0m
[32m23-08-09 10:45:02 INFO (MainThread) [supervisor.auth] Successful login for 'Mqttuser'[0m
[32m23-08-09 10:46:12 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-08-09 10:50:13 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'Mqttuser'[0m
[32m23-08-09 10:50:13 INFO (MainThread) [supervisor.auth] Successful login for 'Mqttuser'[0m
[32m23-08-09 10:55:32 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'Mqttuser'[0m
[32m23-08-09 10:55:32 INFO (MainThread) [supervisor.auth] Successful login for 'Mqttuser'[0m
[32m23-08-09 11:00:22 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'Mqttuser'[0m
[32m23-08-09 11:00:23 INFO (MainThread) [supervisor.auth] Successful login for 'Mqttuser'[0m
[32m23-08-09 11:05:43 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'Mqttuser'[0m
[32m23-08-09 11:05:43 INFO (MainThread) [supervisor.auth] Successful login for 'Mqttuser'[0m
[32m23-08-09 11:10:16 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'Mqttuser'[0m
[32m23-08-09 11:10:17 INFO (MainThread) [supervisor.auth] Successful login for 'Mqttuser'[0m
[32m23-08-09 11:15:11 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'Mqttuser'[0m
[32m23-08-09 11:15:12 INFO (MainThread) [supervisor.auth] Successful login for 'Mqttuser'[0m
[32m23-08-09 11:16:18 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-08-09 11:20:34 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'Mqttuser'[0m
[32m23-08-09 11:20:34 INFO (MainThread) [supervisor.auth] Successful login for 'Mqttuser'[0m
[32m23-08-09 11:25:45 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'Mqttuser'[0m
[32m23-08-09 11:25:45 INFO (MainThread) [supervisor.auth] Successful login for 'Mqttuser'[0m
[32m23-08-09 11:26:28 INFO (MainThread) [supervisor.api.middleware.security] /backups/cc85fe22 access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-09 11:26:28 INFO (MainThread) [supervisor.backups.manager] Removed backup file cc85fe22[0m
[32m23-08-09 11:26:38 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-09 11:26:38 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-09 11:26:38 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-09 11:26:38 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-09 11:26:44 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/local/lib/python3.11/site-packages/aiomusiccast/pyamaha.py", line 256, in request_json
    raise MusicCastConnectionException() from ce
aiomusiccast.exceptions.MusicCastConnectionException[0m
[31m2023-08-09 11:06:12.759 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiomusiccast/pyamaha.py", line 248, in request_json
    response = await self.get(args[0])
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiomusiccast/pyamaha.py", line 268, in get
    return await self.client.get(uri.format(host=self.ip), headers=self._headers, timeout=ClientTimeout(total=5))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiomusiccast/musiccast_device.py", line 147, in handle
    await self._fetch_tuner()
  File "/usr/local/lib/python3.11/site-packages/aiomusiccast/musiccast_device.py", line 228, in _fetch_tuner
    self._tuner_play_info = await self.device.request_json(Tuner.get_play_info())
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiomusiccast/pyamaha.py", line 256, in request_json
    raise MusicCastConnectionException() from ce
aiomusiccast.exceptions.MusicCastConnectionException[0m

 ```
 Copy the info from the previous page here

**Comment by sabeechen** [comment]
Are there any logs form the mosquito addon or the supervisor ([see here](https://github.com/sabeechen/hassio-google-drive-backup#im-getting-weird-errors--where-do-i-look-for-more-detils-about-an-error-supervisor-logs) about getting supervisor logs) when it fails to start?


Is there a reason you need to stop the addons?  This can cause problems and is usually only a last resort option for when an addon is poorly written to handle backup.  ESPHome and moqquitto can be safely backed up live.

**Comment by RobertDeserranno** [comment]
The reason I stopped the mosquitto and EspHome addons is because the config text is saying ; 
-------------------------------
Some addons will not get backed up correctly while they are running. Any addons you select below will be stopped before a backup is taken and then started after it finishes. Note that if this addon is interrupted before a backup completes, you may have to restart the addon manually.
--------------------------------
Now I do not stop the addons anymore because they are not started good after the backup. I do not have any logs anymore I think.
