### ISSUE TITLE
Keep forever not working in drive

### ISSUE THREAD

**Issue by Elarion245** [sabeechen/hassio-google-drive-backup#901]
When manually triggering a backup, I can select to keep the backup forever in Google drive and home assistant.

The deletion lock is applied correctly for the local store, but it I click the backup after it finishes, the Google drive copy is still showing the never delete option instead of allow deletion.

This happens to me also with the newest version of the add on.

**Comment by sabeechen** [comment]
I'm unable to reproduce this.  Is it possible you restarted the addon between when the backup was requested and the backup got uploaded to Google Drive?  If the addon is restarted it loses some state and can't remember if the backup should have been kept forever.

**Comment by Elarion245** [comment]
I don't think so. I have the stopping option enabled, but the backup Addon is obviously not selected:
![grafik](https://github.com/sabeechen/hassio-google-drive-backup/assets/7480315/2ed57d4f-600c-4eba-8c63-31623161f8a3)
![grafik](https://github.com/sabeechen/hassio-google-drive-backup/assets/7480315/fc231354-cd00-4a37-81a0-35c59c840d80)

It is likely not related, but I also see from time to time that once the backup finishes, the watchdog remains disabled and also some add-ons don't get started again. This is why in the screenshots I deselected all addons for remote access from the stopping option. Apart from that all standard settings. Default Backup location is internal EMMC drive.

What can I do to provide helpful inputs? Debug logs prior creating a backup?

**Comment by sabeechen** [comment]
Could I have you go to Actions > "Report a Bug" in the addon UI and post that here?  You don't need to wait for any errors, I just want to get a sense for if there is anything unique about your setup.

**Comment by Elarion245** [comment]
Here you go:
```

###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.111.1`
 Home Assistant Version: `2023.8.2`
 Supervisor Version: `2023.08.1`
 Supervisor Channel: `stable`
 Hassos Version: `10.4.dev20230802`
 Docker Version: `23.0.6`
 Architecture: `aarch64`
 Machine: `qemuarm-64`
 Date: `2023-08-15T18:21:42.707009+00:00`
 Timezone: `Europe/Berlin`
 Failure Time: `2023-08-14T05:58:32.742847+00:00`
 Last Good Sync: `2023-08-15T18:01:40.617933+00:00`
 Next Sync: `2023-08-15T19:35:44.071452+00:00`
 Next Backup: `2023-08-16T23:00:00+00:00`
 Next Cache Warm: `2023-08-15T19:35:25.177508+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 2,
        "retained": 1,
        "deletable": 1,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-08-13T23:00:41Z",
        "max": 3,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "detail": "",
        "size": "1.8 GB",
        "ignored_size": "0.0 B",
        "free_space": "14.0 GB"
    },
    "GoogleDrive": {
        "backups": 2,
        "retained": 1,
        "deletable": 1,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-08-13T23:00:41Z",
        "max": 3,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "1.8 GB",
        "ignored_size": "0.0 B",
        "free_space": "2.1 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 3,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 3,
    "Setting.BACKUP_TIME_OF_DAY": "01:00",
    "Setting.STOP_ADDONS": "core_mosquitto,2ad4c73a_mqtt-explorer,core_configurator,core_mariadb,5c53de3b_esphome,core_samba,a0d7b954_ssh,2ad4c73a_run_on_startup_addon,a0d7b954_sqlite-web"
}
 ```
 ###### Addon Logs:
 ```
 08-15 06:51:36 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
08-15 06:51:40 INFO [backup.drive.drivesource] Deleting 'TEST' From Google Drive
08-15 06:51:46 DEBUG [backup.watcher] Checking backup source for changes...
08-15 06:51:46 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
08-15 06:51:46 INFO [backup.model.coordinator] Syncing Backups
08-15 09:15:29 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
08-15 09:15:29 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-15 09:21:16 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-15 09:21:16 INFO [backup.model.coordinator] Syncing Backups
08-15 10:45:32 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
08-15 10:45:32 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-15 10:52:00 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-15 10:52:00 INFO [backup.model.coordinator] Syncing Backups
08-15 11:05:57 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
08-15 11:06:07 DEBUG [backup.watcher] Checking backup source for changes...
08-15 12:54:34 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
08-15 12:54:34 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-15 13:08:35 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-15 13:08:35 INFO [backup.model.coordinator] Syncing Backups
08-15 15:32:37 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
08-15 15:32:37 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-15 15:44:05 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-15 15:44:05 INFO [backup.model.coordinator] Syncing Backups
08-15 17:18:39 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
08-15 17:18:39 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-15 17:22:41 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-15 17:22:41 INFO [backup.model.coordinator] Syncing Backups
08-15 20:01:40 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-15 20:01:40 INFO [backup.model.coordinator] Syncing Backups
08-15 20:01:40 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
 ```
 ###### Supervisor Logs:
 ```
 [32m23-08-15 20:04:02 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM[0m
[32m23-08-15 20:04:02 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m23-08-15 20:04:02 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m23-08-15 20:04:02 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m
[32m23-08-15 20:04:02 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m23-08-15 20:04:02 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER[0m
[32m23-08-15 20:04:02 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DOCKER_CONFIG/ContextType.SYSTEM[0m
[32m23-08-15 20:04:02 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m23-08-15 20:04:02 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m23-08-15 20:04:02 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-08-15 20:04:02 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m23-08-15 20:04:02 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m23-08-15 20:08:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/adamoutler/Addons repository[0m
[32m23-08-15 20:08:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m23-08-15 20:08:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m23-08-15 20:08:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-08-15 20:08:00 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[33m23-08-15 20:08:04 WARNING (SyncWorker_7) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of DeskPi Pro Active Cooling[0m
[33m23-08-15 20:08:07 WARNING (SyncWorker_0) [supervisor.addons.validate] Add-on have full device access, and selective device access in the configuration. Please report this to the maintainer of DeskPi Pro Active Cooling[0m
[32m23-08-15 20:08:07 INFO (MainThread) [supervisor.store] Loading add-ons from store: 85 all - 0 new - 0 remove[0m
[32m23-08-15 20:08:07 INFO (MainThread) [supervisor.store] Loading add-ons from store: 85 all - 0 new - 0 remove[0m
[32m23-08-15 20:09:03 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-08-15 20:19:11 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-15 20:19:11 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-15 20:19:11 INFO (MainThread) [supervisor.api.middleware.security] /mounts access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-15 20:19:11 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-15 20:19:18 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-15 20:19:18 INFO (MainThread) [supervisor.api.middleware.security] /core/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-15 20:21:42 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     raise ve_exc
ValueError: 'unavailable' is not a valid HVACMode[0m
[31m2023-08-15 19:55:17.665 ERROR (MainThread) [homeassistant.helpers.event] Error while dispatching event for climate.thermostat_sofa to <Job track state_changed event ['climate.thermostat_sofa', 'climate.thermostat_esstisch'] HassJobType.Callback <function ClimateGroup.async_added_to_hass.<locals>.async_state_changed_listener at 0xffff701299e0>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 289, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 625, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/climate_group/climate.py", line 175, in async_state_changed_listener
    self.async_defer_or_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/components/group/__init__.py", line 493, in async_defer_or_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 808, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 752, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 246, in state
    return HVACMode(hvac_mode).value
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 711, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: 'unavailable' is not a valid HVACMode[0m

 ```
 
```

**Comment by Elarion245** [comment]
Any news? The issue still persists.
