### ISSUE TITLE
Please add a title

### ISSUE THREAD

**Issue by wynand64** [sabeechen/hassio-google-drive-backup#906]
Copy the info 
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.111.1`
 Home Assistant Version: `2023.8.2`
 Supervisor Version: `2023.08.1`
 Supervisor Channel: `stable`
 Hassos Version: `10.4`
 Docker Version: `23.0.6`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2023-08-15T06:19:40.779679+00:00`
 Timezone: `Africa/Johannesburg`
 Failure Time: `Never`
 Last Good Sync: `2023-08-15T06:18:19.795051+00:00`
 Next Sync: `2023-08-15T08:56:43.190680+00:00`
 Next Backup: `2023-08-18T06:09:44.314629+00:00`
 Next Cache Warm: `2023-08-15T08:53:06.438416+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 2,
        "retained": 0,
        "deletable": 2,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-08-15T06:09:44Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 4,
        "detail": "",
        "size": "436.9 MB",
        "ignored_size": "3.4 MB"
    },
    "GoogleDrive": {
        "backups": 2,
        "retained": 0,
        "deletable": 2,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-08-04T20:00:00Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "wynand64@gmail.com",
        "size": "888.0 MB",
        "ignored_size": "0.0 B",
        "free_space": "44.4 GB"
    }
}
 ```
 ###### Config:
 ```
 {}
 ```
 ###### Addon Logs:
 ```
 08-15 08:08:09 INFO [backup.ui.uiserver] Starting server on port 8099
08-15 08:08:09 INFO [backup.ui.uiserver] Server started
08-15 08:08:09 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-15 08:08:09 INFO [backup.model.coordinator] Syncing Backups
08-15 08:09:44 INFO [backup.model.coordinator] Syncing Backups
08-15 08:09:44 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-15 08:09:45 INFO [backup.ha.hasource] Requesting a new backup
08-15 08:09:50 INFO [backup.model.coordinator] Syncing Backups
08-15 08:18:19 WARNING [backup.ha.hasource] A backup was already in progress
08-15 08:18:19 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
08-15 08:18:19 INFO [backup.model.coordinator] Syncing Backups
 ```
 ###### Supervisor Logs:
 ```
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 333, in _write_tarfile
    with tar_file as backup:
  File "/usr/local/lib/python3.11/site-packages/securetar/__init__.py", line 100, in __exit__
    self._tar.close()
  File "/usr/local/lib/python3.11/tarfile.py", line 1968, in close
    self.fileobj.close()
  File "/usr/local/lib/python3.11/tarfile.py", line 472, in close
    self.fileobj.close()
  File "/usr/local/lib/python3.11/tarfile.py", line 324, in close
    os.close(self.fd)
OSError: [Errno 28] No space left on device
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 205, in _do_backup
    await backup.store_homeassistant()
  File "/usr/src/supervisor/supervisor/backups/backup.py", line 535, in store_homeassistant
    await self.sys_homeassistant.backup(homeassistant_file)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 156, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 154, in wrapper
    return await self._method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/homeassistant/module.py", line 350, in backup
    raise HomeAssistantBackupError(
supervisor.exceptions.HomeAssistantBackupError: Can't backup Home Assistant Core config folder: [Errno 28] No space left on device
[32m23-08-15 08:18:19 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-15 08:18:19 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-15 08:19:40 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 [31m2023-08-15 08:10:37.565 ERROR (stream_worker) [libav.http] Stream ends prematurely at 6347057, should be 18446744073709551615[0m
[31m2023-08-15 08:10:47.868 ERROR (stream_worker) [libav.http] Stream ends prematurely at 4130525, should be 18446744073709551615[0m
[31m2023-08-15 08:10:47.868 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.192_168_10_3_5] Error from stream worker: Stream ended; no additional packets[0m
[31m2023-08-15 08:10:47.876 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.192_168_10_3] Error from stream worker: Error demuxing stream: [Errno 5] I/O error: 'rtsp://192.168.10.3:554/user=admin&password=123123&channel=2&stream=0.sdp?real_stream--rtp-caching=100'; last error log: [http] Stream ends prematurely at 4130525, should be 18446744073709551615[0m
[31m2023-08-15 08:10:49.559 ERROR (stream_worker) [libav.http] Stream ends prematurely at 4130525, should be 18446744073709551615[0m
[31m2023-08-15 08:11:54.969 ERROR (stream_worker) [libav.http] Stream ends prematurely at 4144132, should be 18446744073709551615[0m
[31m2023-08-15 08:11:54.970 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.192_168_10_3_3] Error from stream worker: Stream ended; no additional packets[0m
[31m2023-08-15 08:11:54.975 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.192_168_10_3_2] Error from stream worker: Error demuxing stream: [Errno 5] I/O error: 'rtsp://192.168.10.3:554/user=admin&password=123123&channel=5&stream=0.sdp?real_stream--rtp-caching=100'; last error log: [http] Stream ends prematurely at 4144132, should be 18446744073709551615[0m
[31m2023-08-15 08:11:55.808 ERROR (stream_worker) [libav.http] Stream ends prematurely at 4144132, should be 18446744073709551615[0m
[31m2023-08-15 08:11:59.935 ERROR (stream_worker) [libav.http] Stream ends prematurely at 3496361, should be 18446744073709551615[0m
[31m2023-08-15 08:11:59.938 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.192_168_10_3_4] Error from stream worker: Stream ended; no additional packets[0m
[31m2023-08-15 08:11:59.941 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.192_168_10_3] Error from stream worker: Error demuxing stream: [Errno 5] I/O error: 'rtsp://192.168.10.3:554/user=admin&password=123123&channel=2&stream=0.sdp?real_stream--rtp-caching=100'; last error log: [http] Stream ends prematurely at 3496361, should be 18446744073709551615[0m
[31m2023-08-15 08:12:00.502 ERROR (stream_worker) [libav.http] Stream ends prematurely at 3496361, should be 18446744073709551615[0m
[31m2023-08-15 08:14:48.791 ERROR (stream_worker) [libav.http] Stream ends prematurely at 9694753, should be 18446744073709551615[0m
[31m2023-08-15 08:14:48.796 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.192_168_10_3] Error from stream worker: Error demuxing stream: [Errno 5] I/O error: 'rtsp://192.168.10.3:554/user=admin&password=123123&channel=2&stream=0.sdp?real_stream--rtp-caching=100'; last error log: [http] Stream ends prematurely at 9694753, should be 18446744073709551615[0m
[31m2023-08-15 08:14:51.796 ERROR (stream_worker) [libav.http] Stream ends prematurely at 9694753, should be 18446744073709551615[0m
[31m2023-08-15 08:15:02.434 ERROR (stream_worker) [libav.http] Stream ends prematurely at 11131643, should be 18446744073709551615[0m
[31m2023-08-15 08:15:02.439 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.192_168_10_3_2] Error from stream worker: Error demuxing stream: [Errno 5] I/O error: 'rtsp://192.168.10.3:554/user=admin&password=123123&channel=5&stream=0.sdp?real_stream--rtp-caching=100'; last error log: [http] Stream ends prematurely at 11131643, should be 18446744073709551615[0m
[31m2023-08-15 08:15:03.128 ERROR (stream_worker) [libav.http] Stream ends prematurely at 11131643, should be 18446744073709551615[0m
[31m2023-08-15 08:17:14.745 ERROR (stream_worker) [libav.http] Stream ends prematurely at 14842505, should be 18446744073709551615[0m
[31m2023-08-15 08:17:14.751 ERROR (stream_worker) [libav.http] Stream ends prematurely at 14842505, should be 18446744073709551615[0m
[31m2023-08-15 08:17:14.757 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.192_168_10_3] Error from stream worker: Error demuxing stream: [Errno 5] I/O error: 'rtsp://192.168.10.3:554/user=admin&password=123123&channel=2&stream=0.sdp?real_stream--rtp-caching=100'; last error log: [http] Stream ends prematurely at 14842505, should be 18446744073709551615[0m
[31m2023-08-15 08:17:26.191 ERROR (stream_worker) [libav.http] Stream ends prematurely at 14661698, should be 18446744073709551615[0m
[31m2023-08-15 08:17:26.194 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.192_168_10_3_2] Error from stream worker: Error demuxing stream: [Errno 5] I/O error: 'rtsp://192.168.10.3:554/user=admin&password=123123&channel=5&stream=0.sdp?real_stream--rtp-caching=100'; last error log: [http] Stream ends prematurely at 14661698, should be 18446744073709551615[0m
[31m2023-08-15 08:17:27.788 ERROR (stream_worker) [libav.http] Stream ends prematurely at 14661698, should be 18446744073709551615[0m
[31m2023-08-15 08:18:15.272 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.192_168_10_3_6] Error from stream worker: Stream ended; no additional packets[0m
[31m2023-08-15 08:18:15.278 ERROR (stream_worker) [libav.http] Stream ends prematurely at 4350789, should be 18446744073709551615[0m
[31m2023-08-15 08:18:15.287 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.192_168_10_3] Error from stream worker: Error demuxing stream: [Errno 5] I/O error: 'rtsp://192.168.10.3:554/user=admin&password=123123&channel=2&stream=0.sdp?real_stream--rtp-caching=100'; last error log: [http] Stream ends prematurely at 4350789, should be 18446744073709551615[0m
[31m2023-08-15 08:18:15.820 ERROR (stream_worker) [libav.http] Stream ends prematurely at 4350789, should be 18446744073709551615[0m

 ```
 from the previous page here

**Comment by sabeechen** [comment]
> supervisor.exceptions.HomeAssistantBackupError: Can't backup Home Assistant Core config folder: [Errno 28] No space left on device

Your HD is out of space
