### ISSUE TITLE
An unexpected error occurred: 400, message='Bad Request', url=URL('https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true')"

### ISSUE THREAD

**Issue by Daguse** [sabeechen/hassio-google-drive-backup#909]
###### Description:
```
I ran a Reauth and the automation also came back with a 401 unauthorized error. 
```

 Addon version: `0.111.1`
 Home Assistant Version: `2023.8.2`
 Supervisor Version: `2023.08.1`
 Supervisor Channel: `stable`
 Hassos Version: `10.4`
 Docker Version: `23.0.6`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2023-08-17T18:50:45.762826+00:00`
 Timezone: `America/New_York`
 Failure Time: `2023-08-17T18:50:23.684245+00:00`
 Last Good Sync: `2023-08-17T18:50:21.763661+00:00`
 Next Sync: `2023-08-17T20:50:23.684245+00:00`
 Next Backup: `2023-08-18T06:00:00+00:00`
 Next Cache Warm: `2023-08-17T20:39:42.248932+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:215 (save)
  addon/backup/drive/drivesource.py:202 (save)
  addon/backup/drive/driverequests.py:268 (create)
  addon/backup/drive/driverequests.py:372 (retryRequest)
  addon/backup/creds/driverequester.py:45 (request)
  /site-packages/aiohttp/client_reqrep.py:1005 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true')

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-08-17T06:00:00Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 121,
        "detail": "",
        "size": "2.5 GB",
        "ignored_size": "11.6 GB",
        "free_space": "187.8 GB"
    },
    "GoogleDrive": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-08-16T06:00:00Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "pittman.matt@gmail.com",
        "size": "2.5 GB",
        "ignored_size": "0.0 B",
        "free_space": "4.1 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.BACKUP_TIME_OF_DAY": "02:00"
}
 ```
 ###### Addon Logs:
 ```
 08-17 12:43:12 INFO [backup.model.coordinator] I'll try again in 2 hours
08-17 12:43:21 DEBUG [backup.watcher] Checking backup source for changes...
08-17 14:31:59 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
08-17 14:31:59 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-17 14:42:54 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
08-17 14:43:04 DEBUG [backup.watcher] Checking backup source for changes...
08-17 14:43:04 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
08-17 14:43:04 INFO [backup.model.coordinator] Syncing Backups
08-17 14:43:04 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
08-17 14:43:04 INFO [backup.drive.drivesource] Uploading 'Full Backup 2023-08-17 02:00:00' to Google Drive
08-17 14:43:04 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
08-17 14:43:05 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:215 (save)
  addon/backup/drive/drivesource.py:202 (save)
  addon/backup/drive/driverequests.py:268 (create)
  addon/backup/drive/driverequests.py:372 (retryRequest)
  addon/backup/creds/driverequester.py:45 (request)
  /site-packages/aiohttp/client_reqrep.py:1005 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true')

08-17 14:43:05 INFO [backup.model.coordinator] I'll try again in 2 hours
08-17 14:43:14 DEBUG [backup.watcher] Checking backup source for changes...
08-17 14:47:50 INFO [backup.model.coordinator] Syncing Backups
08-17 14:47:51 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
08-17 14:47:51 INFO [backup.drive.drivesource] Uploading 'Full Backup 2023-08-17 02:00:00' to Google Drive
08-17 14:47:51 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
08-17 14:47:52 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:215 (save)
  addon/backup/drive/drivesource.py:202 (save)
  addon/backup/drive/driverequests.py:268 (create)
  addon/backup/drive/driverequests.py:372 (retryRequest)
  addon/backup/creds/driverequester.py:45 (request)
  /site-packages/aiohttp/client_reqrep.py:1005 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true')

08-17 14:47:52 INFO [backup.model.coordinator] I'll try again in 2 hours
08-17 14:48:01 DEBUG [backup.watcher] Checking backup source for changes...
08-17 14:50:21 INFO [backup.drive.drivesource] Saving new Google Drive credentials
08-17 14:50:21 DEBUG [backup.model.syncer] Sync requested by GoogleDrive
08-17 14:50:21 INFO [backup.model.coordinator] Syncing Backups
08-17 14:50:22 INFO [backup.drive.drivesource] Uploading 'Full Backup 2023-08-17 02:00:00' to Google Drive
08-17 14:50:22 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
08-17 14:50:22 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
08-17 14:50:23 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:215 (save)
  addon/backup/drive/drivesource.py:202 (save)
  addon/backup/drive/driverequests.py:268 (create)
  addon/backup/drive/driverequests.py:372 (retryRequest)
  addon/backup/creds/driverequester.py:45 (request)
  /site-packages/aiohttp/client_reqrep.py:1005 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true')

08-17 14:50:23 INFO [backup.model.coordinator] I'll try again in 2 hours
08-17 14:50:32 DEBUG [backup.watcher] Checking backup source for changes...
 ```
 ###### Supervisor Logs:
 ```
 [32m23-08-17 14:43:33 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/node-red/aarch64 with version 14.4.5[0m
[32m23-08-17 14:43:56 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m23-08-17 14:43:56 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered[0m
[32m23-08-17 14:43:56 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m23-08-17 14:44:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository[0m
[32m23-08-17 14:44:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/Apipa169/Assistant-Relay-for-Hassio repository[0m
[32m23-08-17 14:44:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m23-08-17 14:44:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/brenner-tobias/ha-addons repository[0m
[32m23-08-17 14:44:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m23-08-17 14:44:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m23-08-17 14:44:03 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-08-17 14:44:03 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m23-08-17 14:44:08 INFO (MainThread) [supervisor.store] Loading add-ons from store: 78 all - 0 new - 0 remove[0m
[32m23-08-17 14:44:08 INFO (MainThread) [supervisor.store] Loading add-ons from store: 78 all - 0 new - 0 remove[0m
[32m23-08-17 14:47:50 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-17 14:47:50 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-17 14:47:51 INFO (MainThread) [supervisor.api.middleware.security] /backups/ca8afe6d/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-17 14:47:51 INFO (MainThread) [supervisor.api.backups] Downloading backup ca8afe6d[0m
[32m23-08-17 14:48:01 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-17 14:48:01 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-17 14:48:14 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[33m23-08-17 14:49:53 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[32m23-08-17 14:50:21 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-17 14:50:21 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-17 14:50:22 INFO (MainThread) [supervisor.api.middleware.security] /backups/ca8afe6d/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-17 14:50:22 INFO (MainThread) [supervisor.api.backups] Downloading backup ca8afe6d[0m
[32m23-08-17 14:50:32 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-17 14:50:32 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-08-17 14:50:45 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 321, in _wait_response
    raise RoborockTimeout(f"id={request_id} Timeout after {QUEUE_TIMEOUT} seconds") from None
roborock.exceptions.RoborockTimeout: id=0 Timeout after 4 seconds[0m
[31m2023-08-17 14:50:19.072 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 321, in _wait_response
    raise RoborockTimeout(f"id={request_id} Timeout after {QUEUE_TIMEOUT} seconds") from None
roborock.exceptions.RoborockTimeout: id=0 Timeout after 4 seconds[0m
[31m2023-08-17 14:50:33.878 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 321, in _wait_response
    raise RoborockTimeout(f"id={request_id} Timeout after {QUEUE_TIMEOUT} seconds") from None
roborock.exceptions.RoborockTimeout: id=0 Timeout after 4 seconds[0m
[31m2023-08-17 14:50:33.884 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 321, in _wait_response
    raise RoborockTimeout(f"id={request_id} Timeout after {QUEUE_TIMEOUT} seconds") from None
roborock.exceptions.RoborockTimeout: id=0 Timeout after 4 seconds[0m
[31m2023-08-17 14:50:43.640 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 321, in _wait_response
    raise RoborockTimeout(f"id={request_id} Timeout after {QUEUE_TIMEOUT} seconds") from None
roborock.exceptions.RoborockTimeout: id=0 Timeout after 4 seconds[0m
[31m2023-08-17 14:50:43.647 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 321, in _wait_response
    raise RoborockTimeout(f"id={request_id} Timeout after {QUEUE_TIMEOUT} seconds") from None
roborock.exceptions.RoborockTimeout: id=0 Timeout after 4 seconds[0m

 ```

**Comment by Daguse** [comment]
Randomly started working last night, so going to just blame it on google drive.
