### ISSUE TITLE
A snapshot was already in progress & backup done to early

### ISSUE THREAD

**Issue by VivantSenior** [sabeechen/hassio-google-drive-backup#92]
Hi,

I noticed that the addon keeps asking for a new snapshot while it already has requested a snapshot to be done. I tried to clean up logs (removed duplicated entries).

In the HA logs, you can see `19-08-23 01:27:56 INFO (MainThread) [hassio.snapshots] Full-Snapshot f842e98c done` which is weird because the first snapshot should be requested at 3 am. After that there are multiple attempts of downloading this snapshot:
```
19-08-23 01:27:58 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:27:58 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
```

Config:
```
{
  "max_snapshots_in_hassio": 10,
  "max_snapshots_in_google_drive": 15,
  "days_between_snapshots": 1,
...
  "snapshot_time_of_day": "03:00",
  "snapshot_password": "!secret google_backup_pass",
  "snapshot_name": "{year}{month}{day}_{hr24}.{min}.{sec}_{version_ha}_{version_super}_{type}_snapshot",
...
  "generational_days": 1,
  "generational_weeks": 4,
  "generational_months": 1,
  "generational_years": 1,
  "alternate_dns_servers": "1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4"
}
```

Addon logs:

```
08-23 03:04:52 DEBUG Sync requested by Coordinator
08-23 03:04:52 INFO Syncing Snapshots
08-23 03:04:52 DEBUG Making Hassio request: http://hassio/snapshots
08-23 03:04:52 DEBUG Requesting refreshed Google Drive credentials
08-23 03:04:52 DEBUG Making Google Drive request: https://www.googleapis.com/oauth2/v4/token
08-23 03:04:52 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:04:53 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:04:53 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:04:54 DEBUG Making Hassio request: http://hassio/addons/self/info
08-23 03:04:54 DEBUG Making Hassio request: http://hassio/info
08-23 03:04:54 DEBUG Making Hassio request: http://hassio/homeassistant/info
08-23 03:04:54 DEBUG Making Hassio request: http://hassio/supervisor/info
08-23 03:04:54 INFO Requesting a new snapshot
08-23 03:04:54 DEBUG Making Hassio request: http://hassio/snapshots/new/full

08-23 03:04:59 INFO Deleting '20190818_03.36.47_0.97.2_179_Full_snapshot' from Home Assistant
08-23 03:04:59 DEBUG Making Hassio request: http://hassio/snapshots/e7fb648a/remove
08-23 03:05:00 INFO Backup directory was written to, we'll reload snapshots from Hassio soon

08-23 03:05:05 INFO Backup directory changed
08-23 03:05:05 DEBUG Sync requested by Backup Directory Watcher
08-23 03:05:05 INFO Syncing Snapshots
08-23 03:05:05 DEBUG Making Hassio request: http://hassio/snapshots
08-23 03:05:05 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:05:05 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:05:06 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:05:06 DEBUG Making Hassio request: http://hassio/addons/self/info
08-23 03:05:06 DEBUG Making Hassio request: http://hassio/info
08-23 03:05:06 DEBUG Making Hassio request: http://hassio/homeassistant/info
08-23 03:05:06 DEBUG Making Hassio request: http://hassio/supervisor/info

08-23 03:05:06 INFO Requesting a new snapshot
08-23 03:05:07 INFO A snapshot was already in progress
08-23 03:05:07 ERROR A snapshot is already in progress
08-23 03:05:07 INFO Another attempt to sync will be made in 0 seconds
08-23 03:05:07 DEBUG Sync requested by Coordinator
08-23 03:05:07 INFO Syncing Snapshots
08-23 03:05:07 DEBUG Making Hassio request: http://hassio/snapshots
08-23 03:05:07 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:05:08 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:05:08 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:05:08 DEBUG Making Hassio request: http://hassio/addons/self/info
08-23 03:05:08 DEBUG Making Hassio request: http://hassio/info
08-23 03:05:08 DEBUG Making Hassio request: http://hassio/homeassistant/info
08-23 03:05:09 DEBUG Making Hassio request: http://hassio/supervisor/info

08-23 03:05:09 INFO Requesting a new snapshot
08-23 03:05:09 INFO A snapshot was already in progress
08-23 03:05:09 ERROR A snapshot is already in progress
08-23 03:05:09 INFO Another attempt to sync will be made in 10 seconds
08-23 03:05:19 DEBUG Sync requested by Coordinator
08-23 03:05:19 INFO Syncing Snapshots
08-23 03:05:19 DEBUG Making Hassio request: http://hassio/snapshots
08-23 03:05:19 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:05:19 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:05:20 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:05:20 DEBUG Making Hassio request: http://hassio/addons/self/info
08-23 03:05:20 DEBUG Making Hassio request: http://hassio/info
08-23 03:05:20 DEBUG Making Hassio request: http://hassio/homeassistant/info
08-23 03:05:20 DEBUG Making Hassio request: http://hassio/supervisor/info

08-23 03:05:21 INFO Requesting a new snapshot
08-23 03:05:21 INFO A snapshot was already in progress
08-23 03:05:21 ERROR A snapshot is already in progress
08-23 03:05:21 INFO Another attempt to sync will be made in 20 seconds
08-23 03:05:41 DEBUG Sync requested by Coordinator
08-23 03:05:41 INFO Syncing Snapshots
08-23 03:05:41 DEBUG Making Hassio request: http://hassio/snapshots
08-23 03:05:41 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:05:41 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:05:42 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:05:42 DEBUG Making Hassio request: http://hassio/addons/self/info
08-23 03:05:42 DEBUG Making Hassio request: http://hassio/info
08-23 03:05:42 DEBUG Making Hassio request: http://hassio/homeassistant/info
08-23 03:05:42 DEBUG Making Hassio request: http://hassio/supervisor/info

...

08-23 03:15:54 INFO Requesting a new snapshot
08-23 03:15:54 INFO A snapshot was already in progress
08-23 03:15:54 ERROR A snapshot is already in progress
08-23 03:15:54 INFO Another attempt to sync will be made in 640 seconds
08-23 03:23:22 INFO Backup directory was written to, we'll reload snapshots from Hassio soon
08-23 03:23:29 INFO Backup directory changed
08-23 03:23:29 DEBUG Sync requested by Backup Directory Watcher
08-23 03:23:29 INFO Syncing Snapshots
08-23 03:23:29 DEBUG Making Hassio request: http://hassio/snapshots
08-23 03:23:31 INFO Backup directory was written to, we'll reload snapshots from Hassio soon
08-23 03:23:31 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:23:47 DEBUG Ran into trouble reaching Google Drive's servers.  We'll use alternate DNS servers on the next attempt.
08-23 03:23:59 ERROR    
Traceback (most recent call last):   
  File "/app/backup/coordinator.py", line 102, in _sync   
    self._buildModel().sync(self._time.now())   
  File "/app/backup/model.py", line 120, in sync   
    self._syncSnapshots([self.source, self.dest])   
  File "/app/backup/model.py", line 192, in _syncSnapshots   
    from_source: Dict[str, AbstractSnapshot] = source.get()   
  File "/app/backup/drivesource.py", line 73, in get   
    self._info.drive_folder_id = self.getFolderId()   
  File "/app/backup/drivesource.py", line 70, in getFolderId   
    return self._getParentFolderId()   
  File "/app/backup/drivesource.py", line 144, in _getParentFolderId   
    self._folderId = self._validateFolderId()   
  File "/app/backup/drivesource.py", line 164, in _validateFolderId   
    folder = self._get(folder_id)   
  File "/app/backup/drivesource.py", line 180, in _get   
    return self.drivebackend.get(id)   
  File "/app/backup/driverequests.py", line 137, in get   
    return self.retryRequest("GET", URL_FILES + id + "/?" + urlencode(q), is_json=True)   
  File "/app/backup/driverequests.py", line 245, in retryRequest   
    raise e   
  File "/app/backup/driverequests.py", line 234, in retryRequest   
    response = self._request_client.request(method, url, headers=send_headers, json=json, timeout=self.config.get(Setting.GOOGLE_DRIVE_TIMEOUT_SECONDS), data=data, stream=stream)   
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request   
    return session.request(method=method, url=url, **kwargs)   
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request   
    resp = self.send(prep, **send_kwargs)   
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send   
    r = adapter.send(request, **kwargs)   
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 498, in send   
    raise ConnectionError(err, request=request)   
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))   
   

08-23 03:23:59 INFO Another attempt to sync will be made in 1280 seconds
08-23 03:24:09 INFO Backup directory changed
08-23 03:24:09 DEBUG Sync requested by Backup Directory Watcher
08-23 03:24:09 INFO Syncing Snapshots
08-23 03:24:09 DEBUG Making Hassio request: http://hassio/snapshots
08-23 03:24:09 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:24:10 INFO Backup directory was written to, we'll reload snapshots from Hassio soon
08-23 03:24:14 DEBUG Ran into trouble reaching Google Drive's servers.  We'll use alternate DNS servers on the next attempt.
08-23 03:24:14 ERROR Unable to connect to www.googleapis.com
08-23 03:24:14 INFO Another attempt to sync will be made in 2560 seconds
08-23 03:24:38 INFO Backup directory changed
08-23 03:24:38 DEBUG Sync requested by Backup Directory Watcher
08-23 03:24:38 INFO Syncing Snapshots
08-23 03:24:38 DEBUG Making Hassio request: http://hassio/snapshots
08-23 03:24:38 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:24:39 INFO Backup directory was written to, we'll reload snapshots from Hassio soon
08-23 03:24:39 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:24:40 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:24:40 DEBUG Making Hassio request: http://hassio/addons/self/info
08-23 03:24:57 DEBUG Making Hassio request: http://hassio/info
08-23 03:24:57 DEBUG Making Hassio request: http://hassio/homeassistant/info
08-23 03:24:57 DEBUG Making Hassio request: http://hassio/supervisor/info

08-23 03:25:00 INFO Requesting a new snapshot
08-23 03:25:00 INFO A snapshot was already in progress
08-23 03:25:00 ERROR A snapshot is already in progress
08-23 03:25:00 INFO Another attempt to sync will be made in 3600 seconds
08-23 03:25:25 INFO Backup directory changed
08-23 03:25:25 DEBUG Sync requested by Backup Directory Watcher
08-23 03:25:25 INFO Syncing Snapshots
08-23 03:25:25 DEBUG Making Hassio request: http://hassio/snapshots
08-23 03:25:25 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:25:25 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:25:26 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:25:26 DEBUG Making Hassio request: http://hassio/addons/self/info
08-23 03:25:26 DEBUG Making Hassio request: http://hassio/info
08-23 03:25:26 DEBUG Making Hassio request: http://hassio/homeassistant/info
08-23 03:25:26 DEBUG Making Hassio request: http://hassio/supervisor/info

...

08-23 03:27:11 INFO Requesting a new snapshot
08-23 03:27:11 INFO A snapshot was already in progress
08-23 03:27:11 ERROR A snapshot is already in progress
08-23 03:27:11 INFO Another attempt to sync will be made in 3600 seconds
08-23 03:27:11 INFO Backup directory was written to, we'll reload snapshots from Hassio soon
08-23 03:27:51 INFO Backup directory changed
08-23 03:27:51 DEBUG Sync requested by Backup Directory Watcher
08-23 03:27:51 INFO Syncing Snapshots
08-23 03:27:51 DEBUG Making Hassio request: http://hassio/snapshots
08-23 03:27:51 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:27:51 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:27:52 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:27:52 DEBUG Making Hassio request: http://hassio/addons/self/info
08-23 03:27:52 DEBUG Making Hassio request: http://hassio/info
08-23 03:27:52 DEBUG Making Hassio request: http://hassio/homeassistant/info
08-23 03:27:52 DEBUG Making Hassio request: http://hassio/supervisor/info
08-23 03:27:52 INFO Backup directory was written to, we'll reload snapshots from Hassio soon

08-23 03:27:52 INFO Requesting a new snapshot
08-23 03:27:53 INFO A snapshot was already in progress
08-23 03:27:53 ERROR A snapshot is already in progress
08-23 03:27:53 INFO Another attempt to sync will be made in 3600 seconds
08-23 03:27:56 INFO Snapshot finished
08-23 03:27:56 DEBUG Sync requested by HomeAssistant
08-23 03:27:56 INFO Syncing Snapshots
08-23 03:27:56 DEBUG Making Hassio request: http://hassio/snapshots
08-23 03:27:56 DEBUG Making Hassio request: http://hassio/snapshots/f842e98c/info
08-23 03:27:56 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:27:57 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:27:57 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:27:58 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:27:58 DEBUG Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
08-23 03:27:59 DEBUG Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType...
08-23 03:28:00 DEBUG Uploading 20190823_03.04.52_0.97.2_181_Full_snapshot 0.75%

...
...
...

08-23 03:31:30 DEBUG Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType...
08-23 03:31:33 DEBUG Uploading 20190823_03.04.52_0.97.2_181_Full_snapshot 100.00%
08-23 03:31:33 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:31:34 INFO Deleting '20190814_03.14.28_0.97.2_173_Full_snapshot' From Google Drive
08-23 03:31:34 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:31:36 INFO Backup directory changed
08-23 03:31:36 DEBUG Sync requested by Backup Directory Watcher
08-23 03:31:36 INFO Syncing Snapshots
08-23 03:31:36 DEBUG Making Hassio request: http://hassio/snapshots
08-23 03:31:36 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:31:36 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
08-23 03:31:36 DEBUG Making Google Drive request: https://www.googleapis.com/drive/v3/files/...
```

HA logs:
```
19-08-23 01:14:10 INFO (MainThread) [hassio.snapshots] Snapshot f842e98c store folders
19-08-23 01:14:10 INFO (SyncWorker_16) [hassio.snapshots.snapshot] Snapshot folder homeassistant
19-08-23 01:14:10 INFO (SyncWorker_4) [hassio.snapshots.snapshot] Snapshot folder ssl
19-08-23 01:14:10 INFO (SyncWorker_19) [hassio.snapshots.snapshot] Snapshot folder addons/local
19-08-23 01:14:10 INFO (SyncWorker_8) [hassio.snapshots.snapshot] Snapshot folder share
19-08-23 01:14:10 INFO (SyncWorker_19) [hassio.snapshots.snapshot] Snapshot folder addons/local done
19-08-23 01:14:10 INFO (SyncWorker_4) [hassio.snapshots.snapshot] Snapshot folder ssl done
19-08-23 01:14:15 INFO (SyncWorker_8) [hassio.snapshots.snapshot] Snapshot folder share done
19-08-23 01:15:51 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-08-23 01:15:53 INFO (MainThread) [hassio.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:15:53 INFO (MainThread) [hassio.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:23:21 INFO (SyncWorker_16) [hassio.snapshots.snapshot] Snapshot folder homeassistant done
19-08-23 01:23:30 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-08-23 01:24:09 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-08-23 01:24:38 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-08-23 01:24:57 INFO (MainThread) [hassio.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:24:57 INFO (MainThread) [hassio.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:25:25 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-08-23 01:25:26 INFO (MainThread) [hassio.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:25:26 INFO (MainThread) [hassio.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:25:34 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-08-23 01:25:35 INFO (MainThread) [hassio.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:25:35 INFO (MainThread) [hassio.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:25:41 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-08-23 01:25:42 INFO (MainThread) [hassio.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:25:42 INFO (MainThread) [hassio.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:25:59 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-08-23 01:26:01 INFO (MainThread) [hassio.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:26:01 INFO (MainThread) [hassio.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:26:17 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-08-23 01:26:19 INFO (MainThread) [hassio.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:26:19 INFO (MainThread) [hassio.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:26:57 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-08-23 01:26:59 INFO (MainThread) [hassio.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:26:59 INFO (MainThread) [hassio.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:27:09 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-08-23 01:27:11 INFO (MainThread) [hassio.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:27:11 INFO (MainThread) [hassio.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:27:51 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-08-23 01:27:52 INFO (MainThread) [hassio.api.security] /homeassistant/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:27:52 INFO (MainThread) [hassio.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:27:56 INFO (MainThread) [hassio.snapshots] Full-Snapshot f842e98c done
19-08-23 01:27:56 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
19-08-23 01:27:56 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/info access from cebe7a76_hassio_google_drive_backup
19-08-23 01:27:58 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:27:58 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:27:58 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:27:58 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:28:08 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:28:08 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:28:44 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:28:44 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:29:01 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:29:01 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:29:18 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:29:18 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:29:28 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:29:28 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:29:39 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:29:39 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:29:49 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:29:49 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:30:00 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:30:00 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:30:13 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:30:13 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:30:23 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:30:23 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:30:34 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:30:34 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:30:44 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:30:44 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:30:54 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:30:54 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:31:04 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:31:04 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:31:14 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:31:14 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:31:24 INFO (MainThread) [hassio.api.security] /snapshots/f842e98c/download access from cebe7a76_hassio_google_drive_backup
19-08-23 01:31:24 INFO (MainThread) [hassio.api.snapshots] Download snapshot f842e98c
19-08-23 01:31:36 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup

...

19-08-23 02:14:03 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-08-23 02:31:37 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup

...

19-08-23 03:31:39 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup

...

19-08-23 04:30:43 ERROR (MainThread) [hassio.api.ingress] Ingress error: None
19-08-23 04:31:23 ERROR (MainThread) [hassio.api.ingress] Ingress error: [Errno 104] Connection reset by peer
19-08-23 04:31:41 INFO (MainThread) [hassio.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
```

**Comment by sabeechen** [comment]
Closing this out due to age, but feel free to reopen if you're still seeing the problem.

**Comment by naked-head** [comment]
Same problem here, this is my log file: 
[home-assistant-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/7128823/home-assistant-google-drive-backup.log)
backup is setted to perform every three day, but the newest at the moment is 5 days old. There are two days I see  "Pending snapshot" show in your web interface, contestually the free space is drastically reduced. How can I stop the snapshot in progress and clean everything?

**Comment by sabeechen** [comment]
I think this is a separate issue, but it sounds like you have the supervisor stuck making a huge snapshot.  The only way to stop a snapshot in progress is to restart the supervisor, it doesn't provide any other way.  It would be easiest to just reboot the machine.
