### ISSUE TITLE
ERROR Google gave an unexpected response

### ISSUE THREAD

**Issue by heyhewmike** [sabeechen/hassio-google-drive-backup#948]
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.111.1`
 Home Assistant Version: `2023.11.3`
 Supervisor Version: `2023.11.6`
 Supervisor Channel: `stable`
 Hassos Version: `11.1`
 Docker Version: `24.0.6`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2023-12-01T11:40:03.656393+00:00`
 Timezone: `America/New_York`
 Failure Time: `2023-12-01T11:37:54.752249+00:00`
 Last Good Sync: `2023-12-01T11:37:54.075766+00:00`
 Next Sync: `2023-12-01T11:43:14.752249+00:00`
 Next Backup: `2023-12-03T09:00:00+00:00`
 Next Cache Warm: `2023-12-01T11:29:17.280789+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/creds/driverequester.py:29 (request)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:560 (_request)
  /site-packages/aiohttp/client_reqrep.py:899 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ClientOSError: [Errno 1] [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2576)
Whose handling caused:
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:202 (save)
  addon/backup/drive/driverequests.py:300 (create)
  addon/backup/drive/driverequests.py:372 (retryRequest)
  addon/backup/creds/driverequester.py:68 (request)
backup.exceptions.exceptions.GoogleUnexpectedError

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 83,
        "retained": 0,
        "deletable": 83,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-11-30T09:00:00Z",
        "max": 0,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "detail": "",
        "size": "23.9 GB",
        "ignored_size": "0.0 B",
        "free_space": "86.7 GB"
    },
    "GoogleDrive": {
        "backups": 15,
        "retained": 0,
        "deletable": 15,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-11-28T00:17:32Z",
        "max": 15,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "kudrak.hass@gmail.com",
        "size": "4.7 GB",
        "ignored_size": "0.0 B",
        "free_space": "10.3 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 0,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 15,
    "Setting.IGNORE_UPGRADE_BACKUPS": false,
    "Setting.BACKUP_NAME": "REDACTED",
    "Setting.BACKUP_TIME_OF_DAY": "04:00"
}
 ```
 ###### Addon Logs:
 ```
 12-01 06:33:46 ERROR [backup.model.coordinator] Google gave an unexpected response
12-01 06:33:46 INFO [backup.model.coordinator] I'll try again in 1 minutes, 20 seconds
12-01 06:33:47 DEBUG [backup.watcher] Checking backup source for changes...
12-01 06:33:52 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
12-01 06:35:06 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-01 06:35:06 INFO [backup.model.coordinator] Syncing Backups
12-01 06:35:06 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
12-01 06:35:06 INFO [backup.drive.drivesource] Uploading 'Full_Backup_2023-11-30_HAVersion-2023.11.3_HAOSVersion-11.1_HASuper-2023.11.6' to Google Drive
12-01 06:35:06 DEBUG [backup.drive.driverequests] Attempting to resume a previously failed upload where we left off
12-01 06:35:06 DEBUG [backup.drive.driverequests] Resuming upload at byte 140771328 of 874813440
12-01 06:35:06 DEBUG [backup.drive.driverequests] Sending 262144 bytes to Google Drive
12-01 06:35:07 DEBUG [backup.drive.drivesource] Uploading Full_Backup_2023-11-30_HAVersion-2023.11.3_HAOSVersion-11.1_HASuper-2023.11.6 16.12%
12-01 06:35:07 DEBUG [backup.drive.driverequests] Sending 10223616 bytes to Google Drive
12-01 06:35:13 ERROR [backup.model.coordinator] Google gave an unexpected response
12-01 06:35:13 INFO [backup.model.coordinator] I'll try again in 2 minutes, 40 seconds
12-01 06:35:17 DEBUG [backup.watcher] Checking backup source for changes...
12-01 06:35:52 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
12-01 06:37:54 DEBUG [backup.model.syncer] Sync requested by Coordinator
12-01 06:37:54 INFO [backup.model.coordinator] Syncing Backups
12-01 06:37:54 INFO [backup.watcher] A backup directory file was modified, we'll check for new backups soon.
12-01 06:37:54 INFO [backup.drive.drivesource] Uploading 'Full_Backup_2023-11-30_HAVersion-2023.11.3_HAOSVersion-11.1_HASuper-2023.11.6' to Google Drive
12-01 06:37:54 DEBUG [backup.drive.driverequests] Attempting to resume a previously failed upload where we left off
12-01 06:37:54 DEBUG [backup.drive.driverequests] Resuming upload at byte 150208512 of 874813440
12-01 06:37:54 DEBUG [backup.drive.driverequests] Sending 262144 bytes to Google Drive
12-01 06:37:54 DEBUG [backup.drive.drivesource] Uploading Full_Backup_2023-11-30_HAVersion-2023.11.3_HAOSVersion-11.1_HASuper-2023.11.6 17.20%
12-01 06:37:54 DEBUG [backup.drive.driverequests] Sending 10223616 bytes to Google Drive
12-01 06:37:54 ERROR [backup.model.coordinator] Google gave an unexpected response
12-01 06:37:54 INFO [backup.model.coordinator] I'll try again in 5 minutes, 20 seconds
12-01 06:38:04 DEBUG [backup.watcher] Checking backup source for changes...
12-01 06:38:53 DEBUG [backup.model.destinationprecache] Preemptively retrieving and caching info from the backup destination to avoid peak demand
 ```
 ###### Supervisor Logs:
 ```
 [32m23-12-01 06:35:18 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system[0m
[32m23-12-01 06:35:18 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor[0m
[32m23-12-01 06:35:18 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon[0m
[32m23-12-01 06:35:19 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system[0m
[32m23-12-01 06:35:19 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system[0m
[32m23-12-01 06:35:19 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m23-12-01 06:35:19 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running[0m
[32m23-12-01 06:35:19 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-12-01 06:35:19 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running[0m
[32m23-12-01 06:35:19 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m23-12-01 06:35:30 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository[0m
[32m23-12-01 06:35:30 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/CoolKit-Technologies/ha-addon repository[0m
[32m23-12-01 06:35:30 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m23-12-01 06:35:30 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository[0m
[32m23-12-01 06:35:30 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-12-01 06:35:30 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m23-12-01 06:35:30 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/mrlt8/docker-wyze-bridge repository[0m
[32m23-12-01 06:35:33 INFO (MainThread) [supervisor.store] Loading add-ons from store: 77 all - 0 new - 0 remove[0m
[32m23-12-01 06:35:33 INFO (MainThread) [supervisor.store] Loading add-ons from store: 77 all - 0 new - 0 remove[0m
[32m23-12-01 06:36:42 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-12-01 06:37:54 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-01 06:37:54 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-01 06:37:54 INFO (MainThread) [supervisor.api.middleware.security] /backups/449a21ca/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-01 06:37:54 INFO (MainThread) [supervisor.api.backups] Downloading backup 449a21ca[0m
[32m23-12-01 06:37:54 INFO (MainThread) [supervisor.api.middleware.security] /backups/449a21ca/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-01 06:37:54 INFO (MainThread) [supervisor.api.backups] Downloading backup 449a21ca[0m
[32m23-12-01 06:38:04 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-01 06:38:04 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-01 06:40:03 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 [0m
[33m2023-12-01 06:33:09.555 WARNING (SyncWorker_8) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
[0m
[33m2023-12-01 06:33:55.340 WARNING (SyncWorker_13) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
[0m
[33m2023-12-01 06:34:41.096 WARNING (SyncWorker_11) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
[0m
[33m2023-12-01 06:35:30.578 WARNING (SyncWorker_15) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
[0m
[33m2023-12-01 06:36:07.968 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '100180398a', 'apikey': 'ad3823cb-acf5-4c3d-b804-059722aacad3', 'sequence': '1701430562003'}[0m
[33m2023-12-01 06:36:25.570 WARNING (SyncWorker_17) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
[0m
[33m2023-12-01 06:37:13.337 WARNING (SyncWorker_9) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
[0m
[33m2023-12-01 06:38:01.448 WARNING (SyncWorker_12) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
[0m
[33m2023-12-01 06:38:53.919 WARNING (SyncWorker_2) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
[0m
[33m2023-12-01 06:39:45.337 WARNING (SyncWorker_12) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.16.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
[0m

 ```

**Comment by guy0nabuffalo** [comment]
Since updating to the latest version of the addon I'm also having this issue. Here are my logs.
```

 Addon version: `0.112.1`
 Home Assistant Version: `2023.11.3`
 Supervisor Version: `2023.11.6`
 Supervisor Channel: `stable`
 Hassos Version: `11.1`
 Docker Version: `24.0.6`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2023-12-05T15:16:57.106998+00:00`
 Timezone: `America/Denver`
 Failure Time: `2023-12-05T15:12:34.206793+00:00`
 Last Good Sync: `2023-12-05T15:04:42.371962+00:00`
 Next Sync: `2023-12-05T17:12:34.206793+00:00`
 Next Backup: `2023-12-06T06:00:00+00:00`
 Next Cache Warm: `2023-12-05T17:10:06.177268+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 
  addon/backup/creds/driverequester.py:33 (request)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:601 (_request)
  /site-packages/aiohttp/client_reqrep.py:965 (start)
  /site-packages/aiohttp/streams.py:622 (read)
aiohttp.client_exceptions.ClientOSError: [Errno 1] [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2580)
Whose handling caused:
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:205 (save)
  addon/backup/drive/driverequests.py:316 (create)
  addon/backup/drive/driverequests.py:388 (retryRequest)
  addon/backup/creds/driverequester.py:74 (request)
backup.exceptions.exceptions.GoogleUnexpectedError

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-12-05T06:00:00Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "detail": "",
        "size": "15.5 GB",
        "ignored_size": "0.0 B"
    },
    "GoogleDrive": {
        "backups": 2,
        "retained": 0,
        "deletable": 2,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-12-04T06:00:00Z",
        "max": 2,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "drewski1034@gmail.com",
        "size": "7.8 GB",
        "ignored_size": "0.0 B",
        "free_space": "82.4 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 2,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.DELETE_IGNORED_AFTER_DAYS": 30.0,
    "Setting.BACKUP_TIME_OF_DAY": "23:00",
    "Setting.BACKUP_PASSWORD": "REDACTED"
}
 ```
 ###### Addon Logs:
 ```
 12-05 08:09:08 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-12-04 23:00:00 68.76%
12-05 08:09:08 DEBUG [backup.drive.driverequests] Sending 7 MB to Google Drive
12-05 08:09:18 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-12-04 23:00:00 68.93%
12-05 08:09:18 DEBUG [backup.drive.driverequests] Sending 7 MB to Google Drive
12-05 08:09:28 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-12-04 23:00:00 69.11%
12-05 08:09:28 DEBUG [backup.drive.driverequests] Sending 7 MB to Google Drive
12-05 08:09:38 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-12-04 23:00:00 69.28%
12-05 08:09:38 DEBUG [backup.drive.driverequests] Sending 6.75 MB to Google Drive
12-05 08:09:47 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-12-04 23:00:00 69.44%
12-05 08:09:47 DEBUG [backup.drive.driverequests] Sending 7 MB to Google Drive
12-05 08:09:57 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-12-04 23:00:00 69.62%
12-05 08:09:57 DEBUG [backup.drive.driverequests] Sending 6.75 MB to Google Drive
12-05 08:10:07 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-12-04 23:00:00 69.78%
12-05 08:10:07 DEBUG [backup.drive.driverequests] Sending 6.75 MB to Google Drive
12-05 08:10:17 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-12-04 23:00:00 69.95%
12-05 08:10:17 DEBUG [backup.drive.driverequests] Sending 6.75 MB to Google Drive
12-05 08:10:26 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-12-04 23:00:00 70.11%
12-05 08:10:27 DEBUG [backup.drive.driverequests] Sending 7 MB to Google Drive
12-05 08:10:36 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-12-04 23:00:00 70.29%
12-05 08:10:36 DEBUG [backup.drive.driverequests] Sending 7 MB to Google Drive
12-05 08:10:46 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-12-04 23:00:00 70.46%
12-05 08:10:46 DEBUG [backup.drive.driverequests] Sending 7 MB to Google Drive
12-05 08:10:56 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-12-04 23:00:00 70.63%
12-05 08:10:56 DEBUG [backup.drive.driverequests] Sending 7 MB to Google Drive
12-05 08:11:06 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-12-04 23:00:00 70.80%
12-05 08:11:06 DEBUG [backup.drive.driverequests] Sending 7 MB to Google Drive
12-05 08:11:16 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-12-04 23:00:00 70.97%
12-05 08:11:16 DEBUG [backup.drive.driverequests] Sending 7 MB to Google Drive
12-05 08:12:34 ERROR [backup.model.coordinator] Google gave an unexpected response
12-05 08:12:34 INFO [backup.model.coordinator] I'll try again in 2 hours
 ```
 ###### Supervisor Logs:
 ```
 [32m23-12-05 07:54:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core[0m
[32m23-12-05 07:54:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system[0m
[32m23-12-05 07:54:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system[0m
[32m23-12-05 07:54:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server[0m
[32m23-12-05 07:54:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system[0m
[32m23-12-05 07:54:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor[0m
[32m23-12-05 07:54:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server[0m
[32m23-12-05 07:54:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system[0m
[32m23-12-05 07:54:22 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m23-12-05 07:54:22 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running[0m
[32m23-12-05 07:54:22 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-12-05 07:54:22 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running[0m
[32m23-12-05 07:54:22 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m23-12-05 07:54:29 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-12-05 07:57:52 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_user[0m
[32m23-12-05 07:57:52 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_pass[0m
[32m23-12-05 08:02:52 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_user[0m
[32m23-12-05 08:02:52 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_pass[0m
[32m23-12-05 08:04:42 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-05 08:04:42 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-05 08:04:43 INFO (MainThread) [supervisor.api.middleware.security] /backups/74e53c97/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-05 08:04:43 INFO (MainThread) [supervisor.api.backups] Downloading backup 74e53c97[0m
[32m23-12-05 08:04:43 INFO (MainThread) [supervisor.api.middleware.security] /backups/74e53c97/download access from cebe7a76_hassio_google_drive_backup[0m
[32m23-12-05 08:04:43 INFO (MainThread) [supervisor.api.backups] Downloading backup 74e53c97[0m
[32m23-12-05 08:07:52 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_user[0m
[32m23-12-05 08:07:52 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_pass[0m
[32m23-12-05 08:12:52 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_user[0m
[32m23-12-05 08:12:52 INFO (MainThread) [supervisor.homeassistant.secrets] Request secret mqtt_pass[0m
[32m23-12-05 08:16:57 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 749, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 623, in state
    raise ValueError(
ValueError: Sensor sensor.disk_nucy_dev_sdb_power_cycles has device class 'None', state class 'measurement' unit 'None' and suggested precision '0' thus indicating it has a numeric value; however, it has the non-numeric value: '12,639' (<class 'str'>)[0m
25+0 records in
0+1 records out
53+0 records in
0+1 records out
[31m2023-12-05 08:16:29.494 ERROR (SyncWorker_57) [homeassistant.components.unifi_direct.device_tracker] Failed to decode response from AP[0m
[31m2023-12-05 08:16:56.706 ERROR (MainThread) [homeassistant.components.amcrest] Amcrest Camera camera back online[0m

 ```

**Comment by sabeechen** [comment]
This issue gets reported [every once in a while](https://github.com/sabeechen/hassio-google-drive-backup/issues?q=%22SSLV3_ALERT_BAD_RECORD_MAC%22).  Here is the run down:

- Currently there is no good explanation for what causes this.
- Usually, it goes away on its own after some number of days.  For some, it does not.
- Attempts to look into the cause have all turned out to be a dead end.

If you are able to provide any information about what causes this, or what resolves it, I would be grateful.  All my efforts to figure it out have turned up nothing and I'm at a loss for how to diagnose it further.

**Comment by heyhewmike** [comment]
@sabeechen 

I just reviewed my logs and found some, new to me, behavior that I do not recall seeing before.

12-16 07:10:43 INFO Uploading 'core_2023.12.1' to Google Drive
12-16 07:10:43 INFO A backup directory file was modified, we'll check for new backups soon.
12-16 07:11:01 ERROR 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:205 (save)
  addon/backup/drive/driverequests.py:316 (create)
  addon/backup/drive/driverequests.py:388 (retryRequest)
  addon/backup/creds/driverequester.py:33 (request)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:601 (_request)
  /site-packages/aiohttp/client_reqrep.py:965 (start)
  /site-packages/aiohttp/streams.py:622 (read)
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

12-16 07:11:01 INFO I'll try again in 0 seconds
12-16 07:11:02 INFO Syncing Backups
12-16 07:11:02 INFO A backup directory file was modified, we'll check for new backups soon.
12-16 07:11:02 INFO Uploading 'core_2023.12.1' to Google Drive
12-16 07:11:27 ERROR 
  addon/backup/model/coordinator.py:198 (_sync)
  addon/backup/model/model.py:250 (sync)
  addon/backup/drive/drivesource.py:205 (save)
  addon/backup/drive/driverequests.py:316 (create)
  addon/backup/drive/driverequests.py:388 (retryRequest)
  addon/backup/creds/driverequester.py:33 (request)
  addon/backup/tracing_session.py:39 (_request)
  /site-packages/aiohttp/client.py:601 (_request)
  /site-packages/aiohttp/client_reqrep.py:965 (start)
  /site-packages/aiohttp/streams.py:622 (read)
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

12-16 07:11:27 INFO I'll try again in 10 seconds
12-16 07:11:37 INFO Syncing Backups
12-16 07:11:38 INFO A backup directory file was modified, we'll check for new backups soon.
12-16 07:11:38 INFO Uploading 'core_2023.12.1' to Google Drive
12-16 07:13:39 ERROR Google gave an unexpected response
12-16 07:13:39 INFO I'll try again in 20 seconds
12-16 07:13:59 INFO Syncing Backups
